### ISSUE TITLE
incorrect Campesh icon

### ISSUE THREAD

**Issue by MrZorG33** [We-the-People-civ4col-mod/Mod#1000]
Having launched the game, I found a pink square instead of the Campesh icon.
![image](https://github.com/We-the-People-civ4col-mod/Mod/assets/61798883/ca139b2d-4a4c-44d9-8114-699f31008c2f)

@Schmiddie1979 , could you please fix this?

**Comment by Schmiddie1979** [comment]
Seems that someone has messed up the corresponding files...that's not good.

**Comment by Schmiddie1979** [comment]
Which version do you use? No issue in the current develop version...

**Comment by MrZorG33** [comment]
I'm using the latest version of develop. After a long break, I updated the mod, translated some text and when checking the correctness of the translation I saw this bug.

**Comment by Nightinggale** [comment]
I can confirm this issue with the newest develop version. No idea when this started. The git log doesn't reveal any obvious culprits.

**Comment by Schmiddie1979** [comment]
Ok, fixed it. It seems that someone had changed something for the worse by changing the path to the icon.

**Comment by Schmiddie1979** [comment]
will upload soon
