### ISSUE TITLE
ships can no longer get rid of negative effects in forts

### ISSUE THREAD

**Issue by MrZorG33** [We-the-People-civ4col-mod/Mod#1003]
I can't say at what point in time this happened, but initially they could have done it.
![image](https://github.com/We-the-People-civ4col-mod/Mod/assets/61798883/8772b543-96dd-4f20-9508-ed72f7c18e5b)

**Comment by devolution79** [comment]
I had a look at the code, and it seems that negative promotions are exclusively cleared in actual cities, not in 'actsAsCity' entities, such as forts and monasteries.

**Comment by raystuttgart** [comment]
Not that I remember.

I am pretty sure that I wanted Ships to be repaired only in Cities, not in Forts or Monasteries.
(Meaning a place where the player could actually build a Pier or some other Harbour buildings.)

Actually I do not even like that Ships can enter them at all.
But that is of course just personal taste.

Also I really cannot imagine that somebody purposely reprogrammed that logic.
(Also not that it happened accidently in any way as it is quite specific check for "Negative Promotions".)

**Comment by MrZorG33** [comment]
>I am pretty sure that I wanted Ships to be repaired only in Cities, not in Forts or Monasteries.

This explanation suits me. Perhaps I confused this with ground military units.
