### ISSUE TITLE
change of graphics of Large forts

### ISSUE THREAD

**Issue by MrZorG33** [We-the-People-civ4col-mod/Mod#1004]
The question is most likely for @Schmiddie1979 (I don’t know if we have anyone else who does graphics): is it possible to somehow reduce the size of Large forts?
![image](https://github.com/We-the-People-civ4col-mod/Mod/assets/61798883/b6e92b89-fec1-4f5a-93d2-21ac080b6298)

so that they look as neat on the map as small forts.
![image](https://github.com/We-the-People-civ4col-mod/Mod/assets/61798883/e8f2b874-6759-4552-9d01-9d54ac28e061)

**Comment by Schmiddie1979** [comment]
done
