### ISSUE TITLE
[v4.1 Bug] EN colopedia: Link from indigo to logwood broken

### ISSUE THREAD

**Issue by estebanthebad** [We-the-People-civ4col-mod/Mod#1014]
**Version**
The played version is 4.1 .

On the english colopedia page for "indigo" is a link to "logwood" which does not work.

**Comment by MrZorG33** [comment]
if you mean the page like in the screenshot, then this has already been fixed in the current version of “develop”.
![image](https://github.com/We-the-People-civ4col-mod/Mod/assets/61798883/d782c78c-7c98-418a-801d-51b1f4a121c4)
