### ISSUE TITLE
[v4.1 Request] Improve colopedia text about goods ingredients and products

### ISSUE THREAD

**Issue by estebanthebad** [We-the-People-civ4col-mod/Mod#1015]
**Version**
The version played is 4.1 .

**What did I do?**

I read the colopedia entries about logwood and indigo. I could not determine for what logwood is used. The entry about logwood doesn't say if it is used as ingredient to produce something else. The entry about indigo mentions, that logwood is next to indigo and cochineal one of 3 dye materials. So? Can it be used to make colored cloth and wool cloth? Selling prices in europe make me guess it. But the pedia doesn't tell.

**What is my request?**

- Generally improve colopedia entries about goods, so that each states if that good is used as ingredient in the production of another good.
- Generally improve colopedia entries about goods, so that each states what other goods are necessary to produce this good.
- Make this section look uniform in all pedia entries of goods.
- Auto generate this section from the XML. (Have a text template for each language which is filled with data from the XML and inserted into the pedia entry.)

**Comment by MrZorG33** [comment]
Two sections of game concepts were created on Pedia: Production chains 
![image](https://github.com/We-the-People-civ4col-mod/Mod/assets/61798883/078afd77-62f2-4d76-b2ca-d4e5ff73388e)

and Unit equipment. 
![image](https://github.com/We-the-People-civ4col-mod/Mod/assets/61798883/2dd31d82-3083-4787-834c-4128338327e6)


This is all we can do for you for now. Perhaps in the future, when there is a person ready for a more global update, what you are asking for will appear. these updates will appear in the next release. I consider the topic closed for now.
