### ISSUE TITLE
[v4.1 Bug/Request] Prepared settler is not teachable/update colopedia

### ISSUE THREAD

**Issue by estebanthebad** [We-the-People-civ4col-mod/Mod#1017]
**Version**
The played version is 4.1 .

**What did I do?**
Moved a "Prepared settler" into a city and let it work a tile for several turns.

**Observed result**
- Next time a student graduated from university in that city, there was no option to create a unit of type "Prepared settler".
- This unit type also is not available in a cities teacher list popup (not even as "NOT available").

**Expected result**
- "Prepared settler" to be an option when the student graduated.
- "Prepared settler" to be available in a cities teacher list popup (also as "NOT available" if a prepared settler did not yet work in that city).

**Remarks**
Maybe it is intentional, that prepared settlers can not be created through education. But then the english colopedia entry needs to be updated. It doesn't say anything about it.

**Comment by Razonatair** [comment]
I'll update the colopedia soon, the Prepared Settler is a special unit that comes with all Settler equipment on the docks. They're otherwise worse than a true Specialist, as they just produce slightly more food than a Free Colonist.

**Comment by Razonatair** [comment]
This is fixed for the next release now.
