### ISSUE TITLE
Replace the current pathfinder(PF) with the K-Mod PF

### ISSUE THREAD

**Issue by devolution79** [We-the-People-civ4col-mod/Mod#102]
@Nightinggale and I decided on this a while ago since the PF provided by the exe suffers from several problems like bugs and poor performance. Another limitation is that the EXE PF uses shared global variables which means that we cannot multithread AI code that reliess on the PF and neither can we "nest" PF calls since that would cause bad performance due to having to "reset" the outer PF calls.

In short, the K-Mod PF should  in the short-term reduce\eliminate bugs caused by bad path finding and boost performance. Later, we can use it to improve both the AI decision making and add proper multithreading support.

**Here are some personal thoughts on how the K-Mod PF can be further improved:**

- RecalculateHeuristics can be vectorized with SSE intrinsics
- Consider using the cache aligned allocator from TBB. We have to deal correctly with realloc since it has to be replaced with one that respects the cache alignment
- ProcessNode should use a heap to avoid having to sort the free list.

**Some general thoughts on how to improve the current performance of the PF (applies to uses of the K-Mod one as well):**

Callbacks
Some of the  calls invoked by the callbacks can be passed the plot as a parameter so that we don't need a redundant plot lookup from x,y . Caution! This is a braindump!

1) We could introduce a cutoff to set a maximum length of the path that we’ll consider
2) Don’t pathfind every turn, stagger it so that we do a quick local search every even turn and then a full pathfinding every odd turn. We can then make more use of continuemission.
3) Introduce a tendering system so that units that are too far away or in the wrong state of fullfill a contract is filtered out early.
4) Introduce additional MISSION_AIs, we really should not recycle / abuse the existing ones to mean different things.
5) More group / stacking behaviour. This way all the units in the stack can share pathfinding and decision logic.

**Comment by Nightinggale** [comment]
`
Some of the calls invoked by the callbacks can be passed the plot as a parameter so that we don't need a redundant plot lookup from x,y 
`

This makes me wonder if it would make sense to cache CvPlot pointers in CvPlot, meaning we have a get function for the 8 plots next to the current one, completely avoiding accessing CvMap and ask based on x,y. Since the plots are fixed, it can be calculated during map generation/load and then used as read only after that.

It's also worth considering how plots are stored in memory as mentioned in #103

**Comment by ErikSandbraaten** [comment]
I decided to have a stab at merging the K-Mod PF (based on the version in the most recent AdvCiv) into 2.8. Due to some comparability issues concerning the AI structure of WTP vs. AdvCiv the PF is not yet completely functional.

**Comment by raystuttgart** [comment]
Sounds interesting.
But also sounds quite difficult / lots of effort.

I can however not really give any real input because I simply don't know anything about K-Mod Pathfinding at all.
But if you like to do it, sure go ahead.
