### ISSUE TITLE
freedom bells bonus text missing

### ISSUE THREAD

**Issue by MrZorG33** [We-the-People-civ4col-mod/Mod#1022]
![image](https://github.com/We-the-People-civ4col-mod/Mod/assets/61798883/439f07e4-5749-4376-912a-c3be796bb540)

I'm guessing it's related to this FF
![image](https://github.com/We-the-People-civ4col-mod/Mod/assets/61798883/249ee025-813f-459d-8b74-478b3e486023)

**Comment by Razonatair** [comment]
Yeah there was a previous objective of Nightinggale's to update the XML reader with the ability to replace TXT_KEYs inside TEXT with the proper information, but that hasn't been successful. As a result, I updated the necessary files with the correct information so now all help text should correctly display Father names.

**Comment by MrZorG33** [comment]
Several more <English>TXT_KEY_FATHER_ were found and fixed.
https://github.com/We-the-People-civ4col-mod/Mod/commit/4a468a5d4ca3c982fd6b4f76e991ad42b32b93c5
