### ISSUE TITLE
crash when merging musket stacks

### ISSUE THREAD

**Issue by Voker57** [We-the-People-civ4col-mod/Mod#1023]
1. load save
2. open europe
3. sell furs
4. buy 20 muskets
5. buy 20 more muskets
6. crash
[AutoSave_AD-1496-January.zip](https://github.com/We-the-People-civ4col-mod/Mod/files/15388158/AutoSave_AD-1496-January.zip)

version: Develop

**Comment by devolution79** [comment]
Could be a side-effect of the grouping rework. Will have a look

**Comment by devolution79** [comment]
Fixed! Thanks for reporting
