### ISSUE TITLE
new units in settlements after the declaration of Independence

### ISSUE THREAD

**Issue by MrZorG33** [We-the-People-civ4col-mod/Mod#1025]
after the declaration of independence, I discovered 2 Indentured Servants in each of my settlements, which were not there before.
![image](https://github.com/We-the-People-civ4col-mod/Mod/assets/61798883/19c940aa-679c-494c-8fb3-1fcca2e42b30) 

I have attached saves before and after the declaration of Independence.
[single.zip](https://github.com/user-attachments/files/15511878/single.zip)

**Comment by raystuttgart** [comment]
Yes, I think there is a Civic that will do that, just look at:
**CIVIC_FREEDOM**

--> this is a normal feature of the mod :)
(Everything working as designed, not a bug.)
