### ISSUE TITLE
description of unit abilities is missing

### ISSUE THREAD

**Issue by MrZorG33** [We-the-People-civ4col-mod/Mod#1026]
As you can see in the screenshots, the description of the unit’s abilities has disappeared. After looking through the Colopedia, I found two units that were missing text: Buccaneer and Conquistador.
![image](https://github.com/We-the-People-civ4col-mod/Mod/assets/61798883/36474119-1518-4194-a90b-0520f446ee39)
![image](https://github.com/We-the-People-civ4col-mod/Mod/assets/61798883/ba1205a1-1fe1-4168-a270-d9e5816d8075)

**Comment by Razonatair** [comment]
I've fixed this problem with some XML edits, the game text manager doesn't seem to be smart enough to find certain TXT_KEYs if they're present in the TEXT fields, so I updated the unit class file with all the names I could to fix this issue for the future. Maybe a better solution is making the game text manager smarter, but it works as it should now.
