### ISSUE TITLE
incorrect Colpedia information regarding goats

### ISSUE THREAD

**Issue by UnderdogzNL** [We-the-People-civ4col-mod/Mod#1033]
Hi,

I just found out that some information in Colpedia may be incorrect.
The background information of "goats" show they may be produced on the terrain "taiga". However, I wasn´t able to build a pasture there, only a breeding pen. While having 300 goats with an expert herder and a breeding pen on taiga, I was unable to procedure extra goats as a resource. I think the description at the goats may be incorrect:
![goats](https://github.com/We-the-People-civ4col-mod/Mod/assets/174946814/73991aed-020a-4c0c-8610-46571f2dea3d)

Especially since the information on the taiga terrain in the Colpedia doesn´t show goats as a reproducable resource, I later found out. 
![taiga](https://github.com/We-the-People-civ4col-mod/Mod/assets/174946814/ddda0667-2fc6-4584-9315-25ee4781f913)

No rush from my side obviously, but maybe something that can be looked into in a future release.
And ofcourse, my eternal gratitude for making this game perfect with this mod. You guys rock!

**Comment by Razonatair** [comment]
The game works properly at least in develop, however, it should be Breeding Pens, not pastures. Goats can grow on Taiga Hills with Breeding Pens to increase them. I'll fix the colopedia portion about the pastures.
