### ISSUE TITLE
Captured city contains all expert miners

### ISSUE THREAD

**Issue by wyphan** [We-the-People-civ4col-mod/Mod#1042]
What are the odds of the AI player dumping a ton of its Expert Miner units onto a single city before it got captured?

![Screenshot from 2024-08-19 16-08-34](https://github.com/user-attachments/assets/0c0ccee6-657f-4382-8414-9305ea8d1ce3)

![Screenshot from 2024-08-19 16-08-45](https://github.com/user-attachments/assets/9f23f528-a5e1-47f1-98a0-5d3f117d47bb)

Here's the save file when the city finishes its assimilation countdown. I've moved all other units that can move on this turn.
[Peter Stuyvesant AD-1756-January.zip](https://github.com/user-attachments/files/16658278/Peter.Stuyvesant.AD-1756-January.zip)

Edit: also, here's the autosave for that turn and the previous turn.

[AutoSave_AD-1756-January.zip](https://github.com/user-attachments/files/16658308/AutoSave_AD-1756-January.zip)
[AutoSave_AD-1755-September.zip](https://github.com/user-attachments/files/16658297/AutoSave_AD-1755-September.zip)

**Comment by Nightinggale** [comment]
Is it possible that the colony had a bunch of free colonists and then the AI decided the best resource to produce happens to be ore, which means they would have the ability to become experts through learning by doing. The terrain doesn't seem like it's rich in what the AI will usually produce.

**Comment by wyphan** [comment]
Hmm, in that case, I guess this is a _feature_ in the AI logic implementation, not a bug. And I can confirm it doesn't happen on another city that I captured later in the same game (La Nouvelle-Orléans). Closing issue.
