### ISSUE TITLE
downloads not recognized on civfanatics

### ISSUE THREAD

**Issue by atoddw** [We-the-People-civ4col-mod/Mod#1049]
tried downloading latest files 4.0 -4.1 from civfanatics site and both files download to the end and then stop and say file cannot be found at website. could you tell me where i can download them from

**Comment by Nightinggale** [comment]
It works just fine for me when downloading it from github using the link to [releases](https://github.com/We-the-People-civ4col-mod/Mod/releases/tag/4.1). If that doesn't work, then you can try to download from [moddb](https://www.moddb.com/downloads/we-the-people-v-41-civilization-iv-colonization-mod).

**Comment by atoddw** [comment]
Yes it still would die as it finishes on civfanatics but the other worked
fine thank you for your help in a timely manner. Have a good day
