### ISSUE TITLE
BUG: Player Terretory yield changes within cultural  borders - Wetland / Taiga

### ISSUE THREAD

**Issue by FrankSTUCKX** [We-the-People-civ4col-mod/Mod#1051]
I noticed an Issue with Wetland and _edit:_ Taiga Terretories claimed by the player. I wanted to produce Goose(pigs are affected too)  and had even a bonus resouce on it. But as soon its Players Domain the yield of goose and pigs is removed from the field - at least next to own cities. Removing the players Influence, it displays regular plot yields again. The Europan Ai´s fields are showing the intedend normal yield. 

In the end, cells claimed by the player are modiefied their yield according to that of the navie influence zones (replacing Goos yield by totems)
 
![WTP-terretory bug 1](https://github.com/user-attachments/assets/33a70f22-4d38-4589-b5db-6d0156355451)
![WTP-terretory bug 2](https://github.com/user-attachments/assets/d36d8227-324d-4079-af52-72cd7744a928)

**Comment by FrankSTUCKX** [comment]
- it seems to affect only the players civ (and at least for england) a second AI-england looks like nto to be affected - at least from wgars displayed at the players screen.
- the resource is not selectable for workers

I tried to find the relevant definition files for the modification, but i wasnt able to determine where this is set, 
i checkd CIV4TerrainInfos.xml and other files insid e the terrain folder but cannot make out modifiers for cultural influence that is patching the calculated feats.  

**Can anybody point me to the xml or py where the definitions for that are set and applied?** As only the player seems to be affected and other resources like horse, cattle sheep and so on aew qorking as intendedit has to be some special combination for that terrain type and the players cutural zone definition.

**Comment by FrankSTUCKX** [comment]
looks like my assumtions were completely wrong. Further ivestigation this "looks" like it has something to do with the distance to an own city. - but somehow not always. I can "paint" my terretory over to the field of anothers ai and it still displays the geese and pigs. Also on some distant fields near some native village and there they are displayed. But for the naitves settlement control zone originally they are not aviable.  
Same when i paint my field with the influence of other nations, either native or european, it is yielding goose then, as well as if its unclaimed. But when its my terretory next to the city there arent goose, regardles if there is a pasture or not.

**Comment by raystuttgart** [comment]
To produce LifeStock you need to have LifeStock stored in your City. (e.g buying+ transporting it from Europe.)
There is a full Colopdia entry about it. Did you read it?

If you have no Lifestock stored the City, the Plot will not display that you can produce it.
This is working as designed and there are lots of discussions about it in our forums and channels.

In other words:
I think you simply did not yet unerstand how the feature **"Lifestock Breeding"** in WTP works.
What you describe is not a bug ... but the intended feature behaviour.

---

**In case I am correct:**
Please  close the ticket.
Otherwise contact  us maybe in discord.

**Comment by FrankSTUCKX** [comment]
Your so true, and absolutely correct. Im sorry, but it was so confusing that the yield info on the map changes by gaining control but not if the ai has that and the ai will aslo immediatly work it - without importing anything prior (from a programming point of view make sense to let them cheat it to be there)...

Thanks for the help - and your pretty quick reaction .-closed-
