### ISSUE TITLE
trade automation issue

### ISSUE THREAD

**Issue by Juppyman** [We-the-People-civ4col-mod/Mod#1056]
Hi

Whats wrong with the trading automation feature? For me its not working at all, i tried manually setting up trade routes and assign wagons to it and also setting up to export and import goods within colonies and chose automating the wagons but they just stay in the colonies and not doing anything. The icon of automation is there, but they are not moving.

Why is this not working?

**Comment by Nightinggale** [comment]
Try attaching a savegame. Answering what went wrong without seeing what you did will be guesswork.

**Comment by MrZorG33** [comment]
this issue is already discussed here - https://github.com/We-the-People-civ4col-mod/Mod/issues/912
Please check the list of what has already been asked before opening a new issue.
@Juppyman attach your save to the thread I indicated.
