### ISSUE TITLE
Improve Pedia / Flax for english Language -Add link to taiga terrain

### ISSUE THREAD

**Issue by FrankSTUCKX** [We-the-People-civ4col-mod/Mod#1057]
The english description missing the Link to the Taiga Terrain which the other languages versions provide and in the text description is 
"Flax grows on many different terrains..." 
Pretty misleading and not helpful as its only aviable on flatland taiga in WTP. 

`[LINK=TERRAIN_TAIGA]Taiga[\LINK]`

In current version on GitHuB 
Assets/XML/Text/CIV4GameText_WTP_New_Yields_utf8.xml

`	<TEXT>
		<Tag>TXT_KEY_YIELD_FLAX_PEDIA</Tag>
		<English>[H1]FLAX[\H1][NEWLINE][BOLD]Strategy :[\BOLD][NEWLINE][COLOR_HIGHLIGHT_TEXT]Flax[COLOR_REVERT], like hemp, is the raw material for[LINK=YIELD_SAILCLOTH]sailcloth[\LINK] and [LINK=YIELD_ROPE]ropes[\LINK], which are made by the [LINK=PROFESSION_SAILCLOTH_MAKER]sailmaker[\LINK] and [LINK=PROFESSION_ROPES_MAKER]roper[\LINK] in the [LINK=BUILDING_DOCK]dock[\LINK] or one of its upgrades. Flax grows on many different terrains. To harvest it, a colonist needs to have the [LINK=PROFESSION_FLAX_PLANTER]flax planter[\LINK] profession. The flax harvest can be doubled by employing [LINK=UNIT_LINEN_PLANTER]expert flax planters[\LINK] who can be hired in Europe or trained in Native villages.[NEWLINE][NEWLINE][BOLD]Background :[\BOLD][NEWLINE]Linen fabrics woven from wild flax date back over 30,000 years. Devout colonists all know that linen is frequently mentioned in the Bible.[NEWLINE][NEWLINE]Linen is comfortable to wear in hot weather. The fabric is strong and absorbent, though it does wrinkle.</English>
		<French>[H1]LIN[\H1][NEWLINE][BOLD]Stratégie :[\BOLD][NEWLINE]Le [COLOR_HIGHLIGHT_TEXT]lin[COLOR_REVERT] pousse dans les plaines sur un terrain de [LINK=TERRAIN_TAIGA]taiga[\LINK]. Pour le récolter, un colon doit avoir la profession de [LINK=PROFESSION_FLAX_PLANTER]planteur de lin[\LINK]. La récolte de lin peut être doublée en employant des [LINK=UNIT_LINEN_PLANTER]planteurs de lin experts[\LINK] qui peuvent être embauchés en Europe ou formés dans les villages autochtones.[NEWLINE][NEWLINE][BOLD]Contexte :[\BOLD][NEWLINE]Les tissus de lin tissés à partir de lin sauvage remontent à plus de 30 000 ans. Les colons dévots savent tous que le lin est fréquemment mentionné dans la Bible.[NEWLINE][NEWLINE]Le lin est agréable à porter par temps chaud. Le tissu est solide et absorbant, mais il se froisse.</French>
		<German>[H1]Flachs[\H1][NEWLINE][BOLD]Strategie :[\BOLD][NEWLINE][COLOR_HIGHLIGHT_TEXT]Flachs[COLOR_REVERT] wächst auf Flachland in der [LINK=TERRAIN_TAIGA]Taiga[\LINK]. Um ihn zu ernten, muss ein Kolonist den [LINK=PROFESSION_FLAX_PLANTER]Flachs-Pflanzer[\LINK] Beruf haben. Die Flachsernte kann verdoppelt werden, indem [LINK=UNIT_LINEN_PLANTER]erfahrene Flachspflanzer[\LINK] eingestellt werden, die in Europa angeworben oder in den Dörfern der Eingeborenen ausgebildet werden können.[NEWLINE][NEWLINE][BOLD]Hintergrund :[\BOLD][NEWLINE]Leinenstoffe, die aus wildem Flachs gewebt werden, gibt es seit über 30.000 Jahren. Fromme Kolonisten wissen, dass Leinen häufig in der Bibel erwähnt wird.[NEWLINE][NEWLINE]Leinen ist bei heißem Wetter angenehm zu tragen. Der Stoff ist stark und saugfähig, knittert aber.</German>
		<Italian>[H1]LINO[\H1][NEWLINE][BOLD]Strategia :[\BOLD][NEWLINE]Il [COLOR_HIGHLIGHT_TEXT]lino[COLOR_REVERT] cresce in pianura su terreni [LINK=TERRAIN_TAIGA]taiga[\LINK]. Per raccoglierlo, un colono deve avere la professione di [LINK=PROFESSION_FLAX_PLANTER]piantatore di lino[\LINK]. Il raccolto di lino può essere raddoppiato impiegando [LINK=UNIT_LINEN_PLANTER]esperti piantatori di lino[\LINK] che possono essere assunti in Europa o addestrati nei villaggi dei nativi.[NEWLINE][NEWLINE][BOLD]Sfondo :[\BOLD][NEWLINE]I tessuti di lino ottenuti dal lino selvatico risalgono a oltre 30.000 anni fa. I coloni devoti sanno che il lino è spesso citato nella Bibbia.[NEWLINE][NEWLINE]Il lino è comodo da indossare quando fa caldo. Il tessuto è resistente e assorbente, anche se si stropiccia.</Italian>
		<Spanish>[H1]LINO[\H1][NEWLINE][BOLD]Estrategia :[\BOLD][NEWLINE]El [COLOR_HIGHLIGHT_TEXT]lino[COLOR_REVERT] crece en llanuras sobre terreno de [LINK=TERRAIN_TAIGA]taiga[\LINK]. Para cosecharlo, un colono necesita tener la profesión [LINK=PROFESSION_FLAX_PLANTER]plantador de lino[\LINK]. La cosecha de lino puede duplicarse empleando [LINK=UNIT_LINEN_PLANTER]expertos plantadores de lino[\LINK] que pueden ser contratados en Europa o entrenados en las aldeas nativas.[NEWLINE][NEWLINE][BOLD]Antecedentes :[\BOLD][NEWLINE]Las telas de lino tejidas con lino silvestre datan de hace más de 30.000 años. Todos los colonos devotos saben que el lino se menciona con frecuencia en la Biblia[NEWLINE][NEWLINE]El lino es cómodo de llevar cuando hace calor. El tejido es resistente y absorbente, aunque se arruga.</Spanish>
	</TEXT>`

**Comment by AlexanderHenry-theYounger** [comment]
Colopedia English now shows flax on taiga.
