### ISSUE TITLE
New main menu background

### ISSUE THREAD

**Issue by Nightinggale** [We-the-People-civ4col-mod/Mod#109]
The background in the main menu should use the correct mod name. Also we should consider a complete redesign. [Proposal ](https://commons.wikimedia.org/wiki/File:We_the_people_~.jpg) (though resolution is an issue).

**Comment by abmpicoli** [comment]
Hi, everyone. I'm attaching here a main art and a png image from a picture montage I did... I've created with the GIMP editor using some museum photos from different stages of colonization. Columbus discovery, Brazilian "Grito do Ipiranga" and a picture of washington visiting the weavers that made the US flag.
I don't know how to place them in the background... I may investigate it later... 
[we-the-people-logo.zip](https://github.com/We-the-People-civ4col-mod/Mod/files/2430712/we-the-people-logo.zip)
![we-the-people-logo](https://user-images.githubusercontent.com/1733170/46246753-d2b17e80-c3d8-11e8-95d6-3b808873bd8e.png)
The zip contains the original art so it can be further "tampered with"

**Comment by Nightinggale** [comment]
That looks really nice. However remember you have to test it in both 4:3 and 16:9 resolutions as people still use both when playing. It looks a bit 4:3 to me and I suspect it will be cut off on 16:9, killing the top text.

**Comment by abmpicoli** [comment]
Hi, everyone. Considering the widescreen and layout, I had to let go with the Inclined "We the People" version. this is the new one:
1024x768 resolution:
![image](https://user-images.githubusercontent.com/1733170/46263268-4dff5700-c4e3-11e8-8bc3-6e110a2ed6d3.png)
1366 x 768

**Comment by ShadesOT** [comment]
Looks awesome!

**Comment by raystuttgart** [comment]
Isn't this issue closed then?
Why do we keep it open?
