### ISSUE TITLE
Rename CvBuildingInfo::getNextSpecialBuilding()

### ISSUE THREAD

**Issue by ShadesOT** [We-the-People-civ4col-mod/Mod#110]
Rename CvBuildingInfo::getNextSpecialBuilding() and associated variables.

The functions name is misleading. It does not return a special building (a building slot), it returns a BuildingInfo.

All the BuildingInfo s of a SpecialBuilding are stored in a linked, looping and ordered list (ordered by SpecialBuildingPriority - the tiers of the buildings). The function in question returns the BuildingInfo of next higher tier or tier 0.
Suggestion: 
```
    getNextInSpecialBuilding()
    getNextBuildingInfo()
    getNextBuildingInfoInSpecialBuilding()
```

**Comment by Nightinggale** [comment]
The function returns m_iNextSpecialBuilding, which is set in CvBuildingInfo::readPass2(). That function could do with a readability upgrade, most likely proper comments about what goes on and possibly why it's needed.
