### ISSUE TITLE
AI cheat ignoresEuropeanBoycott based on handicap level needed?

### ISSUE THREAD

**Issue by ShadesOT** [We-the-People-civ4col-mod/Mod#113]
Question: Do AI players incure boycotts on good types?

If yes:
Currently it is hardcoded that AI players can sell from their cities warehouses to europe, nonregarding if a good is boycotted.
Should there be a XML switch to turn this on/off based on handicap level? Like the minimum overflowSellPercentage is set based on the handicap level for all their cities, nonregarding the buildings in the cities?

If no:
If the AI players should incur boycotts is another question/discussion/issue.

**Comment by ErikSandbraaten** [comment]
I just had a quick look and I'm pretty sure that the AI will never boycott any good. Even if it were to do that, what could it possibly gain?  I never have never boycotted as a player either, maybe I'm just missing out....   The AI already enjoys low or no taxes along with its other benefits. I don't think it makes sense to allow the AI to boycott goods.

**Comment by ShadesOT** [comment]
Question answered.
