### ISSUE TITLE
Music Proposal - Native Americans should have authentic music

### ISSUE THREAD

**Issue by civplayer** [We-the-People-civ4col-mod/Mod#119]
I disagree strongly with the use of electronic/new age music to be used for the new Native American civilizations for both practical and cultural reasons

Practical: The electronic sounds are disturbing- too wild, too extreme for what is mentally intensive gameplay, also they disagree with the original game soundtrack (which still plays if I recall)

Cultural: For a mod that strives for historical accuracy immersion is sorely lost with the inclusion of non appropriate music, also consider that in a certain sense it may be disrespectful to the tribes represented as their pre-colonial identity is being misrepresented. 

Some proposals 
Huron: https://www.youtube.com/watch?v=bAwSC0khWJo
Navajo; https://www.youtube.com/watch?v=xEO5DzObWCk
Algonquin: https://www.youtube.com/watch?v=nNezd-r0FKk (This is from the Pequot) 
Blackfeet: https://www.youtube.com/watch?v=BLIynPaQ9E8
ZaptoecL https://www.youtube.com/watch?v=phyZkV1afkw
Mapuche: https://www.youtube.com/watch?v=iayApXD8Tps&t=170s
Mixtec: Possible music here. https://www.youtube.com/watch?v=XdqwbgjI_nw
Shoshone: https://www.youtube.com/watch?v=b4aLPntsn0k
Caribs: Possible but unsure song about their gods and hurricanes: 
https://www.youtube.com/watch?v=stfYKCVomwY 

Though a little unrelated the music of the Papacy also needs a face lift especially with so many monastic chants available online certainly no need to re-use music that was made for a space scenario.
I propose this one for its small size and significance (used for Christmas singing)
https://www.youtube.com/watch?v=sp-fWQxbtq0  

While many of these sounds would be strange to ordinary users I think they still fit in with the game's original soundtrack and gameplay compared to the electronic music. Some of the prexisting diplomatic music fits well such as the one for Orekeke. Nor does this post give proposals for all of the new native civs but this is certainly a starting point

Please give this post some thought and consideration.

**Comment by raystuttgart** [comment]
We already have a very nice soundtrack.
Otherwise music is always personal taste.

**Comment by civplayer** [comment]
So, I made this comprehensive proposal to have more authentic music.
You come back four years later to essentially call it meaningless
Nice :)

Very-nice? How is having movie music/electronic sounds appropriate? It was both inaccurate and distracting.

Don't give me the "personal taste" comment it does not suit the mood of the period.

Look, I get it you make the decisions, and you created the mod. But the way you responded to this was totally curt.
