### ISSUE TITLE
Drunk-Monk: "Raids are unbalanced?"

### ISSUE THREAD

**Issue by abmpicoli** [We-the-People-civ4col-mod/Mod#13]
https://forums.civfanatics.com/threads/religion-and-revolution-bugs-and-todos.449958/page-120#post-15011864 . 

> Raids though unsuccessful, destroy progress and steal money, not even in the presence of fortifications prevents this, its very annoying and needs to be reworked. As it basically encourages the player to completely destroy the natives as soon as the natives turn hostile. A suggestion is that raids could have other effects, such as damaging rebel sentiment or causing anger ("the settlement feels unprotected") or could kill workers outside of the towns such as lumberjacks farmers etc, to balance larger scale fortifications would make native raids impossible.

**Comment by alexandr-** [comment]
Doesn't a certain level of fortification will a slimmer and slimmer chance on progress/buildings, 
How about to also only alternatively allow for a stealing (stealing (esp. weapons/horses...) from the warehouse and not money from the city's "vault", which is quite unreasonable: natives attack a small city on your outskirts but then get a percentage calculated on your complete treasure)

>As it basically encourages the player to completely destroy the natives as soon as the natives turn hostile.
But I dont quite understand, if raids would kill workers i would encourage me even more to kill natives. Maybe they could take prisoners (settles will keep their professions) from your cities, which you could buy/trade back (with ++ native relations)

How about raids which could damage(rarely entirely destroy) improvements or even transfer the land back to the natives.

**Comment by alexandr-** [comment]
Another idea: 
How about a unit in a fort outside will attract all the attacs / scare them away from the city

**Comment by raystuttgart** [comment]
That was alraedy solved quite a while ago.
