### ISSUE TITLE
Drunk-Monk: "Tome de Sousa's profile needs to be rewritten, as at the moment it has parts of French text"

### ISSUE THREAD

**Issue by abmpicoli** [We-the-People-civ4col-mod/Mod#14]
https://forums.civfanatics.com/threads/religion-and-revolution-bugs-and-todos.449958/page-120#post-15011864

**Comment by ErikSandbraaten** [comment]
We need someone with french skills, what about recruiting Marla Singer since she's been involved with RaR french translations in the past ?

**Comment by Alignn** [comment]
Removed the french text (in branch develop-2.7.2)

**Comment by raystuttgart** [comment]
That issue is no longer valid.
