### ISSUE TITLE
Installer to adjust the packaging system to the fact that github already provides the "source code" for each release.

### ISSUE THREAD

**Issue by abmpicoli** [We-the-People-civ4col-mod/Mod#150]
Github already provides the "Source code.zip" file , containing all resources and source code. 
I propose that we , instead of adding a huge zip that will contain exactly what the existing zip file has , plus the CvGameCoreDLL.dll, that we create an installer.

This installer will:
1) Download the Source code.zip from the github release.
2) Download an extra "cvCorePackages.zip" that we will create with each release (containing Assets/CvGameCoreDLL.dll and the 1 city radius , 2 city radius plots).
3) build the complete solution , by unpacking the Source code.zip and cvCorePackages.zip over the same location.

**Comment by Nightinggale** [comment]
That's good enough, particularly for beta releases. We might consider a simple download for a full release, but a full stable release will only have release DLLs anyway.

Also keep in mind we will hopefully get rid of the 1/2 plot builds and turn the choice into a game option. #60 This will likely break savegames to introduce though, meaning it's not something we will release for 2.7.x.

**Comment by abmpicoli** [comment]
The problem with the "1 download" approach is that we will have to upload this **huge** zip with each release... Which makes the whole process of releasing something very cumbersome. 

And I think that, for the player, if we make the "1 download" the installer, we can even provide some choices to the player ... For example, if they want to download it as a "new mod" or over an existing mod... Another thing we can add is a md5sum signature file to each artifact... or even make the player installation a "patching" one... Say, if the player have already downloaded, say, version 2.7.1-beta5, we can only download a small "patch" and apply it...

**Comment by Nightinggale** [comment]
It would make sense to release an upgrade zip containing the changed files since last release, particularly if the change is DLL and text only. We should however never replace a full download for any release. Downloading one full, and then 4 upgrades in the right order is horrible treatment of the players.

**Comment by abmpicoli** [comment]
This doesn't correspond to the release structure... A release will *always* have the full source code as a zip. For this project, the source code is almost everything... The ideal solution , in fact, would be if the installer could identify exactly which python files are changed from what the player have, and then download only those python files + the CvGameCoreDLL...

**Comment by Nightinggale** [comment]
I noticed that while removing the DLL from the git repository, the 1+2 plot radius folders were left in. We can use that for releases. Make a commit where those two are updated correctly for release, commit, push and then make a release based on that revision. This way there is only one download, not a standalone download for DLL files only.

**Comment by abmpicoli** [comment]
The problem is that this makes the dll files to be tracked again... in the end we will have a lot of intermediate dll artifacts cluttering the repository as people commit debug dlls by mistake. Unless another commit is made removing the files... that will then delete the local dlls with the next pull...

**Comment by Nightinggale** [comment]
Now the DLL files are only updated if RELEASE is defined in Makefile.settings
```
RELEASE = 1
```
It checks if the variable exist, not the contents, meaning the actual value doesn't matter.

When preparing a release, set RELEASE and then *rebuild* both DLL files. Just building will have a (minor) risk that some cache will cause the DLL to not be fully compiled and contain a mixed version. The Makefile should prevent this, but a stable release is not the time to run into an undetected makefile bug.

**Comment by Nightinggale** [comment]
Contains outdated information. Makefile is able to generate a zip file for releases. For the time being there is no need to bother figuring out a way to make small releases. Sure a single DLL file release could benefit from it, but we would need a proper installer and update installer or things will get messy either when packing or when the users have to update their own installs.
