### ISSUE TITLE
I've just discovered that it is possible to plant jungle in the city plot... Is this a feature or a bug?

### ISSUE THREAD

**Issue by abmpicoli** [We-the-People-civ4col-mod/Mod#151]
Well, I've just discovered that it is possible to plant jungle in the city plot. I'm using code from tag 2.7.1-beta5.

To tell you the truth, I've found it an interesting feature in the end... You lose food, but , thanks to #83 , you can change production at the city plot... allowing us to produce both cacao and valueable wood. It would be even cooler if we could produce lumber at the city plot... One more point to allow lumber, hemp and stone to be produced at the #139 discussion... 
[yes it is possible to plant jungle at the city plot.zip](https://github.com/We-the-People-civ4col-mod/Mod/files/2431205/yes.it.is.possible.to.plant.jungle.at.the.city.plot.zip)

**Comment by raystuttgart** [comment]
That is already fixed since I don't know how long.
