### ISSUE TITLE
Defensive Pact with natives doesnt work if another native tribe declares war on you

### ISSUE THREAD

**Issue by alexandr-** [We-the-People-civ4col-mod/Mod#154]
I had a defensive Pact with one native nation and another native tribe declared war on me, could it be possible that there is no logic for war between natives?

**Comment by ShadesOT** [comment]
Hi alexandr,

can you provide a savegame? please also include the mod version, if you can. thanks!

**Comment by alexandr-** [comment]
i am sorry i can't, i had to reinstall the game at some point. 
however i know the version: it was RaR 2.7

ps: thank you so much for continueing the work on this great mod!

**Comment by ShadesOT** [comment]
I playtested the following scenario:
- me , natives A (Tuglawina), natives B (Tecun Uman)
- me + A = defensive pact
- A, B = know each other

On `B.declearWarOn(me)` happened `A.declearWarOn(B)`.
![nativewar relation](https://user-images.githubusercontent.com/43323245/46906607-6bcab400-cf06-11e8-8d3f-cf36ff416e38.jpg)
![nativewar messages](https://user-images.githubusercontent.com/43323245/46906609-71c09500-cf06-11e8-94e5-e0c19b527a26.jpg)

So at least if your ally knows your enemy, it will correctly declare war on your enemy to help you.
@alexandr- : The case @abmpicoli brought up, where your ally does not know your enemy, remains to be tested. Maybe you can help out there?

**Comment by alexandr-** [comment]
I finally had time to play colonization again (updated to current version) and abmpicoli was right, if both players dont know each other, no war will be declared (see attached savegame)

I hope this savegame will help you, please message me if you need an earlier savegame.

PS:
funnily enough one or two rounds earlier a different native player declared war on wild animals ;)

**Comment by raystuttgart** [comment]
It is totally normal that Players that don't know each other can not declar War to each other.
This is no bug to my opinion.

Can we close this issue?
