### ISSUE TITLE
Bring back the loading screen from RAR 2.6

### ISSUE THREAD

**Issue by ShadesOT** [We-the-People-civ4col-mod/Mod#158]
RAR 2.6 had a nice loading screen (landscape drawing in sepia colors) which was changed for an ugly one in RAR 2.7 (close up of badly rendered soldiers) which also was distorted on wide screen resolutions.

**Comment by ShadesOT** [comment]
Probably has something to do with the files in this folder:
Assets\Art\interface\screens\loading

**Comment by Nightinggale** [comment]
[LoadingScreenBGBeyondtheSword.zip](https://github.com/We-the-People-civ4col-mod/Mod/files/2468919/LoadingScreenBGBeyondtheSword.zip)

**Comment by ShadesOT** [comment]
thank you!

Having a look at the xml and the code, I detected, that these xml tags are not accessed from the mod code.
```xml
<Type>MAINMENU_LOAD</Type>
	<Path>Art/Interface/Screens/Loading/LoadingScreenBG.dds</Path>
</InterfaceArtInfo>
<InterfaceArtInfo>
	<Type>MAINMENU_SLIDESHOW_LOAD</Type>
	<Path>Art/Interface/Screens/Loading/LoadingScreenBGslideshow.dds</Path>
</InterfaceArtInfo>
<InterfaceArtInfo>
	<Type>MAINMENU_LOAD_BTS</Type>
	<Path>Art/Interface/Screens/Loading/LoadingScreenBGBeyondtheSword.dds</Path>
</InterfaceArtInfo>
<InterfaceArtInfo>
	<Type>MAINMENU_SLIDESHOW_LOAD_BTS</Type>
	<Path>Art/Interface/Screens/Loading/LoadingScreenBGBeyondtheSword.dds</Path>
</InterfaceArtInfo>
```



Are they accessed from the exe directly? 

- Do you have any information about how and where these tags are used?
- Do you know if the engine also accepts simpler image formats like jpeg, gif, png, tif, ... ? We could save a lot of space using these instead of dds, I assume.
- Do you know if there is a way to have alternating background screens? The name `LoadingScreenBGslideshow.dds` suggests this, or at least that the devs once had the intention to do that.

Using google image search I found out about the artist and the license:
https://de.wikipedia.org/wiki/Datei:New_England_Scenery_Frederic_Edwin_Church_1851.jpeg
I think we can add a text file to the image, that states a short information/link about the license (it is in the public domain).

Clicking some links further shows, that this artist made a lot of other paintings, which in my opinion would very much fit the mood of WTP and its fiction of colonizing untouched and wild lands and which must all be in the public domain. Have a look here:
http://www.the-athenaeum.org/art/list.php?m=a&s=tu&aid=425

So, if we like, we can use them for other background screens as well. And if alternating screens are possible, I would definitely go and use several of them.

**Comment by ShadesOT** [comment]
> Those tags are mentioned in Art/CIV4MainMenus.xml.

Ah great! I will have a look there.


>  I have to say that we should be careful about animation. I hate scrolling backgrounds and I know I'm not the only one to dislike them.

I don't mean scrolling, but different every time the loading screen is shown.

> trial and error.

Yes, I started on that already.

**Comment by Nightinggale** [comment]
We can always resort to adding a list of screens and then make the info class return a random one from the list instead of a fixed one. If the exe reads the xml data each time it's displayed, then we will get a random one. If not, it will be the same until the game is restarted and then it's a new random one (which might be the same).

**Comment by ShadesOT** [comment]
Tested: Using  jpeg, gif, png, tif leads to purple backgrounds.

**Comment by Nightinggale** [comment]
This shows that it's the normal display engine and like the ingame sprites, dds is the way to go. Missing or unreadable sprites ingame will also display all pink. Apparently that's how the GPU API treats missing graphics placeholders.

**Comment by ShadesOT** [comment]
right. I'll test dds save settings, to see which are usable and what reduces the file size.

**Comment by ShadesOT** [comment]
> Those tags are mentioned in Art/CIV4MainMenus.xml

I can not follow that lead as I do not have that file.

**Comment by Nightinggale** [comment]
Any file missing in the mod will be read from vanilla. This means you have to include vanilla when searching around for settings you can't find. You should however never change the vanilla files. They really should be read only.

**Comment by ShadesOT** [comment]
By testing I found out the following:

1) The game engine always fits the width of a background image to the game window's width.
2) Then the engine, nonregarding the actual aspect ratio of the game window, distorts the image to an aspect ratio of 0.75 (1024 x 768).
3) Then, if the AR of the game window is lower than 0.75, it cuts the image on the top and on the bottom equaly.

So if we are heading for an AR of 0.5625 (eg 1920 x 1080), which is the prevalent screen AR today according to http://gs.statcounter.com/screen-resolution-stats/desktop/worldwide , we need to make the image have an AR of 0.75, the picture we want to show undistorted, fill the image width, have an AR of 0.5625 and black bars to fill the gaps on the top and the bottom of the image.
Which looks like this:
![backgrundarciv4col](https://user-images.githubusercontent.com/43323245/46899900-09d46500-ce9a-11e8-92b7-c47a0379740e.jpeg)

This will show only the picture, when the game is set to an AR of 0.5625 and the picture and black bars for all ARs higher. Which imo is preferable to a distorted and cut picture.

**Comment by ShadesOT** [comment]
The tag group MAINMENU_SLIDESHOW_LOAD_BTS has no observable affect on the loading screen.
```xml
<InterfaceArtInfo>
	<Type>MAINMENU_SLIDESHOW_LOAD_BTS</Type>
	<Path>Art/Interface/Screens/Loading/FredericChurch_ViewInPittsfordVt.dds</Path>
</InterfaceArtInfo>
```
