### ISSUE TITLE
Cleared Specialities are still available in Eduction (School/College...)

### ISSUE THREAD

**Issue by alexandr-** [We-the-People-civ4col-mod/Mod#163]
If you clear a Speciality, it's "Skill" is still in the Education Menu

(RAR 2.7)

**Comment by Nightinggale** [comment]
RaR intentionally disabled the schools expert decay feature, meaning once an expert type is learned by the school, it no longer needs the expert in order to teach other units to become such an expert.

**Comment by alexandr-** [comment]
sorry, didnt know. closed.
