### ISSUE TITLE
Semi-arid climate (drylands)

### ISSUE THREAD

**Issue by NoFreeUsernameDammit** [We-the-People-civ4col-mod/Mod#167]
This is one of things that have been bothering me a bit. We have three equally fertile climates, and then just desert. In reality, vast areas of Americas belong to less fertile semi-arid climate. Current praire does not reflect this well, with fertility equal to grassland and savannah, meaning it's similar to the eastern US plains or western part of eurrasian steppe, which are fertile areas that provide their continent with large supply of food. In game, such climate transitions directly to desert. However, in reality, between those are vast expanses of semi-arid land, sometimes called semi-desert or drylands. In Americas, it's more common that actual desert. Such land is quite inhospitable, but with proper agricultural infrastructure and management, it's possible to gain decent harvest.

Ingame characteristics would be like this; 
Flatland: 1 food, 3 hemp (it actually grows well in dry conditions, provided you don't want to use it recreationally), 3 sheep (representing sheep, goats and similar), 1 horse, 1 cattle, 1 barley, 2 indigo. Could be overgrown by light forest but not regular.
Resources: hemp plants, sheep, potatoes, fruit trees (new, food resource), woad (indigo).
I'm not sure which resource would be good for hills though. Indigo perhaps, represented by woad, which is more resilient, but less productive as dye than most commonly used indigo plants.

**Comment by abmpicoli** [comment]
In Brazil, such areas have limited agriculture, zebuine cattle and goats...

**Comment by abmpicoli** [comment]
To cope with the "desert or plain" situation... I've adjusted at my computer one map script to randomize climate, generating points of "mixed" terrain, so the desert is less useless... It "sort of " represents semi-arid conditions. It has other tweaks, and I don't consider it "production ready"... But I'm sharing it here, if you want to try it.
![image](https://user-images.githubusercontent.com/1733170/46833264-9558d380-cd7e-11e8-8d8c-4045a695fa0e.png)
[FaireWeatherTweakEx_albucc.zip](https://github.com/We-the-People-civ4col-mod/Mod/files/2470674/FaireWeatherTweakEx_albucc.zip)

**Comment by Nightinggale** [comment]
So essentially you tweaked the map script to add some useful land in deserts, making it possible to have actual cities there. This could be interesting.

Reading the first post made me worry that we could end up with lots of low food land, meaning we would end up in a "hills everywhere" kind of game regarding food. Mixing up the desert like that will not give that result. Still it's something, which should be watched very closely for how it affect game balance. We know what we have and while it could be better (it always can), odds are that doing something without considering game balance carefully can make the game less balanced, which in turn makes it less fun.

**Comment by NoFreeUsernameDammit** [comment]
Tweaking the map script to not include so many hills would be a good counter. I quit more than one game after finding out that most of the coastline is hills all the way.

Still, with proper farms, drylands wouldn't be that bad for farming. With large farm, expert farmer could squeeze 8-10 food from there I think. Not as bad as attempts at hill farming.

**Comment by LibSpit** [comment]
I think mixing the terrain is a better move than adding another type of terrain, simply because I found myself already overloaded with a lot of choice that seemed quite 'samey' e.g. lots of yield types that were all about the same in price and as far as I could tell served no purpose other than to be sold in Europe.

It made for an info overload, Adding another type of terrain that is plains but just a bit worse, seems like more of the same feeling. Where as mixing the terrain you think, right I put my farms on the plains and the (whatever) on the desert (or ignore the desert, whatever is the right choice) rather than having to figure out another type of terrain and bonus set that doesn't really deliver anything 'new'.

**Comment by ErikSandbraaten** [comment]
Just mentioning that #338 should take care of this. The dryland would then be plains and grassland that happen to fit in the "poor" category for most (if not all) yields.

**Comment by raystuttgart** [comment]
Of course we could create **new Terrain Types** but it is an incredible amout of work.
(Did it for Savannah, which neither existed in Vanilla or TAC.)

**MapScripts** need to be adjuste, **existing Maps** need to be adjusted, **XML (balancing, bonus ressources, improvements, ...)** needs to be adjusted, texts need to be written ...
(**Coding** is really only a tiny part of work for this.)

We **could** suggest more Terrain Types in the community forum **IF we really want to invest the effort**.

So introducing **"Drylands" + "Marshes"** sounds like a nice idea but the team needs to tell if we are willing to **invest the effort** and somebody needs to take the responsibility.

So yes, it sounds nice.

**Comment by raystuttgart** [comment]
Lots of new Terrains are now implemented in "New Hope".
Issue is thus "solved".
