### ISSUE TITLE
Another bunch of assert errors

### ISSUE THREAD

**Issue by NoFreeUsernameDammit** [We-the-People-civ4col-mod/Mod#182]
[QuickSave.zip](https://github.com/We-the-People-civ4col-mod/Mod/files/2477101/QuickSave.zip)

Ending the turn pops up two assert errors. Ignore apparently worked....

Still on beta 6.

**Comment by ShadesOT** [comment]
Any of these?
https://github.com/We-the-People-civ4col-mod/Mod/wiki/List-of-common-assertions

**Comment by ShadesOT** [comment]
Plz copy paste the assertions here. Makes it easier for us, if we see wether we need to start up the save or not.

**Comment by Nightinggale** [comment]
Tip: you can actually select text in the assert windows and copy paste it. There is no need to mess with screenshots and it actually makes it easier for us if we can copy line numbers.

**Comment by raystuttgart** [comment]
Completely outdated.
