### ISSUE TITLE
Disable known assert failures

### ISSUE THREAD

**Issue by Nightinggale** [We-the-People-civ4col-mod/Mod#183]
We have a [list of common assert failures](https://github.com/We-the-People-civ4col-mod/Mod/wiki/List-of-common-assertions). Ideally we should fix all of them, but it's unrealistic to do that within a short time span and they are annoying as they drown the unknown failures.

We should change the code of all of them into:

```cpp
#ifndef ENABLE_KNOWN_ASSERT_FAILS
    FAssert( ... );
#endif
```

This way we can make a DLL, which hides all the known issues while they still trigger on unknown issues. It also makes it easier to get good bug reports because people should just report every single assert failure without considering if it's in some list of known issues.

We can then later enable ENABLE_KNOWN_ASSERT_FAILS when compiling in order to get more data on the known issues when we get to looking into all of the.

**Comment by Nightinggale** [comment]
I started looking into this and now I think it's a bad idea. Instead we should hurry to fix the causes of those asserts. Some of them are rather severe like "I'm likely crashing if you ignore this" kind of assert failures.

**Comment by raystuttgart** [comment]
Completely outdated.
