### ISSUE TITLE
Make a queue for diplo events

### ISSUE THREAD

**Issue by Nightinggale** [We-the-People-civ4col-mod/Mod#185]
M:C has a queue for diplomatic events. This means during the AI turn, the AI will contact the human player(s). Instead of sending it to the exe, store the event in a vector in CvPlayer (for human players). During the human turn, you can click on a button to get the next event rather than having all of them pop up at the start.

You can't click end turn until your diplo queue is empty.

### Postponing replies

We can add some "Let me think about it", which will put the diplo event back to the queue. This allows cycling through all of them before you start replying. It's also beneficial in case you need to look something up before replying, like if the king wants you to attack certain natives, then you can pause the conversation, look up where they are, how many settlements they have etc before going back and replying if you can accept a war with them or not.

### Postponing answer generation

The possible answers are generated when the diplo event is send to the exe file. This means natives can offer something for gold, you get the only option to reply that you can't afford it, a ship arrive in Europe, you sell stuff and when returning from the EUrope screen, the diplo event shows up and you have 3000 gold and have to turn down their offer because you can't afford 1500 gold. If the event isn't send to the exe until after you empty the ship, then it will generate the answers matching your current amount of gold.

**Comment by raystuttgart** [comment]
Not necessary anymore, since according bug was fixed.
