### ISSUE TITLE
Pillaging road types downgrades by 1 tier instead of removing

### ISSUE THREAD

**Issue by ShadesOT** [We-the-People-civ4col-mod/Mod#186]
Currently, when road types (road, country road and plastered country road/rail tracks) are pillaged, the plot is left without any road.

We could change this, so if the road type on a plot is pillaged, the road is downgraded by one tier. Eg from 'plastered country road' to 'country road'. Only if the lowest tier 'road' is pillaged, the plot is left without any road.

Discussion!

**Comment by raystuttgart** [comment]
Seriously - it is totally unimmersive if "Pillaging just downgrades The Route Type".
It is absolutely logical that Roads and Improvements (Grown Improvements as welll) are destroyed.

When a City is razed it is also not just "razed a little bit" - it is gone.

Everythig else would be hard to explain to Players.

Let us please close this issue.
