### ISSUE TITLE
smallfry: "European kings from other powers seems useless".

### ISSUE THREAD

**Issue by abmpicoli** [We-the-People-civ4col-mod/Mod#19]
From smallfry at https://forums.civfanatics.com/threads/religion-and-revolution-bugs-and-todos.449958/page-120#post-15021942 
>Why do we have all the European kings in the Foreign Advisor screen? I have never been able to interact with them. It says somewhere that good relations with them improve the chance of help during the WoI. But what gives if I can't do anything to change these relations?
> Same goes for the Pope. He took my money about 5 times and gave me 2 bishops but that's it so far in my present game. I can't even buy favors with the foreign European kings through him which should be easy to implement.

**Comment by abmpicoli** [comment]
I'm adding a thumbs up to this. For checking bug #36 I've made the Russian King have +100 relations with me. What can be done with that? Nothing: there are nothing we can get from them...

**Comment by raystuttgart** [comment]
I think this issue is completely outdated now.
They got new features just recently.
