### ISSUE TITLE
Network games desync like crazy

### ISSUE THREAD

**Issue by Nightinggale** [We-the-People-civ4col-mod/Mod#190]
Network games are sometimes very stable and sometimes not stable at all. I just had a game with beta6 and while it started out ok, it went into desync frenzy for apparently no reason. It was desyncing like every second turn, sometimes 3 turns in a row. No known pattern and no clue to what caused it to go from synced to desync crazy.

**Comment by Nightinggale** [comment]
Apparently the desync is due to plot ownership. I have a log, which says a certain AI player has 30 plots on one computer and 34 on the other. It apparently takes those plots from NO_PLAYER as the global count of owned plots is increased as well and the computers doesn't disagree on owned plots for any other player.

Still not fixed, but at least now we have a clue to which part of the game is buggy and it's not one I would expect.

**Comment by Nightinggale** [comment]
Looks like it's not a problem with ownership specifically, but rather culture.

Turn A: both players have the same culture
Turn A+1: computer 0 has 3 higher culture on a bunch of plots than computer 1. It seems to apply to multiple players.

To make this really strange, it's consistent and it's always the player 0 game, which has 3 more than the player 1 game. This is even true when both run on the same computer, loading the very same mod files (not just a copy; the actual very same files). This means we can exclude any differences in python, DLL or xml to cause this as those files are all shared.

This means somewhere there is code, which only grants culture if active player is player 0. The question is where that would be...

**Comment by ShadesOT** [comment]
maybe in one of those: doCulture, doPlotCulture

**Comment by Nightinggale** [comment]
Found the culprit: 
```cpp
int CvGame::getCultureLevelThreshold(CultureLevelTypes eCultureLevel) const
```
It uses getActivePlayer() to figure out which traits to apply as modifiers. It looks like the human player at the computer is used regardless of which player should get the threshold. Since the exe isn't using this function, it's just a matter of adding a PlayerTypes argument and it should be good. While the function is a vanilla function, the trait addon (the culprit) is modded.

The game desyncs because player 0 is Spain, which requires -25% culture for expansion while player 1 is England with no modifiers. This means colonies expand faster in the game for player 0 as all players gained -25%. This smells strongly of a bug, which affects singleplayer as well.

I will ignore optimization possibilities for now and add those with CivEffects #93 as it makes no sense to optimize and then rewrite again for CivEffects. We really shouldn't loop traits inside (nested?) loops in doTurn.

**Comment by ErikSandbraaten** [comment]
That'a nice find and thank you for the analysis. This will be very helpful in the future for tracking down OOS issues 😄

**Comment by Nightinggale** [comment]
Fixed and committed.
