### ISSUE TITLE
XML ProfessionInfo: Rename value of ConsumedYields>Yieldtype from NONE to NO_YIELD

### ISSUE THREAD

**Issue by ShadesOT** [We-the-People-civ4col-mod/Mod#191]
For the sake of no confusion.
The XML in the ProfessionInfos feature "NONE" as yield type, instead of "NO_YIELD".
```xml
			<YieldsProduced>
				<YieldType>YIELD_BELLS</YieldType>
			</YieldsProduced>
			<YieldsConsumed>
				<YieldType>NONE</YieldType>
			</YieldsConsumed>
```
The XML read function will insert -1 == NO_YIELD into the professionInfo object in both cases. No problem there.

**Comment by ShadesOT** [comment]
Even better: check if this tag can be ommited altogether. Needs thorough check, becaus some code is testing for "NO_YIELD" as consumed yield. Maybe this fact is already a bug prone implementation as the schema says, it can be ommited.
```xml
	<ElementType name="YieldsConsumed" content="eltOnly">
		<element type="YieldType" minOccurs="0" maxOccurs="*"/>
	</ElementType>
```
Does the XML reader still insert a consumed yield of type NO_YIELD then? If not ... the gods probably will strike us down.

**Comment by Nightinggale** [comment]
We should rethink how to set up produced and consumed yields. The xml implementation isn't nice and we already have #162, which is related.

Also we might want to consider not cleaning up xml beofre merging CivEffects as the CivEffects branch has some new classes and functions for xml reading. They serve both as more clean C++ code for reading and reading from info classes, but also it makes the reading code aware what to expect and it will assert if somebody does the classic mistake of mixing up units and unit classes.

**Comment by Nightinggale** [comment]
Should be one of many cases where converting to an InfoArray would make sense. Also #396 would need <YieldTypes, int> pairs, which is another reason to not keep the existing code. There is however no real reason to keep this specific task open as in reality we should use InfoArrays for all lists read from xml.
