### ISSUE TITLE
Assert failed, when selling in port royal

### ISSUE THREAD

**Issue by ShadesOT** [We-the-People-civ4col-mod/Mod#197]
[Assert when selling in port royale-1616-January.zip](https://github.com/We-the-People-civ4col-mod/Mod/files/2504576/Assert.when.selling.in.port.royale-1616-January.zip)

Assert Failed, when selling cloth in port royal

File:  DLLSources\.\CvGameTextMgr.cpp
Line:  7997
Expression:  eYield == NO_YIELD || kPlayer.getSellToEuropeProfit(eYield, iAmount * (100 - iCommission) / 100) == iGross
Message:

**Comment by ShadesOT** [comment]
The problem seems to be the call to `CvPlayer::getSellToEuropeProfit(...)`. If the yield is not tradable in europe (as boycotted yields are not), this function always returns 0. Thus `returnValue != iGross`.

**Comment by orlanth** [comment]
Maybe the solution is to enable XML moddable tradescreens like MC. Would be even better to enable moddable supply/demand prices for Yields, and let civeffects unlock trade screen access ❤️

**Comment by Nightinggale** [comment]
#147 mentions the use of standard trade screen code and xml setup.

**Comment by raystuttgart** [comment]
I just fixed this now.
It was related to the Trade Messages in Trade Log (when selling in Port Royal).
