### ISSUE TITLE
Make doubleclick a unit in the garrison bring up the job selection popup

### ISSUE THREAD

**Issue by ShadesOT** [We-the-People-civ4col-mod/Mod#199]
![double click garrison prof menu](https://user-images.githubusercontent.com/43323245/47381921-6426be80-d701-11e8-8f28-f105be989526.png)

I always found it more comfortable to doubleclick units to assign professions to them, instead of dragging them around in the city. Even to the extent, that I exited the city summed up the job menu for a unit in the garrison and assigned a job inside the city to it, from outside the city. 
(This probably is to a good part due to the laggy game when dragging units around inside. ... Which in turn is probably to a very big part due the calculateNetYields(...). )

Anyhow, if a double click on a unit in the garrison would work the same way as for a job assigned unit, it first would be more coherent and comfortable and thus a better user experience.

**Comment by Nightinggale** [comment]
I like this idea and I suspect I have an idea on how to implement this relatively quickly.

**Comment by Nightinggale** [comment]
This was indeed fast to code as it follows the standard approach for actions for widgets (in this case double click event). The reason it took two days to code wasn't the coding time, but rather that non-modding stuff took all my time for a few days.

**Comment by ShadesOT** [comment]
OOOOOh yes!!! I just tried it out. It is awesome! Thank you so much for implemetning this! This will save players a lot of time. And now I can commission pioneers, scouts, missionaries, soldiers from within the city without the need of dragging them around. So cool. Perfect.
