### ISSUE TITLE
Native haggling issue: native tribes doesn't reevaluate trade agreements when items of the agreement are changed

### ISSUE THREAD

**Issue by abmpicoli2** [We-the-People-civ4col-mod/Mod#2]
Issue originally reported at https://forums.civfanatics.com/threads/religion-and-revolution-bugs-and-todos.449958/page-123#post-15215925

**Comment by abmpicoli2** [comment]
Since this issue seems to demand a different diplomacy screen, and this demands creating a new diplomacy screen from scratch. I don't think it is feasible to finish this now...

**Comment by ErikSandbraaten** [comment]
Like stated by @Nightinggale , the diplo screen is not in SDK. However, there is some documentation here:
http://civ4bug.sourceforge.net/PythonAPI/Classes/CyDiplomacy.html

I have an idea for how this can be fixed, will play around a bit and report back.

**Comment by ErikSandbraaten** [comment]
Ok, it's clear to me now that this is fixable and we certainly don't need a new diplo screen 😃 
I'll try to implement a fix in CvDiplomacy.py, but it may require DLL changes as well.

**Comment by ErikSandbraaten** [comment]
Fixed! It turned out to be easier than I thought. Just a tiny mod to CvDiplomacy.py :smi

**Comment by abmpicoli** [comment]
Please make a push to 2.7.1 branch so we may deliver a beta patch / release...
