### ISSUE TITLE
From smallfry: Possible balance issue: Overfriendly king ?

### ISSUE THREAD

**Issue by abmpicoli** [We-the-People-civ4col-mod/Mod#20]
https://forums.civfanatics.com/threads/religion-and-revolution-bugs-and-todos.449958/page-120#post-15021942

My king however seems to be overly friendly now. I actually thought about not even producing any guns because I could and still can (at 41% revolutionary support!) buy so many military units they might be enough to kill the REF.
Although the king has been building up his military for some time now we still have positive relations and I can still buy units at ridiculously low prices. All I did to achieve that was paying my dues each time and agreeing to higher taxes most of the time.
The two times I did not was before I realized that selling boycotted goods through the Custom House gives me less money than shipping the underlying raw materials to Europe or Africa!?

**Comment by raystuttgart** [comment]
I think this issue is completely outdated now.
