### ISSUE TITLE
Big coastal ship misses the "go to destination x" button

### ISSUE THREAD

**Issue by ShadesOT** [We-the-People-civ4col-mod/Mod#200]
Big coastal ships buttons:
![big coastal no goto button](https://user-images.githubusercontent.com/43323245/47383396-e49aee80-d704-11e8-815c-37640ad17492.png)

High sea ships buttons:
![high sea ships buttons got marked](https://user-images.githubusercontent.com/43323245/47383428-f7152800-d704-11e8-9e6b-8ae6e3977410.png)

Probably, the small coastal misses this button as well.

I found coastal ships to be very usefull in trading with native villages along the coast, which are not yet connected with a road. Being able to send them home via the "go to" - popup would be comfortable.

Anyways, it is missing a button which other ships (high sea ships) have.

**Comment by ErikSandbraaten** [comment]
This is actually a feature since I disabled the goto button for coastal ships since they cannot move through ocean. This was simpler than figuring out a way to filter the reachable cities. I agree that this should probably be implemented at some point.

**Comment by raystuttgart** [comment]
That is fixed now - GoTo works correctly for Coastal Ships.
Will thus close it.
