### ISSUE TITLE
Add overflow icons to the city billboards

### ISSUE THREAD

**Issue by Nightinggale** [We-the-People-civ4col-mod/Mod#208]
Add two GameFont icons, one for warning about approaching warehouse capacity and another for having discarded something this turn. Figure out when to add those. Drawing is simple if it's just two bools in CvCity. The real task is to write code to update those bools as needed and if changed, mark the billboard dirty to force the exe to redraw it.

There is also the task of drawing new GameFont icons. Billboards only use the big version of GameFont, meaning there is a possible shortcut here, though I would prefer keeping the two files in sync.

**Comment by ShadesOT** [comment]
The code for calculating overflow and loss is there. In the refactoring branch it is untangled and layed out straight and readable. Local variables keep track of overflow, loss and many more values. As of now they only live within doYields() which is called at turn end, but these values can easily be persited to the next turn using member variables.

**Comment by Nightinggale** [comment]
I was kind of hoping to display a warning for what happens next turn rather than a cached result of the previous turn. It's still not a bad place to fetch the numbers.

What we really need is a function, which returns an enum value telling status of warehouse next turn, like "normal, nearly full, overflowing". The billboard update code can then call this function. This will reduce the issue to marking the billboard dirty once the situation change. This could be done in a function, which is called whenever warehouse capacity or stored yields change.

**Comment by ShadesOT** [comment]
> I was kind of hoping to display a warning for what happens next turn rather than a cached result of the previous turn.

As of now, every change in the city, which affects production, makes it necessary to recalculate. This is already done and the cause of the lag when opening the city screen and when adding or removing workers.
Calculation of potential overflow and loss could be added on top of that. Then the values you are thinking of are available and up to date. It would just slightly add to the lag. (I am writing this without much pain, as the complete and costly recalculation of the net yields after every change over and over again is something, which has to be refactored anyways and is a candidate for caching and/or multithreading.)

**Comment by Nightinggale** [comment]
Just to be clear: the city billboard is the nameplate on the map and has nothing to do with the city screen.

**Comment by ShadesOT** [comment]
Thanks for clarifying that. I indeed thought the billboard has something todo with the city screen.

**Comment by raystuttgart** [comment]
I implemented it just now.
