### ISSUE TITLE
Bug paying for the Bishop

### ISSUE THREAD

**Issue by MichaelQuell** [We-the-People-civ4col-mod/Mod#209]
[AutoSave_AD-1580-January.zip](https://github.com/We-the-People-civ4col-mod/Mod/files/2546036/AutoSave_AD-1580-January.zip)

See attached savegame 2.7.1 beta 6
Through a random event i get enough money to pay for the bishop, but there is no option to acctually do it.
Is this behavior intentded?

**Comment by Nightinggale** [comment]
I haven't checked, but my guess is that you sold stuff in Europe the same turn. There is an issue where the answers are generated during the AI turn, meaning it doesn't update just because you sell stuff in Europe in the meantime. Would this be the case or should I download the savegame to investigate a new bug?

#201 is intended to fix this issue as well as a lot of other issues.

**Comment by MichaelQuell** [comment]
I didnt sell anything in europe, but there is an random event something in my silvermine witch gives me 90 gold, with the result that i have enough money to pay for the bishop. During the AI turn i didnt have enough gold. So this seems to be related.

**Comment by raystuttgart** [comment]
This is most likely not related to the specific Diplo-Event.
This is the problem with the precalculated Diplo-Events that affects all Diplo-Events.

IF we ever figure out how to solve the "pre-calculation" issue of DLL-Diplo-Events then this specific issue will most likely be automatically fixed as well.

**Comment by raystuttgart** [comment]
Hi guys, could we close this one and make a general issues "Precalculation of DLL-Diplo-Event causing issues if Sales in Europe Sceen happen first and money changes"?

**Comment by Nightinggale** [comment]
It's not even if the player sells anything in the meantime. It might as well be domestic market, other events or anything else which changes the amount of money the player has. It's also causing issues with the natives wanting to trade and having moved the unit in the meantime.

We should however close this one and have a more general "diplo event with out of date data" bug open.
