### ISSUE TITLE
Multiplayer

### ISSUE THREAD

**Issue by Villovik** [We-the-People-civ4col-mod/Mod#212]
Hi people, may be this is wrong place for my message, but, where I can find people for multiplayer game? All forums almost dead, I have some people from Russia, but our ping was 220 (I live in USA), and second question is how depend game from ping?
I apologise if my message in incorrect place

**Comment by Nightinggale** [comment]
This is for development, not players seeking players. However I can't really tell how you find other people to play with. I wouldn't mind knowing that myself.

As for ping, the network code is actually written to be used on dialup. This means data is only transferred when it's absolutely required, like when ordering a unit to move or similar. Anything which can be calculated on all computers will be calculated in parallel without communication (the AI is completely network free).

While I haven't tried such a bad ping, I would say go for it and see what happens. Maybe you will get a delay in watching how other players move their units etc, but often that's not a huge issue.

**Comment by LibSpit** [comment]
In Civ V I regularly play with people at +200 ping US/UK/EU with no noticeable effect, So I imagine that would not be so bad. As for finding people it would just be going to every site related to the game as possible, steam forums/moddb/civfanatics/etc. and just trying your luck posting for players.
