### ISSUE TITLE
Clean up TXT_KEY_CREDITS_TEXT (ingame mod credits)

### ISSUE THREAD

**Issue by Nightinggale** [We-the-People-civ4col-mod/Mod#224]
The string TXT_KEY_CREDITS_TEXT in CIV4GameText_Credits_Readme_Hints_utf8.xml seriously needs cleanup. It's very problematic the way it's implemented right now.

The problem is mainly that it is a list of multiple people with a bit of text in between. Since a translation is all or nothing, in order to translate the in between text, the entire list needs to be translated. Essentially we need to maintain a full list of people for each translated version. Not only is this a gigantic hassle, it has a high risk of going out of sync. We need something, which is easier to maintain and with less risk of "translation sync errors".

We also need to update the text in general. It claims the mod is RaR and doesn't mention the WTP team.

*****

Part of the problem with this is likely that the credits screen is in the exe, meaning we can't mod it at display time. It will display TXT_KEY_CREDITS_TEXT regardless of what we do.

What we should do is to add a bunch of TXT_KEYs and then at on load merge them together into one string. First of all this will avoid using a gigantic string in xml, which in itself will make translations easier.

Next we split the string into logical substrings, like headlines and list of modders. This has multiple benefits. The headlines will be short and manageable for translators. This makes the translation work easier.

The other benefit is that the lists of usernames will be just that: usernames. No need to translate, meaning we only add them in English. Other languages will then use the new feature where TXT_KEYs without the proper translation will use English as fallback. This will give us a single list to maintain, or rather one copy of each list since there are actually multiple lists. This will protect the lists from going out of sync between translations and it will be a lot easier for us to maintain.

*****

The next question is how to implement this. At startup or when changing the language, CvXMLLoadUtility::LoadGlobalText() is called. It will call CvXMLLoadUtility::SetGameText() for each file and this will call CvGameText::read() for each entry.

Most likely the easiest approach to this is to mod CvGameText::read(). If getType() ==TXT_KEY_CREDITS_TEXT, then use setText(new combined string). If we place all the needed strings into one xml file and place TXT_KEY_CREDITS_TEXT last, then we will be sure all the other strings are read by the time we reach TXT_KEY_CREDITS_TEXT. From here it seems like it's just a matter of making a CvWString and adding the TXT_KEYs (contents, not actual keys) one by one.

**Comment by raystuttgart** [comment]
That was implemented already by @Nightinggale to my knowledge.
(Since quite a while ago actually.)
