### ISSUE TITLE
Name of the city did not show appropriately in the event

### ISSUE THREAD

**Issue by digvoo** [We-the-People-civ4col-mod/Mod#225]
Name of the city did not show appropriately in the event:
![20181208135726_1](https://user-images.githubusercontent.com/2730069/49686819-8ed6a600-fafa-11e8-9324-202b480930ef.jpg)

I suppose this random event is generated when the new turn starts, but still, here is the save game (end of the previous turn):
[Turn-before-event-CityName.zip](https://github.com/We-the-People-civ4col-mod/Mod/files/2659745/Turn-before-event-CityName.zip)

**Comment by Nightinggale** [comment]
This is really odd. The text says

> <English>Some women have recently arrived in **%s2_city** and want to work as bar ladies in the saloon. Once the women of **%s2_city** heard about that they started rioting. They claim that those bar ladies are prostitutes and would seduce their good men. If we don't chase those bar ladies away, the women will riot.</English>

%s2_city should be replaced with the name. Why does it fail for the first one when it works for the second....

**Comment by raystuttgart** [comment]
This is already fixed in New Hope.
(Just checked it.)
