### ISSUE TITLE
Stockade not visible

### ISSUE THREAD

**Issue by digvoo** [We-the-People-civ4col-mod/Mod#226]
Stockade not visible around city Nieuw Amsterdam:
![20181208174838_1](https://user-images.githubusercontent.com/2730069/49688627-4ed0ec80-fb15-11e8-820e-7b483aa22342.jpg)
Maybe it has to do with rivers around it, random guess. Here is the save file:
[StockadeNotVisible-city-NA.zip](https://github.com/We-the-People-civ4col-mod/Mod/files/2659891/StockadeNotVisible-city-NA.zip)

**Comment by raystuttgart** [comment]
What?

Never heard of this issue before. (Stockades not being displayed.)
I also don't have any idea what could cause it ...

**Comment by ErikSandbraaten** [comment]
Not sure if WTP uses the same code but I know that in BTS there is a bitset that will control how many buildings will be displayed. There is a priority mechanism as well so it is at least theoretically possiblye that some building could be filtered out by this mechanism. I suppose that there is a way to force a specific building to always be visible which makes sense for fortifications.

**Comment by Nightinggale** [comment]
If there is a list of buildings somewhere, which the exe use to draw buildings until it has drawn X buildings, then all we need to do is to make sure "city wall type" buildings will always be first. It would be nice to be able to control this through. Maybe we don't need any changes other than priorities, but we will need to document how to control this system.

**Comment by raystuttgart** [comment]
I have no idea myself.
But people that might know are **Kathy**, **Willi_Tell** and **Schmiddie**.
All other graphical specialsist I had known are not around in the forums anymore.

**Comment by ErikSandbraaten** [comment]
I just checked the code and it appears that there is no mechanism to force defensive buildings to always be visible, which is kinda important 😩 
AdvCiv on the other hand has this mechanism so we'll just borrow some code :)

**Comment by ErikSandbraaten** [comment]
Should be fixed now in fixes :)
