### ISSUE TITLE
Display hidden parameters(lbd etc.)  when inside the city view

### ISSUE THREAD

**Issue by ErikSandbraaten** [We-the-People-civ4col-mod/Mod#233]
![image](https://user-images.githubusercontent.com/32330976/50724932-d0f10880-10f5-11e9-96c1-1a3a08c2051e.png)

I've enchanced CvGameTextMgr::setCitizenHelp to show the following when hoovering the mouse over a colonist (if assigned to a profession) inside the city:
- Yield bonuses (primarily for experts, but also relevant for slaves)
- Chance of escaping (indentured servant, petty criminal, slaves)
- Chance of becoming free (indentured servant)
- How many (minimum) turns required to become an expert and the odds of becoming one when the threshold has been reached.

Other features to consider:
- Use the yield button rather than the image
- Add support for these tags: getYieldDemand \ getBonusYieldChange (Unless the list of yields demanded clutter up the UI)

**Comment by Nightinggale** [comment]
One thing I have been wondering about with issues like this is to merge display code and stats calculation like adding a CvString pointer to the arguments. If the string pointer isn't NULL, it will fill in each parameter to the string as they are calculated. This will ensure a fast way to get the final modifier (set string to NULL) and at the same time it prevents the display code from going out of sync with the calculations.

Maybe it's not a huge issue here, but it is in some locations and we might as well figure out a standard for doing this everywhere. If we always do it like this, we get fairly clean code and avoid display bugs in the future.

**Comment by Nightinggale** [comment]
In M:C I added GameFont icons for units. This adds CvUnitInfo::getChar(), which works just like getChar from say yield info. Maybe it's something to consider.
One limitation of this is unless it's added before game symbols, it won't be possible to display it on city billboards. This won't be an issue unless we actually want units to show up there, in which case we can be creative and get it to work anyway. There are a significant number of unused IDs in the billboard working range.

**Comment by orlanth** [comment]
Maybe I’m just too nearsighted or amnesiac lol, but I wouldn’t be able to readily recognize all possible units from gamefont pics :) But replacing the current “Minimum turns required to become an expert:” with “Minimum turns to become Expert Sugar Planter” or even “Min turns to Expert Sugar Planter” would be clear while using the same number of lines.

**Comment by raystuttgart** [comment]
By the way, we already have a game Option "Show hidden Parameteres", does this trigger displaying this extra information.

If yes: Fantastic :)
If no: It would be great if it would

**Comment by raystuttgart** [comment]
@ErikSandbraaten 

Could we also integrate your changes for this to "fixes"?

Then we can also close issue #77 

I personally would
A) Display **Yield Bonusses** of Units to be **always visible**
B) Have the turns a **Unit already worked** to be **always visible**
C) display the **min turns until possibly becoming an expert** only **Game Option Show hidden Parameteres**
D) display the **chances (Fleeing, Becoming Free, Becoming Expert)** only with **Game Option Show hidden Parameteres**

But if you want to display all always, that is ok for me as well.

**Comment by ErikSandbraaten** [comment]
I think that my initial implementation and @raystuttgart refinements have solved this sufficiently.
