### ISSUE TITLE
Coats-Event Text / Color

### ISSUE THREAD

**Issue by alexandr-** [We-the-People-civ4col-mod/Mod#235]
On the Coat-Event it should be decreased by -1 and colored red - see attached screenshot

![img_5457](https://user-images.githubusercontent.com/6338481/50725709-eff59780-1101-11e9-9add-6681c3bdd9a6.JPG)

**Comment by raystuttgart** [comment]
Yes, it should say "Relations to Royal French king are decreased by -1".

I will correct the Python Event System Text to sound ok for positive and negative changes of Attitude.
(I will just adjust the text though without any DLL changes.)

It will simply say Yes, it should say "Relations to Royal French king will change by -1".

**Comment by raystuttgart** [comment]
This is fixed now.
(Color and Text are correct now.)

Was an error in Python:
def getHelpRequisition(argsList):

Did not consider all cases of positive / negative.
(XML entries were already there.)

Strange it had not been discovered earlier.
This erros must have exited since years already.
