### ISSUE TITLE
Interface issue: two buttons for travelling to port royal

### ISSUE THREAD

**Issue by abmpicoli** [We-the-People-civ4col-mod/Mod#24]
https://forums.civfanatics.com/threads/religion-and-revolution-bugs-and-todos.449958/page-118#post-14975902

**Comment by ErikSandbraaten** [comment]
I remember spotting this as well, but is a very minor issue.

**Comment by Nightinggale** [comment]
Confirmed. Go to Europe/Africa have two buttons each, one for moving to access plot and "jump" and the other for when it's already on an access plot. When the ship is on an access plot, the goto plot button will vanish. For some reason the goto access plot and jump to Port Royale button lacks the condition check, hence making it possible to display both at the same time.
