### ISSUE TITLE
Random event coward native substracts money when it should add

### ISSUE THREAD

**Issue by Nightinggale** [We-the-People-civ4col-mod/Mod#244]
[forum post](https://forums.civfanatics.com/threads/we-the-people-bug-reporting.636760/page-5#post-15329842)

Two issues:
1. apparently selling the man to the natives subtracts money. Obviously it should add money if he is sold.
2. Typo in answer "give hin a Bible". It should be "him".

We need to figure out if it makes sense to pay for the relationship boost or if the boost should cost you money. This is purely a game balance issue. The random event display engine should be able to display both cost and gain correctly if it can't already.

**Comment by raystuttgart** [comment]
The bug is fixed.
Texts corrected and XML-Event corrected.

This is actually a bit tricky.
I also just figured it out in **void CvGameTextMgr::eventGoldHelp**

Because if you **don't give any "non-random gold"** the "random gold" is considered to be a random amount to be substracted ...
