### ISSUE TITLE
TXT_KEYs containing references to TXT_KEYs

### ISSUE THREAD

**Issue by Nightinggale** [We-the-People-civ4col-mod/Mod#251]
We have some TXT_KEYs, which refers to other TXT_KEYs, like
`    <TEXT>
        <Tag>TXT_KEY_UNITCLASS_COLONIST</Tag>
        <English>TXT_KEY_UNIT_COLONIST</English>
    </TEXT>`
The problem with this is that this will display TXT_KEY_UNIT_COLONIST rather than the contents of that TXT_KEY. We currently have 237 such references across 19 files.

Obviously we need to fix this before the next release, but how should we do it?

-----

Solution 1:
Manually fix all 237 cases.
Pro: no codechange needed
Con: time consuming and boring to accomplish

-----

Solution 2:
Mod the DLL to follow the reference if the string starts with TXT_KEY.

Pro:

- Allows reuse of strings to avoid re-translation of the same string multiple times
- Allows consistent naming since it allows something like all unitclasses to use TXT_KEY_UNITCLASS even if pointing to a TXT_KEY_UNIT string
- Avoids a lengthy cleanup of text xml files for no obvious benefit

Con:

- Stores the same string in memory more than once
- Requires more modding to the code, which reads the text xml files

When the game starts or when a new language is picked, CvXMLLoadUtility::LoadGlobalText() is called. This will generate a list of all text xml files and call CvXMLLoadUtility::SetGameText() for each file. This will load each CvGameText entry (string) in the file. Somehow each "broken" CvGameText has to go back to LoadGlobalText() and should be added last as in after the entries they point to. The most obvious candidate for this is a vector reference argument in SetGameText().

-----

I'm not completely happy with either solution. Do anybody else have a good idea on what to do about this? Complete redesigns would be possible considering it's all about loading a TXT_KEY and 3 CvWStrings for each language. 2 of those CvWStrings have default values in case they aren't mentioned in xml (defaults to singular male words). It's actually a fairly simple task.

A complete redesign might actually be attractive. CvGameText inherits CvInfoBase for no apparent reason and it's actually a lot of data and strings to init without ever being used. Perhaps it would be best to make a complete redesign. Most of the eseential code can be reused (xml reading, language picker, list files etc)

Ideas and other feedback are most welcome.

**Comment by Schmiddie1979** [comment]
Do we have it in the DLL files? I could not locate such file in the XML files.

**Comment by raubwuerger** [comment]
In my opinion we should do solution 1. If we do solution 2 we work around the main problem, bad master data. We should correct the bad data...
But I also couldn't locate the text string (<English>TXT_KEY_UNIT_COLONIST</English>) you mentioned.
Did a full-text search with AgentRansack ...
Can you point me to the correct files?

I can do the boring job ... *g*

**Comment by Alignn** [comment]
The strings in question are in the automatically created XML files. For example:
[...]\We the People\Assets\XML\Text\XML_AUTO_UTF8_UnitInfo.xml

I'd say it wouldn't be bad data anymore if we went with solution 2, but instead an efficient way of reusing resources.

**Comment by raubwuerger** [comment]
I'm sorry. But I can't reproduce this behavior. Neither in the DEBUG-Version of the DLL, nor in the RELEASE-Version. I've loaded a game, changed the language (also in the CivilizationIV.ini) saved the game again, and so on ...
I didn't searched for a specific string (XML_AUTO...), but I checked the timestamp of every xml file ... nothing?

What do I have to do to reproduce the issue? Is there some cache mechanism?

**Comment by Alignn** [comment]
If you can't find a file called XML_AUTO_UTF8_UnitInfo.xml then you've probably got the wrong branch -
develop-2_7_2 is the most up to date.

**Comment by Nightinggale** [comment]
XML_AUTO_UTF8_UnitClassInfo.xml

```xml
<TEXT>
    <Tag>TXT_KEY_UNITCLASS_COLONIST</Tag>
    <English>TXT_KEY_UNIT_COLONIST</English>
</TEXT>
```

*****

I just searched the Text xml dir for ´<English>TXT_KEY´ and it is present in 237 times across 19 files.

Take for instance TXT_KEY_BUILD_REFORESTATION in XML_AUTO_UTF8_BuildInfo.xml. It turns up for multiple terrains like

```xml
<TEXT>
    <Tag>TXT_KEY_BUILD_REFORESTATION_PLAINS</Tag>
    <English>TXT_KEY_PLANT_FOREST</English>
</TEXT>
```

There are 5 build entries for planting forests in units/Civ4BuildInfos.xml. A more clean solution would be to call them TXT_KEY_BUILD_PLANT_FOREST, TXT_KEY_BUILD_PLANT_JUNGLE and TXT_KEY_BUILD_PLANT_TAIGA. Some of those can then be used for more than one buildInfo, like plains and grassland both plant forests.

Grep is a nice linux/unix tool for searching multiple text files at once. [Grepwin](https://sourceforge.net/projects/grepwin/) is a well working port for windows. I use it whenever I need to search multiple xml files at once. It's really useful when you don't know which file contains the TXT_KEY you are looking for.

*****

> I'd say it wouldn't be bad data anymore if we went with solution 2, but instead an efficient way of reusing resources.

While it's not a critical resource drain, the text system is surprisingly memory hungry and it leaks memory whenever somebody changes the language. Unsurprisingly the memory usage seems to be linked to the amount of TXT_KEYs we add. It would likely be nice to go through the files and make a minimalistic set, like reusing if possible and remove all the unused _HELP strings, which are ???? anyway.

It would also be nice if we could generally get the text xml files organized, like they are sorted by contents rather than the order they were added or who added it or whatever else semi-random pattern people have used so far.

None of this is game breaking or critical, but it would be nice if we could keep track of the text we are actually using. I tried to automate the sorting and that went.... not precisely according to plan, but at least it mostly worked.

**Comment by raubwuerger** [comment]
Ok, now I see the files. It was excatly what you mentioned ...

> 
> 
> If you can't find a file called XML_AUTO_UTF8_UnitInfo.xml then you've probably got the wrong branch -
> develop-2_7_2 is the most up to date.

**Comment by raystuttgart** [comment]
Hey, I just saw that the issue about TXT_KEYs I report is already really old and known.

**Comment by raystuttgart** [comment]
I think this is solved now as well, with our rework of the TXT_KEYs.
Seems to be working.
