### ISSUE TITLE
"Go to destination" when inside travel zone always displays Port Royal

### ISSUE THREAD

**Issue by Alignn** [We-the-People-civ4col-mod/Mod#252]
If a ship is in the "Access to Europe" travel zone out in the ocean and you bring up the "Go to destination" menu, Port Royal is available regardless of what type of ship you're using (tested with Galleon and Caravel). Clicking the option does nothing, and there's no such error outside of the zone, so it's a minor interface issue.
![portroyalbug](https://user-images.githubusercontent.com/18351802/51803536-91ca5900-2256-11e9-8937-736baa317b9f.jpg)

**Comment by raystuttgart** [comment]
I could try to take care of that.
Should not be that difficult.

**Comment by raystuttgart** [comment]
This is fixed now and tested.
(It was a simple change of brackets for the "canSailToPortRoyal" check.)

Will pus to fixes now.
