### ISSUE TITLE
Useless ranger

### ISSUE THREAD

**Issue by MichaelQuell** [We-the-People-civ4col-mod/Mod#253]
[quell AD-1616-October.zip](https://github.com/We-the-People-civ4col-mod/Mod/files/2825353/quell.AD-1616-October.zip)

In the attached save simon bolivar will capture santo domingo when you press next turn. There is no fight my ranger stays at the same plot. I think this behavior is not intended.

**Comment by ErikSandbraaten** [comment]
There are some issues with invisible units like the ranger that I indent to look into at some point...

**Comment by raystuttgart** [comment]
I implemented "Invisibility" because I had ideas to flesh it out.
(I think I adapted it from Civ4 BTS and modified it.)

Currently however it is pretty much useless.
Why not simply **change the XML setting of the Ranger** so it does **not use "Invisibility"** anymore?

We could still leave the "Invisibility" code in there for the future if we might ever make it a worthwhile feature or if a mod-mod might want to use it someday.
(I currently however have no plans for any feature to make use of it.)

**Comment by Nightinggale** [comment]
I would like to fix the issue "the correct way". However it's most likely not worth the time.

The ranger already has a reputation of being useless. Maybe it should be rebalanced to have another purpose than the broken invisibility.

**Comment by raystuttgart** [comment]
Sounds good.
"Invisibilty" can be deactivated easily in XML which might make sense.
Small "Colopedia" changes are no problem either.
About "rebalancing" the Ranger I will try to come up with a suggestion (probably in the forum).

About "fixing Invisibility" I currently do not consider it to be worth the time.
There is simply no real game mechanic in WTP that might make use of it and I also do not have any idea to make it worthwhile.

I will assign the issue to myself for now if nobody minds.

**Comment by raystuttgart** [comment]
A) For now, I have deactivated "INVISIBILTY_RANGER" for all **Units** in **XML only**.
(Only the Unit Ranger was using it anways and it was not even working perfectly.)
This includes the "**SeeInvisible**". (for Native Mercenary and Scout)
The **Colopedia Text** of Ranger was adjusted as well.

B) The ranger has now gotten **2 Free Promotions** though:
Veteran (+10% strength)
Forced March (+1 Sight, no Movement Malus from Terrain

---------
The rest of the ragner was unchanged.
It was actually a really powerful Unit already. (Good Strenght + lots of Terrain Bonusses)
But now witht the "Sight Bonus" it should become even more valuable.

I feel this is pretty balanced and fair now.
(It is a powerful Unit but only given by DLL-Event, Python Events and Founding Fathers.)

Nobody should complain anymore about "Ranger being Useless".
