### ISSUE TITLE
City names are displayed incorrected due to being hardcoded and can't be translated

### ISSUE THREAD

**Issue by Nightinggale** [We-the-People-civ4col-mod/Mod#259]
The names for the cities for each civilization are listed in CivilizationInfos.xml. Here they are written directly without using the TXT_KEY system.

This has the following issues:

- No unicode support
- Non-ASCII characters are displayed incorrectly
- No translation support
- Complete failure if used with non-western European language (like Russian)

Converting each name to a TXT_KEY and then adding a text xml with all the cities will solve all those problems.

Semi related. Cities are apparently named using the local language yet for some reason the capital of Denmark is written in German, not Danish. It should be København if we go for consistency.

**Comment by Nightinggale** [comment]
I have been thinking about this. If we need to list the city names in TXT_KEYs anyway, why should we bother to list them in CivilizationInfos in the first place?

If we want to do this clean, all we do is to add a tag for a string prefix like TXT_KEY_ENGLISH_CITY_ and then the DLL can generate
TXT_KEY_ENGLISH_CITY_0
TXT_KEY_ENGLISH_CITY_1
TXT_KEY_ENGLISH_CITY_2
etc

Right now the game relies on CvCivilizationInfo::getNumCityNames(), but the TXT_KEY system doesn't give us that number as the code is right now. We would either need an int tag in CvCivilizationInfo or read it from the text system indirectly.

Indirectly would be something like looping through all the names and read them from the text system. If input string == output string, then the TXT_KEY isn't present and we know the number of names. Alternatively we can mod the string setting system to store numbers if a certain prefix is used, though I would say the Text xml file reading is complex enough as it is. I would rather have a loop elsewhere, like in the CvCivilizationInfo::read().

**Comment by raystuttgart** [comment]
That is implemented already to my knowledge.

**Comment by Nightinggale** [comment]
This is NOT implemented and personally this occasionally results in font encoding issues ingame for me so let's keep this one open.

**Comment by Nightinggale** [comment]
Fixed after only 4 years.

**Comment by raystuttgart** [comment]
Nice. 👍
