### ISSUE TITLE
Request: Return of the Town Guard

### ISSUE THREAD

**Issue by orbayyazanlar** [We-the-People-civ4col-mod/Mod#260]
Greetings. I know Town Guard was removed from RnR at some point but I really liked it. Colonists should have their own melee units as well. I'm putting a poll on civfanatics about the issue.

https://forums.civfanatics.com/threads/poll-for-return-of-town-guard.643228/

**Comment by raystuttgart** [comment]
As far as I understood, this would break savegames.

So we will probaly **not** do it with the **next small "improvement and bugfixing" Release**.
But I currently do consider it **planned for 2.8** and will take the (little) effort for doing it as written in the poll.

**Comment by raystuttgart** [comment]
Since it is on the todo list and we have a thread in our forum for it, we do not need the additional issue.
It is basically just a duplicate.
