### ISSUE TITLE
Pet Wolf cant enter native teritory

### ISSUE THREAD

**Issue by MichaelQuell** [We-the-People-civ4col-mod/Mod#263]
I got a random event, which gave me a pet wolf. The wolf cant enter the teritories of the natives. I tested this also with all the other animals the same issue apears.

**Comment by raystuttgart** [comment]
Why is this an issue if your "Pet Wolf" can enter Native Territory?
These Natives might simply have heared of your tame Wolf and know that it will not harm them.

You are still not allowed to attack any Native Settlements or Native Units you are at peace with.
That would be an issue for me - but it is not the case.

Thus I see no need to change.
