### ISSUE TITLE
Reduced # of Native Civs option

### ISSUE THREAD

**Issue by dcrookston** [We-the-People-civ4col-mod/Mod#272]
Add an option when starting a game to reduce the number of native civs that are included.  This would result in each civ having more settlements and a larger population, making them more dangerous when going to war with them.

**Comment by raystuttgart** [comment]
In Custom Games you can already set yourselfs how many Native Nations you want.
In Scenario-Maps it (with preset Players) it will not work anyways.

This issue is pretty much unnecessary and just wasted effort (see explanation above).
Could we close it?

**Comment by raystuttgart** [comment]
I will close this because it is already possible in Custom Games.
