### ISSUE TITLE
Turn JustInTimeArray into a template class

### ISSUE THREAD

**Issue by Nightinggale** [We-the-People-civ4col-mod/Mod#280]
Right now JustInTimeArray is a template class, which contains the following members:

```cpp
T* m_tArray;
const unsigned short m_iLength;
const unsigned char m_iType;
const T m_eDefault;
```

This will use 12 bytes (8 if T is one byte). I started wondering what would happen if it's just a T pointer and the rest being done with using two templates T and xmlType. First of all this will bring it down to 4 bytes, meaning it will compile into just a regular pointer and the memory overhead is gone. It will however still add a bunch of functions, which makes coding easier and they are designed to catch bugs at both compile and runtime time, making it easier to write bugfree code.

getType and getLength are both inline functions, which returns essentially an int each. They can be turned into specialized functions (like one for YieldTypes, one for BuildingTypes etc), in which case they can return enum values. This will allow the compiler to know the type and length at compile time and optimize accordingly. getLength would turn into getting a global variable when xml hardcoding is turned off, which would still work just fine.

m_eDefault should be set to 0. We really rarely use it for any other value anyway. I can only think of one exception, which is when generating the default CivEffect. This can be fixed with a new function to set all values to whatever argument value the caller sets. We should keep m_eDefault, but make it a static const. This way if we really need to add a default in the future, we can just change it back. We can use specialized getDefault too, like if it's a TerrainArray of Routes, then we can make a default inline getDefault returning 0 while routes will return NO_ROUTE. Right now I'm not sure what we can use this for, but since the current code supports it (even with xml type conversion in savegames), it would be stupid to just remove it without any plan to bring it back.

The template allows adding compile time checks. Like the overloaded operators will only be able to compile if they use the same template. Right now if you type in RouteArray = ImprovementArray, it compiles just fine and will trigger an assert. With a template it will fail to compile because it doesn't have an operator/function to call when they mismatch.

Index arguments can be of the template type. UnitArray can only be accessed with UnitTypes variables. If somebody tries to use UnitClassTypes, it will fail to compile.

The bad stuff:

The header file will need to specify each valid type. It's not as bad as it sounds because it can be a macro and then a line for each xml file, which can use a JIT array. PlayerArray (in savegame branch) does this and next to the macro calls it has a generic get function, which will be used if a type is missing a macro. The trick is that the generic get function has no return, hence it makes a compile error in the function in question (click to jump to the right place in the code). The programmer will then read the text in the empty function, which states another macro call is needed. I consider this to be a minor issue.

The cpp file however needs to fill in all the types used and there is no clever compiler trick to tell the programmer where the issue is. Missing declarations will result in missing functions at link time without specifying which file. The only fix to avoid this issue that I can think of is to skip the cpp file entirely and make it a header file. However I'm not happy with making big functions like the savegame code inline.

Being template the compiler will make a new instance for each type rather than sharing. Right now YieldArray and UnitArray will use the same savegame code. Using templates they will have unique code in the dll even though they technically can share. The frequently used code tend to be in the header file and is inline, but still it's something to consider.

Another issue is partial arrays. Currently we have YieldCargoArray, which is precisely the same as YieldArray, except it's shorter (less memory allocated). We can't have both if they both rely on using the template for YieldTypes. This means we need a new YieldTypes, one which is interchangeable with YieldTypes, but can be told apart when it comes to templates. What I came up with is:

```cpp
class YieldCargoTypes
{
public: 
	operator YieldTypes() const
	{
		return m_eYield;
	}

	YieldTypes operator =(const YieldTypes& eYield)
	{
		FAssert(eYield < NUM_CARGO_YIELD_TYPES); // useful?
		m_eYield = eYield;
		return m_eYield;
	}
private:
	YieldTypes m_eYield;
};
```

Very quick testing indicates that it is working as intended and that it doesn't matter if a variable is YieldTypes or YieldCargoTypes. They can be assigned to each other, both can be used when a YieldTypes argument is needed etc. The same approach can be used for other reduced size arrays, like I'm wondering about an array, which only holds data for units, which can join a city. There is no need to have array data for animals if the array is used to figure out if the school can teach the unit in question etc. Since there are so many non-city units, this is both a lot of memory and a lot of loop iterations to save. There might be other cases as well where a reduced array length is useful and our "library" classes should support this concept.

Any thoughts on this?

**Comment by Nightinggale** [comment]
Switching to a template means the array will work with a default constructor. This usually doesn't matter, but new can only use the default constructor, meaning the template approach allows an array of JIT arrays.

This is a really strong argument for switching to the template approach. It's not even a theoretical issue because I started to think about it because I just happened to require a player array of culture arrays. This issue makes it a whole lot harder to write reusable code.

**Comment by clonkia** [comment]
Seems like a good idea.

**Comment by Nightinggale** [comment]
After some careful consideration and research, I have come to the conclusion that it's likely the time to retire JIT arrays. The issue is that JIT arrays are 6 years old and not well planned. It's a simple array, one with automated memory allocation (hence the name), but then it has been exposed to feature creep multiple times and it now contains code, which is no longer in use etc.

Instead I want to write a new template class from scratch, which can be designed according to the current needs. The functions should be the same (get, set, add, read, write etc) meaning in most cases existing code will work if the variable type is changed. In fact changing the "subclasses" like YieldArray will in most cases be enough and the individual places where YieldArray is used will not need updating.

I'm thinking of calling the new class XmlArray, though I'm not completely happy with that name. Ideas are welcome.

The new array class should support the xml lengths like JIT does now, but it should also be easy to add non-xml types like PlayerTypes and TeamTypes.

I have a 2D version of the array, which is nearly complete. It's an array of arrays (currently array of jit arrays). Works the same way, except it takes another template parameter in the class and as arguments for get/set.

**Comment by Nightinggale** [comment]
Replaced by EnumMap.
