### ISSUE TITLE
Assert Failures

### ISSUE THREAD

**Issue by Drunk-Monk** [We-the-People-civ4col-mod/Mod#282]
Just some Assert failures along with a save game before they happen. 

![Annotation 2019-09-25 204237](https://user-images.githubusercontent.com/49459725/65809855-e0265380-e167-11e9-9238-bc41bc32eb36.png)

![Annotation 2019-09-24 221043](https://user-images.githubusercontent.com/49459725/65809863-e9172500-e167-11e9-919c-66a86b78ddf3.png)

[Dominic AD-1633-April- 2530 - 10302 Asset Failure .ColonizationSave.zip](https://github.com/We-the-People-civ4col-mod/Mod/files/3664984/Dominic.AD-1633-April-.2530.-.10302.Asset.Failure.ColonizationSave.zip)

**Comment by Drunk-Monk** [comment]
![Annotation 2019-09-25 152842](https://user-images.githubusercontent.com/49459725/65809947-32b43f80-e169-11e9-8660-8199986b8646.png)

![Annotation 2019-09-25 171049](https://user-images.githubusercontent.com/49459725/65809971-77d87180-e169-11e9-8e7f-2a45284a8049.png)

[Dominic AD-1650-July 9059 -2530 - 10302 - 3298 Asset Failure .ColonizationSave.zip](https://github.com/We-the-People-civ4col-mod/Mod/files/3664985/Dominic.AD-1650-July.9059.-2530.-.10302.-.3298.Asset.Failure.ColonizationSave.zip)

**Comment by Drunk-Monk** [comment]
![Annotation 2019-09-26 221922](https://user-images.githubusercontent.com/49459725/65809985-b9691c80-e169-11e9-9916-5878aca510ca.png)

Unfortunately this one did not occur just before a save game

**Comment by Drunk-Monk** [comment]
![13631 Assert Failure](https://user-images.githubusercontent.com/49459725/66086997-9361c480-e53b-11e9-9c0e-495c23339e4a.png)

[Dominic AD-1700-July Assert Failure 13631.ColonizationSave.zip](https://github.com/We-the-People-civ4col-mod/Mod/files/3683676/Dominic.AD-1700-July.Assert.Failure.13631.ColonizationSave.zip)

![Assert Failure 15810](https://user-images.githubusercontent.com/49459725/66087098-dfad0480-e53b-11e9-8bf7-57c2d4c53a1f.png)

[AutoSave_AD-1704-January Assert Failure 15180.ColonizationSave.zip](https://github.com/We-the-People-civ4col-mod/Mod/files/3683682/AutoSave_AD-1704-January.Assert.Failure.15180.ColonizationSave.zip)

**Comment by Nightinggale** [comment]
We have a list of [known assert failures](https://github.com/We-the-People-civ4col-mod/Mod/wiki/List-of-common-assertions). Getting savegames for those isn't bad though.

We should fix all of them, but they aren't that easy to fix. For instance checkPower checks the cached power against the real value once a turn and when it says it failed, what it actually says is it did something since last check, which broke the cache, but it delivers no clue to what went wrong.

**Comment by Drunk-Monk** [comment]
The first four occurred every time I continued my save game in a new session, and first occurred when I had played the first one hundred turns (approximately). The last three were rarer and occurred towards the end of the game.

**Comment by ErikSandbraaten** [comment]
Closing, most of these are either fixed, already listed or part of other issues
