### ISSUE TITLE
2.8 Yield Branch: Observations, suggestions, questions and bugs

### ISSUE THREAD

**Issue by Drunk-Monk** [We-the-People-civ4col-mod/Mod#283]
### Observations

The game is much faster, RAR would often take upwards of five minutes to load to the main menu and to load a save game could take a couple of minutes (although I never experienced really long end of turn times). Now the game loads in under 90 seconds and save games in less than one minute.

The AI seems to be better at colony location and development, tending to build next to rivers and resources and better at selecting not to start to close to other Europeans. Although if you look into the saves in the thread of asset failures you will find in my early save games that the Spanish failed to develop, not even building many roads. All the powers still love to spam coastal boats.

I don’t know if you adjusted the AI, or this is just a geographical quirk, but the REF, didn’t just chose to focus all its strength on my largest and most heavily guarded cities and instead took a path through a forested peninsula (although this did give me more time to prepare) and it even made a diversionary force through other players territory. 

I did not receive any war of independence help from other Europeans powers after the DOI, whilst this feature was not originally well implemented, it added a lot of flavour and I would like to see it return, but with better balance.

I didn’t experience any of the native factions either offering me mercenaries or native slaves, with one exception which happened after the Declaration of Independence and after choosing native rights. Given that the message when they sale, is related to them selling a surplus at the end of a war it would be good to see this tied together, with war events.

The natives seemed to have a lot of braves and successfully fought back against the European powers.

### Suggestions

**Economy / Balance**

At the moment large buildings require more resources, however it’s only the resources from vanilla (Silver, tools and stone). It would be good to see other resources required, seeing as the mod has such diversity of resources which are underutilized, for example it would be good to see Cathedrals and grand state buildings that require rare wood / furniture / leather / gold / gems. Bastions would require cannons. Almost all industry required horses in some role, until the 20th century, hence why we still use “horsepower”. Train oil was also exceptionally valuable in early industry. It would be good to see this represented in game.

I also think the larger military buildings (Arsenal, Great tool factory, Bastion) should increase REF size as they are obvious threats to the King’s power and assets to the player. 

Would you consider rebalancing prices? It’s just very easy as soon as you are established, to make more money than you can spend, because there are so many valuable yields.

I think Industrial goods (tools etc) should always be more expensive in Africa, unless there is a specific event

Make coastal boats require tools, just as fishing boats do. I think this will also stop the AI spamming them so much.

Carriages should require the Wheelwrights Workshop and require horses etc just as with normal wagons

As per this thread https://forums.civfanatics.com/threads/suggestion-ability-to-get-professional-missionaries.649738/ I agree with the OP, that we should be able to request missionaries from the church. It would also be interesting to see immigration shaped by the civilisation and leaders’ traits i.e more aggressive Civs and leaders have a greater likelihood to see Soldiers, agricultural leaders get Farmers and Fishermen etc

Is it possible to have Shipwrecks spawn randomly and drift, rather than have them pre-spawned at the beginning of the game, it’s strange to arrive at the continent full of more European wrecks, than there are ships constructed in the average game. Also, the real benefit is the initial boost to your early ships, which counter intuitively end up faster than your later ships.

**Diplomacy / Management** 

Whilst the mod has some of the notions towards the health and happiness mechanics of Civ 4, it would benefit to be fleshed out, adding another dynamic to the game other than just trying to produce as much as possible, as quickly as possible. For example, colonists could request that you build educational, religious and entertainment buildings and supply certain goods (Tobacco and Alcohol for example). These would rise in complexity and price as the game goes on and happiness would be also shaped by Native Raids, lengthy wars, Pirates etc. At the very least a notification, when your city becomes unhealthy would be nice 😊

As per this thread https://forums.civfanatics.com/threads/native-ai.645834/page-2#post-15457248 I think it would be better that European culture does not automatically “dominate” the natives. The natives have the possibility to construct culture producing buildings, and during the Constitution the player is asked if they want the possibility to override or respect native boundaries. This suggests that it was not intended to be this way in the game, but it was just poorly implemented, as with so many other features in vanilla. Instead whilst I think the European culture should be more powerful (and with greater potential due to the range of buildings) it should compete with Natives as it does with other powers in the game.

I think John Jay and other Founding Fathers should give you a choice about peace rather than automatically establishing peace, as often it is not in your interest to do so.

Unlike in the Civilisation games where understandably all Civilisations start with a neutral opinion of each other, it would be good to see the other players holding a range of opinions on each other, from friendly to hostile. For example, in reality much of colonisation was driven by competition between the powers, however as of now this is not represented, if you are the British and start next to the French and Spanish it’s of no real consequence. Also, all of the large Native states (Aztec triple alliance, Incan Empire, Iroquois) fell because the Europeans were able to utilise the grievances, of all the peoples they had previously attacked or conquered. However, in the game the natives start with a neutral opinion and this tension does not exist. Obviously, the Aztec do not need to feel threatened by the Inuit, but it would be good to see them have an opinion of their neighbours.

### Questions 

Does the AI know how to fish/whale? Has anybody seen this?

Thanks a lot to everybody who contributed their time and energy to this great project. If you have any questions don't hesitate to ask.

**Comment by Drunk-Monk** [comment]
### Bugs

I believe that the event where the king asks for 200 lumber to help build his fleet seems to be bugged. It doesn’t seem to function correctly.

Refugees don’t seem to have learning by doing enabled, so can’t progress in their profession and also have the sound effects of elder statesman enabled.

The AI ships act very strangely, when near the edge of the map, near the travel to Europe area. Constantly turning in circles and travelling back and forth, rather than effectively patrolling.

The AI is very poor at building defences larger that the stockade.

Natives can’t trade blades or coloured cloth and possibly other resources.

Capturing an enemy city should not cause Natives who lost the plots many turns ago, to declare war for stealing their land.

In the attached save game and image I encountered a bug when I put a seasoned scout into a settlement, hoping to transform the unit into a cavalry unit. However, I was then unable to withdraw the seasoned scout from the settlement, until I had cleared its profession. 

![Seasoned Scout bug](https://user-images.githubusercontent.com/49459725/66233112-291e6080-e6b0-11e9-9872-c28ba89cb1b4.png)

What is this promotion? At 50% strength it is incredibly strong.

![What is this promotion](https://user-images.githubusercontent.com/49459725/66233195-5c60ef80-e6b0-11e9-9423-f116fc7837b7.png)

I believe this event related to culture is bugged.

![Culture Bug](https://user-images.githubusercontent.com/49459725/66233238-7ac6eb00-e6b0-11e9-9cea-2b017b5aa719.png)

Once you start to abandon a city you cannot change your mind. It also messes with the UI.

![Colony Abandonment](https://user-images.githubusercontent.com/49459725/66233271-9205d880-e6b0-11e9-9a86-f828327b5d88.png)

Dragging treasures onto the Galleon, doesn't fill out the UI

![Galleon UI issue](https://user-images.githubusercontent.com/49459725/66233341-bd88c300-e6b0-11e9-9940-b2f773f43904.png)

**Comment by Nightinggale** [comment]
> The game is much faster, RAR would often take upwards of five minutes to load to the main menu and to load a save game could take a couple of minutes (although I never experienced really long end of turn times). Now the game loads in under 90 seconds and save games in less than one minute.

Keep in mind that you played RAR without assert checks and WTP with assert checks. Enabling the checks slows down the game around 30%. There is also still not insignificant stuff on the todo list regarding performance.

It would be nice to have each bug or proposal in a separate issue. This will make management easier as we can assign milestones to each and close them one at a time as features are implemented. This becomes really useful when you ask for all open issues for a certain milestone (like 2.8) as it will then create a todo list for the remaining tasks for the next release. It also tells how many tasks for the milestone in question have been completed, meaning you can go "oh, 40% completed. It was 32% a week ago. Looks good". Also issues can link to each other, allowing comments like "we should do this, but we can't until feature X is implemented", which will not only link to feature X, but also add a link in the other issue telling that it was mentioned.

I will not comment on the individual bugs/proposals. That would be something for when there is a dedicated issue for each. I like most (all?) of the feedback and it's really useful for improving the game.

**Comment by Drunk-Monk** [comment]
Ok, I will do so. I tend to wait until I have completed a game to contribute, and I can organise my thoughts better through long form writing. But I can appreciate that breaking the post down, would make it far more comprehensible to others in terms of concrete objectives.

**Comment by raystuttgart** [comment]
This is a thread from 2019 and completely outdated.
Also discussions like that are better done in the forum - here nobody will decide it anyways.
