### ISSUE TITLE
2.8 Yield Branch: Seasoned Scout bug

### ISSUE THREAD

**Issue by Drunk-Monk** [We-the-People-civ4col-mod/Mod#285]
In the attached save game and image, I encountered a bug when I placed a seasoned scout into a settlement, hoping to transform the unit into a cavalry unit. However, I was then unable to withdraw the seasoned scout from the settlement, until I had cleared its profession.

[Dominic AD-1695-July Seasoned Scout bug.ColonizationSave.zip](https://github.com/We-the-People-civ4col-mod/Mod/files/3693480/Dominic.AD-1695-July.Seasoned.Scout.bug.ColonizationSave.zip)

![Seasoned Scout bug](https://user-images.githubusercontent.com/49459725/66257947-013d0480-e765-11e9-80c4-2e559a3926ab.png)

**Comment by raystuttgart** [comment]
I just tested and cannot confirm that with the current beta.
It was working perfectly for me to put him in the settlement as worker and make him a Scout again.

Are you still able to reproduce?
Please try again with the current beta.

**Comment by Drunk-Monk** [comment]
This bug was from a Branch of 2.8 with altered yields. So I won't be able to reproduce in 2.7.2

**Comment by ErikSandbraaten** [comment]
Closing, most likely it has already been fixed or it was never a bug to begin with
