### ISSUE TITLE
2.8 Yield Branch: Refugee Bug

### ISSUE THREAD

**Issue by Drunk-Monk** [We-the-People-civ4col-mod/Mod#286]
Refugees don’t seem to have learning by doing enabled, so can’t progress in their profession and also have the sound effects of elder statesman enabled.

**Comment by raystuttgart** [comment]
Yes but probably that is not a bug.
It might be working as intended by Schmiddie.

Although we can of course discuss to change this.
This would be a simple change in the XML settings.

**Comment by raystuttgart** [comment]
Learning by doing not enabled is already fixed and commited.
I have no idea what I should do with the sounde effect though - also don't consider it a real issue.
