### ISSUE TITLE
2.8 Yield Branch: Galleon and Treasure Issue

### ISSUE THREAD

**Issue by Drunk-Monk** [We-the-People-civ4col-mod/Mod#287]
Dragging treasures onto the Galleon, doesn't fill out the UI. It would be good to see the icons fill out the ship, as it would be easier for the player to see.

![Galleon UI issue](https://user-images.githubusercontent.com/49459725/66258022-e74ff180-e765-11e9-883a-7cb2079e1d7e.png)

**Comment by raystuttgart** [comment]
Way too much effort to implement for basically no gain.
So let us please cancel this, it is unrealistic.
Nobody will ever work on this and nobody really complains about it either.
