### ISSUE TITLE
2.8 Yield Branch: Great Artist bug 

### ISSUE THREAD

**Issue by Drunk-Monk** [We-the-People-civ4col-mod/Mod#289]
This event about a great artist emerging to boost culture, does not seem to function correctly. 

![Culture Bug](https://user-images.githubusercontent.com/49459725/66258106-e9ff1680-e766-11e9-9530-691d8716ecd1.png)

**Comment by raystuttgart** [comment]
I will take a look.

**Comment by raystuttgart** [comment]
This is fixed now.

Seems as if it was an old **Vanilla** bug. 
First thought I could not trust my eyes that it was not yet discovered.
It was f... obvious.

Will push to fixes now.
