### ISSUE TITLE
Issue with group and ungrouping : inconsistent behavior when a ship previously grouped is selected individually.

### ISSUE THREAD

**Issue by abmpicoli** [We-the-People-civ4col-mod/Mod#29]
https://forums.civfanatics.com/threads/religion-and-revolution-bugs-and-todos.449958/page-117#post-14971396 

> Accidentially send My Linienschiff (Battleship?) to Port Royale - not able to send it Back to the Colonies. The Battleship was in a Convoy with Some Pirate Ships witch i sent To Port Royale with some freight. I sent the ships directly from New Amsterdam to Port Royale but I've seperatet them from convoy first (if I remember right)

**Comment by abmpicoli** [comment]
Evaluating if the issue proceeds.

**Comment by abmpicoli** [comment]
UNCONFIRMED the original issue, but we have other issues with the  buttons. 

It seems the issue is related to stacking in general... When we stack/ unstack units, it seems the buttons aren't adjusted for the units in every case... Example: this situation have a privateer and a coastal ship. While separated, the pirate can go to port royal:
![image](https://user-images.githubusercontent.com/1733170/45660980-d3d9d600-bad1-11e8-8fee-a89f5c68ac05.png)

I place it at the same tile as the coastal ship: 
![image](https://user-images.githubusercontent.com/1733170/45661023-0be11900-bad2-11e8-980a-c133e5734dfc.png)

I stack. The button for going to port royal disappear:
![image](https://user-images.githubusercontent.com/1733170/45661063-421e9880-bad2-11e8-8db5-e3b261e2d288.png)

I unstack by clicking at the pirate unit. The pirate can no longer go to port royal / europe until it moves again... 
![image](https://user-images.githubusercontent.com/1733170/45661159-a17ca880-bad2-11e8-8bad-2788f6bac260.png)

If I unstack by clicking the "Separates the group" 
![image](https://user-images.githubusercontent.com/1733170/45661211-d38e0a80-bad2-11e8-9090-2347309560fc.png) button this doesn't happen. 

Now I have a stack with a pirate and a normal ship. In this case, I don't see the issue mentioned: I can't get the warship into port royal...
![image](https://user-images.githubusercontent.com/1733170/45661383-b148bc80-bad3-11e8-99b6-68030442786c.png)

However, when I split the group by simply clicking at the privateer , two things happen: 
* The button for "create a group" appear, even if there is only one ship.
* The ship can't go to europe as well...
![image](https://user-images.githubusercontent.com/1733170/45661502-2a481400-bad4-11e8-968d-8e1f764f823f.png)

The workaround is to stack everything, unstack everything and then click at the ship I want to move.

**Comment by ErikSandbraaten** [comment]
The issue with hidden nationality ships allowing other ships to travel to PR has been resolved here:
https://github.com/Religion-And-Revolution-Extended/Mod/commit/ed3d2e7eb8ade1d7eefde6151b07b4d1a60c4373
"BUG22: We only allow ships to sail to Port Royal if all units in the group are allowed to do so"

**Comment by ErikSandbraaten** [comment]
Regarding the coastal ship, did you place it in the ocean ? This is not allowed by the movement  rules (unless it's bugged), but it is possible to construct "invalid gamestates" by using the WB. so be careful.

**Comment by ErikSandbraaten** [comment]
The grouping rules could probably have an overhaul. I suppose it is a minor issue that the smuggling ship would have to move a tile to "refresh" its state. It is also possible to end up with multiple buttons (if my memory is not corrupted :/)  for the same action! this is clearly a bug, albeit a minor one

**Comment by abmpicoli** [comment]
In the next days I will be playing the game , instead of dealing with mods. Later I may get back to it, but if someone wants to stand up and work with this, be welcome ... :)

**Comment by ErikSandbraaten** [comment]
Should have been fixed by now
