### ISSUE TITLE
2.8 Yield Branch: Scout issue

### ISSUE THREAD

**Issue by Drunk-Monk** [We-the-People-civ4col-mod/Mod#290]
This converted native scout, seems to have an incredibly strong promotion. What is this? 

![What is this promotion](https://user-images.githubusercontent.com/49459725/66258164-5d088d00-e767-11e9-8162-6ebf4f115ea0.png)

**Comment by raystuttgart** [comment]
This is not a normal promotion this is given by a founding father and he gives it explicitly to Converted Natives.
It is not a balancing issue but acutally makes Converted Natives a little bit useful in War.
It was implemented by purpose (already in TAC).
