### ISSUE TITLE
2.8 Yield Branch: Native Trade

### ISSUE THREAD

**Issue by Drunk-Monk** [We-the-People-civ4col-mod/Mod#291]
Natives can’t trade blades or coloured cloth and possibly other resources. Whilst some items they cannot use like cannons, it seems strange that they would desire cloth, but not coloured cloth and want tools but not want blades.

**Comment by raystuttgart** [comment]
Ok, I adjusted it. 
They now buy also Blades, Coloured Cloth, ... since it is in fact realistitic / immmersive.
