### ISSUE TITLE
Diplomacy should not start neutrally

### ISSUE THREAD

**Issue by Drunk-Monk** [We-the-People-civ4col-mod/Mod#299]
Unlike in the Civilisation games where understandably all Civilisations start with a neutral opinion of each other, it would be good to see the other players holding a range of opinions on each other, from friendly to hostile. For example, in reality much of colonisation was driven by competition between the powers, however as of now this is not represented, if you are the British and start next to the French and Spanish it’s of no real consequence. Also, all of the large Native states (Aztec triple alliance, Incan Empire, Iroquois) fell because the Europeans were able to utilise the grievances, of all the peoples they had previously attacked or conquered. However, in the game the natives start with a neutral opinion and this tension does not exist. Obviously, the Aztec do not need to feel threatened by the Inuit, but it would be good to see them have an opinion of their neighbours. Destroying Natives Civs whom the other Native Civs aren't hostile towards, should obviously make them more suspicious of you.

**Comment by raystuttgart** [comment]
It is already possible to create Scenario (Maps) where the diplomacy status is not neutral.
But for random games - which most people play - it really should stay as it is.

Closed because this will never be worked on anyways.
