### ISSUE TITLE
Changing Russias Colour?

### ISSUE THREAD

**Issue by Drunk-Monk** [We-the-People-civ4col-mod/Mod#306]
Is there any possibility of changing Russia’s colour? Its very similar to Portugal’s and the colour green has never featured on any Russian flag or state symbol. I think a shade of red might suit them better.

**Comment by Nightinggale** [comment]
You can alter the color in xml (civ info I believe). The colors are in vanilla, but we can copy that file to the mod, which will allow us to add more colors. When adding a color, we declare the color using RGB values, meaning we can get whatever color we like.

Technically this is simple to do. Figuring out which color to use, which works well with the other colors is less trivial.

**Comment by raystuttgart** [comment]
Another aspect to consider:
The "mission crosses" should also have matching color to the Player color.
This however increases effort (at least a bit if you know what you are doing) because GameFonts need to be adjusted.

**Comment by Nightinggale** [comment]
As always when touching the GameFont files, use GameFontEditor. It removes a lot of ways to mess up the files, which are rather time consuming to fix. It supports copy paste (control +c/v), making the task of adding new icons way easier than the interface indicates it to be.

**Comment by raystuttgart** [comment]
I was using GameFontEditor as well (at least later on).
When we started Civ4Col modding, we did not have it though and it was really tedious.

But you are right, it it much easier by using GamFontEditor.

Just wanted to mention though that the "Mission Cross" needs to be adjusted as well - so it is not forgotten.

**Comment by MrZorG33** [comment]
red because of the association with the USSR?)
but the Russian Empire, or rather the Russian-American Company, participated in the colonization of America. here is her official flag:
![image](https://user-images.githubusercontent.com/61798883/117858803-eb73b780-b296-11eb-90e4-0b5582a366a3.png)

one must choose a color that is not used by other nations.

**Comment by raystuttgart** [comment]
All prime colours are already taken and people got used to them. It never really was a problem.
So let us please not start any unnecessary efforts 14 years after Russia was implemented.
