### ISSUE TITLE
Orthodox Church

### ISSUE THREAD

**Issue by Drunk-Monk** [We-the-People-civ4col-mod/Mod#308]
Russia should not have Jesuits Missionaries, as Catholics especially Jesuits were a tiny minority in Russia, and did not participate in colonisation. Orthodox Monastics played the largest role in conversion. This looks like a good model for a priest:

https://forums.civfanatics.com/resources/russian-orthodox-priest.16388/

**Comment by Nightinggale** [comment]
I think we should drop the idea of civ specific units, which does the same thing. All nations should have expert missionaries and not add more units purely for the sake of assigning a different name. We can still keep different graphics, which can be done with civ art styles.

Each time a unit is added, the game will slow down a little and use a bit more memory, even if the unit is never used. With this in mind, it seems silly to have identical units.

**Comment by Drunk-Monk** [comment]
I am in total agreement with you there. I am just suggesting a name change and different unit art.

**Comment by raystuttgart** [comment]
@Drunk-Monk 
Different **UnitArtStyles** can be done without technically having a different Unit.
(But then all Units need to have the **same name**, same balancing and Colopedia texts.)
But when we also want to have a **new name for the Unit** (or different balancing or different Colopedia texts), we currently need to add a new Unit technically.
But I do get your point that "Jesuit Missionary" does not fit for Russia.

@team:
**Thus I suggest the following compromise:**
We make an **exception** to the rule **this one more time** (so we can also have a different name and Colopedia text) but later on we try to **avoid adding new Units** whenever we can and instead try to simply **use new UnitArtStyles**.

@Drunk-Monk: 
**If every team member gives his ok**, could you please ask **Schmiddie** if he would like to create **2D graphics** (Europe Screen/City Screen) and **Button** (in Atlas) for Colopedia. 
If he creates them, I volunteer to add (configure) **"Orthodox Monastic"** in Release 2.8. - If we don't get the 2D graphics and Button, we currently (in 2.8) can not do it anyways. (Not even if we use just different UnitArtStyles and call them all "Expert Missionaries".)

**Comment by raystuttgart** [comment]
I will assign it to me and discuss it with Schmiddie.
If the team agrees, I will add the Unit **"Orthodox Monastic"** as "Expert Missionary" for Russia - in **Release 2.8** - if Schmiddie is interested in creating the 2D graphics and button.

**Comment by Nightinggale** [comment]
I'm wondering if we need multiple expert missionaries. We have the option to have one and then use art styles to display them differently for different players. The real question is if we want to keep it simple with one pedia page for all (making it clear they are all the same) or if we want to provide a different pedia page for each and make a unique kill count for each type etc.

One unit with multiple art styles will also be faster to handle for the computer and use less memory. However the difference is likely so minor that it's not a valid argument if we want a pedia page for each or whatever other argument we might have for having a unique unit type for each.

**Comment by raystuttgart** [comment]
"Religious Units" (like Expert Missionaris) are kind of special for me and I believe they are **worth** to have a **separate Name** and **separate Pedia** text. 
The difference in effort is really also not that big and the difference in performance should not be noticable for one single Unit.

I would definitely not like to do it for all "Worker Experts" or "Military Experts" for our other Professions though because I historically also don't see any big difference.
Those are fine with just having different UnitArtStyles.

**Comment by raystuttgart** [comment]
@Schmiddie1979 

Could you take a look at this?
Maybe we can really give Russia separate Unit Graphics for:

A) Priest (3D and 2D)
B) Missionary (3D and 2D)

If we have the graphics, I can do all the configuration.

@team

If we do "Religions of the New World" this even makes more sense.

The UnitClassType will of course be the same, but the UnitType will differ.
(This concept is massively used in Civ4 BTS and should not really cause performance issues.)

**Comment by Schmiddie1979** [comment]
This is no problem. I have already two units in mind that could work.

**Comment by Schmiddie1979** [comment]
Work finished, 2D (including Button and city management) and 3D unit graphic for both - Russian missionary and Russian priest are ready and could be implemented (unit atlas has been updated). Hence please let me know how I can provide the files.

**Comment by raystuttgart** [comment]
@Schmiddie1979 
You could either:
A) attach them in the Forum (I would save them locally then)
B) attach them in our private chat in the team chat (I would save them locally then)
C) send them to me by mal (I would save them locally then)
D) Push / Commit to GitHub once we have set up the next "main" development branch after we published current release

**Comment by raystuttgart** [comment]
This is now implemented.
