### ISSUE TITLE
Bandits / Criminality

### ISSUE THREAD

**Issue by Drunk-Monk** [We-the-People-civ4col-mod/Mod#319]
Banditry, smuggling and rebellion against authority, was a huge problem in the Colonial and post-Colonial Americas. It would be great to see this recognised, rather than just fighting wild Animals who cease to be a threat, outside the very early stages of the game. This would also add more unpredictability and encourage the player to build troops outside of the late game. Perhaps at the same time as pirates appear we could have buccaneers appear on land.

**Comment by Nightinggale** [comment]
Animals is the barbarian player. It can easily gain the ability to use certain human units. M:C has bandits, which can enter your land and attack units and cities, even destroying cities. On the other hand they are human units, meaning if you attack and defeat a bandit, you have a chance of capturing said unit, which can then be used as any other unit, like added to city population.

It could be interesting to create rouge native units, meaning it's like native attacks, except it's not from a specific tribe, meaning you can have native combat without being at war with natives. Attacking and winning against such a unit has a chance of creating a native slave under your control.

Creating the units is easy. Creating the capture code is also doable. Creating the AI code to make them hunt Europeans is... not sure about that one.

We should link creation of such rouge units to difficulty level, meaning they won't appear when new players start at an easy level, but they will once experienced players select greater difficulty levels.

**Comment by Drunk-Monk** [comment]
This sounds promising. Rouge Natives are good, but alot of criminality in the Colonies, was American / European against American. We have the famous example of Port Royal and Buccaneers, some lesser known examples from the Latin American independence era are:

https://en.wikipedia.org/wiki/Jos%C3%A9_Tom%C3%A1s_Boves

https://en.wikipedia.org/wiki/Vicente_Benavides

https://en.wikipedia.org/wiki/Pincheira_brothers

**Comment by raystuttgart** [comment]
We have stuff like this now.

1) Revolting Criminals etc.
2) Defended Camps
