### ISSUE TITLE
Events

### ISSUE THREAD

**Issue by Drunk-Monk** [We-the-People-civ4col-mod/Mod#322]
Whilst somewhat present in vanilla, I'd like to see more boom and bust events to simulate the economic cycle. This would require you to make the most of all the range of your specialists and all the new resources in the game. It would add more of a challenge by adding a risk reward mechanic, rather than the situation now, where you face an economic landscape of diminishing returns once you begin exporting in bulk. 

For example, if you are constantly building things a building boom event could occur, that would add extra hammers of production, but would add to the price of buying materials (lumber, stone etc) and add to the cost of recruiting specialists in Europe (carpenters, stonecutters etc). Or say Coffee becomes unfashionable in Europe, so the player will want to switch to the more in demand (and valuable) Cocoa. A war in Europe could see the King ask you for troops and ships, and increase the flow of some types of emigrants (refugees) but restrict others (soldiers) #321 . A war in Africa would mean that demand for weapons and war material would sharply increase, but there might be some turns where the fighting makes the market inaccessible. These are just some ideas for events, that would add variety and break up the monotony of the mid and late game.

**Comment by raystuttgart** [comment]
A vague feature idea that nobody will really take care and should be discussed in the forum if really wanted.
There is no clear concept or anything visible in this post.

Issues like this are really not suitable for proper discussion and clarification.
