### ISSUE TITLE
Reforming Indian Raids

### ISSUE THREAD

**Issue by Drunk-Monk** [We-the-People-civ4col-mod/Mod#323]
Reform the Indian raids, looking at the forums this has been a concern of many other players. It is ridiculous that the Indians can gain 6000 gold from a failed raid, this is far more damaging than the REF. Also the player cannot defend against this, as even if the attackers are killed they still steal money. When a player destroys a village they may gain a treasure, which needs to be protected etc. Whereas natives can have a raid fail and then thousands of gold are magically spirited away to their settlements. This is internally inconsistent to the rules of the game.

Instead it would be good to see more nuance in the affects of raids, where not every raid has to end in the death of a unit and not have the natives just raid Cities. #319 

It would be good to see more reasonable consequences, such as:
" A Native raid was successful, 100 sheep etc were stolen"
or "A Native raid was successful, they have destroyed a plantation"
or " A Native raid was unsuccessful, but a storehouse was destroyed, 80 Coats etc were lost"
or " A native raid was successful a farmer has been killed / kidnapped"
or " A native raid was unsuccessful, but 15 tools were stolen from a wagon" 

Perhaps the underutilised happiness mechanic could also be used, with the towns populace or even the King being made unhappy by continual raids on settlements #317 . Make the fortification upgrades actually protect against this.

**Comment by raystuttgart** [comment]
In the forum in this [forum post](https://forums.civfanatics.com/threads/discussion-how-should-native-raids-cause-damage.653810/#post-15649760) I think devolution made a good suggestion at least for the **"gold stolen" aspect**.

@ErikSandbraaten : 
Are you planning to implement it for 2.7.2 (upcoming Release) or 2.8?
(There is no need to hurry of course.)

The rest of the effects is not that bad to my opinion, but if necessary they could be reworked as well.

**Comment by raystuttgart** [comment]
This is also outdated.
There were no complaints about Raids anymore.
It was also slightly rebalanced.
