### ISSUE TITLE
Differentiation between Swamps and Marshes

### ISSUE THREAD

**Issue by Drunk-Monk** [We-the-People-civ4col-mod/Mod#334]
I think the game could benefit from having both Swamp and Marsh terrain as these are both numerous in the Americas. These would both be more likely to form in the lowlands, around the 'Large River Terrain'. #34 #275 

Here is a good visual summary of the difference between the two:

https://upload.wikimedia.org/wikipedia/commons/a/a1/USGS_image_cropped.jpg

Swamps should be woodland and be located upstream, they could be a source of Furs, Fish and Shellfish, and when drained in lower warmer latitudes could become a source of Sugar, Tobacco, Indigo, Cotton and Rice.

Marshes are normally found nearer large bodies of water and could be a source of Iron, Salt and Pearls, and when drained should form especially fertile farmland.

Here is a nice visual database for use : https://forums.civfanatics.com/threads/graphics-infinite-terrain-pack.487022/

Further Reading:

https://en.wikipedia.org/wiki/Bog_iron

https://en.wikipedia.org/wiki/The_Fens

**Comment by ErikSandbraaten** [comment]
I would like more varied terrain as well just like in the original Colonization. 
More terrain types would allow us to distribute the yields a bit so that terrain like plains did not need to have 5 or so different potential yields.

#338 Is intended to solve the "diversity problem" in way that does not require additional terrain types.

**Comment by raystuttgart** [comment]
Actually the terrain in original Colonization did not have more variation than RaR at all.
There were basically the same types of terrain and the Yields of each plot were also not random.

I am generally open to the idea of differentiation of Swamps and Marshes.
During RaR I was thinking of that myself.

Major issue with this is the overall effort though:
- Graphics need to be found or created including Button atlas (medium effort) 
- XML configuration incl. Colopedia Text of the new Terrain needs to be created (small effort)
- XML for Plots and Bonus Ressources need to be adjusted (medium effort)
- Scripts for Map Generation need to be adjusted (medium effort)
- Existing maps need to be adjusted (major effort)
- Feature "Draining Swamps needs to be adjusted" (small effort)

If we find people that are interested in doing all of this it would be nice of course.

But other than "Differentiation of Swamps and Marshes" I don't think that we need to have even more Terrain Types.
I cannot imagine really that it would improve gameplay and fun for the majority of players.

**Comment by raystuttgart** [comment]
Already implemented in Plains.
