### ISSUE TITLE
WTP 2.7.2 beta1 issues

### ISSUE THREAD

**Issue by ErikSandbraaten** [We-the-People-civ4col-mod/Mod#339]
When you pop a conquistador from a goody the log simply says "Conquistador", likewise when receiving a with missionary from a hut.
When popping an indentured servant from a water goody the log says "Indentured servant"
Maybe add some additional text ? I'm pretty sure that we used to have more text?
Gametext for Conquistador shows "vs. TXT_KEY_UNIT_NATIVE_MERC"
Scout sometimes show: TXT_KEY_UNIT_SCOUT
Free Colonist->Expert miner native training completes on the same turn. Not a bug but it makes more sense that native training should require at least 1 turn 
City  Screen redraw issue when dragging colonist to the cargo hold of a ship. Perhaps the same issue that has been reported when moving a treasure ?

**Comment by raystuttgart** [comment]
We are **currently** (in the last beta) missing **massive amouts of TXT_KEYS** as I wrote in our Slack chat. This is most likely related to the same general issues about these **"lost TXT_KEYs"**.

However, they are all **still there** in the **previous release** before the current beta.
This it is probably **related to a script** (maybe the UTF8 conversion) and we should be able to fix it without too much effort.

Thus I suggest we handle all of these missing TXT_KEYs in this issue.

I personally simply don't know how to fix this - probably by fixing the conversion script.
(I hope it is not needed to manually copy-paste the missing TXT_KEYs from previous release.)

**Comment by raystuttgart** [comment]
This bug is about our TXT_KEYs which we repaired.
I will thus close it.
