### ISSUE TITLE
Large rivers.

### ISSUE THREAD

**Issue by abmpicoli** [We-the-People-civ4col-mod/Mod#34]
https://forums.civfanatics.com/threads/religion-and-revolution-large-rivers.473788/page-2

**Comment by ErikSandbraaten** [comment]
See my post (BTS modding forum) concerning strategic rivers:
https://forums.civfanatics.com/threads/strategic-rivers-mod.468148/page-3

I have fixed some bugs in my private build and we could base the implementation on a refinement of this mod.

**Comment by raystuttgart** [comment]
It is started and almost finished. :)
We can close this now.

**Comment by raystuttgart** [comment]
Closed because almost finished
