### ISSUE TITLE
idea ... better distinguishable weather for ship navigation by keyboard

### ISSUE THREAD

**Issue by 3tag** [We-the-People-civ4col-mod/Mod#342]
Making weather on the sea a bit easier to identify on which plot is the impact and what kind of weather is it.
Behind this suggestion is the thought of navigating ships precisely with the numpad.

What do you think about that?

**Comment by raystuttgart** [comment]
I generally like it, but how should it be done visually?
Also we lack graphical modder currenlty ...

**Comment by 3tag** [comment]
I don't have any idea what it should look like. 

And maybe the weather phenomena could be more clustered, so there appear bigger cloud formations you cannot easily avoid without going longer ways.

**Comment by raystuttgart** [comment]
Sounds to me that there currently is no real problem with the feature as it currently is.
Also we currently only have a vague idea that it could be "better" and do not know how to make it better.
Also this is one of the less important features of WTP and most likely only few players really care about it.

Thus it seems we end up with very low priority of the issue.
But let us see, maybe some team member is really interested in doing something here.

**Comment by Nightinggale** [comment]
We could add colored circles to the plots in question. Vanilla provides the ability to select both sprite (usually a circle, but we can pick X, star and a bunch of other stuff) as well as color. In fact we have full RGB control of the colors. This would be possible to add without modding graphics at all.

**Comment by raystuttgart** [comment]
Could we have a button to activate those circles and deactivate them?
Similar to activating and deactivating the display of Bonus Ressource icons on the map.

Because maybe not every player wants to see theses circles on the map **all the time**.
But some might like to activate it temporarily for moving the ships with Numpad as 3tag has mentioned.

Then I think that it could in fact be a nice little addition without too much effort.

**Comment by Nightinggale** [comment]
Sure we can add an on/off switch to the circles. We can also make them only appear when ships are selected or whatever else condition we can come up with. The circles are controlled by the dll, meaning we can call an update function whenever we want based on whatever trigger conditions we want.

**Comment by raystuttgart** [comment]
The coolest kind of button would be one right next to the other visualization helpers (e.g. Bonus Ressources) in my opinion.

We should hover be able to turn it on/off ingame.
Thus having an XML setting in GlobalDefinesAlt or a Game Option when starting a new game is probably not the nicest way to solve it and could cause more complaints than we have now as it is.

But I am open to all suggestions that anybody who volunteers to implement this might choose.

**Comment by Nightinggale** [comment]
I think the settings part should be a part of #153. That way settings are stored between games as in you start a new game and the mod will remember, yet at the same time other players in multiplayer can have different settings and the player can change the settings while the game is running.

**Comment by raystuttgart** [comment]
But what if the user only wants to turn on the setting for this one ship he wants to move and then deactivate again?
Should he really save, end the game, change the setting and start the game again.

#153 sounds cool for stuff you don't want to change every turn or every couple of turn. 

But everything you change dynamically whenever you like ingame is ideally just a "turn on/off" button from a user perspective.
The only problem here is that we don't have a button for that yet.

Although I might ask **Schmiddie** and he might agree to do such a small button for us - because most likely it will only take him like 5 minutes.
Otherwise I still have a couple of other contacts (graphical modders) like **Kathy** or **Willi Tell** who might also do something like that if asked kindly.

But as I said, I am open to everything. 
The team member that volunteers to implement this shall choose his preferred solution.

**Comment by Nightinggale** [comment]
The idea with #153 is that it's saved by the game, meaning no human should edit the file. Instead the settings should be controlled from an ingame menu or buttons or whatever and whenever the player clicks something the entire file is then written again, overwriting the old settings. This means it's fine to change the setting multiple times each turn.

We might want to skip writing the file each time a button is pressed though, like we could write the file at new turn event if a bool tells that it has been updated. No need to harass the disk I/O, SSD and all that for insignificant changes.

**Comment by 3tag** [comment]
Ray already said there are no modders with graphical skills at the moment ...
but I think for a supporting wind the water tile/plot could show some crests of waves ...
and for dangerous water one could use some picture of a freak wave

**Comment by 3tag** [comment]
what do you think about the idea on top ... making big weatherzones/clusters you cannot easily avoid by a sidestep ... maybe they could even move slowly from turn to turn ... this would end in regional wether effects if we like

**Comment by raystuttgart** [comment]
The idea of the "clusters" could potentiall become annoying for some players.
I also don't really feel the current system for placing Winds and Storms is bad. 

It would require some recoding of course and would need to be tested and especially balanced again.
In fact the balancing of this feature was much more work then the programming of the placement logic.

As you see, I am personally not a big fan of that idea.
But if other team members are interested to invest the time and effort - go for it. :)

**Comment by raystuttgart** [comment]
About the water effects you describe:
We currently really have nobody on board that could do it.
And even if we had, I really don't know if he would be interested in investing the efforts ...

If you however find somebody that could do that for us, it might actually be great.
(Then we might not even need the other solution with coloured circles we have discussed.)

But if you don't find somebody that would do it, the other suggestions with the **coloured circles** that can be turned on/off (with whatever mechanic we might chooses) is much less work for us.

**Comment by Nightinggale** [comment]
I think clusters moving around would be unfair. You could have one moving around your colony for many turns while other players have fine weather. Sure the game shouldn't treat everybody completely equal as in not the same map features for all starting locations etc, but still it shouldn't just randomly block one player where the player can do nothing regardless of size of army/navy.

**Comment by 3tag** [comment]
Ah, I see there are a lot of aspects to take in consideration ...

**Comment by raystuttgart** [comment]
It is not that many, but it is also not that simple to make a good concept.
Most importantly you need to think about:
- Gameplay for Players / good Balance (Users)
- Stability / Performance / AI issues (Technical)
- Effort / Motivation (Team)

**Comment by 3tag** [comment]
good overview   ... I realise the 1st branch is the only one I can think into ... in a shallow kind :-)

**Comment by raystuttgart** [comment]
Well yes, a Player of our mod does not have to think about more. :)
So that is perfectly fine.

We modders will then need to think about the rest.
We need to explain this though, so community understands our decisions.

**Comment by raystuttgart** [comment]
Solved.
