### ISSUE TITLE
idea for easier navigation between colonies

### ISSUE THREAD

**Issue by 3tag** [We-the-People-civ4col-mod/Mod#347]
Hi guys,

what do you think about a colonylist inside the colonyscreen for switching fast between colonies without clicking the left and right buttons?
Maybe it shows up when clicking on the colonyname ...

**Comment by Nightinggale** [comment]
Isn't it there already? I mean there are 3 buttons to the right where you can select trade, buildings and map. If you click on the map, the colony list should be in the top right.

**Comment by raystuttgart** [comment]
I also think that from the "Overview Screens" e.g. Production Overview you can directly jump to a City by clicking it.
But I am not completely sure - would need to check again.

**Comment by 3tag** [comment]
Thank you both,
its been so long since I clicked the map-button ...

**Comment by raystuttgart** [comment]
Is this issue solved then?

**Comment by 3tag** [comment]
The issue is solved by using the map-button :-)

**Comment by raystuttgart** [comment]
Ok, then let us close it. :)
