### ISSUE TITLE
idea - "go to" function for coastal ships

### ISSUE THREAD

**Issue by 3tag** [We-the-People-civ4col-mod/Mod#348]

**Comment by raystuttgart** [comment]
"Go-To" does not work for Coastal Ships?

"Go-To" (Pressing "G") **should** work for **all Units** already in the game.
I cannot see any reason why it should not work for Coastal ships.

If it does not however that would be a **bug** we should fix.

**Comment by raystuttgart** [comment]
Indeed!

"Go-To" is **not** working for Coastal Ships.
Thanks for reporting this. This is a bug!

I will try to take a look and fix it.

**Comment by raystuttgart** [comment]
Ah, ok I found out why "Go-To" does not work for **Coastal Ships**.

It was **purposely** deactivated.
// Erik: Disable the goto menu for coastal transports for now until we figure

Could you guys explain it to me?
I don't want to mess around until I understand the reasons.

From the comment I read it sounds more difficult than I expected.
Coastal Ships were added after I had left and I don't have enough knowledge about that feature yet.

**Comment by ErikSandbraaten** [comment]
If I recall correctly, I deactivated the goto due to not having a way to filter out the Europe destination. I guess that it shouldn't be very problematic to fix this.

**Comment by raystuttgart** [comment]
If it is only about the filtering out **Europe / Port Royal and Africa** it should be really pretty simple to do. (Just put a check in there as the "canSailToPortRoyal" but using "isCoastal".)

If that is the only problem I will be able to fix it easily I think.

**Comment by raystuttgart** [comment]
This is fixed now.
Will push to fixes.
