### ISSUE TITLE
idea for easy entering buying- and transfernumers

### ISSUE THREAD

**Issue by 3tag** [We-the-People-civ4col-mod/Mod#349]
Is it possible to enter the numbers straight before splitting the amount of wares (when holding shift)?
Now you have to click in the box to set the cursor and mark the existing numer and write new or delete ... 

maybe this way:
1. shift + left mouse button on the yield
2. holding shift + releasing left mouse button >> to drop the yield elsewhere
3. typing amount of yield (without bringing cursor in the box, marking oder deleting)
4. pressing enter for confirmation

**Comment by raystuttgart** [comment]
It is not possible to implement the changes as you suggest because this is handled by the Exe.

**Comment by Nightinggale** [comment]
```cpp
bool CvDLLWidgetData::executeDropOn(const CvWidgetDataStruct& destinationWidgetData, const CvWidgetDataStruct& sourceWidgetData)
```

What is what we can do with drag-n-drop. We get the widget it comes from and the widget it is going to. Nothing else. I suppose we can sort of hack our way into checking for shift on release, but that's about it.

**Comment by raystuttgart** [comment]
I really think that this is not worth the effort to try to hack the exe. 
(i.e. stuff like "not having to click into the box for changing the number".)

Nobody is going to invest dozens of hours into it for such little benefit.
(It is working now acually quite well. You just need to get used to the Usability.)
