### ISSUE TITLE
More "realistic" ship repair mechanics.

### ISSUE THREAD

**Issue by abmpicoli** [We-the-People-civ4col-mod/Mod#35]
at https://forums.civfanatics.com/threads/drydocks-buildings-etc.634195/ it was proposed that ship repair should take carpenters and consume resources.

**Comment by ErikSandbraaten** [comment]
As the resident AI guy, I would have to caution that the AI is already struggling at the moment.
We would either have to add another cheat to let it repair / consume yields for free or write elaborate AI logic to let it handle it. I don't think that either would improve the game atm.

**Comment by raystuttgart** [comment]
A compromise is kind of implemented already with "negative Promotions" that can be earned from Combat.
AI can handle it perfectly fine.

Everything else is overexagerated.
So let us close this please.
