### ISSUE TITLE
Diplo events causes bugs if conditions change between AI calling and it is displayed for the player

### ISSUE THREAD

**Issue by Nightinggale** [We-the-People-civ4col-mod/Mod#352]
The system for the diplo events is as follows:

- AI decides to create a diplo event
- Event with answers is calculated
- Event is queued in the exe
- AI finishes it's turn
- Other AIs goes through their turns
- Human player starts turn
- If a ship arrives in Europe, the game opens the Europe screen to allow trade
- Closing the Europe screen (if open) will request events from the queue
- Display event 1
- Display event 2
- etc

The problem is that quite a lot can happen between the answers being generated and they are displayed to the player. This means sometimes the answers are out of date. This is most noteworthy while being offered to buy something and the player has to deny despite having the money or the player can say yes to buy despite having spent the money.

However there are other issues as well like native shows up at a colony and wanting to sell something. If the unit has moved or the colony it links to is gone, then answers will not be valid anymore. RaR used to crash if this happens, but I changed it to either ignore or trade without actually altering the storage for the native. Which case it will use depends on which pointers ends up being NULL pointers.

There are other issues as well, like the king requesting war against a dead player. The list goes on and on regarding what can go out of date if we are unlucky.

## **Possible solutions (likely an incomplete list)**

#185, basically keep the queue in the dll and only forward to the exe when the player is ready to read an event. This way the answers can be calculated once the event leaves the dll rather than when it enters the dll queue.

#201, rewrite of the entire diplo screen, complete with new network code and everything. This will allow us to mod the diplo screen itself and as such we can do whatever we want. However the workload isn't trivial.

**Comment by raystuttgart** [comment]
Thanks for opening a general "DLL-Diplo-Event"-Issue.
It is a pretty common compaint with the current implementation.

**Comment by f1rpo** [comment]
Adding to the list of possible solutions:
Insert a sequence of AI "diplomacy turns" right before the human turn so that the AI players receive an immediate response to each of their offers and requests. I'm not sure if that's actually viable in Colonization; it's what I plan to do in BtS (where there might also be obstacles that I don't foresee). I've talked briefly to Ifgr about this idea: [CFC post](https://forums.civfanatics.com/threads/advanced-civ.614217/page-13#post-15522125)

**Comment by raystuttgart** [comment]
Thanks for your solution input.
It is one of the most annoying bugs we still have - even thought it does not break the game though.

**Comment by raystuttgart** [comment]
I had solved this in Plains about 2 months ago.
