### ISSUE TITLE
Cattle thief event

### ISSUE THREAD

**Issue by dgucwa** [We-the-People-civ4col-mod/Mod#356]
There's a random event involving cattle rustlers where you're given a choice of either:
1. nothing happens. or 
2. you lose 100 cattle and gain a petty criminal.

Maybe others evaluate this choice differently than I do, but I can't imagine _ever_ considering that to be a good trade. For one, 100 cattle generally costs 700 gp, and that's way expensive for a criminal. But also, this event always triggers when I first bring in a load of cattle to get a ranch economy going, and losing the cattle would require bringing in another load of 100 from Europe, setting back the whole operation by several turns at the very least.

I feel like a more appropriate amount of cattle to lose would be somewhere in the range of 20 to 40.

**Comment by raystuttgart** [comment]
Sounds ok to me.
I will adjust that event.

**Comment by raystuttgart** [comment]
Implemented as requested.
