### ISSUE TITLE
Scrollable "Score List" necessary due to huge amount of Nations in WTP

### ISSUE THREAD

**Issue by raystuttgart** [We-the-People-civ4col-mod/Mod#360]
Hi guys,

due to the Huge amount of Nations in WTP we might need to make the Score List scrollable.
(Otherwise it simply starts looking really ugly, once you discovered about 20 Native Nations.)

Does any one of you have a good idea on this?
(This issue is already know since RaR by the way.)

It is probably not even that difficult (or at least not impossible to do).

![Civ4ScreenShot0003](https://user-images.githubusercontent.com/59391125/75631683-4a4e9300-5bf5-11ea-86c2-8d4ad6fd3ab8.JPG)

**Comment by ErikSandbraaten** [comment]
Already implemented this, gotta dig out the code though.

**Comment by LibSpit** [comment]
Erik gets the "Work of a Time Traveller" Achievement.

Another possibility (although a much larger project) might be moving the scoreboard into a pop up window with a button access, to keep the whole screen clearer. Another thought might be removing the various kings from the board as they don't really have a score? (though I guess that might change at a revolution?)

**Comment by raystuttgart** [comment]
Great!

Was this just recently?
Or was there any other reason why it was not added yet to fixes?

@LibSpit 
You can already no activate / deactivate it by button "Show Score List".
(This does not need to be implemented because it already exists.)

**Comment by ErikSandbraaten** [comment]
It was eons ago...

**Comment by raystuttgart** [comment]
Ok, but what was the reason not to add it to RaR / WTP?
Or was it just forgotten?

**Comment by ErikSandbraaten** [comment]
I managed to find some old sample code laying around. Don't expect too much as the code is a simple port of a BTS scrolling score board.

**Comment by raystuttgart** [comment]
@ErikSandbraaten 

Thanks for digging it out again. 
It will really be a useful improvement.

As you wrote yourself, the file you used seems to be older, so some merges will be needed.
(e.g. I moved the Gold Pile a bit so it would not cover the Turn Counter anymore.)

But since you labeled it "initial commit" I guess you are still working on that.

**Comment by ErikSandbraaten** [comment]
May already have been implemented for the BTS mod "Dawn of Civilization".

Check out this pull request:

https://github.com/earthcrafterman/Civilization-Reborn/pull/9/commits/43fcc47ccc9da499714db3a7a25cb48ef9c041ea

**Comment by raystuttgart** [comment]
Sounds good.
Could you take a look at it and integrate if it is what we are looking for?

**Comment by Ramstormp** [comment]
Alright, merging in Devolution's Scrollable score list and made some adjustments. What do people want? Take up the most of the screen or how about half? Do you want bar or no scroll bar?

![Civ4ScreenShot0124](https://user-images.githubusercontent.com/69612762/141229900-6a31b134-feed-4d44-922b-ed80813da25b.JPG)

**Comment by Curt56** [comment]
Looks good

**Comment by MrZorG33** [comment]
could you do the same scrolling for the unit list on the left side of the screen?

**Comment by raystuttgart** [comment]
@Ramstormp
 The "score list" looks perfectly fine in that screenshot. 👍 
 
 1. Yes, please leave it with a bar. 
 2. Half of the screen as seen, is also fine.
 
 **Summary:**
 As seen in the screenshot is great.
 You can open a pull request if you like.
 
 Thanks. 😃

**Comment by Ramstormp** [comment]
![Civ4ScreenShot0129](https://user-images.githubusercontent.com/69612762/141381776-2ae0c04e-fdba-4567-9c1d-aeed18043a1f.JPG)

Just to be clear - this is how it will look before the list gets filled up, which I suppose appears a bit float-in-the-airish. It also takes up more space than I would like, which is entirely, I believe, the fault of the ruler of Holland. I might look into the Dawn of Civilization Score list at some point to see if it is better (I took the  simplest route).

@MrZorG33 The Unit stack panel probably can't be made to scroll in the same way since since it is a window that pops up when hovering the pointer over a unit. I mean, even if there is some code that allows you to use the scroll wheel on a mouse to move the text in the window, some people probably don't have scroll wheels.  I was hoping there is some way to make it automatically scroll upwards while you keep the mouse over the unit; or maybe add an additional spillover popup next to the first window (which could of course get filled up too when facing the ultimate stack of doom). I still have much to learn and do not know what is possible yet.

**Comment by MrZorG33** [comment]
okay thanks for the clarification. let's leave the list of units for the future. I can't wait to test your work and see how quickly I get used to the new kind of list of nations.

**Comment by raystuttgart** [comment]
This is solved now by the changes of Ramstormp - however he has not yet commited it anywhere.
@Ramstormp Why is this not commited anywhere?

**Comment by Ramstormp** [comment]
> This is solved now by the changes of Ramstormp - however he has not yet commited it anywhere. @Ramstormp Why is this not commited anywhere?

I guess I commited it from my own fork to my own fork. Sorry, I am still a bit lost in the hub. I was trying to figure out the way to do it without having to copy and paste sections of code (not that it is a lot of lines or anything)

**Comment by MrZorG33** [comment]
works now - there are no more problems with the colony screen.
however, if you try to select any native leader / governor of the colonies, the list will scroll up. It is very uncomfortable.
my suggestions (if possible):
1. fix the automatic scrolling of the list and leave everything as it is.
2. return the previous order of the list - Europeans on top, sorted by points.
3. fix the automatic scrolling of the list and return the previous order of the list - Europeans on top, sorted by points.

**Comment by MrZorG33** [comment]
moving the screen to the selected unit does not work if the move icon is on the right (in the Score List area).
![image](https://user-images.githubusercontent.com/61798883/143677340-c3b5d52c-e604-4136-b3e8-d0f673fcc5ff.png)

**Comment by raystuttgart** [comment]
Ok, I hope this works now.

![Civ4ScreenShot0003](https://user-images.githubusercontent.com/59391125/143681738-7e62dd70-67d0-42f0-8ce2-97761648af75.JPG)

**Comment by MrZorG33** [comment]
works only outside the list area. in addition, the zone became visible even when the list was collapsed.
![score list](https://user-images.githubusercontent.com/61798883/143682050-76ce5737-0e7f-4a77-a1f9-6cd157af89fe.jpg)

**Comment by raystuttgart** [comment]
Try again please.
Just commited a fix.

**Comment by MrZorG33** [comment]
now everything works.
it remains to resolve the issue on the 3 points that I described above.

**Comment by raystuttgart** [comment]
Ok, then I consider it closed.

**As I wrote:**

I can not prevent that it is jumping back to the top once you select something.
(It always happens once you select something because the screen display is refreshed. Happens e.g. in Colopedia as well.)

**Considering the order:**

It should still sort itself **by score** throughout the game.
(Just like it did before.)

**Comment by MrZorG33** [comment]
well, if the jump back can't be fixed yet, let's leave it. but can the Europeans be brought back to the top of the list? it will be much more convenient.

**Comment by raystuttgart** [comment]
The sorting has **not** been **changed** actually.
It should **sort itself** by **score** during the **course** of the **gameplay**.

**Comment by MrZorG33** [comment]
yes, and we can see that the sorting goes from top to bottom (top is the player with the most points). and now it goes from bottom to top (see my screenshot). and since the list jumps up when the screen is refreshed, it will be better if the sorting is the same as before - from top to bottom.
![image](https://user-images.githubusercontent.com/61798883/143690634-112eeced-9725-46d0-8b09-8c73c98ad4dd.png)

**Comment by raystuttgart** [comment]
Ok, now I understand. 

I can switch the order tomorrow. 👍 
(I am a bit too tired now after adding all these ships.)

**Comment by raystuttgart** [comment]
Ok, I switched the order in my latest commit.
I guess that is then done now.)

**Comment by MrZorG33** [comment]
Yes thank you.
but I also propose to slightly shorten the visible area of the Score List. it will look more aesthetically pleasing.

I would also like to clarify whether it is possible to make the Score List area solid, like the area on the left side of the screen? now this area has lines with different colors or shades.
![укоротить список очков](https://user-images.githubusercontent.com/61798883/143783157-85bb5e70-bf12-447a-9645-0c48a7022bcf.jpg)

**Comment by raystuttgart** [comment]
**@MrZorG33** 

That is simply because of **your resolution**. I cannot adjust everything perfect to every resolution.
And for other resolutions I need to leave a little bit of Space if e.g. Gold gets really high.

Can we PLEASE leave it like this now.
I have invested way too much time into this already. ;)

**Comment by MrZorG33** [comment]
oh I'm sorry. I forget that not everyone has high resolution monitors. case closed)

**Comment by MrZorG33** [comment]
I'm sorry, but .. the "go to mode (city selection)" button stopped working. Look please.
![image](https://user-images.githubusercontent.com/61798883/143784557-7d1aa5ab-3f70-4301-add9-cc3371555eb4.png)

**Comment by MrZorG33** [comment]
I apologize, I didn’t watch it. everything works)
