### ISSUE TITLE
Schmiddie's Gold Stack covers up Turn Counter

### ISSUE THREAD

**Issue by raystuttgart** [We-the-People-civ4col-mod/Mod#361]
Hi guys, while Schmiddie's Gold Stack looks really nice, it **covers up the Turn Counter**.

We somehow **either** need to:

A) Move it a bit to the right and up
B) Make it smaller.
C) A+B

![Civ4ScreenShot0004](https://user-images.githubusercontent.com/59391125/75631809-56872000-5bf6-11ea-8ded-32af4547e8de.JPG)

**Comment by LibSpit** [comment]
I think all it really needs is 'A' Right now it just looks like it is in a wonky position.

**Comment by raystuttgart** [comment]
I already fixed it and will commit/push to fixes.
