### ISSUE TITLE
BTS style city icons and effects

### ISSUE THREAD

**Issue by ErikSandbraaten** [We-the-People-civ4col-mod/Mod#363]
![image](https://user-images.githubusercontent.com/32330976/76691074-19377f00-6647-11ea-84ce-2d8e699f8bc5.png)

Implemented:

- Disease / "green ooze" animation effect
- "Disease" city icon
- First city (capital) indicator -> gold star icon

**Comment by Schmiddie1979** [comment]
Hm, I don't like these icons. They do not fit with the period of this game. Do we really need them?

**Comment by raystuttgart** [comment]
When you are talking about "disease", do you mean "negative Helath"?
Because maybe we could do something with the "Health Icon" instead (e.g. recolouring black+red).

Positive Health: Red Cross on White
Desease (Negative Health): Black Cross on Red

**Comment by ErikSandbraaten** [comment]
Yeah, it would be nice to have a more "authentic icon". We should probably visualize 3 states:
Max\steady health, trending negative (but not necessarily negative yet), actually negative (only this state should trigger the ooze). Perhaps even a fourth state for totally unhealthy cities (-25) and only apply the ooze here.

**Comment by raystuttgart** [comment]
let us not make it too complicated.
2 icons should suffice (negative and positive)

**Comment by ErikSandbraaten** [comment]
Closing, it is my understanding that we've already merged and adapted what we want from this branch
