### ISSUE TITLE
World Builder

### ISSUE THREAD

**Issue by Curt56** [We-the-People-civ4col-mod/Mod#364]
I can't seem to load any scenarios\WB saves I create. I get the wheel of death spinning continually.

????

**Comment by raystuttgart** [comment]
Loading Worldbuilder saves has always been really slow.
Especially if you create maps with MapSize "Gigantic".

To test:
Try to create and load a Worldbuilder save for a **small map**.
If it works, this is most likely just a performance issue.
You might need to be **really** patient and wait longer.

**Comment by Curt56** [comment]
You can close this. No problem now
