### ISSUE TITLE
bug? cattle and sheep disapear from the map once inside cultural borders

### ISSUE THREAD

**Issue by pro-fesor** [We-the-People-civ4col-mod/Mod#368]
Hello,

PLots where cattle and sheep can be produced only show it when outside of my cultural borders. Once the plot gets in range of my town, I cannot assign anyone to produce it. Bonus icons remain visible, but the amount of the ressource disponible disapear.

I play the Steam version of the game and the latest (2.8) mod.
 
![image](https://user-images.githubusercontent.com/65909889/82824806-4a83c500-9eaa-11ea-9446-a30ee1bf9565.png)

You can see in this picture that the sheep Inside my cultural borders cannot be produced.

**Comment by clonkia** [comment]
You need the appropriate livestock in your town to start production.
