### ISSUE TITLE
Add a target for packaging the mod into a zip for release.

### ISSUE THREAD

**Issue by abmpicoli** [We-the-People-civ4col-mod/Mod#37]
The idea is to add a target called "Package" that will make the build in "Release" mode, then will package the final product into a zip file. 

Personally, I vote that the compression tool (we will have to choose one) , be 7-zip

**Comment by Nightinggale** [comment]
I would love this, but at the same time I fear that so much could go wrong. I made 2.7.2 beta 1 by simply downloading the repository as a zip from GitHub and then I copied all the files into a new compressed file and added the dll files. Sure it was slow in terms of CPU power and internet speed, but it was trivial for human interaction.

If somebody wants to design a build script, then it would be welcome, but it's certainly not high priority.

**Comment by Nightinggale** [comment]
Implemented.
