### ISSUE TITLE
Error in Port Royal when attempting to buy a frigate you can't afford

### ISSUE THREAD

**Issue by Calaesir** [We-the-People-civ4col-mod/Mod#374]
![Right before error](https://user-images.githubusercontent.com/68597811/88057997-2c150f80-cb63-11ea-904f-cdcb9d0e3134.png)
![Bug error](https://user-images.githubusercontent.com/68597811/88058032-359e7780-cb63-11ea-8403-04fda631c2f2.png)

Obviously I have no business buying a boat I can't afford.
I am not a programmer or strictly novice. Let me know if I can provide any other useful information files etc.

**Comment by ErikSandbraaten** [comment]
i think I solved a similar issue for the African port a while ago. Will take a look tomorrow.

**Comment by raystuttgart** [comment]
So this was just about a fix already in "Large Rivers" not being merged?
Or was this issue identified in an outdated branch? (I think "master" is not the most recent branch anymore, right?)
