### ISSUE TITLE
Cannot buy partial cargo load at Port Royal

### ISSUE THREAD

**Issue by mkeroppi** [We-the-People-civ4col-mod/Mod#375]
Cannot buy partial cargo load (<100) at Port Royal.

**Comment by raystuttgart** [comment]
So basically you say that the "Shift-Key" does not work?

**Comment by mkeroppi** [comment]
Yes.  Works in Europe and Africa.

**Comment by raystuttgart** [comment]
Yes, I can confirm this bug (as described).
Shift-Key works in Europe Screen + Africa Screen but **not in Port Royal Screen**.

**Comment by raystuttgart** [comment]
It is fixed now.
Will commit to "Happiness".
