### ISSUE TITLE
event log shows europe prices for sold goods

### ISSUE THREAD

**Issue by mkeroppi** [We-the-People-civ4col-mod/Mod#376]
event log shows europe prices for sold goods even if goods were sold in africa or port royal.

**Comment by raystuttgart** [comment]
That is known.
It is very difficult to change though, since the logic of the "sales log" was very badly designed in Civ4Col.
(It is very badly structured considering modularity.)

**Comment by ErikSandbraaten** [comment]
@raystuttgart You fixed this ?

**Comment by raystuttgart** [comment]
Yes, this is fixed.
The event log shows the correct numbers now according to the place it was sold.
(I fixed it together with the wrong display in Port Royal.)
