### ISSUE TITLE
For builds in "Release" mode, validate if the user have properly committed/pushed the change.

### ISSUE THREAD

**Issue by abmpicoli** [We-the-People-civ4col-mod/Mod#38]
When building in "Release" mode, we must avoid the situation where code that is not yet committed / pushed into the remote tree is compiled.

I believe we should have an artifact list of pieces that must be properly pushed, and if we find artifacts that are not committed, we should abort the build.

**Comment by abmpicoli** [comment]
To check the remote name to use:
$ git remote -v
origin  git://git.code.sf.net/p/religion-and-revolution-git/code (fetch)
origin  git://git.code.sf.net/p/religion-and-revolution-git/code (push)
rare    https://github.com/Religion-And-Revolution-Extended/Mod (fetch)
rare    https://github.com/Religion-And-Revolution-Extended/Mod (push)
rare2   git@github.com:Religion-And-Revolution-Extended/Mod.git (fetch)
rare2   git@github.com:Religion-And-Revolution-Extended/Mod.git (push)

**Comment by abmpicoli** [comment]
It is possible to check if the remote is up to date as well.

```
$ git remote -v update
Fetching origin
Looking up git.code.sf.net ... done.
Connecting to git.code.sf.net (port 9418) ... 216.105.38.16 done.
From git://git.code.sf.net/p/religion-and-revolution-git/code
 = [up to date]      develop-2_7_1 -> origin/develop-2_7_1
 = [up to date]      develop       -> origin/develop
 = [up to date]      master        -> origin/master
Fetching rare
From https://github.com/Religion-And-Revolution-Extended/Mod
 * [new branch]      develop-2_7_1 -> rare/develop-2_7_1
 * [new branch]      master        -> rare/master
Fetching rare2
From github.com:Religion-And-Revolution-Extended/Mod
 = [up to date]      develop-2_7_1 -> rare2/develop-2_7_1
 = [up to date]      master        -> rare2/master
```

**Comment by raystuttgart** [comment]
I think we have no more issues here.
We have had no problems the last years.
