### ISSUE TITLE
Save game crashing on next turn 

### ISSUE THREAD

**Issue by stepik-tug** [We-the-People-civ4col-mod/Mod#384]
So i have save game where it constantly crashed on the next turn 3 times in a row same turn. 
Any feedback / ideas appreciated as i really liked that game :D 
[QuickSave.zip](https://github.com/We-the-People-civ4col-mod/Mod/files/5306814/QuickSave.zip)

**Comment by stepik-tug** [comment]
so for some reason after goofing aroudn and starting a new game without WTP mode loeaded , then starting the mode and loading the game it runs past this turn .

**Comment by raystuttgart** [comment]
Some additional information would help as well.

Which release version did you play?
Do you play a specific map?
Did you modify anything on your own?

**Comment by stepik-tug** [comment]
> Some additional information would help as well.
> 
> Which release version did you play?
> Do you play a specific map?
> Did you modify anything on your own?
> 
> **Edit:**
> Ok I saw you just closed it a few seconds ago.

No i have not modified anything not even in world builder . 

Yes Gigantic Americas Map 

The current release.

I have no idea why it suddenly didint crash but consistently before . Weird but i cant replicate it anymore .
