### ISSUE TITLE
Add colony radius to scenario files

### ISSUE THREAD

**Issue by Nightinggale** [We-the-People-civ4col-mod/Mod#385]
The ability to select 1 or 2 plot radius for colonies at runtime means there should be a selector in scenario files. Under BeginMap, the new tag City Catchment Radius is added (currently in big_merge branch only) and this tells which one to use. Valid values are 0, 1 and 2. 0 means ask the player as in the scenario supports both.

We need somebody to go through all the scenario files and assign this new value to them. If you want to do this, contact Nightinggale as this feature is still under development.

**Comment by Nightinggale** [comment]
```python
BeginMap
    City Catchment Radius=2
EndMap
```
Adding the syntax for this feature.

- 1: one plot radius
- 2: two plot radius
- 0: use user setting (read: either)
- any other value or not mentioned: assume 0

**Comment by raystuttgart** [comment]
This is already implemented.
(Saw it in the Scenarion files.)
