### ISSUE TITLE
Make rare bonuses always accessible

### ISSUE THREAD

**Issue by Nightinggale** [We-the-People-civ4col-mod/Mod#386]
When random maps place rare bonuses like gold, it should check if it's possible to build a colony close enough to use them. Once in a while particularly gold ends up in a group of peaks, which renders it unreachable. Not a game breaking issue, but it is annoying whenever you get far into a game and then discover this.

**Comment by raystuttgart** [comment]
boah, but it is kind of **a lot of effort** for a really **small / rare problem**
Almost never encountered that issue

**Comment by Nightinggale** [comment]
I noticed it multiple times. Maybe it's more of a 1 plot radius issue. I'm thinking something like adding a check for being able to build a colony in the 3x3 area around the bonus (excluding the bonus plot, hence 8 plot check) and then add a bool in the bonus to tell if it should check. It then needs a non-peak, non-water plot in that area to make the plot valid.

**Comment by raystuttgart** [comment]
Yeah, in 2-Plot it always never happens :)

**Comment by raystuttgart** [comment]
Let us please not code things **just for 1-Plot-DLL**
(until now nobody from cummunity has ever complained about that)

And in worst case, there is still WorldBuilder

**Comment by raystuttgart** [comment]
Also what I do not like about that:
We would need code for **2 specific Ressources** - and maybe even need XML flags to trigger the logic ...

**Comment by dcrookston** [comment]
You could circumvent this issue by adding outposts:
https://github.com/We-the-People-civ4col-mod/Mod/issues/247

Similar idea: https://github.com/We-the-People-civ4col-mod/Mod/issues/142

**Comment by raystuttgart** [comment]
Guys, let us close this.
That is totally unnecessary messing with code for nothing.

**Comment by dcrookston** [comment]
You seem to be the only person who thinks that, but okay.

**Comment by Nightinggale** [comment]
Clearly we do not agree how serious this issue is and that's likely due to not agreeing on map sizes or colony plot radius. However even though this might not be a big deal on some map option combos, it is on others and we should ideally provide a decent gaming experience using all available combos.

The answer might actually be quite simple. Mod CvPlot::canHaveBonus. If bonus plot is PLOT_PEAK, then scan 3x3 or 5x5 for plots, which are either PLOT_HILLS or PLOT_LAND. End result is that all land bonuses will have at least one plot where a colony can be founded. Looping plots can be used by calling cityPlot from 0 to < NUM_CITY_PLOTS. Since this only triggers for bonuses on peaks, performance is not much of an issue.

Maybe add CvPlot::canHaveCity to have consistent terrain checks with CvUnit::canFound. For ease of read, add a CvPlayerAI pointer for which player deciding to build and if said pointer is NULL, skip checking for colonies (bonuses should clearly use NULL). Not only will this make it clear if colonies are checked or not, knowing the specific player will allow player specific issues like reduced colony distance game option.

This might even be a good task for a new modder.

**Comment by raystuttgart** [comment]
**Summary:** 
Keep this issue open as long as you want.
Simply do not implement it, while I am still a team member.

**Comment by raystuttgart** [comment]
**By the way:**
This is just **100% proving my point**, why I did not like to have 2 City-Plot-Variants from the beginning.
We start messing around with code just to take care of the balancing issues of 1 variant ...
That is also exactly the reason why I do not want to have 1000 game options ...

**Comment by raystuttgart** [comment]
I will close it, because it just clutters the list and nobody will ever work on it anyways.
There is really nothing to do here other than specific balancing improvements in case there is an extreme issue.

You can never write a generic logic that will be able to handle 100+ Bonus Resources and Yields "perfectly".
Also randomness is part of the game and thus part of the fun.
