### ISSUE TITLE
Prevent pirates from destroying the last ship of a player

### ISSUE THREAD

**Issue by Nightinggale** [We-the-People-civ4col-mod/Mod#387]
When the barbarian player destroys a ship, if that ship is the only one owned by that player, which can both sail to Europe and carry units, then the ship should have a 100% chance of going for repairs. This way a player can't end up entirely without ships because a barbarian happened to pass by.

This should apply to barbarians only. Other players need to be able to combat each other or it will be impossible to kill a player entirely.

**Comment by raystuttgart** [comment]
I am perfectly ok with that. 
It may help weak AIs in some cases.

**Comment by raystuttgart** [comment]
This problem does not exist anymore, because player gets a Ship again if the last one is lost.
(This was fixed with the Settler Profession and also changes considering "eliminating Players"..)
