### ISSUE TITLE
Small typos in colopedia

### ISSUE THREAD

**Issue by Sorxus** [We-the-People-civ4col-mod/Mod#389]
Long time Colonization player here (yes, since 1994).
So a few days ago I found a WTP mod, and I'm excited. I also found some small typos in colopedia and I decided to help with the the mod with my small contribution.

I found XML file where change should be made. So can I upload file and you can merge it in newest version or shall I just write where to find (line in file) that small typo?

Additional question: is this profession info for a particular profession only on one place or could be on several places (read files)? Because I found it in XML_AUTO_UTF8_ProfessionInfo.xml, I corrected it, but there isn't a change ingame/in colopedia visible... :(

**Comment by Sorxus** [comment]
Here:
![image](https://user-images.githubusercontent.com/37362600/102234049-2db7e900-3ef1-11eb-9eab-d8a3201a6264.png)

**Comment by raystuttgart** [comment]
Which version do you play?
Because in "Large Rivers" that is already corrected.
(It was one of the text corrections of @Kendon)
