### ISSUE TITLE
Portuguese wolf...?

### ISSUE THREAD

**Issue by Sorxus** [We-the-People-civ4col-mod/Mod#390]
Picture tells it all. I guess all animals should be "Independent" nation.

![slika](https://user-images.githubusercontent.com/37362600/101732069-eaa6e180-3abc-11eb-87da-7d50c6b59384.png)

And save file:
[George Washington AD-1593-April-Portuguese wolf.zip](https://github.com/We-the-People-civ4col-mod/Mod/files/5670801/George.Washington.AD-1593-April-Portuguese.wolf.zip)

**Comment by MrZorG33** [comment]
before opening a new Issue, it was worth looking at the forum.
the game has an event that gives a wolf.

**Comment by Sorxus** [comment]
Thanks for info, didn't know that.
