### ISSUE TITLE
Petty criminal assigned to forbidden profession (town guard)

### ISSUE THREAD

**Issue by ErikSandbraaten** [We-the-People-civ4col-mod/Mod#394]
This issue eventually causes a null pointer deref because CvUnitAI::AI_betterJob cannot handle the case when a colonist needs to be assigned to an illegal profession (because the original profession is assumed to  be valid)

Original bug report:
https://forums.civfanatics.com/threads/release-candidate-2-8-2-0-testers-needed.665065/page-2#post-15973309

Screenshot:
<img width="1152" alt="petty_criminal_in_town_guard_profession" src="https://user-images.githubusercontent.com/32330976/102686433-0b231a00-41e8-11eb-9e20-d24250297d30.png">

CIV4UnitInfos.xml:

Under <Type>UNIT_CRIMINAL</Type>
           
  <ProfessionNotAllowed>
      <VoidProfessionType>PROFESSION_TOWN_GUARD</VoidProfessionType>
      <bIsNotAllowed>1</bIsNotAllowed>
  </ProfessionNotAllowed>
  <ProfessionNotAllowed>

Summary:

This should obviously not happen. Either the game has been WB'ed or there is a bug that allows illegal professions to be assigned to some units.

I have a candidate fix that prevents the ensuing crash by checking that the unit can have its original profession back. However, there may be a "deeper issue " lurking here that needs to be addresses!

**Comment by raystuttgart** [comment]
I already answered in the thread.
It is related to the **broken 1650 Scenario** which I did not include for good reasons in the Mod.

The Scenario is **not included in WTP** for **good reasons**.

It is imcompatible beyond any realisitc hope to save it again without days of efforts.
(Too many pre-placed Units/Professions, Buildings, ...)

**Comment by dcrookston** [comment]
Is it possible to load it in WTP? Maybe if it's broken beyond repair there
should be a way to prevent it from being loaded at all.

**Comment by raystuttgart** [comment]
How do you want to prevent that???
Old outdated Maps will always be allowed to be loaded, they just instantly crash (at extreme incompatibilities) or eventually cause issues at some point (at smaller incompatibilities).

**Comment by raystuttgart** [comment]
It really is not worth wasting more time on this.
It is just an absolutely typical issues of such "Scenario Maps" with lots of pre-placed stuff.
Problems like that when mods still heavily change have been know since I started modding.

**Comment by dcrookston** [comment]
There must be a way to check, as a map is loaded, that job assignments are
legal. If not they can be reassigned to no job.

**Comment by raystuttgart** [comment]
So you really want to start dll coding for that?
Lots of code checking uncounted special dependencies that might change with every new feature?

Every time the mod loads you would need to check against all possible XML combinations ...
(And again, all of that stuff might change again at some point in time and new XML attributes might be added.)

Seriously, you are wasting your time and efforts.
WTP is not "finished" so there is no realistic chance of catching all possible future changes.

From my perspective:
The map is broken, we knew it and that is it.
Players should simply use the things we deliver and maintain with our releases.
