### ISSUE TITLE
PublicMaps should be PrivateMaps

### ISSUE THREAD

**Issue by Nightinggale** [We-the-People-civ4col-mod/Mod#401]
The Civ4 engine has two places for map scripts

- PublicMaps
- PrivateMaps

The difference is that public maps are available to all mods while private maps are mod specific. FaireWeather requires our python/dll to work and as such doesn't work in other mods or vanilla. This becomes a problem when people load vanilla since the game loads the last used map script from the ini file and does something with it. This results in a torrent of errors before reaching the main menu.

This is fixed by simply renaming the folder. However doing so right now is prone to cause merging issues now that we have a lot of modified files in that folder due to large rivers.

Semi related: a number of people opens vanilla and then pick load mod from the main menu. The awareness of using the mod="whatever" argument in a shortcut seems to be close to non existing.

**Comment by raystuttgart** [comment]
Sounds good.
Had not yet thought about that.

And yes, 95% of our players seem to not know that the mod can be started directly with the shortcut.
