### ISSUE TITLE
Bonuses to market buildings don't apply to the statue of the governor

### ISSUE THREAD

**Issue by Nightinggale** [We-the-People-civ4col-mod/Mod#410]
[link](https://forums.civfanatics.com/threads/release-candidate-2-8-2-0-testers-needed.665065/page-7#post-15991161)

**Comment by raystuttgart** [comment]
Probably very very easy to solve in XML.
Simply copy the XML configuration for "Custom House" effects to the Statue of the Governor.

Will assign it to me and fix it in "Large Rivers".
(Thus when merged with "Big Merge" also in "Common Main Branch".)

**Comment by raystuttgart** [comment]
This is fixed now.
(Commited to "Large Rivers")
