### ISSUE TITLE
Captured horses when capturing an English free colonist standing on a native settlement

### ISSUE THREAD

**Issue by Nightinggale** [We-the-People-civ4col-mod/Mod#412]
Description with savegame.
[link](https://forums.civfanatics.com/threads/release-candidate-2-8-2-0-testers-needed.665065/page-4#post-15981722)

**Comment by ErikSandbraaten** [comment]
I was not able to reproduce this issue with the given save

**Comment by raystuttgart** [comment]
@Nightinggale 
Is this bug still open?

**Comment by Nightinggale** [comment]
Nobody ever managed to reproduce this. If it ever occurs again, it should be reported again with a new savegame. That way we might have a chance to figure out what is going on.
