### ISSUE TITLE
Typos in EVENT_PROSTITUTES_2

### ISSUE THREAD

**Issue by Nightinggale** [We-the-People-civ4col-mod/Mod#413]
Both an extra space in the second option and the city didn't show up in the text.

![screenshot](https://forums.civfanatics.com/attachments/prostitutes-jpg.580516/)
[link to forum report with replies](https://forums.civfanatics.com/threads/release-candidate-2-8-2-0-testers-needed.665065/page-8#post-15994231)

**Comment by MrZorG33** [comment]
I met such a error when I was translating into Russian. most likely misspelling "%s2_city".
the text is in the CIV4GameText_Colonization_Events_utf8.xml file

**Comment by raystuttgart** [comment]
I will check it.
