### ISSUE TITLE
Large Rivers. The point of appearance of the Pirate Frigate was on a large river.

### ISSUE THREAD

**Issue by MrZorG33** [We-the-People-civ4col-mod/Mod#417]
Slack chat we_the_people
https://colonization-mod.slack.com/archives/CCYAJA0SY/p1610483357000600

**Comment by raystuttgart** [comment]
This is solved now.
Bugfix commited.

**Comment by MrZorG33** [comment]
@raystuttgart now Frigate has appeared in the city on the Large River (Plains from 04/02/22).
![image](https://user-images.githubusercontent.com/61798883/152890764-75ee698f-94f0-4a28-a159-d90fc192db7b.png)

**Comment by raystuttgart** [comment]
Is it a Pirate Frigate or a normal Frigate? This is **important** to know.
(The bug was about "Spawning of **Pirate** Frigates".)

**Edit:**
I see, it is a **normal Fritgate**.
(Thus not related to Pirate Spawning.)
