### ISSUE TITLE
Large Rivers. trade routes disappear from auto-transports

### ISSUE THREAD

**Issue by MrZorG33** [We-the-People-civ4col-mod/Mod#419]
Slack chat we_the_people
https://colonization-mod.slack.com/archives/CCYAJA0SY/p1610225758179300

also need to fix disabling auto-export after loading a saved game

**Comment by ErikSandbraaten** [comment]
Please create a separate issue for:" fix disabling auto-export after loading a saved game"

**Comment by MrZorG33** [comment]
issue #425

**Comment by ErikSandbraaten** [comment]
In the attached save I see that Jamestown and Plymouth are in the same area while Boston is in a different one. Essentially the first two settlements are on their own "island" and that is why there's no option to trade with Boston.

**Comment by ErikSandbraaten** [comment]
I am not sure if this is intended (I suppose this map has been edited). Either we should ensure that land masses separated by large rivers end up in the same area or we have to change quite a bit of the movement logic (which could have several side effects that could be hard to anticipate)

**Comment by ErikSandbraaten** [comment]
@MrZorG33 Please check that the issue has been resolved

**Comment by MrZorG33** [comment]
I will try to check it before the end of the week.

**Comment by MrZorG33** [comment]
trade routes also disappear. automated transport "stuck" in the ford on the Big River.
files in working chat.
https://colonization-mod.slack.com/archives/C01TTSTMEGZ/p1617738649001900

**Comment by MrZorG33** [comment]
fixed.
