### ISSUE TITLE
Large Rivers. forecast of the battle results is not shown

### ISSUE THREAD

**Issue by MrZorG33** [We-the-People-civ4col-mod/Mod#420]
Slack chat we_the_people
https://colonization-mod.slack.com/archives/CCYAJA0SY/p1610198908170100

**Comment by ErikSandbraaten** [comment]
I have a candidate fix for this issue. It turns out that the original code is probably a bit buggy. For example, it fails to check if the unit considering the attack can actually move into the target plot (a soldier attempting to attack a mountain for example) so it is not surprising that it fail to deal with the addition for large rivers \ river fords.

**Comment by ErikSandbraaten** [comment]
@MrZorG33  Please check that the issue has been resolved

**Comment by MrZorG33** [comment]
@**ErikSandbraaten** Okay. but I have to start a new game. I will need a little time.

**Comment by MrZorG33** [comment]
fixed

**Comment by MrZorG33** [comment]
in the late game (**Plains** from 04/02/22) sometimes does not show the calculation of the results of the battle. so far I have only noticed this when attacking non-military ground units.
![image](https://user-images.githubusercontent.com/61798883/152916740-810540ce-9882-4be0-8c51-1f5d266cacb3.png)

sometimes when loading a game, you may get this error:
![image](https://user-images.githubusercontent.com/61798883/152918435-0a5baee9-3867-4f42-92df-c89a653aba47.png)

[war.zip](https://github.com/We-the-People-civ4col-mod/Mod/files/8020805/war.zip)

**Comment by raystuttgart** [comment]
@MrZorG33 
The bug in the **"Python Exception"** is related to encoding (**Characters**)
I highly suspect that it is somehow related to the **Russian Translation changes**.

**Comment by raystuttgart** [comment]
@MrZorG33 
The Combat Chances not being shown may be an issue already fixed in "Yields".
(I have to check it once I find a bit of time - it might be related to "bDefensiveOnly" in XML.)

**Comment by MrZorG33** [comment]
@raystuttgart , what does the translation into Russian have to do with it? I haven't translated anything yet.

**Comment by raystuttgart** [comment]
There is **GameFonts** for Russian **Language / Chars**.
The exception says it has a **bug in "encoding a char"**.

**Comment by raystuttgart** [comment]
However both bugs we discuss right now are **completely unrelated** to the **original bug report** ... :(

**Comment by raystuttgart** [comment]
Closed because bug reports unrelated to original issue.
