### ISSUE TITLE
Large Rivers. horses disappearing

### ISSUE THREAD

**Issue by MrZorG33** [We-the-People-civ4col-mod/Mod#421]
Slack chat we_the_people
https://colonization-mod.slack.com/archives/CCYAJA0SY/p1610801518016700

**Comment by raystuttgart** [comment]
It is simply: Warehouse Overflow
(You are beyond the limits of your Storage Capacity.)

**Comment by MrZorG33** [comment]
a customs house was built in the colony. the screenshots show this.

**Comment by raystuttgart** [comment]
So what? The Custom House would just sell.
There is no way to prevent "Overflow" (goods being lost) once your storage capacity is exceeded.
