### ISSUE TITLE
Missing "<string>", line 1 file on startup of base civ4col

### ISSUE THREAD

**Issue by TheRawrInc** [We-the-People-civ4col-mod/Mod#422]
Hey guys, I'm having trouble with my files after installing your mod and it won't let me start a new game without the mod.  I can however start a new custom game on base civ4col without any complications.  I only installed the mod last last night and played 1 game with it, but I'm relatively new with civ4col in general.  Upon start up w/o mod it says on repeat "Missing Files: "<string>", line 1, in, ?  Import Error: no module named FaireWeather" and, "Failed to load python module FarieWeather"

When I finish clicking through all the error messages it takes me to the standard loading screen as usual.  But the only thing that doesn't seem to work now is the issue stated in my previous statement.  When I load up the WTP mod and click "Play Now" It's fine.

TheRawrInc

**Comment by Nightinggale** [comment]
Same problem as #401

**Comment by TheRawrInc** [comment]
Thank you @Nightinggale
