### ISSUE TITLE
Large Rivers. indestructible village market

### ISSUE THREAD

**Issue by MrZorG33** [We-the-People-civ4col-mod/Mod#424]
during the raid of natives on the colony, a message appears several times about the destruction of the village market. but it is not physically destroyed.
a message with screenshots and a game save file on the forum.
https://forums.civfanatics.com/threads/release-candidate-2-8-2-0-testers-needed.665065/page-11#post-16010875

**Comment by MrZorG33** [comment]
should be corrected by @ErikSandbraaten , but needs verification.

**Comment by Nightinggale** [comment]
I fixed this in f9ccdfaeea4766182c4e4b2b37e1553b9e915681
However apparently I forgot to close the bug report.
