### ISSUE TITLE
Large Rivers. auto-export disabling after loading a saved game

### ISSUE THREAD

**Issue by MrZorG33** [We-the-People-civ4col-mod/Mod#425]
need to fix this before a new release.

**Comment by MrZorG33** [comment]
by the way, playing for a long time, I noticed that goods are not delivered to other colonies. this is an auto-export error. goods produced in the colonies are transported to the capital. but they are not delivered from the capital to other colonies.


https://colonization-mod.slack.com/archives/CCYAJA0SY/p1615735476025000

**Comment by ErikSandbraaten** [comment]
Could you explain a bit better what this issue is about.  Not sure if I understand.

Also, are you saying that this feature works for a bit and then stops working. Perhaps you loaded a savegame and something is not saved correctly?

**Comment by MrZorG33** [comment]
it was a long time ago. now the auto-export activation disappears immediately after loading the game.
screen 1 - before loading, screen 2 - after loading. You can see this in any of your game.

https://colonization-mod.slack.com/archives/C01TTSTMEGZ/p1618093158004800
