### ISSUE TITLE
move the game screen to the colony when the building availability screen appears

### ISSUE THREAD

**Issue by MrZorG33** [We-the-People-civ4col-mod/Mod#426]
discussion on the forum:
https://forums.civfanatics.com/threads/center-of-the-screen-on-the-city-when-an-event-occurs.663321/

**Comment by raystuttgart** [comment]
Finished now.

**Comment by MrZorG33** [comment]
I pasted the code into vDLLButtonPopup.cpp but there is no change. maybe I missed something?

// Ramstormp, WtP, Add Examine Settlement option to the no longer lacking yields for building production popup - START 
		iExamineCityID = 0;
		iExamineCityID = std::max(iExamineCityID, GC.getNumUnitInfos());
		iExamineCityID = std::max(iExamineCityID, GC.getNumBuildingInfos());

		if (pPopupReturn->getButtonClicked() == iExamineCityID)
		{
			CvCity* pCity = GET_PLAYER(GC.getGameINLINE().getActivePlayer()).getCity(info.getData1());
			if (pCity != NULL)
			{
				gDLL->getInterfaceIFace()->selectCity(pCity, true);
			}
		}

		else if (pPopupReturn->getButtonClicked() >= GC.getNumUnitInfos())
// Ramstormp - END

![image](https://user-images.githubusercontent.com/61798883/143787116-3b908e64-aa65-4173-af37-c5d9f2946632.png)

**Comment by MrZorG33** [comment]
I checked - it works.
![image](https://user-images.githubusercontent.com/61798883/143891097-fefe00d8-1416-4a2f-8fd7-a5ef7b2b1a57.png)

but if you enter the city to check the information and leave, then the proposal to build a building disappears and does not appear any more.
![image](https://user-images.githubusercontent.com/61798883/143891387-818680cb-e536-433a-b95f-5e84b544ca21.png)

**Comment by raystuttgart** [comment]
Once you entered the City it is fine for me that the proposal does not appear anymore.
You can make your decision in there or in the Pop-Up the first time.

**Comment by MrZorG33** [comment]
in my opinion this is not correct - we go into the city to see what needs to be built. and if a building is under construction in the city, then we will lose one turn if we manually choose from the proposed one. and if the offer appears again, the building will be built automatically. construction of another building will continue, without delay.
if this is possible, let's try it.

**Comment by raystuttgart** [comment]
Well, if **@Ramstormp** wants to continue working on it, I do not mind. :dunno:
Personally I feel it is fine as it is.

**Comment by MrZorG33** [comment]
the fact is that when this message appears, the building is built immediately and you do not need to put anything in the queue.
I know about the "Build Queue")

if @Ramstormp is ready to continue, that's great.

**Comment by raystuttgart** [comment]
So all you want is that the Pop-Up does **not** close, when "Examine Settlemen" is selected?
Might be easy to do - will not have time to check it though before the weekend comes.

**Comment by MrZorG33** [comment]
it's okay - it's not urgent)
