### ISSUE TITLE
request to increase the size of the import / export window

### ISSUE THREAD

**Issue by MrZorG33** [We-the-People-civ4col-mod/Mod#428]
There are a lot of goods for import / export in the colonies. and the window for displaying them is small. you have to scroll a lot. to improve the gameplay, I suggest increasing the size of this window.
screenshot in work chat
https://colonization-mod.slack.com/archives/C01TTSTMEGZ/p1617807256002800

**Comment by Nightinggale** [comment]
I fully agree that we should make this window bigger. However it's of type CvPopup, which is drawn by the exe file. We can't adjust the size. Instead we would need to rewrite the entire draw code from scratch. I'm not saying it won't happen, but it's not a simple task.

**Comment by MrZorG33** [comment]
I did not know it.
close the Issue?
