### ISSUE TITLE
Random event "skipper's widow opened up a brothel" have a strange option: perhaps from before there are sailcloth and ropemakers?

### ISSUE THREAD

**Issue by abmpicoli** [We-the-People-civ4col-mod/Mod#43]
This random event have a strange option: "These harlots sure have nimble fingers. Set each one in front of a loom!" ... and this gives a Master Weaver... 
This make sense, perhaps , with TAC, where the requisite for building ships was cloth... But with this game, where sailcloth and rope are the proper components for ship, this doesn't make much sense... 
![image](https://user-images.githubusercontent.com/1733170/45648200-1f728c80-ba9e-11e8-80ee-c0d40b49f3d8.png)

**Comment by raystuttgart** [comment]
It also makes sense now, because for a Weaver you really need nimble fingers.
Why should widows of Sailors not be able to work as Weavers? :dunno:
