### ISSUE TITLE
CvEventInfo iGenericParameters should allow enum text

### ISSUE THREAD

**Issue by Nightinggale** [We-the-People-civ4col-mod/Mod#438]
I just noticed an event, which has YIELD_MUSKETS as a generic parameter. That is it has 30 as an int parameter. Not great as it's less readable and if yields updates, it will break the event.

Change the generic parameters to be of type string on read. Let CvEventInfo::read() convert it to int if it's an int and if not, then convert it to the int of the index of whatever xml type the string matches. If none of those and the string isn't empty, then cause an assert failure.

Implementation should take place in CvXMLLoadUtility as this will allow it to be reusable, not just for all 4 generic parameters here, but in general in all xml files.

This is not to be confused with CvXMLLoadUtility::GetEnum. Despite this function being able to convert a string to an enum index, it is designed to be strict and only accept enum strings and only from the file specified by the template argument type (like YieldTypes only accepting CvYieldInfo type strings). It is designed to assert fail if the xml contains an invalid string, like a type from the wrong xml file.

**Comment by raystuttgart** [comment]
Originally simply I did not create "Generic Parameters" for any other than ints.
(All my original use cases were just numbers, not Types.)

The suggested solution sounds good.
(Will definitely make it less error prone.)

Currently not high priority for me though, because all Events currently work.
