### ISSUE TITLE
promotion system may not be working as intended

### ISSUE THREAD

**Issue by inaiwae** [We-the-People-civ4col-mod/Mod#441]
this maybe redundant as Ray is planning to redesign Promotion system, but as of current code I came across these:

ships that cannot attack, i.e. can defend only are excluded from getting Merchant Vessel promotion because it grants Withdrawal chance (it is there 2x actually, someone wanted to be extra sure ;)

```cpp
if (isOnlyDefensive())
    {
        if (kPromotion.getWithdrawalChange() != 0)
        {
            return false;
        }
```

code would not let one pick promotion if withdrawal chance would increase above threshold set in XML file (default 90% chance), barring from finishing promotion tree ... for example I couldn't promote into higher levels of Naval Combat tree because of that ... we should not care about "raw" value being higher than MAX_WITHDRAWAL_PROBABILITY during promoting, that check and cap should be moved to phase that handles combat result

```cpp
    if (kPromotion.getWithdrawalChange() + withdrawalProbability() > GC.getDefineINT("MAX_WITHDRAWAL_PROBABILITY"))
    {
        return false;
    }
```

maybe there were some intentions behind this, maybe it's just a unintended bug, I modded it myself to fit my play-style , but was told to bring it to the attention of mod team :)

**Comment by raystuttgart** [comment]
Thisneeds to be checked, because it is possible that "only defensive" Units should never get Withdrawal Promotions, because the Combat System may not Trigger Withdrawal for them.

**Summary:**
The combat logic needs to be checked how it handles "Withdrawal" for "only defensive" Units.

**Comment by inaiwae** [comment]
it definitely worth to check, but it should be fine as those ships have native withdrawal chance

<Type>UNIT_CARAVEL</Type>
<bOnlyDefensive>1</bOnlyDefensive>
<iWithdrawalProb>10</iWithdrawalProb>

**Comment by raystuttgart** [comment]
This has been taken care off now.
The Promotion was adjusted.
