### ISSUE TITLE
the unit continues to auto-move after meeting the enemy

### ISSUE THREAD

**Issue by MrZorG33** [We-the-People-civ4col-mod/Mod#452]
my Caravel was doing automatic scouting. She was attacked by Privateer, but was unable to destroy. before, after such an attack (or when meeting an enemy), the unit would stop so that the player could make a decision. however, my Caravel continued automatic scouting. I found the same behavior in the Scouts.

![атакованный корабль продолжает автодвижение](https://user-images.githubusercontent.com/61798883/117339076-fea61200-aea7-11eb-927d-2b7ede2f49ca.jpg)

**Comment by Nightinggale** [comment]
The caravel stops if it scans for danger and detects something. It's too time consuming to always scan and if the pirate can show up, attack and vanish between two attacks, then no scan from the caravel will detect danger. At least that would be my guess without checking the code.

Fixing this problem for good would likely require a solution like the visual counter. CvPlot counts how many units can see a plot, which are also set to "stop at danger". If a unit enters a plot where the count isn't 0 and said team would classify it as danger, then perform a scan to find units to stop.

The problem with this implementation is that it isn't an easy or quick solution to implement. A faster solution would be to always disable if set to "stop at danger" if it enters combat.

**Comment by dcrookston** [comment]
Couldn't you just add something to the combat code that unsets the
"currently scouting" flag?

**Comment by MrZorG33** [comment]
What is the principle of responding to danger in auto transport? they stop moving if there is a danger within a radius of 2 tiles.

**Comment by XSamatan** [comment]
ideally any unit would stop its movement when it enters a plot from which it can see an enemy unit. An attack should always stop movement orders.

**Comment by raystuttgart** [comment]
@Nightinggale 
I think you fixed this as well in 3.0
At least I saw such a commit.

**Comment by MrZorG33** [comment]
**develop** testing.
this bug showed up again.
if possible, please check it. ships continue to auto move after being attacked.

**Comment by raystuttgart** [comment]
I will check it again - might actually be easy to fix.
(Might have been wrong with thinking that it was already fixed by @Nightinggale)

**Comment by raystuttgart** [comment]
Definitely fixed now.
Check the commit (in Plains).
