### ISSUE TITLE
CvTraitInfo: tag CityExtraYields is not used correctly

### ISSUE THREAD

**Issue by Nightinggale** [We-the-People-civ4col-mod/Mod#459]
CvTraitInfo's tag CityExtraYields lacks a proper implementation. It seems the bonus is never added, or rather maybe it is, but then the cache isn't updated... not sure. Either way getting a trait through an FF (discovered with Ivan Aleksandrovich Kuskov) doesn't work as expected.

-----

I propose scrapping the implementation and redo it with strict typing in CivEffects. This way anything providing CivEffects can get it.

-----

Perhaps it would be best to introduce some sort of "city promotion". This will create cleaner and reusable code (less risk of bugs) and quite possibly allow more aggressive caching in CvCity, making the game faster. It could also be used for more detailed GUI regarding how colonies are affected.

**Comment by raystuttgart** [comment]
This was and is definitely working correctly in "Large Rivers".
It must have been broken in 2.8.2.x ...

**Comment by Nightinggale** [comment]
I got it. 

CvPlayer::updateCityExtraYield needs to be called to update the cache. However CvPlayer::processTrait calls CvPlayer::updateYield without using CvPlayer::updateCityExtraYield, hence it doesn't update the cache.

The calls looks like an awful waste of CPU cycles. For each yield, which changes, all traits are looped and all plots are recalculated for for each yield. Same is true for extraYieldThreshold. Also if either one of them changes anything, for good measure all plots recalculate all yields once done.

Looks like this is vanilla code.

**Comment by raystuttgart** [comment]
Ok just checked.
(Using Cheat Menu for Founding Fathers)

I was wrong:
It is **already broken** in **Large Rivers**

By the way:
**Might** have been broken already since **TAC** or even **Vanilla**.
(The only other traits that use such a modifier are given to Natives - so maybe nobdy ever noticed ...)

**Summary:**
This is definitely not a new bug of 2.8.2.x
No idea why I thought it was working and never noticed ingame ...

**Comment by raystuttgart** [comment]
I confirm as well. 
(Just also tested.)

Working nicely. 👍
