### ISSUE TITLE
Make savegames more bug resistant survive code and xml changes

### ISSUE THREAD

**Issue by Nightinggale** [We-the-People-civ4col-mod/Mod#46]
Medieval Conquest has highly modded savegames. There are two parts to this (partly merged together).

~~Savegame breaking issue 1:
Savegame code doesn't use read and write functions. Instead it use readWrite(bool bRead). The idea is that savegames are ruined if read and write goes out of sync regarding how many bytes they store and in which order the variables appear. If it's just one function, it becomes one list and it won't go out of sync.~~
Idea discarded. There is an enum approach explained further down, which handles the order issue in a different way and that approach will not mess up the read function code like this one would do.

Savegame breaking issue 2:
Prevent savegames from breaking if xml changes.
Vanilla approach is say it saves a unit and it saves UnitTypes for the unit, which is UNIT_MINER. It looks up the index in xml and saves the index. The index is currently 5. When reading, it reads 5 and converts it back to UNIT_MINER. If a new unit is added to the front, 5 is no longer UNIT_MINER and the savegame is broken.

Another issue is saving arrays. They can be saved of the length of the array, meaning if one index is added, the number of read and written bytes differs and the savegame is completely gone.

**Proposed solution** (which works in M:C):
What I added in M:C is a kind of header to savegames. It loops through the files, writes the number of files and the Type tag from xml, though with the prefix removed for size reasons (they all start with UNIT_ in one file etc, though there is an assert check for this at startup). On load, it compares those strings with the current xml and makes a conversion table. When reading the 5, which should be UNIT_MINER, it can figure out the new index is 6 and it writes 6 in memory. This way even if the int _value_ differs, the same _game contents_ is read.

Arrays of length of some file is another issue. The answer here is simple. Use JustInTime arrays. In Medieval Conquest they have readWrite build into it and can handle both offset issues in the array and change individual indexes (say an array of type UnitTypes, each containing a UnitClassTypes and both are converted).

Using this system is simple. It's done with overloaded readWrite functions. If it's called with int, it reads an int. If it's called with UnitTypes, it reads and int and then does the conversion. If it's YieldTypes, it converts according to the yield xml and so on. No special code in the savegame code itself. The same with JIT arrays. No special code in the savegame code. Just copy the JIT files from M:C.

**Comment by abmpicoli** [comment]
I'm changing the title. Because there is not only xml based data that is stored. If we add an extra variable to be persisted, for example, we will also lose structure, and, hence , the save.

**Comment by Nightinggale** [comment]
adding variables is supported by vanilla. Take a look at CvCity::read()

```
	uint uiFlag=0;
	pStream->Read(&uiFlag);	// flags for expansion

	// just-in-time yield arrays - start - Nightinggale
	uint arrayBitmap = 0;
	if (uiFlag > 3)
	{
		pStream->Read(&arrayBitmap);
	} else {
		arrayBitmap  = SAVE_BIT_CUSTOM_HOUSE_SELL_THRESHOLD | SAVE_BIT_CUSTOM_HOUSE_NEVER_SELL;
		if (uiFlag == 3)
		{
			arrayBitmap |= SAVE_BIT_ORDERED_STUDENTS | SAVE_BIT_ORDERED_STUDENTS_REPEAT;
		}
	}
```
uiFlag is a version counter. Each time a variable is added/changed/removed, increase the number by one. In this case I apparently changed some code related to how custom house and students are saved, meaning it loads a different amount of bytes depending on version 3, higher or lower. This system actually works ok if people remember to use it consistently.

**Comment by abmpicoli** [comment]
You can see where this spaghetti is going , right? Super Megazorde Class of Doom :smile:

**Comment by Nightinggale** [comment]
If you have an idea on how to make a better system, then go ahead and design it. Besides we can clean this specific case up because pre uiFlag 4 savegames can't be read anymore due to other people not being as picky about preserving savegames and backward compatibility broke elsewhere.

**Comment by abmpicoli** [comment]
I still don't have a complete idea... But we could make structures similar to json trees, or streams... where we could have a dictionary header, and then a data stream that feeds into a map. This map data could then be collected to feed the properties, by searching for key/value tags...

**Comment by abmpicoli** [comment]
As long as we don't change the key names, we could add new properties to be persisted at will... As long as we don't make them mandatory values (that is, properties with no valid default value).

**Comment by Nightinggale** [comment]
I kind of like that idea, but it's not without issues.

First of all, the M:C savegame file (yes I moved everything into one file, not spread across the various files). [Savegame.coo](https://sourceforge.net/p/colonizationmodcollection/sourceDLL/ci/develop/tree/DLL_Sources/Savegame.cpp)

The exe calls read() or write() of classes in the following order
 * CvInitCore
 * CvGameAI
 * CvMap
 * CvTeamAI * MAX_PLAYERS
 * CvPlayerAI * MAX_PLAYERS

The last two are arrays of length MAX_PLAYERS, which is a define in a DLL header file.

Reading is done by reading variables from a bytestream and it supports variables of 1, 2 and 4 bytes. You can read arrays, but then you have to tell in advance how many elements the array has. Converting this to a text based format is not trivial, though it could likely be done.

It looks like once in a while the game only wants to read CvInitCore.

Another issue is that when somebody joins a network game, the host saves in memory and then transmits the savegame. This game is certainly not optimized for fast transfers, meaning adding all that plain text will make it even slower to join.

If we make a brand new format and make the exe handle it as a byte array, then we should take the chance to compress it because currently savegames are uncompressed.

**Comment by abmpicoli** [comment]
I'm not talking about using json, notice that. I'm talking about a compact format, formed by a key-value map and some binary markers.... say.... a json like this:
{ "bla":"ble" , "bli":"blo" } ... would become a header where there were mappings for key x values:
0=bla ; 1=bli ; and then a stream like [00]ble[01]blo ...

**Comment by Nightinggale** [comment]
Here is what we can do: we can make an enum and then each variable gets an enum value. If the variable isn't used anymore, it stays in the enum (perhaps with a comment). Also we only append to the end. That way each variable can get a permanent ID.

Reading is then read int (enum) and then do a switch on the enum value. repeat forever and have the first enum value mean return/end of this class. This seems doable without being creative with the existing exe file API (which we can't alter). We can make code to skip saving variables containing the default value, which is often a lot of them.

This would be using 4 bytes extra for each variable though, but we could start the savegame with a byte array, each byte telling the bytesize of the prefix for each class. Saving will then set the bytesize according to the end value in the enum. This way it will start out with just a byte for each variable, but increase to two bytes if needed even without the programmer paying attention to the issue.

It would still require the conversion mentioned in the first post though. Small savegames would still mean we save UnitTypes values instead of the Type string each time, but it would solve the issue of read and write going out of sync, hence removing the benefit of merging them into one.

**Comment by Nightinggale** [comment]
The more I think about this savegame format, the more I like it. We should make a new directory in the source and make a file for each class being saved. Each file should consist of:

* enum
* init
* read
* write

The file can then have a static function (not member function) which takes enum and a variable as arguments. It then returns the default value of the variable linked to the enum. The variable is not really used other than it can be used to overload, which in turn allows different return types.

We could argue that a set function could be useful as well, but that wouldn't be long because it would be a template function taking the enum and a template reference as arguments. It then sets the reference to the get function return value.

This approach will isolate the savegame code from the rest of the code and at the same time init and savegames can will read default values from the same location, meaning they can't get out of sync.

This would likely need a bit of trial and error in an experimental branch to see if we can get to a result we can agree on. One thing is that it sounds great in text. Another is if the code turns out as maintainable as it is in my mind right now. It's certainly something experimental and not something for the next release.

**Comment by Nightinggale** [comment]
I think the approach should be one file for each class. Each such file should contain

* Default values
* Class reset to default values
* Enum for saved variables
* read/write

The default values should be "global" const. Reset is obvious.

Writing should be a bunch of lines, each being a function call of 3 arguments (enum, variable, default). This function to call will then compare the variable to the default and if they aren't identical, save first the enum and then the variable. The code to do this is shared for all classes. The goal of this function is to make the write classes simple.

Read should start by resetting and then an infinite loop. It starts by reading an enum value and then it goes with a switch case. Each case reads a certain variable. Enum value 0 is "end of class", which is handled with just a return.

Ints, which refers to xml indexes should all be enum types. Reading enum types should be overloaded to convert indexes on load in case the xml files changed.

Arrays should be BoolArray or JIT array. Both will be converting indexes as needed as well internally. This means the entire engine to convert indexes to match xml changes will be able to take place without a single line of code in the savegame files for each class.

Read and write can't go out of sync with this approach, the default is written once and in an easily readable format and everything can be done with fairly clean code.

**Comment by Nightinggale** [comment]
New savegame format done.
