### ISSUE TITLE
upload the corrected Amerayca map to the repository

### ISSUE THREAD

**Issue by MrZorG33** [We-the-People-civ4col-mod/Mod#460]
![неправильная плитка01](https://user-images.githubusercontent.com/61798883/118379284-e178ee00-b5e1-11eb-9120-dd7286ec6bd2.jpg)

fixed
![image](https://user-images.githubusercontent.com/61798883/118379871-8ac1e300-b5e6-11eb-9105-5e47fb84eb05.png)

[Amerayca.zip](https://github.com/We-the-People-civ4col-mod/Mod/files/6488369/Amerayca.zip)

**Comment by raystuttgart** [comment]
@MrZorG33 
You can upload youself as well, if you simply directly fix by e.g. Notepad++ in the file. 
There is no need to assign it to others. :)

I uploaded it now though.

**Comment by MrZorG33** [comment]
I have not been able to find how this can be done.  maybe I don't have permission for this?

**Comment by raystuttgart** [comment]
Ah ok, thanks for telling. 👍 
Thought we had given you commit permissions as well.

**Comment by MrZorG33** [comment]
I found a discrepancy in the LR tiles. now fixed (coast -> LR).  need to upload the corrected version of the map to the repository.
[Amerayca.zip](https://github.com/We-the-People-civ4col-mod/Mod/files/6529035/Amerayca.zip)

**Comment by raystuttgart** [comment]
Thanks.
The corrected map is now uploaded.
