### ISSUE TITLE
allow ships to transport only units

### ISSUE THREAD

**Issue by MrZorG33** [We-the-People-civ4col-mod/Mod#462]
land carriages and smuggling ships can only carry goods.
I have a proposal to allow warships to transport only units. and only military units. it would be logical - warships could carry troops.

What do you think about it?..

**Comment by dcrookston** [comment]
I think if you have room in the hold for people, you can also put
non-people things in there.  You can't necessarily put people in a cargo
hold though -- at least if you want them relatively intact when you get to
your destination.

**Comment by MrZorG33** [comment]
"_I think if you have room in the hold for people, you can also put non-people things in there._"
Yes, I agree. But I want to make it so that "warships" can only transport military units. I think this will be an interesting innovation. Let the rest be transported by "merchant ships".

**Comment by raystuttgart** [comment]
@MrZorG33 
Ok that is possible and not event difficult for a programmer.

But I need to have to **implement** it for you. (in DLL)
You currently have no chance to do it by yourself.

I will post in the forum and ask the team and community if they want to have it.

**Comment by raystuttgart** [comment]
Might even work already by just XML if the SpecialUnits are **not "Types"** in DLL. (Have not checked yet.)
But you still need to understand what you have to do.

If @Nightinggale likes it, this request is a piece of cake.
We can simply have the System support it.

Maybe your complete idea might be interesting for WTP.

**Comment by Nightinggale** [comment]
I'm fine with this. I want it to be fairly easy to set up in xml. Something like a cargo type tag in units and then an array in transports telling which types they can load. That's simple and intuitive in xml and the DLL can be made to check this easily in a very fast approach.

**Comment by raystuttgart** [comment]
@MrZorG33 It is implemented if you want to use it in your modmod. :)
(Already available in develop.)

Have fun modding. 👍  

Since this is realized I will close the issue now.
(Again, it is done and you can modify it yourself.)

**Comment by MrZorG33** [comment]
thanks, i will try)
