### ISSUE TITLE
Land areas should spread across large rivers

### ISSUE THREAD

**Issue by Nightinggale** [We-the-People-civ4col-mod/Mod#464]
Mod the land area spread code allow spreading across large rivers without altering the river plot's water area. This way only land units won't be confused even if two islands are split by only a large river.

Setting two areas in CvPlot might be attractive to do this as it can be used to make area() and getArea() faster.

This isn't urgent at the moment because the trigger condition for this issue isn't in any current maps. As such this will not affect gameplay, but it might with future maps (particularly if large rivers shows up in random maps).

**Comment by raystuttgart** [comment]
@Nightinggale 
This is fixed now to my knowledge. :)
Will thus close it now.
