### ISSUE TITLE
after the destruction of the colony, trade routes did not leave

### ISSUE THREAD

**Issue by MrZorG33** [We-the-People-civ4col-mod/Mod#466]
during the war with the natives, two colonies were destroyed. however, trade routes remained. I now have two trade routes with an unknown destination. because of this, wagon trains are loaded with stones and do not move. why trade routes were left with only a stone - I cannot understand.

![image](https://user-images.githubusercontent.com/61798883/119387497-b2ddd000-bcd1-11eb-8640-fc7a00ed61ce.png)
[war.zip](https://github.com/We-the-People-civ4col-mod/Mod/files/6534109/war.zip)

**Comment by raystuttgart** [comment]
Yeah, stuff like that can easily happen in programming.
You simply do not consider every use case.
Most likely I would also have forgotten to regularly check the alredy created / stored Trade Routes (each turn) if they are still valid.

**Comment by Nightinggale** [comment]
Fixed.

Vanilla code turned import off, but then feeder service turned it back on. Now CvCity::kill will also turn auto export and feeder service off, preventing this from happening again.

Fixing the existing savegame can be done by turning off export of stone in Novo Arkhangelsk as that kills all trade routes with stone starting from this colony. It can then be turned on again right away.
