### ISSUE TITLE
 tribalvillage_md_pop.kf refers to non-existing EFFECT_IMPROVEMENT_GOODYHUT_POP

### ISSUE THREAD

**Issue by Nightinggale** [We-the-People-civ4col-mod/Mod#469]
As title says. Assets\Art\structures\improvements\NativeHostileVillage\tribalvillage_md_pop.kf contains a reference to EFFECT_IMPROVEMENT_GOODYHUT_POP, but that's the only place that string exist, which causes an assert failure when the exe asks the DLL for the effect in question.

**Comment by raystuttgart** [comment]
@Nightinggale 
That graphic is used from Civ4BTS and the Effect might exist there - but not in Civ4Col.
Maybe that is the reason why it causes the Assert.

@Schmiddie1979 could definitely easily correct it, but I can not.
I do not know how to modify those KF files properly. (NIF-Scope)

**Comment by raystuttgart** [comment]
Kathy sent us the correction.
Issue should thus be solved.

@Nightinggale 
Let me know if the Asserts still triggers.
I expect it will not do that anymore and thus close the issue.
Have not yet tested though myself.
