### ISSUE TITLE
automated transport "captured" a moving unit

### ISSUE THREAD

**Issue by MrZorG33** [We-the-People-civ4col-mod/Mod#470]
automated transport in cities / forts can "capture" a moving unit. 
in the screenshot: the automated Conestoga, transporting cargo from one colony to another, has loaded a unit (Line Infantry) into its cargo space ("captured"). The line infantry also moved from one colony to another - it was on the move. automated transport can "capture" only moving unit. this happens very rarely, but always unexpectedly) in this case, the automatic delivery of goods is canceled and the transport stops.

![image](https://user-images.githubusercontent.com/61798883/120691601-58055f00-c4af-11eb-8176-84c926a5375f.png)
[war.zip](https://github.com/We-the-People-civ4col-mod/Mod/files/6593499/war.zip)

**Comment by raystuttgart** [comment]
Thanks for reporting, that is actually easy to fix.
(Had read that already but had forgotten about it.)

**Comment by raystuttgart** [comment]
It is fixed.
(Branch "Lakes")
