### ISSUE TITLE
Fix directory structure for "Assets" and "assets" in released zip file

### ISSUE THREAD

**Issue by wyphan** [We-the-People-civ4col-mod/Mod#474]
On Linux, the zip file contains two separate directories, one called "assets" (all small letters) containing only `CvGameCoreDLL.dll`, and the other one called "Assets" (with a capital "A") containing the rest of the mod resources. Perhaps it's better to merge them together into just "Assets"?

**Comment by Nightinggale** [comment]
Already fixed in the build script. Only Assets will be used starting with the next release.

**Comment by wyphan** [comment]
That was fast, thanks!
