### ISSUE TITLE
Ugliness in UnitInfos.xml: Builds inherited from Civ4BTS

### ISSUE THREAD

**Issue by raystuttgart** [We-the-People-civ4col-mod/Mod#477]
In Civ4BTS Builds were only related to Units.
So all Builds had to be configured at each Unit specifically.

But in Civ4Col Builds are related to the Profession Pioneer.
(And of course could theoretically also be given to another Profession.)

Thus we shoud consider one of the 2 solutions:

- Shift the "Builds" from Units to the Professions (and configure it at Profession "Pioneer")
- Or Shift the Builds from Units to or a separate XML (and reference it at Profession "Pioneer".)

If we do our XML will be **much cleaner**.
Adding a new Build will also n**ot be stupid Copy & Paste** at uncounted places anymore ...

**Comment by Nightinggale** [comment]
I plan to add a new xml file, something like unit data info.xml
It can contain the lists, which are shared between multiple units such as BuildInfo and then BuildInfo can have a single tag to tell which one to use. That way multiple units can share the same list.

UnitInfo can have multiple tags, one for each list. That way a unit can mix lists from unit data, which will help to keep the needed amount of unit data short.

Implementation can be to include a bool EnumMap in CvUnitInfo, hence keeping multiple copies of the list. With the current 27 buildinfos (develop), it will take up 4 bytes, the same as a pointer or an int. Keeping it as static memory in CvUnitInfo will be the fastest way for access.

Storing a pointer is also an option. It depends on the size of the array, which is the best solution.

CvUnitInfo should still have the get functions. The surrounding code shouldn't know what is stored in CvUnitInfo and what is from unit data. That makes the implementation easier as nothing outside of CvUnitInfo needs updating.

Note: storing bool EnumMaps of sizes of max 64 entries will be faster with hardcoded xml data.

**Comment by raystuttgart** [comment]
duplicate of issue #525.
Thus closed.
(The other one is better described.)
