### ISSUE TITLE
Bug Report - Negative cargo stored error - Part 2

### ISSUE THREAD

**Issue by LGMailhos** [We-the-People-civ4col-mod/Mod#478]
A second report of the same bug, on new savegames. Should I keep posing this bug if it happens again?

[004.zip](https://github.com/We-the-People-civ4col-mod/Mod/files/6659300/004.zip)

**Comment by Curt56** [comment]
I just started getting the same error. ???

**Comment by Nightinggale** [comment]
Same bug as before meaning I already fixed it and it will work in the next version.
