### ISSUE TITLE
Adding buildings or units to xml breaks savegames

### ISSUE THREAD

**Issue by Nightinggale** [We-the-People-civ4col-mod/Mod#480]
The problem: the exe assumes the number of building and unit-infos in xml to be the same on load as when the savegame was saved. If changed, the savegame fails to load. This is quite annoying as it kills savegames even after I rewrote the savegame format in the DLL to get around this issue.

The technical issue is that the exe apparently saves an int array of length of each of those two xml files. Reason unknown.

-----

Proposal 1:

Redirect getNumUnitInfos calls from the exe to report the number in the savegame rather than in the game. Same with buildings. This will force the exe to only load as many entries as there are variables in the savegame and avoid the crash when it reads past "no more data".

Issue: will the exe allocate too little memory and then crash during gameplay?

-----

Proposal 2:

Add number of buildings and units to global defines (xml). This won't change the DLL, but the exe is redirected to use those numbers. This way the exe will save the number of entries from global defines rather than 

 If we have say 15 buildings and global defines says 30, then we can add an additional 15 before the savegame format will be changed.

This will break if the global define is lower than the actual length of the xml files meaning an error message for this has to be added. Luckily this is easy to add as I added CvGlobals::postXMLLoad for the purpose of such checks (and cache setup).

Issue: what will happen if the exe calls functions with the padding indexes as arguments? Worst case we need to redirect all calls to DllExport functions, which takes UnitTypes or BuildingTypes as argument.

-----

Yes this requires some work and adding this will break savegames, but if done correctly we won't be breaking savegames between releases, at least not as easily anymore.

**Comment by raystuttgart** [comment]
If I am correct this is fixed now.
As the XML should now have become savegame compatible.
