### ISSUE TITLE
Renaming of colonies and units

### ISSUE THREAD

**Issue by Fuerstbischof** [We-the-People-civ4col-mod/Mod#483]
![renaming_units](https://user-images.githubusercontent.com/45920798/122667406-1c5adc80-d1b3-11eb-87bc-bdc79483bc43.png)
TXT_KEY_CHANGE_NAME is used to change the name of colonies AND units. Since I never bothered with the names of units I'd wrongly assumed it would be solely used for renaming colonies. Can we add another tag for renaming units exclusively?

![renaming_colony](https://user-images.githubusercontent.com/45920798/122667412-1fee6380-d1b3-11eb-8dbb-e668af3d9e4f.png)
I'd like to see this tooltip to be improved:
1 - the name of the colony should be colourised using COLOR_SELECTED_TEXT
2 - founding date and population size should be switched
3 - taking into account that the typical size of military units (regiments, but actually battalions) is roughly 500 men, we should set the number of people which one colonist represents at least to that number. ATM the number is set to 100 which grosssly underestimates the people living in the Americas (see demographics screen). Even a true colonial empire with 1000 colonists numbers only a measly 100k people - compare that to the 3 millions living in the 13 colonies...

**Comment by raystuttgart** [comment]
@Fuerstbischof 
Please create separate issues for separate topics in the future.
(We have 2 different topics in here.)

1. Yes, we can have 2 texts for Units and Cities. No Problem.
2. Yes, we can increase the default value muliplied for "Realistic Population Count".

**Comment by raystuttgart** [comment]
Both is implemented now.
(Including adjustments in XML.)

The texts are now separated and corrected as well.
**TXT_KEY_CHANGE_NAME_UNIT
TXT_KEY_CHANGE_NAME_CITY**

You can now balance "Real Population coputation" in **Global DefinesAlt**:
**REAL_POPULATION_MULTIPLIER**  ---> Adjusted that already to 1000
