### ISSUE TITLE
text of pop-up cut off

### ISSUE THREAD

**Issue by Fuerstbischof** [We-the-People-civ4col-mod/Mod#485]
The third line of the text is simply cut off by the pop-up, even though the inserted (yellow) string is shorter.
![_text_cut](https://user-images.githubusercontent.com/45920798/123149844-0161c400-d462-11eb-9a56-b48bef23a942.png)

IIRC are the other pop-ups of the same type also suffering from this issue although I couldn't reproduce it.

Out of curiosity: can we reduce the size of the font a little bit to a more intermediate size between the size of the colony name and the list of (building) options?

**Comment by raystuttgart** [comment]
I fixed this in Plains.
