### ISSUE TITLE
profession missing in tooltip

### ISSUE THREAD

**Issue by Fuerstbischof** [We-the-People-civ4col-mod/Mod#486]
The first line of the tooltip doesn't mention the profession. Instead the unit is mentioned twice.

Once changed, please use COLOR_UNIT_TEXT for colouring the string.

![_missing_profession](https://user-images.githubusercontent.com/45920798/123149987-281ffa80-d462-11eb-92c2-237ba77c2845.png)

**Comment by raystuttgart** [comment]
Ok will take care of it.
Replacing the Unit in the first line by the Profession makes sense.
Using COLOR_UNIT_TEXT to highlight is also makes sense.

**Comment by raystuttgart** [comment]
Implemented as requested.

Text Keys are:
TXT_KEY_CITIZEN_HELP_PROFESSION_NAME_DISPLAY <--- Always used if Unit has a Profession
TXT_KEY_CITIZEN_HELP_UNIT_NAME_DISPLAY  <--- Fallback if Unit has no Profession

See here:
https://github.com/We-the-People-civ4col-mod/Mod/commit/2111daef9e274799aa3e5cca5da7a5c5151633dc
