### ISSUE TITLE
WTP Wild Animals Bug

### ISSUE THREAD

**Issue by rap33042** [We-the-People-civ4col-mod/Mod#487]
Ticking the "No wild land animals" checkbox during setup may or may not work. Sometimes it does and other times it does not -- mostly not.

- Gigantic map
- Two continents

The one for sea animals seems to be working.

**Comment by MrZorG33** [comment]
my favorite map - I have never had this bug.
which release are you using?

**Comment by raystuttgart** [comment]
Are we talking about "Defended Goodies" - Animal Caves?
Because those will **always** be defended.  (You can not turn that off by the checkbox.)

The only thing the checkboxes turn off is the **"Additional Spawning"** on free space.

**Comment by rap33042** [comment]
Hi Ray,

I'm talking about the occasional leopard, wolf, or bear lying about in
lairs (caves?). Incidentally, do they re-spawn after being killed?

Thanks,
Richard

**Comment by raystuttgart** [comment]
That is what I was talking about as well. (The "Animal Lairs".)
The other spawning can happen on "pure land".

They should not respawn after being killed but there may be a bug we have not yet checked.
That is unrelated to the Game Option "No Wild Animals on Land" though.

Best regards
ray

**Comment by rap33042** [comment]
Thanks for the info, Ray.

Richard
