### ISSUE TITLE
Easier way to access data from GlobalDefineALT

### ISSUE THREAD

**Issue by Nightinggale** [We-the-People-civ4col-mod/Mod#488]
Some hardcoded values aren't in GlobalDefineALT because the extra step of putting it there takes time. getDefineINT is slow meaning adding a value often requires caching. If accessing those ints in C++ is easier, maybe we can make the DLL less hardcoded without too much hassle.

I want to extend the script, which generates the xml enum header file to also include all ints from GlobalDefineALT. If you say add MAX_UNITS_ON_DOCKS, then add that to the xml file and MAX_UNITS_ON_DOCKS will become a globally available constant you can use in the code. It's automatically cached.

-----

Should be able to handle xml values like default unitclass and check for correct type.
Should be able to hardcode using the same compile flag as the rest of that file. Likewise startup assigning global variables or verifying constants to be the same as xml should be done automatically (just like xml types).

**Comment by raystuttgart** [comment]
@Nightinggale 
Didn`t you just recently implemement something related to "GlobalDefines"?
Was it this or something else?

**Comment by Nightinggale** [comment]
Implemented ages ago. It's now accessible using GLOBAL_DEFINE_ prefixes.
