### ISSUE TITLE
Cattle bug?

### ISSUE THREAD

**Issue by irjowo99** [We-the-People-civ4col-mod/Mod#490]
I have a game where their is a prairie tile with cattle on it but it only produces one cattle per turn, even after I put down a pasture.

**Comment by raystuttgart** [comment]
You first have to bring one full cargo load of Cattle to the City. 
In Normal 100: Cattle
in Marathon 300: Cattle

If you have less then the amount of cattle you can breed is reduced.

**Comment by raystuttgart** [comment]
Since that is most likely the issue I will close this.
(Let me know if that did not work though.)

**Comment by irjowo99** [comment]
thanks for the info
