### ISSUE TITLE
Markings on the sails are gone

### ISSUE THREAD

**Issue by vissercsp** [We-the-People-civ4col-mod/Mod#491]
Just recently, I noticed that the markings on the sails are gone. If I start COL without the WTP 3-0-1 mod, they appear and if I start COL with WTP they are gone. Error/bug or something that was designed out of the MOD? See attached file for details...
[Ships sails without markings.docx](https://github.com/We-the-People-civ4col-mod/Mod/files/6867415/Ships.sails.without.markings.docx)

**Comment by raystuttgart** [comment]
That is working as designed because these markings are simply not realistic / immersive.
