### ISSUE TITLE
Remove support for the old storage system (per yield storage limit)

### ISSUE THREAD

**Issue by ErikSandbraaten** [We-the-People-civ4col-mod/Mod#493]
I propose that we remove support for the (old) storage system that we inherited from TAC and which was subsequently replaced by VET's new storage mod. The new system has been the default for as long as I've been part of the project and I don't think that anyone is using the old system anyway and it has probably not been properly tested in ages. We'd also get to clean up a bit of the code in the process.

If you need a brief reminder just do a search for this string in the code : "VET NewCapacity"

**Comment by Nightinggale** [comment]
I fully agree we should get rid of the vanilla approach. It's too simple and nobody wants to use it anymore.

If anybody needs the old one, what we really should do would be to add a bool to CvYieldInfo to tell that it has unique storage. I can think of cases where this would make sense, though we shouldn't bother to implement it unless we need it.

**Comment by raystuttgart** [comment]
Hi guys, I have no objections, since I was the one who merged the "New Storage Capacity". 👍 
I always hated the boring old system. The new Storage System is way supperior.

**Thus:** 
Go ahead and remove that old crappy thing.
Nobody will miss it since I am pretty sure nobody currently uses it.

**Comment by ErikSandbraaten** [comment]
I volunteer to carry out the work, but it will have to wait until after we've dealt with my develop branch.

**Comment by ErikSandbraaten** [comment]
https://github.com/We-the-People-civ4col-mod/Mod/commit/7eb55e3dfc4df87607d6ccd890923f609231e946
Good riddance!

**Comment by devolution79** [comment]
Merged to Plains
