### ISSUE TITLE
Galleon CAN enter fresh water lake

### ISSUE THREAD

**Issue by vissercsp** [We-the-People-civ4col-mod/Mod#495]
Not sure if it is a bug, but today I noticed that my galleon can enter fresh water lake, but only in the city radius. In the Colopedia it clearly reads it CANNOT enter... Just wondering if this is a program error or a bug... Or if it is nothing to worry about....

Cheers, Chris

![image](https://user-images.githubusercontent.com/61378714/128075251-5490ca4b-1911-4807-a5db-932618b5881f.png)
![image](https://user-images.githubusercontent.com/61378714/128075282-9dab9049-edbd-41e9-8967-721b3bcd4f37.png)

**Comment by raystuttgart** [comment]
It is probably nothing to worry about.

**Comment by raystuttgart** [comment]
It seems that this is just part of the logic that - I think - @ErikSandbraaten coded to allow Coastal Ships to move in City Radius.
This now seems to also affect the logic for "Large Rivers" and "Lakes".

I will check and correct it. (For Large Rivers and Lakes)
Should not really be a big issue anyways.

**Summmary:**
Nothing to worry about but it can and will be corrected.

**Comment by ErikSandbraaten** [comment]
Not sure how this would be related to Coastal Ships, they are only barred from entering non-coastal water. This should have no bearing on other ships IMHO.

**Comment by raystuttgart** [comment]
It is not the "Coastal Ships" themselves it is the logic for: 
**TerrainImpassables**
(Lakes and Large Rivers use that logic as well.)

If I remember correctly I had read somewhere in the logic about "CityRadius".
Need to check in detail when I find the time to do so.

**Comment by raystuttgart** [comment]
Edit:
Found it and corrected it. :)
Will commit in a few minutes.

**Comment by ErikSandbraaten** [comment]
We need a cleaner way to check for the movement rules than relying on a bunch of ad-hock checks IMO

**Comment by raystuttgart** [comment]
@ErikSandbraaten 
I agree. 👍 

But for the moment I could not figure out a better solution.
I am not a professional programmer like you or Nightinggale.

So if you have a good idea for a code improvement, I would not mind of course.
Feel free to change and improve my code whenever you see potential for improvements.

Best regards
ray

**Comment by Nightinggale** [comment]
I think a clean solution would be a major redesign as it should incorporate #270. It wouldn't make sense to do some redesigning on this system without focusing on performance of this performance critical part of the code.
