### ISSUE TITLE
TAC, R&R and WTP

### ISSUE THREAD

**Issue by 10vorne** [We-the-People-civ4col-mod/Mod#498]
If I understand correctly, the Mod We the people emerged from Religion & Revolution. And if I understood correctly, R&R emerged from Tac. So when I install WTP, I get all the features of the previous mods? I played the earlier Colonization from 1995 and now had TAC installed and watched some YT-Tutorials.

So I'm actually a bit out of the subject and now want to start playing again, possibly also in multiplayer. What would you recommend to me, which mod should I play at the beginning or does WTP mainly take care of bugs, etc. that have been through in the previous mods and adaptations to modern systems? I don't necessarily want to overload myself with new, perhaps unknown, features in the game to begin with.

**Comment by raystuttgart** [comment]
The answer was already given in steam.
(Where you posted as well.)

See here:
https://github.com/We-the-People-civ4col-mod/Mod/issues/498
