### ISSUE TITLE
python eror messages resulting in visual bugs

### ISSUE THREAD

**Issue by foeffelaar** [We-the-People-civ4col-mod/Mod#500]
hi, 
clean install of latest 3.0.1 release on a updated win10 pc
firststart of a single player scenario huge map , playing with france.
game launches and 2 message windows pup up with python eror??
resulting in units not visible , ship already near land with a few indian villages already present. landis in fog of war , moving ship does not uncharter new land. but ventures into  nothing. 
![IMG_20210825_210651](https://user-images.githubusercontent.com/89481952/130858771-ddc14ef2-0498-42d0-a910-be33dd414be6.jpg)
![IMG_20210825_210717](https://user-images.githubusercontent.com/89481952/130858787-00c19a05-0a0a-41fa-862a-44d8986353b8.jpg)
![IMG_20210825_210840](https://user-images.githubusercontent.com/89481952/130858798-cd22516b-7ca7-4492-9528-ea7655aa21b1.jpg)

**Comment by raystuttgart** [comment]
Seems to have resolved itself.
