### ISSUE TITLE
Sitting Bull wins again in 1524!

### ISSUE THREAD

**Issue by mastrude** [We-the-People-civ4col-mod/Mod#511]
Saved game available. Is it him, specifically? Doesn't seem likely but I'll try the map without him. Custom scenario using the A_New_World map on huge
![Sitting Bull 2](https://user-images.githubusercontent.com/3690745/143210251-30ae9559-6650-40ff-bcd8-7a31dc8a760d.jpg)
.

**Comment by MrZorG33** [comment]
Please attach the save game of the previous turn.

**Comment by mastrude** [comment]
Can't do that, because I didn't expect that. I can send you a save file
from just after I got the message.

**Comment by MrZorG33** [comment]
you can attach an auto-save file.

**Comment by mastrude** [comment]
Sorry I couldn't respond earlier. I'll respond today.

**Comment by mastrude** [comment]
Here are JPGs and the save files. 
[Sitting Bull.zip](https://github.com/We-the-People-civ4col-mod/Mod/files/7607124/Sitting.Bull.zip)

**Comment by MrZorG33** [comment]
I can’t check these files yet, I’m at work. I can check them in about 10 hours. but tell me, is it saving the previous turn of the game, or a turn when the victory has already occurred?

**Comment by mastrude** [comment]
Since I didn’t know it was coming, a turn right after. I no longer have
auto saves from right before. I guess I’m willing to replay and catch the
turn before.

**Comment by mastrude** [comment]
I would be willing to try to replicate this by replaying the game. 1524 isn't very far in. But please remind me which map I used. I'm not that familiar with the scenario maps. Can you do that?

**Comment by MrZorG33** [comment]
I looked at your saved games and saw no reason why Sitting Bull could win.
if I remember correctly, the map is Two continents.

I correctly understood that you played without other Europeans?

**Comment by mastrude** [comment]
I don't see why either, of course. The problem is I don't remember which
map I used. If you can tell me, I can try replaying. I think it was a
scenario.

I think I played with no other Europeans.

**Comment by MrZorG33** [comment]
I can't watch the game now, but I've seen another tribe of natives with much better performance. perhaps, as Rei said, it was some kind of accident, one in a million.
as I said - "Two continents" map, if I remember correctly. you can try to start the game on it.

**Comment by MrZorG33** [comment]
"FaireWeatherTweakEx" creates a random map. you had a map already created "by hand". you can load your save games and see in the settings which map you used. I'm sure it will be "Two Continents".

**Comment by mastrude** [comment]
I tried loading the options, in game. The name of the map isn't listed.

**Comment by MrZorG33** [comment]
attach a screen, I will show

**Comment by mastrude** [comment]
I don't think we can spend any more time on this. If it recurs, I'll know
to preserve a pre-victory autosave. Please close the incident as
"unresolvable".

**Comment by MrZorG33** [comment]
yes, good idea.
if this happens again, we will open it again.

**Comment by mastrude** [comment]
We can't get back to the pre-bug state, so I'm closing this until (and if) it recurs, hopefully to someone else. :)
