### ISSUE TITLE
wrong prices or percentages in the event

### ISSUE THREAD

**Issue by MrZorG33** [We-the-People-civ4col-mod/Mod#514]
in the first case, 100 gold is subtracted from the treasury and the percentage of successful completion is 80. in the second case, 200 gold is subtracted from the treasury, but the percentage of successful completion is lower - only 60.
in the description you need to change either the % or the value of gold.
![image](https://user-images.githubusercontent.com/61798883/144912500-6c2c16ff-ce57-4df7-8433-4e9dc7e20ac3.png)
![image](https://user-images.githubusercontent.com/61798883/144912523-aac2febf-0ffa-4463-9f40-82f9c4641757.png)

**Comment by raystuttgart** [comment]
I fixed it, before somebody is going to search long.
(I know these events in and out.)

**Comment by MrZorG33** [comment]
@raystuttgart, in the description of the second paragraph, an increase in cargo space is indicated by 2. but in the code it is 4. in the description of the event, is this fixed?

**Comment by raystuttgart** [comment]
What it indicates in XML with "4" is **not** the increase of **Cargo Space**.
It is **4 turns of "inactive"** (not being able to move)

The XML and the Event are now correct. ;)

**Comment by MrZorG33** [comment]
I'm sorry, I was not attentive, of course, this is the number of turns)
