### ISSUE TITLE
Graphics on the map are very jerky

### ISSUE THREAD

**Issue by wezlinch** [We-the-People-civ4col-mod/Mod#515]
> Recently returned to playing WTP and updated to the latest version, but the graphics in the map when moving people / ships / or the map are very jerky and delayed. It's almost unplayable. Not sure what you'd need to be able to diagnose the issue?

**Comment by Nightinggale** [comment]
I can't think of anything, which would trigger this for new releases, but not old ones. Have you tried the old releases on your current computer for comparison to confirm it's indeed triggered by different versions of WTP?

My best guess would be some modern computer/driver with less than perfect support for DirectX 9. If you have a general DirectX 9 issue, then you might not have noticed in other games as most games today use DirectX 11 or 12. Everything you point to seems to be the 3D graphics engine, which is one of the parts of the game, which we can't even mod.

**Comment by Draugheim** [comment]
DX9 and DX11 is fairly similar just more material layers essentially, not dabbled much in DX12 but i assume it would have even more layers of material complexity. But reinstalling/updating DX might fix the issue.

What you describe sounds abit like good ol performance issues, if you recently acquired a 4K monitor and using resolutions like that it means your computer needs to draw 4x more pixels per frame, Still on good ol 1080p myself but I've seen instances where fairly up to date computers would struggle to spit out the desired framerate. The game in question here was Terraria on 4K.

**Comment by raystuttgart** [comment]
Nothing we can really do about it.
Not a general issue of the mod.
