### ISSUE TITLE
Game crashes at specific turn

### ISSUE THREAD

**Issue by Bienhofer** [We-the-People-civ4col-mod/Mod#521]
1st of all, huge credit to developers, it is an amazing Mod!

Re bug:
Just started my first game playing as Sweden now in May 1670.
Everything went well but now I am an encountering a crash upon ending the turn.
Tried to start an earlier save game and switch production, movement etc but doesn't prevent game crashing to desktop.

Uploaded the game at the turn before crash.

Thanks for provding feedback, will start a new game in meantime  :)

[crash save.zip](https://github.com/We-the-People-civ4col-mod/Mod/files/7781396/crash.save.zip)

**Comment by raystuttgart** [comment]
@Nightinggale 
Could you take a look at this then next days?
(If you are currently working on something else, please finish that first of course.)

**Comment by Nightinggale** [comment]
Another crash due to b32fb59
While this solution avoids the crash it still haven't identified how the number of units ends up being negative, which in turn makes the AI plan poorly.

**Comment by raystuttgart** [comment]
Thanks for analyzing.

At least we know that it is not a new bug and our "bugfix code prevents the CTD" even though it does not fix the cause.
However it would be great to really cure the disease and not just treat the symptom.
Although I fully understand how difficult it is to find out what went wrong here.

**Comment by Nightinggale** [comment]
A proper fix might require rewriting the entire area code from scratch, assigning two areas to each plot, one for land and one for water. That's a huge task, but it will fix a number of known issues, which are really hard to fix otherwise.

**Comment by MrZorG33** [comment]
I already have [this code](https://github.com/We-the-People-civ4col-mod/Mod/commit/b32fb59452cfc208d03dbcc35ec6570e2722fd8e) in my files, but the game still crashes. maybe something else is causing this?
[plains.zip](https://github.com/We-the-People-civ4col-mod/Mod/files/7964630/plains.zip)

**Comment by windock** [comment]
Guys, is there a hope to get at least a "beta" release of "development" branch? I have 2 games in the row that I cannot continue for this reason

**Comment by Nightinggale** [comment]
I'm working hard towards a release. However it's not a 5 minute job because messing up this step can introduce new bugs and/or break savegame compatibility. All I can say right now is that working towards a bugfix release is top priority right now.

**Comment by windock** [comment]
Thank you. I have overcome the issue by switching to development branch, in the meantime.

**Comment by raystuttgart** [comment]
A duplicate and totally outdated now with "New Hope"
