### ISSUE TITLE
DomesticAdvisor - Yield Coca Leaves missing

### ISSUE THREAD

**Issue by raubwuerger** [We-the-People-civ4col-mod/Mod#522]
In the DomesticAdvisor the yiel CocaLeaves is missing. Although it is displayed and also consumed in the city screen.

**Comment by raystuttgart** [comment]
Please be precise. 
Otherwise please post a screenshot.
 
Which Tab / Screen? Is it just the "Domestic Market Tab"?
(Domestic Advisor has many Tabs / Screen.)

**Comment by raystuttgart** [comment]
**Edit:** 
I know why. 
```

		## R&R, Robert Surcouf, Domestic Market display START
		elif(self.CurrentState == self.GENERAL_STATE and self.CurrentPage == 2): 
			iStartYield=gc.getDefineINT("DOMESTIC_MARKET_SCREEN_START_YIELD_ID")


```
DOMESTIC_MARKET_SCREEN_START_YIELD_ID
---> It is set to **"35"** in **GlobalDefinesAlt.xml** (It is the ID where normally produced Yields start.)
---> Coca Leaves is below that and the only "raw Yield" that is sold on Domestic Market (as of now)

**@Nightinggale** 
This will cause us issues every time somebody adds new Yields ...
We should figure out something better than that, e.g. simply checking if the Yield has "getYieldDemand".

**Comment by raystuttgart** [comment]
Since I am right now working on "New Yields" I will need to adjust those Screens anyways.
So I will simply take it on my own Todo-List ...

**Comment by raubwuerger** [comment]
I'm sorry. Just in the moment I wanted to post the screenshots my father in law ringed the door ....

**Comment by raubwuerger** [comment]
I've alreadey fixed the issue. See Screenshots attached...

![grafik](https://user-images.githubusercontent.com/7585446/147745031-29d60be1-e619-451b-ae50-53ae07f8f35f.png)
![grafik](https://user-images.githubusercontent.com/7585446/147745360-96f7ccd4-3093-4b47-a2cd-d9978aad2006.png)

Now the fixed one
![grafik](https://user-images.githubusercontent.com/7585446/147745408-1e91715a-f1cb-429f-ada6-29f9c19bbd2a.png)

**Comment by raubwuerger** [comment]
However, the implementation is not very elegant. The previous consumables all had an ascending ID, starting at 35. They were simply handled in a loop. The CocaLeaves, however, have the ID 8...

**Comment by raystuttgart** [comment]
Did you commit to "Plains" ?
I did not see any commit message there.

**Comment by Nightinggale** [comment]
Known issue and I have started rewriting all pages in the domestic advisor. However this specific page is one, which I haven't touched yet and I ended up getting sidetracked.

The plan is to use the code I have used for some other pages where the columns are set by whatever is in an InfoArray. The DLL will generate this InfoArray at startup by looping through all units and buildings to see which yields are used by at least one unit/building. This way the page will adapt itself to xml changes by itself.

**Comment by raystuttgart** [comment]
This needs to be adjusted again, once I commit the new Yields stuff.
Thus I open it again and assign it to me - just so I do not forget.

**Comment by Nightinggale** [comment]
I'm going to look into getting the self configuring code up and running rather than having some code, which needs updating every time somebody touches xml. Much easier to work with in the long run.

**Comment by raystuttgart** [comment]
This is fixed.
So let us close this.

**Comment by Nightinggale** [comment]
> DOMESTIC_MARKET_SCREEN_START_YIELD_ID

Perhaps it would be a good idea to remove this as the new code will not use it. It's autogenerated by demands from unit/building xml and should not require maintenance to keep up to date from any other files.
