### ISSUE TITLE
European does not build a settlement

### ISSUE THREAD

**Issue by MrZorG33** [We-the-People-civ4col-mod/Mod#523]
**Plains**, updated 01/02/22

in one test game, I found a ruined Russian settlement. perhaps, immediately after its foundation, the natives declared war on them and the settlement was destroyed. I do not know. but after that the Russians did not establish a single settlement, and their caravel constantly runs along the coast.
if anyone has time to figure out why, please do so.
![разрушенное поселение русских](https://user-images.githubusercontent.com/61798883/147953999-4d5a5264-c750-4552-b66d-42b9b4b52b5d.jpg)

I have few auto-saves, I can only attach the oldest one available.
I also attach the very first auto-save. I don't know if it really helps or not.
[AutoSave_AD-1565.zip](https://github.com/We-the-People-civ4col-mod/Mod/files/7802903/AutoSave_AD-1565.zip)
[AutoSave_Initial_AD-1492.zip](https://github.com/We-the-People-civ4col-mod/Mod/files/7802905/AutoSave_Initial_AD-1492.zip)

**Comment by ErikSandbraaten** [comment]
It may just be me, but I think there are only 2 plots between the razed settlement and the danish town.  Assuming that you are playing with the default minimum of 3 plots between cities, I don't think it's valid to settle there ?

**Comment by raystuttgart** [comment]
I think that @devolution is probably right. This was bad luck that the coast did not allow to settle there because it was too close to the danish city.

**Comment by MrZorG33** [comment]
I founded this settlement much later than the beginning of the game (this is my second or third settlement). so this settlement could not interfere in any way.

**Comment by raystuttgart** [comment]
It also will not found a settlement next to any Nation that is at war with it.
So most likely it was really simply bad luck. Let us see if something like this happens agian.

**Comment by raystuttgart** [comment]
I think that is completely outdated.
