### ISSUE TITLE
spawn of large ships in the city in shallow water

### ISSUE THREAD

**Issue by MrZorG33** [We-the-People-civ4col-mod/Mod#524]
after a lost battle, my Galleon was sent to the city in shallow water. now he cannot get out of there.
![галеон перенесло в город с мелководьем](https://user-images.githubusercontent.com/61798883/148183808-fd3f338e-883c-46a3-a7d3-2450010e3f23.png)

in the same situation was one of the Europeans, to whom the king gave Man-o-war and the Frigate. although in his case it was possible to build a Fort and withdraw ships. but the AI could not come up with this.
![европейцу дали мановар и фрегат  они не могут пройти по мелководью](https://user-images.githubusercontent.com/61798883/148183851-c7c2b52c-42e1-4820-8417-c4d119efb55e.png)

**Comment by raystuttgart** [comment]
@MrZorG33 
Thanks for reporting,

I had just not thought about such a situation.
It is relatively easy to correct though.
I will take care of it the next days. 👍 

Best regards
ray

**Comment by MrZorG33** [comment]
the harbor does not matter as the second level docks can accommodate any ship. but as practice has shown, second-level docks can be built in a colony with shallow water. therefore, I consider the harbor linkage inappropriate.
if I understood correctly what you want to do...

**Comment by raystuttgart** [comment]
@MrZorG33 
You are actually correct. 👍 

All we need to do is to change the XML of the Ships and Harbour Buildings.
(According to their Movement Rules considering "Shallow Water")

--> Harbour Buildings: Which Type fo Water they need (in adjustment to the Units they can build, see below)
--> Ships: The Harbour they flee to (in adjustment to above, considering their Movement Rules)

@Nightinggale 
Do not worry about this anymore.
This can be handled purely in XML.

**Comment by raystuttgart** [comment]
The issue with "fleeing Ships" is solved.
I will now also check if DLL and Python Event could have a similar issue.

**Comment by raystuttgart** [comment]
I checked the Python Events, there is currently none that gives a Ship that could not pass "Shallow Coast".
It could easily be handled in a similar fashion by having the XML check for the City having "BUILDINGCLASS_DRYDOCK".
(Otherwise there would be no DLL changes needed.)

**Comment by raystuttgart** [comment]
There is nothing to fix in DLL either, becauce the only DLL-Event that generates a Ship is the Pirate DLL-Diplo-Event.
And the Pirate Ships are allowed to sail in Shallow Coast.

**Comment by raystuttgart** [comment]
**Summary:**
Everything checked and fixed for now.

**However:**
For future **DLL-Diplo-Events** that spawn Ships we need to remember "Shallow Coast Case".
For future **Python Events** that spawn Ships we also need to remember "Shallow Coast Case".

**Comment by jo-oe** [comment]
There is also the diplo event where the king asks you declare war on another european. Accepting gives you a MoW spawning in your first city. If that city is behind shallow water, the ship cannot leave.

**Comment by raystuttgart** [comment]
I will check the DLL-Diplo-Event "European Wars" again to be sure.

**Comment by raystuttgart** [comment]
Ok, I have checked and adjusted all DLL-Diplo-Events.

There is now a method:
**hasDeepWaterCoast()**
(Basically checking for "TERRAIN_COAST" being adjacent.)

**Comment by raystuttgart** [comment]
Was this a new DLL Diplo-Event?
Or one of the really old ones?

**Comment by raystuttgart** [comment]
I updated the code again and hope that it now works. 
(I will close this for now - let us see if it re-occurs.)

Please reopen the issue if it really happens again by a DLL-Diplo-Event. 👍 

But normally this check in the DLL-Diplo-Event forthe spawning City should work.
**hasDeepWaterCoast()**

**Comment by MrZorG33** [comment]
in a new test game, my king demanded to declare war on another European. I agreed, but asked to help with the troops. my adversary also received military aid from his king. and again the same situation: the European has a colonial capital on the coast with shallow water (and all the ships from the events appear in the capital) and his Manowar cannot go to the open sea.
![image](https://user-images.githubusercontent.com/61798883/210350813-7a68e2ea-d771-4ee2-a56b-dfd2652a5fee.png)

**Comment by devolution79** [comment]
This is a general problem that requires a general solution. We need to perform pathfinding before we decide where to spawn a unit (regardless of source which could be an event, FF or animal spawn etc.)
The branch generatePathForHypotheticalUnit should fix this since it allows pathfinding without having a real unit (think of this a pathfinding for a virtual unit)

**Comment by raystuttgart** [comment]
Most likely I had simply forgot the **hasDeepWaterCoast()** for the AI. :)
I can take care of that and fix it. 👍 

In **DLL Diplo-Events** otherwise this **should be solved**.
For **Python Events** this is **still an open Problem**.

**Comment by raystuttgart** [comment]
Fixed this issue once more. :)
(As I said I forgotten "hasDeepCoast()" check for AI troops.)

Now also if there is no "deepCoast" harbour it will simply just spawn Land troops.
(Before that it was not spawning any troops at all which was also bad.)

----

**As I said:**
All **DLL-Diplo-Events** should **not have this issue anymore** now.
But the **Python Events still do**, but that already has another open issue.
