### ISSUE TITLE
Political refugee cannot be trained

### ISSUE THREAD

**Issue by raubwuerger** [We-the-People-civ4col-mod/Mod#526]
The profession Political Refugee is in the city training list and also in the Colopedia is deposited that you can train him (TeachLevel 1).
But you can not train him. See screenshot ...
![grafik](https://user-images.githubusercontent.com/7585446/148362559-f4454549-b9be-4383-b1a5-d802e87a5845.png)

**Comment by raystuttgart** [comment]
Thanks, this is easy to fix.
I will take care of it.

**Comment by raystuttgart** [comment]
I fixed it.
