### ISSUE TITLE
make closing the shopping window an "escape" button

### ISSUE THREAD

**Issue by MrZorG33** [We-the-People-civ4col-mod/Mod#531]
on the screens of Africa and Port Royal, the "escape" button does not work to close the purchase window.
![image](https://user-images.githubusercontent.com/61798883/149198648-aa78cba3-38cf-418d-8a63-b285a9152da4.png)

**Comment by ErikSandbraaten** [comment]
See https://github.com/We-the-People-civ4col-mod/Mod/issues/536
