### ISSUE TITLE
Unrest in previous turn, then it ends in next turn, but then starts up again in the same turn. 

### ISSUE THREAD

**Issue by Teddymac22** [We-the-People-civ4col-mod/Mod#533]
Turn 1513 my city of Trankebar went into unrest. Then, in 1515 it ended, but then I received another message, also in 1515, saying the city was back in unrest. 

I haven't played in a long long time and I haven't played R&R in an even longer time so I'm coming into WTP with fresh eyes. 
From a new gamer perspective I would also say that there should be some kind of notification that your town could go into unrest, perhaps with a neat image. Also, there is no Colopedia entry for Unrest. There is for happiness with the word unrest highlighted, but no entry for Unrest itself. 

My people will not leave in order to take up arms, so I appear to be stuck.

**Comment by raystuttgart** [comment]
@Teddymac22 
This was fixed already in internal development just recently
By the way, did you find this bug in last official release **WTP 3.0.1** or in internal development **branch "Plains"**.
