### ISSUE TITLE
Escape button not working on Africa and Port Royal screens

### ISSUE THREAD

**Issue by MrZorG33** [We-the-People-civ4col-mod/Mod#536]
on the Africa and Port Royal screens, the Escape button does not close the unit purchase window. On the screen of Europe everything works.
![escape](https://user-images.githubusercontent.com/61798883/151043632-5a7e0538-cc47-4e54-b66d-e60ae3782b5b.jpg)

**Comment by ErikSandbraaten** [comment]
Confirmed, easy fix incoming :)
