### ISSUE TITLE
Make get(xml file)Info functions return const pointers instead of references

### ISSUE THREAD

**Issue by Nightinggale** [We-the-People-civ4col-mod/Mod#54]
Right now getting info from xml is done with references like:

```cpp
CvUnitInfo& CvGlobals::getUnitInfo(UnitTypes eUnitNum)
```

We should turn them into returning const pointers like

```cpp
const CvUnitInfo* CvGlobals::getUnitInfo(UnitTypes eUnitNum) const
```

There are two reasons for this. One is the obvious that the xml data is fixed and should be const. The other is less obvious and could very well be a compiler bug. Take for instance this code:

```cpp
CvUnitInfo &kInfo = GC.getUnitInfo(eUnit);
```

This will work fine. Now make a typo and it becomes:

```cpp
CvUnitInfo kInfo = GC.getUnitInfo(eUnit);
```

Now it's no longer a reference. It's a normal variable. However the function call still returns a reference and it's put into kInfo. Now because kInfo isn't a reference, but a standard variable, it will be freed once it goes out of scope. The next time something calls getUnitInfo with the same eUnit, the memory will have vanished and the game crashes.

I tried this once. There is no warning or anything. It works apparently fine when it kills the instance and when it crashes later, the debugger might not give a clue to where it went wrong because it could now be in a completely different file and the offending code is long gone from the call stack. Using const pointers will ensure that nothing outside CvGlobals can write to the info classes or even free them.

**Comment by Nightinggale** [comment]
The goal here is to make the compiler more picky and throw errors instead of accepting buggy code. It will possibly end up as the same compiled code. In other words the player will not be able to tell the difference.

I can't really say anything about milestone, but it's likely not a change for 2.7.x.

The implementation difficulty is likely quite low compared to a lot of the other tasks. Write the new get function, make the old one private and then fix all the cases where it claims it can't access the private one. In most cases the fix is just a new name and changing . to ->
The reason for keeping the old ones (at least in some cases) is to remain compatible with the exe, which will expect references. The exe calls a few of them, but not many.

It would be a good idea to make a local copy of a pointer if it's used more than once, like looping yields and it uses GC.getYieldInfo(eYield) many times for each yield (there is code like that).

Expected time to implement this: unknown

I would say normally I wouldn't bother changing something like this, but because the compiler accepts freeing the memory if the & is missing, it's another crashing bug waiting to happen and it's a nasty one when it crashes not at the bug, but next time the info class is used.

**Comment by ShadesOT** [comment]
+1000
The compiler does not throw an error if a function returns a reference but the variable it is assigned to, is NOT declared as reference. Which in my case lead to seemingly random offset issues and crashes. It took me ages to track down that little shit!

**Comment by ErikSandbraaten** [comment]
See my recent comments in the WTP chat. We can probably catch these issues by making the classes noncopyable, that should ensure that attempting to create a copy a compilation error.

**Comment by Nightinggale** [comment]
boost::noncopyable saved the day. Now we can't corrupt memory by simply forgetting a & when declaring a variable. Instead compilation will fail. It will also catch any other case of instances of info classes, which tries to be copied, which is good because it will never work.
