### ISSUE TITLE
Smuggling ship selling stuff in Europe weirdness

### ISSUE THREAD

**Issue by ErikSandbraaten** [We-the-People-civ4col-mod/Mod#542]
I've come across this assertion in several of my games (develop branch)

Assert Failed

File:  DLLSources\.\CvGameTextMgr.cpp
Line:  8577
Func:  CvGameTextMgr::setEuropeYieldSoldHelp
Expression:  eYield == NO_YIELD || kPlayer.getSellToEuropeProfit(eYield, iAmount * (100 - iCommission) / 100) == iGross
Message:  

----------------------------------------------------------
It is seemingly caused by an AI smuggling ship selling goods in Africa! The assert is in gametext so it could be a mixup between commission and bribe?
bSmuggling is true which is strange since one cannot smuggle to Africa and hence it makes little sense to go anywhere  but PR ?

@raystuttgart 
Maybe you could chime in here ? Perhaps it's the result of the new fix concerning the correction of the bribe display text ?
It could even be two bugs, one concerning the text and the second concerning the smuggling ship ending up in Africa  (maybe the ship is sailing away from danger and we forgot to check hidden nationality and hence we should send it to PR, it's just a theory though)

**Comment by ErikSandbraaten** [comment]
Update: Changed the title since I mistakenly put Africa in place of Europe, sorry about that!

**Comment by raystuttgart** [comment]
I will take a look.
"Smuggling" is also one of my earliest RaR features and was also a bit "hacked".

There are 2 methods:

A) Actual Sales Tranistion
B) Text Entry for Log

Maybe they are not in sync when Smuggling happens.
(So the number I give B) from A) may cause an Assert.)

--> B) Checks the data from A) and things: Something does not fully match.

But as I said:
I will take a look and fix it. 👍

**Comment by ErikSandbraaten** [comment]
I actually think it's caused by the Smuggler escaping to Europe! Even if this is not the case, I am still going to ensure that it escapes to PR instead since otherwise that would be (another) bug waiting to happen!

**Comment by raystuttgart** [comment]
The Assert was triggered by a Trade Message.
It is fixed by my last commit to "Yields".

The case "Smuggler escaping to Europe" is something I do not really understand.
Because they are allowed to go to Europe and smuggle there. 
--> There they circumvent taxes, which is the actual "Smuggling feature".

Them being allowed to sail to "Port Royal" as well is just a goody.
It was later added, when "Port Royal" was implemented.
The feature "Smuggling" is much older. (Maybe even RWL already.)
