### ISSUE TITLE
Python exception when zooming out (globe view)

### ISSUE THREAD

**Issue by ErikSandbraaten** [We-the-People-civ4col-mod/Mod#544]
![image](https://user-images.githubusercontent.com/32330976/151705147-7fced4f1-acdb-46c6-8723-d64a55acbaea.png)
[](url)

**Comment by ErikSandbraaten** [comment]
Occurred while testing the develop2 branch. Since this branch contains no changes that should be relevant with respect to this issue, we can likely reproduce it with our other branches.

**Comment by ErikSandbraaten** [comment]
[Laptop AD-1714-July-python-exception-when-zooming-out-globe-view-maximally.zip](https://github.com/We-the-People-civ4col-mod/Mod/files/7966143/Laptop.AD-1714-July-python-exception-when-zooming-out-globe-view-maximally.zip)
Folder: wtp

**Comment by MrZorG33** [comment]
Plains (downloaded 01/30/22) - no error (map a_New_world, custom game)
![image](https://user-images.githubusercontent.com/61798883/151705381-1db1384c-94b6-4064-b69b-3dbd6f91fd95.png)

[01.30.22.ColonizationSave.zip](https://github.com/We-the-People-civ4col-mod/Mod/files/7966161/01.30.22.ColonizationSave.zip)

**Comment by ErikSandbraaten** [comment]
Commenting out the following lines: 3577 and 3578 in def updateGlobeviewButtons prevents the exception

`screen.setPanelSize("ScoreBackground", iPanelX, iPanelY, iPanelWidth, iPanelHeight )`
`screen.show("ScoreBackground")`

**Comment by ErikSandbraaten** [comment]
@raystuttgart  Have you encountered this issue (or perhaps even fixed it) in Plains ?

**Comment by raystuttgart** [comment]
**@ErikSandbraaten** It is fixed already in Plains.
