### ISSUE TITLE
great generals and admirals are not transported by naval ships

### ISSUE THREAD

**Issue by MrZorG33** [We-the-People-civ4col-mod/Mod#547]
naval ships cannot carry great generals (and most likely admirals). although, in fact, these are the same military units.
![image](https://user-images.githubusercontent.com/61798883/151713451-865897d4-04fc-4030-9d31-3dc096f683fd.png)

**Comment by MrZorG33** [comment]
sorry for the bad screenshot, but it really can't be put on a naval ship, only on a merchant ship that can transport units.

**Comment by raystuttgart** [comment]
No problem, I understand the issue and can take care of it.

**Comment by raystuttgart** [comment]
It is fixed in my last commit in "Yields".
