### ISSUE TITLE
Random map script: premade maps

### ISSUE THREAD

**Issue by Nightinggale** [We-the-People-civ4col-mod/Mod#548]
Add a new map script, which instead of generating a random map presents a map option, which lists the scenario files. The game will then load the file in question rather than generating anything by itself.

Benefits:

- Players will be presented with premade maps when clicking new game
- Unlike the scenario screen, a map script will allow multiple map options
- 1/2 plot radius is a map option, which is currently hidden from the GUI in scenarios
- new map options like randomize bonus locations could allow maps, which supports either approach

Technically a map option requires the map script to tell how many answers there are and a text string for each option. Adding a new python exposed C++ class can make it read the list of files once and then provide the answers without using scanning the directory over and over. Once selected same class should be able to call the scenario file parser and... well that's it.

**Comment by ErikSandbraaten** [comment]
Another related option is to allow the player to enter the map seed which should then result in the same map being generated each time.

**Comment by Nightinggale** [comment]
I can't think of a way to add an int selector to the exe controlled GUI without listing every single option. That seems excessive.

**Comment by raystuttgart** [comment]
MapSeed? I know that it exists for other games like e.g. Battle Brothers (which I love by the way).
But is Civ4Col even using something like that to generate maps? 

Also sounds like kind of unnesessary, since you can **always save a mapsave in WB** if you want to play again or share.
So I think we should not waste too much time or effort for somethong like "MapSeeds" to regenerate exact same Map.

**Comment by raystuttgart** [comment]
Otherwise the "MapScript" to slightly randomize "premade maps" sounds like a great idea.
(Then it would not be necessary to "hardcode" randomization options into the mapsaves anymore.)

**Comment by Nightinggale** [comment]
This completely derailed with focus on map seeds, which is not part of what I'm proposing. My proposal is a way to get the existing premade maps into "new game" and grant them access to map options. It will solve the messy approach to 1/2 plot radius and whatever else we add in the future.

Also there is currently a post on steam asking how to get a map of America. Clicking new game will not provide it. In other words even if the maps are there, some people can't find them.

**Comment by raystuttgart** [comment]
As I said, I like the idea. 👍
