### ISSUE TITLE
Switch code to support new storage type only?

### ISSUE THREAD

**Issue by ShadesOT** [We-the-People-civ4col-mod/Mod#55]
`GC.getNEW_CAPACITY()` , only seen being used in an if-condition like
```cpp
if (GC.getNEW_CAPACITY())
{
    //... code for new storage type
}
else
{
    //... code for old storage type
}
```
is allmost certainly a leftover from the transition between old and new storage type.
(old storage type: where every yield had its own max capacity; new storage type: where all yields share a common max capacity)

It is obsolete now, as only the new storage type is used.

- Examine if these conditions and the attached else-clauses can be removed safely.
- Remove all those conditions and else-clauses.
- Check the xml if there is a setting (most likely in the global context and 0/1 or true/false) and remove it.

**Comment by ErikSandbraaten** [comment]
There's still at least one user (on the forum) that claims that he/she is playing with the old-style\vanilla capacity.  We need to determine if we should remove it completely. I vote in favor of removal!

**Comment by ShadesOT** [comment]
hi devolution,
can you provide a link to that post? thx

**Comment by ShadesOT** [comment]
It seems we will keep the parallel implementation of old and new storage type for now.
