### ISSUE TITLE
shift the position of the logs

### ISSUE THREAD

**Issue by MrZorG33** [We-the-People-civ4col-mod/Mod#550]
since the number of logs shown on the screen becomes very large towards the middle of the game, they begin to block the view of the map. I suggest (if possible) move the log window to the left side of the screen.
![логи в левую часть экрана](https://user-images.githubusercontent.com/61798883/152648270-57e9e647-0fbe-4131-a05a-2444352a1264.jpg)

**Comment by raystuttgart** [comment]
To be honest, I **like them in the middle** because there it is **easier to read**.
Putting them to the left would basically mean that I **would not read them at all** anymore.
(My attention during turns i8s not focussed to the sides.)

**Comment by MrZorG33** [comment]
it is strange that you will not see the same lines, but a little to the left. I will try to implement this (in a test version, for myself) if I figure out where the necessary lines are.

**Comment by raystuttgart** [comment]
Ok, let us shift them to the left of the sreen as suggested.
Maybe one of the new programmers does have some time to give it a try.

**Comment by raystuttgart** [comment]
We talked to f1rpo over at CivFanatics.
He said that it is not possible to move this window with reasonable effort.

Reason is that it is all handled in the exe.
There is no separate Python logic to position it.

We will thus close it.
