### ISSUE TITLE
Frigate's spawn point was on a Large River

### ISSUE THREAD

**Issue by MrZorG33** [We-the-People-civ4col-mod/Mod#556]
now Frigate has appeared in the city on the Large River (**Plains** from 04/02/22).
![image](https://user-images.githubusercontent.com/61798883/152968611-9517c623-9b66-4e40-bf94-eba2dc3c94a6.png)

**Comment by raystuttgart** [comment]
**From previous bug report:**
I see, it is a **normal Frigate**.
(Thus not related to Pirate Spawning. / DLL-Events)

I currently suspect it is a "Python Event".
(Need to check if there are Python Events that give a Frigate)

**Comment by ErikSandbraaten** [comment]
Just a quick opinion: I would prefer if all the magical spawning units resulting from events actually spawn in Europe (off the map) to preserve immersion a bit

**Comment by MrZorG33** [comment]
I think these two issues (this and #563 ) are related.
