### ISSUE TITLE
Plains: Africa UI cannot be open, but ships may go there

### ISSUE THREAD

**Issue by windock** [We-the-People-civ4col-mod/Mod#558]
"Plains" branch.

I did not have this problem in 3.0.1 and "development"

Start a new game with default settings. Pressing button "Africa" in the top menu, or pressing Shift-F2 does nothing. However, you may order the ship to go to Africa. Ship will be effectively lost.
Similar issue may be for Port Royale.

Attaching a save file of a new game with this problem
[AutoSave_Initial_AD-1492.zip](https://github.com/We-the-People-civ4col-mod/Mod/files/8025990/AutoSave_Initial_AD-1492.zip)

**Comment by raystuttgart** [comment]
Currently we have the **complete internal team** playing / testing on "Plains" **since weeks**.
e.g. @MrZorG33 as well.

Also I tested this in my internal version, which is much newer than "Plains" though.
And I really do not have this bug.

**Comment by raystuttgart** [comment]
**Edit:**
See here, I just tested in my current internal development / prototype branch "Yields".
(And that branch was originally based on "Plains" where everything considering Africa / Port Royal worked perfectly so far.)
![Civ4ScreenShot0000](https://user-images.githubusercontent.com/59391125/153051349-b46308f3-1448-44c0-acc1-ca7af8603503.JPG)
![Civ4ScreenShot0001](https://user-images.githubusercontent.com/59391125/153051357-be1958fa-c292-4f49-91f0-5b3d4568119d.JPG)

**Comment by MrZorG33** [comment]
@windock what does "new game with default settings" mean? which game exactly? there are so many options...
I have never had this either. but I can try if you tell me which game to run.

**Comment by windock** [comment]
I have just verified that mod folder has no changes from github sources, made fetch, deleted "Project Files/temp_files" and re-compiled DLL by running "Compile-Release". Are there any other steps that I can perform to make sure I have a better clean install?

I have started a new game by running an original civ4col, loading the save file of the mod, then going to the main menu.

"Play Now" => Danish Colonies => "A_New_World" => Patriot/Normal/Large => 2 plot radius => ok.

I see nothing suspicious in logs.

**Comment by windock** [comment]
I have just tested in the Yields branch, and I can confirm that Africa loads fine there, and I see no other issues. It really seems to be the problem with Plains, and not my local environment.

**Comment by MrZorG33** [comment]
@windock 
![image](https://user-images.githubusercontent.com/61798883/153057004-6a34959d-ef14-42a2-8108-51b43808e8fc.png)

![image](https://user-images.githubusercontent.com/61798883/153057041-aa10ed2d-6b7b-4718-921a-c372f0f040fb.png)

![image](https://user-images.githubusercontent.com/61798883/153057093-7a2d7da5-cd03-42be-8453-a2212441dabe.png)

I have Plains, downloaded 02/04/22

I will try to update today and check again.

**Comment by MrZorG33** [comment]
confirm.
Plains from 02/08/22
when you try to get to the screen of Africa or Port Royal, nothing happens (neither pressing buttons nor hotkeys work). enters the screen of Europe without problems.

also I found a problem: when trying to call the Chronicle screen, a Python error appears.
![image](https://user-images.githubusercontent.com/61798883/153067893-bbeafc5c-09f9-4807-8dbe-f3e3bdd6a531.png)

**Comment by Nightinggale** [comment]
Confirmed. It appears that the game goes wonky when there are calls to CvScreensInterface. Apparently the very same code works in the release candidate branch so something changed in Plains. This mean whatever the bug is, it is logged and using the log will tell what changed when it broke.

There is just one issue with that approach, which is I don't have a clue to what to look for. I suppose this will be a case of a bunch of trial and error to pinpoint precisely when it broke.

**Comment by Nightinggale** [comment]
Fixed

**Comment by ErikSandbraaten** [comment]
Sorry about that guys! Somehow I failed to spot that we already had imported and modded CvScreensInterface.py  :(

**Comment by windock** [comment]
I confirm it is fixed. Thank you, guys!

**Comment by raubwuerger** [comment]
Yesterday I also noticed that the two scrrens can no longer be opened. If I see correctly, the bugfix refers only to the file CvScreensInterface.py, right? But it does not work for me!

**Comment by MrZorG33** [comment]
@raubwuerger carefully look at the folders in which the files are changed

**Comment by raubwuerger** [comment]
I see this. But in the second folder Screens is nothing changed!
![grafik](https://user-images.githubusercontent.com/7585446/153234032-ad233431-672b-4420-b354-49e4fe73a474.png)

**Comment by MrZorG33** [comment]
@raubwuerger open the commit and see what has changed.
