### ISSUE TITLE
"Barracks System" (Space for Military) should also check when "Equipping Military Profession"

### ISSUE THREAD

**Issue by raystuttgart** [We-the-People-civ4col-mod/Mod#559]
Currently "Barracks System" (Space for Military) is not checked when "Equipping Military Profession". 
Thus it is possible to completely bypass the system by first unequipping Military Units to make space and later equipping them again.

It is not necessarily game breaking but most likely it should be fixed at some point.
I will probalby take care of it at some point.

**Comment by devolution79** [comment]
We may want to take this feature out of the next release since we need to overhaul the combat system first IMHO otherwise we risk a situation in which  there are more restrictions for cities rather than any random plot.

**Comment by MrZorG33** [comment]
or, at the very least, you will need to limit the number of units in the stack to compensate for the decrease in the number of troops in the city.

**Comment by raystuttgart** [comment]
This is fixed now.
