### ISSUE TITLE
Plains. change the algorithm for moving automated units

### ISSUE THREAD

**Issue by MrZorG33** [We-the-People-civ4col-mod/Mod#561]
as Ray already wrote somewhere, due to the change in the cost of moving through different types of terrain, for units moving in automatic mode, we need to change the movement algorithm.

new movement cost:
forest - 2
dense forest - 3
jungle - 3
tropical grove - 2
mangroves - 2
hill - 2
hill with forest - 3
hill with dense forest - 4
hill with jungle - 4
hill with tropical grove - 3
peak - 5

automated units prefer to end their turn on the tile with the highest defense level. given the current cost of moving, this is a disaster)
I don't have any suggestions yet, but maybe you will.

By the way, I have only one complaint about the automated movement of ships. while testing **Plains**, I began to notice that automated ships can end their turn in a storm. I had not seen this before.

**Comment by raystuttgart** [comment]
Yeah, the Pathfinding needs to be adjusted to the new Movement Cost System.

It is also mentioned in this post:
https://forums.civfanatics.com/threads/new-terrain-movement-cost-system-work-in-progress.671596/

It is actually one of the biggest open issues we have.
But I just do not have enough knowledge of pathfinding to adjust it myself.

@ErikSandbraaten 
Do you mind if I assign this to you? You probably know pasthfinding best of us all.
(If you do not have the time to take a look, don't worry.)

Simply look for this comment in the code to see what I had implemented:
// ray, new Movement Calculation - START
