### ISSUE TITLE
Spawnig of Ships from Python Event does not check for Ocean Access

### ISSUE THREAD

**Issue by raystuttgart** [We-the-People-civ4col-mod/Mod#563]
The Spawning of Ships by **DLL** checks for Ocean Access.
But the Spawning of Ships by **Python Events** does **not**.

e.g. compare this in DLL: This spawning is save, cause it checks "hasDeepWaterCoast" + "getMIN_WATER_SIZE_FOR_OCEAN()"
(Both conditions need to be check to find a valid city to spawn ship that is always safe to spawn for sure.)

// R&R, ray, Pirates - START
if (pLoopCity->isCoastal(GC.getMIN_WATER_SIZE_FOR_OCEAN()) && pLoopCity->plot()->hasDeepWaterCoast())

-----

Solution A): --> relatively easy to do but each single event needs to be checked.

1. A DLL method needs to be written: isPlotValidForSpawningShipsByEvents() 
2. This DLL method needs to be made accessible to Python (Plot)
3. It needs to be called by the Python Event logic to check if the Plot / City to spawn is valid 

Solution B): --> Safer because Python Event Programmer does not need to consider anything, single events can stay untouched

Simply change the spawning of such Ships in DLL. (Python Event Unit Spawning.)

1. A DLL method needs to be written: isPlotValidForSpawningShipsByEvents() 
2. During spawning of Ships check the plot of the City that the Python Event tries to chose
3. If the Plot is valid chose the City, if not use "Starting Plot on Ocean" to spawn the Ship

-----

Affected Events are e.g.

- EVENTTRIGGER_COMMANDEERED
- EVENTTRIGGER_ANTI_PIRATE_1
- EVENTTRIGGER_FIVE_DOCKS_DONE

But there may be more.
(Just checked for generation of a "Frigate", which we had a bug for.)

-----

Most likely Solution B) is much safer for the future.
(The single Python events do not need to be checked.)

**Edit:**
Texts of the spawning may need to be different in case of "Startig Plot".)
(Because they currently assume that they always spawn in a City.)

**Comment by Nightinggale** [comment]
In general, if the DLL can do the task, let the DLL do the task. Don't add the same ability to python and introduce multiple versions of the same code. This applies both to checks and actions (here: can spawn and spawning). It's my impression that doing anything in python, which can be done in the DLL will make the code more prone to bugs.
