### ISSUE TITLE
Hardcoded lattitude for generating Ice Lakes instead of normal Lakes

### ISSUE THREAD

**Issue by raystuttgart** [We-the-People-civ4col-mod/Mod#565]
Hi guys, 

in this code I still have **hardcoded** a parameter to generate **Ice Lakes** instead of (normal) **Lakes** for lattitudes above 75.

Look at this code:

```

// autodetect lakes - start
void CvMap::updateWaterPlotTerrainTypes()
{
	EnumMap<TerrainTypes, bool> em;
	em.set(TERRAIN_COAST, true);
	em.set(TERRAIN_OCEAN, true);
	em.set(TERRAIN_SHALLOW_COAST, true); //WTP, ray considering shallow Coasts as well for being transformed to lakes
	em.set(TERRAIN_LAKE, true);
	em.set(TERRAIN_ICE_LAKE, true);

	PlotRegionMap regions(em);

	const int iNumRegions = regions.getNumRegions();
	for (int iRegion = 0; iRegion < iNumRegions; ++iRegion)
	{
		const PlotRegion& kRegion = regions.getRegion(iRegion);
		const int iNumPlots = kRegion.getNumPlots();
		for (int iPlot = 0; iPlot < iNumPlots; ++iPlot)
		{
			if (kRegion.isEurope())
			{
				kRegion.getPlot(iPlot)->setCoastline();
			}
			// ray, Ice Lakes
			else
			{
				// WTP, ray, we improve the logic by also checking for size
				// if it becomes to big, we rather not change to Lake or Ice Lakes
				// this prevents really strange stuff e.g. in MapScripts like "Carribean"
				bool isSmallEnoughForLake = kRegion.getNumPlots() < 50;
				if (isSmallEnoughForLake)
				{
					// Ice Lakes only in Lattitudes (North or South) above 75 degrees - else normal Lakes
					bool bIsBetterIceLake = kRegion.getPlot(iPlot)->getLatitude() > 75;

					if (bIsBetterIceLake)
					{
						kRegion.getPlot(iPlot)->setTerrainType(TERRAIN_ICE_LAKE);
					}
					else
					{
						kRegion.getPlot(iPlot)->setTerrainType(TERRAIN_LAKE);
					}
				}
			}
		}
	}
}
// autodetect lakes - end

```

Once the MapScript and Maps consider Lakes / Ice Lakes properly this should most likely be removed.
(Or maybe it can be made XML configurable at Terrains. - There are Lattitude settings for Terrains if I am correct.)

**Problem currently:**
Also MapScript "Carribean" declares to generate Lattitudes between +90 and -90 degrees, which it actually does not.
(Thus MapScript "Carribean" could also have Ice Lakes in theory which it never should.)

**Comment:**
IceLakes / Lakes only occur if the Water Plot is not "Ocean" or "Large Rivers" so it happens rarely on MapScript Carribean, but it can.
(On Maps like "Americas Gigantic" everything works perfectly.)

**Comment by Nightinggale** [comment]
> Also MapScript "Carribean" declares to generate Lattitudes between +90 and -90 degrees, which it actually does not.
(Thus MapScript "Carribean" could also have Ice Lakes in theory which it never should.)

As I recall it, Carribean is a vanilla map script, which I added to allow adding colony plot radius. We can add Latitudes to it too. In fact it sounds like we should. That still doesn't say that we shouldn't get rid of the hardcoding mentioned in this issue.

**Comment by raystuttgart** [comment]
I fixed this now with my last commit.
