### ISSUE TITLE
MapScripts shall also call "addFeaturesOnLand()" in DLL like "Random Maps, "addFeaturesOnWater()" needs to be implemented in DLL

### ISSUE THREAD

**Issue by raystuttgart** [We-the-People-civ4col-mod/Mod#567]
Current situation:

**Maps** can call:   **addFeaturesOnLand()** <--- This fully takes care of Features according to XML
(I had implemented this method for "Random Features for Maps")

**MapScripts** however still try to place all Features themselves fully ignoring placement rules in XML
(It is extremely prone to errors and would be lots of effort to adjust to new XML in "Plains".)

Simply check:
#WTP, ray, Randomize Features Map Option 
(in CvWBDesc.py) 

Then copy paste logic to the MapScripts.
(It should work perfectly fine.)

-------

Additionally to be implemented:
**addFeaturesOnWater()** 

**BUT**, each of the Water Features needs special treatment !!!!
(So most likely each of them needs a DLL method of its own.)

addFeaturesOnWater() could fully ignore features like "Winds and Storms" (everything that has <bGeneratedEveryRound> in XML)
addFeaturesOnWater() needs to have special logic to generate good "RiverFords" --> not as easy as other TerrainFeatures
addFeaturesOnWater() needs to have special logic for "Corral Reefs, Rock Reefs, ...
addFeaturesOnWater() needs to have special logic for "Streams"

-------

The "**addFeaturesOnLand()**" is fully done and just needs to be called.
The "**addFeaturesOnWater()**" is more complicated though and still needs to be implemented.

-------

**Summary:**
Having the DLL take care of the **placement of Terrain Features** is much safer for future additions to the mod.
Trying to code this in Python considering all XML checks will be a nightmare --> DLL already can handle it.

**Comment by raystuttgart** [comment]
Great news. 👍 

**"Taiga"** should also technically be no problem in a MapScript because it could be handled similar to "Tundra".
(Considering Lattitude Taiga should be placed **between Grasland and Tundra**.)

"Shrublands" should also be no big issue in a MapScript, because it also be handled similar to "Prairie" (in XML still "PLAINS").
(Considering Lattitude Shrubland should be placed **between Desert and Prairie**.)

**"Stone Steppes"** should be relatively simple to handle as well, because it could be randomly and sparsely placed in "Tundra and Taiga" regions - most likely best not near Rivers.
(Basically you could just have a random that turns e.g. **1 out of 20 Tundra or Taiga Plots** to Stone Steppes - if there is no river.)

**Lakes** and **Ice Lakes** are currently generated by DLL logic after the MapScript has run.
(Which might be good enough for now as a first version and considered later on.)

**Comment by devolution79** [comment]
Shrubland and taiga are now also generated

**Comment by devolution79** [comment]
Rock steppes and wetland support is in

**Comment by raystuttgart** [comment]
Sounds great. 👍 

Is this MapScript also already capable of generating "Large Rivers"?
(And if yes, did you use the work of @FlaviusBelisarius?)

**Comment by devolution79** [comment]
I am not aware of any support for generating Large Rivers other than the rudimentary effort that I put in last year. Is his work available somewhere for me to have a look ?

**Comment by MrZorG33** [comment]
@devolution79 see here https://github.com/MagisterBelisarius/Mod/blob/FaireWeather_LargeRivers/PrivateMaps/FaireWeatherTweakEx.py

**Comment by Ramstormp** [comment]
Dang it! Didn't notice that the work already been more or less completed!? So you want to rely on the <iAppearance> tag in  Features.xml for the positioning of the new features?

**Comment by raystuttgart** [comment]
**@Ramstormp** 
What is written in this post is all already working in "FaireWeatherTweakEx.py".
It is not yet complete but it also does not work that bad.

The actual work that needs to be done / finished:
**Generation of Large Rivers**

Otherwise it is just about systematically checking / testing.

**Comment by raystuttgart** [comment]
And yes, the **Terrains** are already generated by **XML / DLL.** --- Just like for the Maps.
(There are DLL functions made accessible to Python generating of WaterTerrains and LandTerrains.)

What needs to be taken care of are the **Terrains** (which incl. **Large Rivers.**)

**Comment by raystuttgart** [comment]
Guys please, before working on Maps first discusses with the others what had already happened. 
Anything else will just end up in chaos because nobody knows what the other actually does. 

Please communicate ! 👍

**Comment by Ramstormp** [comment]
@raystuttgart Well, I just wanted to play a random game at that moment with large rivers and new terrain so off I went. Anyway, unless I missed something it took 5 seconds to copy @devolution79 's work on FaireWeatherTweakEx.py over to @MagisterBelisarius mapscript. I will put up what I have I have added to the script in case it is deemed useful in the future, and if someone wants to test it for further analysis on what ought to be done.

**Comment by raystuttgart** [comment]
I also posted you in the Forum.

Basically in the future for Terrains Features the MapScripts should generall all just call these 2 functions.
```
addFeaturesOnLand()
addFeaturesOnWater()
```

**Comment by raystuttgart** [comment]
So the only 3 things that need to be changed / ensured :

1) All Terrains are Placed
2) Large Rivers generated
3) The 2 functions above being called. <--- instead of otherwise coding it in Python
(then of course Resources and Goodys)

**Comment by raystuttgart** [comment]
This is outdated.
