### ISSUE TITLE
Maps need to be adjusted considering new Terrains of "Plains" (randomize the rest)

### ISSUE THREAD

**Issue by raystuttgart** [We-the-People-civ4col-mod/Mod#574]
**Suggestion:**

- First place all **new Terrains**. And try to use a "Checklist" for each map if you got all of the Terrains.
- Then place the Terrain Features on Water like Fords. Reefs / Streams (except the Storm stuff) manually since the randomization in DLL explicitly excludes them at the moment
- Then have **Goodies**, **Terrain Features** (Land) and **Bonus Ressources** placed randomized by using the Map settings.

**Suggestion 2:**

Throw away the "non-random" Maps because they have caused so many problems in the past already every time the Terrains, Terrain Features, Bonus Ressources, ... changed.
Every major change in XML causes issues ... but it is up to you guys if you want to keep them as well.

--------

It should be the most efficient way to create those Maps.
It will still take some time to adjust all the Maps properly.

**Comment by dcrookston** [comment]
Is this something that could be done in the World Builder, then saved and
uploaded? If so I would be happy to do it.

**Comment by raystuttgart** [comment]
90% of the Work is done in **Worldbuilder** ingame.
But after that you need to edit the **WorldbuilderSave** with **Notepad++**.

You must make sure that the "Header Information" in the WorldbuilderSave is correct.
(In most cases you can simply copy&paste the first part of the WorldbuilderSave from the previous save.)

1. Adjust by Woldbuilder (place Terrains) and Save
2. Open new the WorldbuilderSave by Notepad++ and open the old version of the map as well by Notepad++
3. Copy&Paste the complete header information until "EndMap" from old version to new WorldBuilderSave

**Summary:**
Copy the complete beginning of the WorldbuilderSave (MapConfig) until about "EndMap".
(It should be the around first 261 lines of the map that need to be copied 1:1.

Read here:
https://forums.civfanatics.com/threads/important-map-creation-for-wtp.662649/

**Comment by ArchdukeLiet** [comment]
Hello to everyone!

I've committed to adjusting maps so the new terrains will be present on it.
I'll start working on the South America map first.

Best regards,
Liet

**Comment by raystuttgart** [comment]
Thanks for your support. :)

**Comment by MrZorG33** [comment]
we will mark the readiness of maps here or on the forum? if on the forum, then I think this issue can be closed.

**Comment by raystuttgart** [comment]
Yes, let us close the issue and track the work in the forum.
