### ISSUE TITLE
c++ exception in game

### ISSUE THREAD

**Issue by TBFGMBHmstepan** [We-the-People-civ4col-mod/Mod#575]
Tried to buy smuggler ship and did not have enought money i clicked on it neverless because i did not recognize how expensive it is and this poped up and the trade icons dispaeared ,i did not recieve the ship 

![image](https://user-images.githubusercontent.com/69200212/155249072-f4249785-e985-41bd-a922-ab6a7eb76b3f.png)

**Comment by TBFGMBHmstepan** [comment]
after turn end the message disapeared

**Comment by Nightinggale** [comment]
Looks like this is related to the log of what was sold. Did you sell anything in Europe/Africa/Port Royal this turn?

**Comment by TBFGMBHmstepan** [comment]
the log of what i sold i opened by "accident"(i was clicking anything to see if game crashed)  after this exception poped up , the exception poped up immediately after trying to purchase the ship with insufficient funds.  I do not remember for sure if i sold something but as a habbit i only visit port royal to sell stuff so probably .

**Comment by ErikSandbraaten** [comment]
In which branch / release did this happen?. A save would be helpful!

**Comment by TBFGMBHmstepan** [comment]
im sorry but i dont know which safe file that was i have a lot , dont know how to identify the correct one , i can however provide the game version , and i will remember if it happens again to remember the save file .

Game Version : We the People 2.8

**Comment by MrZorG33** [comment]
> Game Version : We the People 2.8
current release 3.0.1
use it. Some bugs from previous releases have been fixed in this release.

**Comment by ErikSandbraaten** [comment]
Ok, so this seems to be a really old bug. It's likely that it's been fixed already though
