### ISSUE TITLE
Events should have dedicated DLL code for spawning

### ISSUE THREAD

**Issue by Nightinggale** [We-the-People-civ4col-mod/Mod#579]
Issues keep popping up with events and goodies, which spawns units in bad locations. Last was on discord where a unit spawned from a goodie on a peak surrounded by only peaks and water, hence nowhere to move.

There should be a single canSpawn function, likely in CvPlayer. This should then be called from whatever place wants to spawn and we have one place to add all the conditions we want to check for while spawning. No more hacks to patch up bugs. We should do this right once and for all.

**Comment by raystuttgart** [comment]
Hi, 

I thought I should let you know.

I had changed the Code for Goodies to not appear on Peaks anymore.
(Because of similar issues like this and also graphical issues.)

I am not really sure in which branch that had happened though.
(I am not even sure if I had commited it - I have endless uncommitted / unfinished stuff.)

This is the code:
`
bool CvPlot::canHaveImprovement

`
```

	// WTP, ray, small adjustment for Goodies spwawning hostile Units - START
	// we do not want them to be spawned on Peaks, the graphics look really ugly there and it is bad for gameplay
	// Hills should still be allowed
	if (GC.getImprovementInfo(eImprovement).isGoodyForSpawningHostileAnimals() || GC.getImprovementInfo(eImprovement).isGoodyForSpawningHostileNatives() || GC.getImprovementInfo(eImprovement).isGoodyForSpawningHostileCriminals())
	{
		if (isPeak())
		{
			return false;
		}
	}
	// WTP, ray, small adjustment for Goodies spwawning hostile Units - END

```

Best regards
ray

**Comment by ErikSandbraaten** [comment]
Yeah, we should consolidate these "ad-hoc" checks.
In particular we need a way to allow pathfinding from a plot/area to another similar tuple be part of the (optional) constraints. A similar function would be useful for unit spawning as well (animals/pirates)

**Comment by raystuttgart** [comment]
By the way, there are now new DLL methods implemented for Spawning Units.
Both Hostile and Own.

So in case there is an issue the event could be adjusted to use those.

**read here:**
https://forums.civfanatics.com/threads/improved-python-event-system-spawning-hostile-units-implemented.665112/page-2#post-16374470

**Comment by raystuttgart** [comment]
This has now been fixed today by myself and jooe.
There is no issue related to Python Events spawning Ships anymore.
