### ISSUE TITLE
Unable to build new improvement or change old improvement

### ISSUE THREAD

**Issue by TBFGMBHmstepan** [We-the-People-civ4col-mod/Mod#580]
![image](https://user-images.githubusercontent.com/69200212/156919301-1108a420-8603-47c3-add1-cfa0faa9767b.png)

After capturing cities from enemy , im unable to change the land improvements it has in its vicinity . I also cant build new improvement after i pillage and destroy the old .   //sorry for the right side of the picture it was a screenshot of a dual monitor set up did not realize it at the time

**Comment by TBFGMBHmstepan** [comment]
![image](https://user-images.githubusercontent.com/69200212/156919544-58c2e0ce-e5cf-427a-8547-f6d5ba379585.png)
this does not change on other turns , im unable to change the tile improvements

**Comment by MrZorG33** [comment]
if you looked carefully, you would see that this is a simple colonist, not a pioneer. he needs to be given the profession of "pioneer". this must be done in a colony that has the right amount of tools.

please report all bugs in the 3.0.1 release on the forum.
if you are using the "plains" branch, then:
1. This is not a major release. it is still under development. errors will be present.
2. Before creating a new issue, check the list of current and closed ones.

**Comment by TBFGMBHmstepan** [comment]
where do i check "Before creating a new issue, check the list of current and closed ones." please ?

**Comment by MrZorG33** [comment]
@TBFGMBHmstepan the list is here
https://github.com/We-the-People-civ4col-mod/Mod/issues
