### ISSUE TITLE
update Readme.txt

### ISSUE THREAD

**Issue by MrZorG33** [We-the-People-civ4col-mod/Mod#592]
we need to make changes to the Readme.txt file to set up the game in Steam, as described in [this topic](https://forums.civfanatics.com/threads/important-for-all-steam-users-follow-these-instructions-to-play-wtp-without-bugs.674675/).

**Comment by AlexanderHenry-theYounger** [comment]
English install instructions are now more detailed in Plains and Release_candidate_3.0.2
