### ISSUE TITLE
Train Oil Random event only gives a negative option if the player already have some conditions met.

### ISSUE THREAD

**Issue by abmpicoli2** [We-the-People-civ4col-mod/Mod#6]
Details at https://forums.civfanatics.com/threads/religion-and-revolution-bugs-and-todos.449958/page-122#post-15159712 .

**Comment by abmpicoli2** [comment]
I don't know what this train oil random event is...

**Comment by abmpicoli** [comment]
https://forums.civfanatics.com/threads/religion-and-revolution-bugs-and-todos.449958/page-120#post-15012010 have further information on the issue

**Comment by raystuttgart** [comment]
As far as I know, this is already fixed, right?

**Comment by ErikSandbraaten** [comment]
... yep!
