### ISSUE TITLE
Game crash to desktop without any error or notification

### ISSUE THREAD

**Issue by diggzakk** [We-the-People-civ4col-mod/Mod#600]
version 3.0.1 just CTD for unknown reason, just crashes always during "next turn"

[saveandLogs.zip](https://github.com/We-the-People-civ4col-mod/Mod/files/8929700/saveandLogs.zip)

**Comment by devolution79** [comment]
Try the DLL attached to this post
https://forums.civfanatics.com/threads/we-the-people-bug-reporting.636760/page-61#post-16291971
