### ISSUE TITLE
Plains failed assertation checks

### ISSUE THREAD

**Issue by devolution79** [We-the-People-civ4col-mod/Mod#602]
Below is list of recent failed assertion checks from the Plains branch 

After autoplay for 100+ turns:

Assert Failed

File:  DLLSources\.\CvGlobals.cpp
Line:  2974
Func:  CvGlobals::getInfoTypeForString
Expression:  strcmp(szType, "NONE")==0 || strcmp(szType, "")==0
Message:  info type UNIT_MAN_O_WAR not found, Current XML file is: xml\GameInfo/CIV4DiplomacyInfos.xml

----------------------------------------------------------

After clicking around on the map:

Assert Failed

File:  c:\development\sid meier's civilization iv colonization\mods\wtp\project files\dllsources\CvPlayerAI.h
Line:  26
Func:  CvPlayerAI::getPlayer
Expression:  ePlayer >= 0
Message:  Player is not assigned a valid value

----------------------------------------------------------

>	CvGameCoreDLL.dll!CvPlayerAI::getPlayer(PlayerTypes ePlayer) Line 26	C++
 	CvGameCoreDLL.dll!CvPlot::getUpgradeTimeLeft(ImprovementTypes eImprovement, PlayerTypes ePlayer) Line 4918	C++
 	CvGameCoreDLL.dll!CvGameTextMgr::setPlotHelp(CvWStringBuffer & szString, CvPlot * pPlot) Line 2893	C++
 	[External Code]	
 	Colonization.exe![Frames below may be incorrect and/or missing, no symbols loaded for Colonization.exe]	Unknown
 	CvGameCoreDLL.dll!boost::python::detail::upcast_impl<_object,_object>(_object * x, _object * __formal) Line 84	C++
 	[External Code]	
 	CvGameCoreDLL.dll!CyArgsList::makeFunctionArgs() Line 94	C++
 	[External Code]	

CvPlot::getUpgradeTimeLeft(ImprovementTypes eImprovement, PlayerTypes ePlayer) ePlayer is -1 (NO_PLAYER)
because iTurns = pPlot->getUpgradeTimeLeft(eImprovement, eRevealOwner); is called with eRevealOwner = NO_PLAYER

When hoovering over the happy indicator in a size 15-ish city:

Assert Failed

File:  DLLSources\.\CvGameTextMgr.cpp
Line:  8803
Func:  CvGameTextMgr::setCityYieldModifierString
Expression:  iBaseModifier == kCity.getBaseYieldRateModifier(eYieldType)
Message:  Yield Modifier in setProductionHelp does not agree with actual value

----------------------------------------------------------

**Comment by raystuttgart** [comment]
The first Assert (UNIT_MAN_O_WAR) is definitely fixed.
I do not know about the others though. 

Since "Plains" however is not in development anymore, let us close this.
We will see which Asserts we get with "New Hope". 👍
