### ISSUE TITLE
Checkboxes are not shown in "Assign trade routes (Automate)" screen.

### ISSUE THREAD

**Issue by windock** [We-the-People-civ4col-mod/Mod#606]
I have tested both "plains" and "develop2" branches. Tested different resolutions.
![checkboxes](https://user-images.githubusercontent.com/79237/181776114-0939d225-e214-4275-92f5-871dded76167.png)
Steps to reproduce: have at lease 2 cities, set up trade routes. Select a Wagon Train. Hit "R", or press Assign Trade Routes (Automate). 
I expect the leftmost column to have visible checkboxes. But there are none visible. They work, however, as I can actually click them, and trade routes are created correctly.

City governor screen for Import/Export has correctly working and visible checkboxes.
[George Washington AD-1541.zip](https://github.com/We-the-People-civ4col-mod/Mod/files/9220571/George.Washington.AD-1541.zip)
This save file was created by the up-to-date "develop2" branch.

Windows 10. Compiled through Mod/Compile repositories, Compile-Release script

**Comment by windock** [comment]
Downloaded 3.0.1 release works as expected though.

**Comment by MrZorG33** [comment]
maybe I would have reported this issue too if I had created trade routes before [fdc4d9a](https://github.com/We-the-People-civ4col-mod/Mod/commit/fdc4d9a072a831bebc61fca5e66014ea2d95cbc6) came out. however, after the latest update, I don't see such a problem.
![image](https://user-images.githubusercontent.com/61798883/182426876-6520bf30-01ce-48a3-bf09-798ef9d70cf3.png)

**Comment by devolution79** [comment]
Guys, there's nothing special with that commit. It simply was the most recent one when I wrote the previous post.

**Comment by windock** [comment]
I have tested it on 3.0.1 commit, however this time I re-built the whole project, not download it. It works there perfectly. Does anyone have better ideas on where to start? I'm currently just doing bisect-debug to find the commit where it stopped working. However, it may really take a long time. I am very open to have a call to debug the issue together with someone who has more experience with the project. It would be very cool to see your workflow.

**Comment by windock** [comment]
Bisected it. This is the commit in question that broke my trade screen checkboxes:
https://github.com/We-the-People-civ4col-mod/Mod/commit/8df475400fb6cd238938f35987a52bf47eab6447
@Nightinggale Any advice?

**Comment by windock** [comment]
I have resolved the issue for myself. However, it needs a discussion. I really do not understand, why this issue cannot be reproduced for others.

Let's look into https://github.com/We-the-People-civ4col-mod/Mod/blob/develop2/Project%20Files/DLLSources/CvGlobals.cpp#L3135

```
CyGames().getSymbolID(FontSymbols.ATTITUDE_FRIENDLY_CHAR)
```
returns "535 "for me.

Let's see font icons. The ATTITUDE_FRIENDLY_CHAR is the third row from bottom, first symbol on the left. I have issues with loading symbol CHECKBOX_CHAR, 6th row from bottom, 1st column from the left. None of the 6th row symbols are shown for me.

![GameFont_75 tga](https://user-images.githubusercontent.com/79237/183129504-6b621c00-7b44-4f64-99fa-3dc0b44b11d1.png)

There are 25 icons in 5,6,7 (from the bottom). So the correct offset of that CHECKBOX_CHAR is 535 - 25*3 = 431. If I change the file https://github.com/We-the-People-civ4col-mod/Mod/blob/develop2/Assets/XML/GlobalDefinesAlt.xml#L1284
from value *8783* to *431* I get that CHECKBOX_CHAR icon shown correctly in my CvTradeRoutesAdvisor.py screen. 
https://github.com/We-the-People-civ4col-mod/Mod/blob/develop2/Assets/Python/Screens/CvTradeRoutesAdvisor.py#L423

Now, let's just try to evaluate number of icons in that GameFont_75.tga file. It really seems to have some hundreds of icons. First few rows contain very small icons. I cannot bother counting them all. However, number *431* for the CHECKBOX_CHAR seems very much more believable than *8783*.

So my question here is. Where is that number *8783* taken from? It was defined in the commit I have mentioned in the above comment.

**Comment by windock** [comment]
So I have resolved the issue for myself. However, I worry that this font offset number may depend on the specific build process. Maybe CPU/architecture. It doesn't seem to be consistent for users. Let me propose to calculate that value as an offset from CHECKBOX_CHAR: CHECKBOX_CHAR - 75. And then we can get rid of two settings in XML FONT_SYMBOL_BONUS_OFFSET and FONT_SYMBOL_CUSTOM_OFFSET

**Comment by raystuttgart** [comment]
@windock 
I had to recreate the GameFonts to include all the Icons for the new Bonus_Icons.
So the GameFonts you see are custom made.

By the way there is also a "GameFont"-Debug Screen in the Advisor-Screens.
There you can easily check all the Icons if they match or not. (It was programmed by @Nightinggale)

However I cannot explain why it sould match for all others but not you.

See my Screenshots for how it works:

1) Open UserSettings.txt (in the root folder of the mod) and enable Gamefonts Debug with "1"
2) Enter the AdvisorMainScreen and click the last Button which says "GameFont Debug"
3) Check all the Icons to your liking

![UserSettings](https://user-images.githubusercontent.com/59391125/183238461-85496aeb-9679-4009-bc26-e643087e1488.png)
![Civ4ScreenShot0012](https://user-images.githubusercontent.com/59391125/183238487-42ef6816-f4f0-480b-a330-eea7bd7ed1c0.JPG)
![Civ4ScreenShot0013](https://user-images.githubusercontent.com/59391125/183238495-656ab393-19aa-4090-95a5-341dea907ec4.JPG)

**Comment by windock** [comment]
@raystuttgart thank you!

**Comment by raystuttgart** [comment]
**By the way:**
In Yields we also created a **new "GameFonts"-System**.
(@Nightinggale did DLL and I did XML and once more restructured GameFonts)

see here:
https://github.com/We-the-People-civ4col-mod/Mod/commit/50e005480ac90ed90922308bee713334e15f7a45

I would h**ighly advise though to wait** for this being published with the release of "Yields" - the most advanced feature branch.
Because there are several dependencies in that "GameFonts"-System only fully reflected in "Yields".

**Comment by raystuttgart** [comment]
The issue was caused by using "official Steam version" instead of following advices in this thread.
https://forums.civfanatics.com/threads/important-for-all-steam-users-follow-these-instructions-to-play-wtp-without-bugs.674675/
