### ISSUE TITLE
No Found City for Free Civilian

### ISSUE THREAD

**Issue by arviman** [We-the-People-civ4col-mod/Mod#607]
Started a new game. I was able to found my first colony but don't see the option the second time. Tried various units like "free colonist", "scout", "expert hemp planter" - i thought they all had the flag to be able to found a colony? Is there some new rule that says shouldn't found a colony 2-3 tiles next to a native camp?

![no found city](https://user-images.githubusercontent.com/1166530/182033119-c307afcb-8270-450d-9c3f-021f86e6f359.png)

**Comment by arviman** [comment]
Attaching the save file:
[AutoSave_AD-1558-September.zip](https://github.com/We-the-People-civ4col-mod/Mod/files/9229143/AutoSave_AD-1558-September.zip)

**Comment by arviman** [comment]
i didn't know there was a separate "settler" profession

**Comment by raystuttgart** [comment]
Yeah, the mechanic has changed. 👍 
You now need to equip Units in Settler Profession.
(Good that you noticed it yourself already.)
