### ISSUE TITLE
City culture output is not consistent with it's popup

### ISSUE THREAD

**Issue by windock** [We-the-People-civ4col-mod/Mod#609]
Develop2 branch.

Steps to reproduce:
- load save file
- open city "Conception de la Vega"
- observe top panel showing current culture output

As you can see, culture of the city in UI is shown as 7, however, popup shows it is 4. I am not sure of ways to reproduce it, but it is consistent across multiple turns in the attached save file. 
That city was conquered a lot of turns ago from Spain.

![city-culture](https://user-images.githubusercontent.com/79237/184425030-f8c4cd31-f657-48f7-96f6-61725a1e37aa.png)
[windock AD-1660-January.zip](https://github.com/We-the-People-civ4col-mod/Mod/files/9329284/windock.AD-1660-January.zip)

**Comment by raystuttgart** [comment]
Oh ok, that should be pretty simple to explain.
(And yes it is a small bug - that simply nobody noticed so far.)

There is an additional component to "Culture".
It is directly created from Population size.

The "Culture from Population Size" is not displayed in the Mouse Over.
I will correct it though. 👍

**Comment by raystuttgart** [comment]
It is fixed in "Yields" by my last commit.

![Civ4ScreenShot0000](https://user-images.githubusercontent.com/59391125/184485440-f6f32018-a1ef-4620-bd05-c9a1796cb9f9.JPG)
