### ISSUE TITLE
Game crashed at end of turn

### ISSUE THREAD

**Issue by semenovdmitriy** [We-the-People-civ4col-mod/Mod#621]
After ending the turn game crashes.

Version of mod - 3.0.1

Save attached.
[DELL AD-1581-May.zip](https://github.com/We-the-People-civ4col-mod/Mod/files/9780925/DELL.AD-1581-May.zip)

**Comment by raystuttgart** [comment]
Most likely already fixed in the internal development branch which is 2 years ahead in development.
3.0.1 is so old that it is hardly worth to keep analyzing the same bugs again and again and again ...

**Comment by raystuttgart** [comment]
There is no point in analysing outdated bugs of 3.0.1.
Let us see what happens once we publish 4.0.
