### ISSUE TITLE
New Hope. problem with units purchased from other kings

### ISSUE THREAD

**Issue by MrZorG33** [We-the-People-civ4col-mod/Mod#624]
the problem is this: until you manually (on the colony screen) assign a unit to work, double-clicking on the colony screen or the button on the map (change profession) does not work.

military units that can be purchased from other kings have only a profession, but are essentially free colonists that the player needs to arm.
![image](https://user-images.githubusercontent.com/61798883/197367950-77375a25-b2ba-431b-8291-f72e78b4b8b3.png)

**Comment by raystuttgart** [comment]
I will check it.

**Comment by raystuttgart** [comment]
It is solved in my last commit.
