### ISSUE TITLE
New Hope. the amount of resources produced is not visible on the colony screen.

### ISSUE THREAD

**Issue by MrZorG33** [We-the-People-civ4col-mod/Mod#628]
on the screen of the colony, the amount of produced resources in the bottom line of Yelds is not visible. In the screenshot, you can see that the amount of coffee produced goes beyond the screen.
the resolution used is 1920x1080.
![не видно приход на экране колонии](https://user-images.githubusercontent.com/61798883/198857803-883b2ad2-02ca-4f68-9e0b-db1587417f3c.jpg)

perhaps we should reduce the height of the numbers and move them up a bit.

**Comment by raystuttgart** [comment]
@MrZorG33 Please for the moment use this solution: **1280 x 960**
This resolution works perfectly fine, it is a **4x3** resolution and actually **works best**.

I will need to see what I can do with the other resolutions.
(It is really really annoying to get them all right.

![Civ4ScreenShot0002](https://user-images.githubusercontent.com/59391125/198866248-1032cfd7-5473-4391-81d9-2bfd7e631919.JPG)
![Civ4ScreenShot0003](https://user-images.githubusercontent.com/59391125/198866249-4f98a3ea-c5fe-48d5-bc61-d0f245c9643d.JPG)

**Comment by MrZorG33** [comment]
Unfortunately, this permission is not suitable for me.
I had to take a photo of the monitor. the screenshot shows that everything is fine, but it is not)
![image](https://user-images.githubusercontent.com/61798883/198878548-d5a408a1-38d1-40c1-a355-3e9462cc1b7a.png)

I'll wait for a fix as using the recommended resolution of 1280 x 960 4x3 on a 16:9 monitor is just awful)

**Comment by raystuttgart** [comment]
@MrZorG33 
Ok, the screen is now adjusted, so it works for both 4x3 and 16x9 resolutions.
(See my last commit to "New Hope".)

**Comment by Nightinggale** [comment]
The main culprit for issues like this is that vanilla code assumes 4:3 resolutions and will in some places set height of objects based on the width of the screen. This fails for 16:9 resolutions as it assumes 1920:1080 is 1920x1440.

Just keep reporting whenever this issue shows itself as there is no other way to fix it than to do it one by one.
