### ISSUE TITLE
New Hope. creating domestic animals out of nothing

### ISSUE THREAD

**Issue by MrZorG33** [We-the-People-civ4col-mod/Mod#629]
even if you don't have any domesticated animals (cows, goats, sheep), by sending a colonist to produce milk, they will start to appear.
![image](https://user-images.githubusercontent.com/61798883/198858596-488e2723-d18e-474c-985e-1b7e465f719e.png)

**Comment by raystuttgart** [comment]
Ok, that is kind of an issue probably with the way I have programmed / configured this.
I will look into it, don't worry it should be easy to fix. :)

**Comment by raystuttgart** [comment]
It is fixed with my last commit. :)
