### ISSUE TITLE
New Hope. ships carry units prohibited for them

### ISSUE THREAD

**Issue by MrZorG33** [We-the-People-civ4col-mod/Mod#632]
the ban on transporting a certain type of unit does not work for the following ships:

Slave barque (can only transport goods and slaves)
![image](https://user-images.githubusercontent.com/61798883/199982216-c1e6b17a-7076-4966-989c-b1e3d7cf935f.png)

Ship of the Line (can only transport goods and troops)
![image](https://user-images.githubusercontent.com/61798883/199977926-6d6f105a-581f-41ec-9d04-cc7784b21697.png)

Frigate (can only transport goods and troops)
![image](https://user-images.githubusercontent.com/61798883/199979233-da393deb-eaf5-47cf-a9e1-a6e38ea9c5cd.png)

Naval Brig (can only transport goods and troops)
![image](https://user-images.githubusercontent.com/61798883/199979767-32a805cf-15a8-48fb-81ef-96b953af709f.png)

Corvette (can only transport goods and troops)
![image](https://user-images.githubusercontent.com/61798883/199980022-2216b538-abe6-4e8a-99e1-b4669e7ff9dd.png)

Man-o-War (can only transport goods and troops)
![image](https://user-images.githubusercontent.com/61798883/199983279-633bbe3a-b604-4573-a9dc-16acb1219695.png)

Galleon (can only carry goods and treasures)
![image](https://user-images.githubusercontent.com/61798883/199980676-7ea7c7ed-8ef7-49b8-ac80-f3cae51b9582.png)

**Comment by raystuttgart** [comment]
Is this also a problem on the Map?
Or is this just a problem in Europe / Africa / Port Royal?

**Comment by raystuttgart** [comment]
Strange, it seems like the code is completely not working anymore.
Even on the Map ... maybe it was really removed during the merge.

**Comment by raystuttgart** [comment]
It is fixed now again.
(It needs to compile a new DLL with my last change.)
