### ISSUE TITLE
New Hope. need to change FF bonuses

### ISSUE THREAD

**Issue by MrZorG33** [We-the-People-civ4col-mod/Mod#633]
since the warehouse is no longer used as a place of work, the bonuses for FF James Wilson need to be changed (see screenshot).
![image](https://user-images.githubusercontent.com/61798883/200050500-db8b95fe-e017-4413-bb0c-72bf0b0b0d9c.png)

Perhaps there will be other FFs. I suggest writing about them in this issue.

**Comment by raystuttgart** [comment]
No, the bonus just says how fast their are **built**.
Meaning how fast the **Warehouse itself** is produced.

There is no issue with this, since it does **not affect the Yields**.
