### ISSUE TITLE
fix description of FF bonuses

### ISSUE THREAD

**Issue by MrZorG33** [We-the-People-civ4col-mod/Mod#638]
before a new release 4.0 is published.
correct the description of the FF bonuses in accordance with the changes in the buildings that release the product.
![image](https://user-images.githubusercontent.com/61798883/200633921-c2a0fbbf-777b-49a9-8e83-3a9f1d05ed44.png)

if not already done, reassign bonuses to the desired buildings.

**Comment by raystuttgart** [comment]
This is fixed now.
