### ISSUE TITLE
Can't conquer settlement!

### ISSUE THREAD

**Issue by RBRiddick** [We-the-People-civ4col-mod/Mod#640]
The popup tab with the option to raze or conquer the city (of an other european colony, not native) doesn't appear. 
The city is suddenly razed.
Thank You
[William Penn d.C. - 1541-Maggio.ColonizationSave.zip](https://github.com/We-the-People-civ4col-mod/Mod/files/9970760/William.Penn.d.C.-.1541-Maggio.ColonizationSave.zip)

**Comment by MrZorG33** [comment]
if the size of the city was 1, then it will be destroyed. what is the size of the city you are trying to capture?

**Comment by RBRiddick** [comment]
3 size.
I have also tried to modify population/buildings with map editor, but nothing change.
Conquering an other city (7population) is the same.

**Comment by RBRiddick** [comment]
Previously during the game I can conquer settlements "normally".

**Comment by MrZorG33** [comment]
what version of the game are you using?

**Comment by RBRiddick** [comment]
It is patched 1.01f. It should be the last one, right?

**Comment by RBRiddick** [comment]
Rebooting windows and the game all work fine. 
I will try to reproduce the problem...

**Comment by RBRiddick** [comment]
I have tried several times to get the error but (fortunately) I did not succeed.
I close the post.
Thanks for the interest to MrZorG !
