### ISSUE TITLE
[BUG] Unit XP not shown with other units in the same tile 

### ISSUE THREAD

**Issue by nci-wtp** [We-the-People-civ4col-mod/Mod#641]
Latest development branch.

![col-unit-xp-not-shown](https://user-images.githubusercontent.com/97903628/200922754-6878223d-3061-4b63-a1ca-731e0ac01548.png)

**Comment by MrZorG33** [comment]
this is not a bug, but an overload of the tooltip screen with unit data. this issue has already been discussed. so far unchanged.
