### ISSUE TITLE
[BUG] Assigned professions lost after disorder

### ISSUE THREAD

**Issue by nci-wtp** [We-the-People-civ4col-mod/Mod#642]
Latest development branch.

![col-professions-lost-after-disorder](https://user-images.githubusercontent.com/97903628/200925120-d9b3feb0-2731-499e-8037-ee86798ab3da.png)
[Saves-Assigned-Professions-Lost-After-Disorder.zip](https://github.com/We-the-People-civ4col-mod/Mod/files/9974569/Saves-Assigned-Professions-Lost-After-Disorder.zip)

**Comment by MrZorG33** [comment]
until I saw the screenshot, I was thinking about something completely different. this situation already has its issue.
please, before creating a new one, check the list of existing ones (open and closed).
