### ISSUE TITLE
Drill Sergeant promotion is useless?

### ISSUE THREAD

**Issue by abmpicoli** [We-the-People-civ4col-mod/Mod#65]
I'm looking at the Drill Sergeant promotion... 5% strength increase, +10% experience from combat... but combat experience is an integer value, right? 10% over 2 is 2... no change in experience whatsoever...

**Comment by Nightinggale** [comment]
We need a general overhaul of what is integer values, like health can give -1%, which is horrible for mining 2 silver each turn. I'm not sure we should make a ticket for each such case, but rather brainstorm on how we want the engine to work in general and the coding style way of solving such issues.

**Comment by abmpicoli** [comment]
Good idea... I can see two ways of implementing this : multiply everything by 100, or convert the numbers to float (or even double) . However this will make saves incompatible, I'm afraid...

**Comment by raystuttgart** [comment]
The combat Strength in Combat is not checked as Integers.
So 10% will indeed have an effect.

The issue can be closed.
--> The Promotions are not useless, they work.
