### ISSUE TITLE
Symbols are broken on city billboards..... again

### ISSUE THREAD

**Issue by Nightinggale** [We-the-People-civ4col-mod/Mod#657]
Once again GameFont symbols will be displayed as ? on city billboards.

I'm not going to attempt to fix it the same way as in the past through because this time it is especially complicated. The bullet char works in text and the index for that one is hardcoded in the exe meaning if we move the symbols, text from the exe containing the bullet char will break (such as the event log).

Besides fixing this will likely just break again at some point in the future so I have given up on a fix with the current system. GameFont should just be placed where the exe excepts it to be and then in one row for simplicity. Screw billboards. It will make symbols just work. This will break the GameFont following symbols, but that can be corrected in GameFontIDs.xml.

-----

### Solution to billboards

Add a list of billboard symbols to GameFontIDs.xml. Those symbols will then work on billboards and only those. This saves a lot of IDs in the billboard compatible range. The mentioned symbols are placed in a row at the new location without considering the symbol IDs. It's perfectly fine having 4, 8, 11, 12, 15 as 5 icons in a row.

On startup, make an array of symbols and getting a symbol ID is then an array lookup. This allows populating the array once while reading xml while it's not a huge drag each time it's used. This eliminates the need to group symbols together in GameFont.tga.

-----

The problem with this approach is that currently you can't write say OCCUPATION_CHAR_CUSTOM in xml and then get the DLL to convert this to an ID. To get this started, a perl script is needed to convert the content of GlobalTypes.xml into enums and add converters between enum and the string counterparts. This would have been useful in the past and it likely will be useful in the future as well so it might as well be done once and for all.

**Comment by raystuttgart** [comment]
@Nightinggale 
I just tested and there seemed to be absolutley no issues.

**Comment by raystuttgart** [comment]
**Edit:**
Ah ok, all the GameFont Icons for Billboards I have tested seem to be the custom ones. (Those work.)
But as you said, there seems to be an issue with the Vanilla ones again. (Damn these Icons ...)
