### ISSUE TITLE
AI - Unrest if town grows over 4

### ISSUE THREAD

**Issue by raubwuerger** [We-the-People-civ4col-mod/Mod#672]
I have observed this a few times now. When a player city becomes larger (>= 5), unrest arises. Regardless of nation and environment. This is a big disadvantage, especially at the beginning. Or doesn't the AI have mali?

![image](https://user-images.githubusercontent.com/7585446/208745340-91b4bb8c-8e63-4bb4-be03-958d8fd9fa32.png)

**Comment by MrZorG33** [comment]
this is the concept of the game - a city with a population of =>5 must have a military unit garrisoned. this is not an error.

**Comment by raystuttgart** [comment]
Yeah, it is not like this is a new feature. ;)

**Comment by raubwuerger** [comment]
Ok, so I can close this issue ...
