### ISSUE TITLE
2 minor events defects

### ISSUE THREAD

**Issue by RBRiddick** [We-the-People-civ4col-mod/Mod#688]
1) In the event you have to be the first to found 3 inland colonies, after you have achieved that, the description remain in the achievement list (tab of the events log).
2) In the event in which the king want you to became the fur trade leader -by hiring 5 expert trapper/cacciatore esperto, before any other can- other colonies reach the goal with 5 "expert hunter", while you have to obtain 5 "expert trapper"("cacciatore esperto" in italiano).

Thank to all the team for your great work!

**Comment by raystuttgart** [comment]
1) An Achievement and Event / Quest are different things.
Achievements is basically a "Trophy" and will not be removed after an Event was finished.
This is no bug. (Just the "Event / Quest" has to be removed from the lsit of "Events / Quests")

2) The rules for the Quests are absolutely identical for both AI and Human Player.
It is simply technically not possible that they have different rules because they both use the same Triggers / Events.
Also I checked the Quest again and indeed it requires 5 Trappers. (There was probalby just some minor confusion.)

**Comment by raystuttgart** [comment]
Edit:
I also just tested and the Quest Log was successfully cleared after the Quest was finished.
(see Screenshot.)

**WARNING:**
If you end the game after finishing a Quest without first pressing "End Turn", it may happen that a Quest is not cleared from Quest Log - but there is nothing we can do about that. (It is a Vanilla Bug.)

![Civ4ScreenShot0005](https://user-images.githubusercontent.com/59391125/210512594-35d59b04-3ec0-4b91-8127-16346e198bf6.JPG)

**Comment by RBRiddick** [comment]
> 1. Just the "Quest" has to be removed from the list of "Quests"
It is just that the 'problem'. To me it doesn't happens. Check the first saved game I have attached please. To me it is again in the quest list.
2) Again in the first game (1593), if you end turn, you get a message in red (God's sake...) that you fail the quest. But none of the other nation has 5trappers. Only  Russian colonies have 5expert_hunters. I assume that it has switched the quest to failed. For holland and sweden, I have conquered them in the second save, to be sure.

[wp1593.zip](https://github.com/We-the-People-civ4col-mod/Mod/files/10345862/wp1593.zip)

**Comment by raystuttgart** [comment]
**About 1:**
Again, you need to have the turn end first so the Quest can be removed. :)
If you exit the game before that it will not be removed.

**About 2:**
What you assume is simply not true. 
Because again AI and you use the same XML.

**Comment by RBRiddick** [comment]
Thank you for your patience. 
1)sorry, I leave out the "warning".
2) ok, but then I can't explain what happen. Have you tried to end turn with my savedgame? It happens to you too?

**Comment by raystuttgart** [comment]
You can try yourself to open **Civ4EventTriggerInfos.xml**.
**UNITCLASS_HUNTER** does **not even appear once** in that file.
