### ISSUE TITLE
AI: after losing all colonies, sends ships back to Europe in loop

### ISSUE THREAD

**Issue by jo-oe** [We-the-People-civ4col-mod/Mod#701]
After losing all their colonies in a war and ending up without a settler unit on the map, the AI will send their ships back to Europe in an endless loop. The ships are full of military units, arrive on the map and the same turn the are sent back to Europe.
This continues in an endless cycle. The AI player cannot be killed, because their units are never actually on the map.

**Comment by jo-oe** [comment]
Note that giving the AI a new settlement via WB will break the loop, as the AI will then send the ships loaded with military to that settlement, so they can be fought.

**Comment by jo-oe** [comment]
I think the problem is that CvPlayer::sortEuropeUnits() does not put the settler units in front of the queue, so the transports will always load the (more valuable) military units and then cycle to the map and back to Europe.

I'll need some help with iterators and vectors for fixing this, maybe one of the more experienced coders can help me in discord to improve the CvPlayer::sortEuropeUnits() function putting settlers in front of the queue ...

**Comment by devolution79** [comment]
Hi, I am the one who originally implemented the prioritization feature and it predates the introduction of the settler so that's part of the explanation. I agree that the logic should be overhauled and I've been meaning to add some form of of dynamic demand system whereby the colonists to be picked up the the ship are determined by what's needed the most. Perhaps we could collaborate on this :)

**Comment by jo-oe** [comment]
Hi, thanks for your comment! I currently play with a small code modification that will move units that canFound() to the beginning of the queue (overriding the purchase value as sort order) and it appears to improve the situation. It might even avoid the situation above alltogether.
There is already a sorting of the Europe queue by purchase value, which will probably be quite adequate for most situations (because military units are more expensive than others). 

The problem seems to be that ships (fully) loaded with army units will unconditonally return to Europe as soon as the last settlement is conquered. (which could be changed to only occur after the military units have been onloaded somewhere (where?)
But what I don't understand that apparently the transports don't unload in Europe (which is actually meant to happen if I read the code correctly) to pick up settlers. But instead they just return back to the map with their load of army units and then return to Europe upon arrival on the map -> loop.

So the case that remains open to be fixed is when all ships are full of military units so none of them can pick up the waiting settlers. That situation might not occur anymore though if settlers are always prioritised. (as they are in my local build)

**Comment by raystuttgart** [comment]
I guess this is now fixed by the latest commits. :)
