### ISSUE TITLE
need animation for Capable Captain

### ISSUE THREAD

**Issue by MrZorG33** [We-the-People-civ4col-mod/Mod#706]
the new unit Capable Captain has no animation (like Great Generals and Admirals) when attaching it to the ship.

**Comment by raystuttgart** [comment]
Please contact Schmiddie about it, I have no idea what I should do about it.

**Comment by MrZorG33** [comment]
@Schmiddie1979 can you solve this problem?

**Comment by raystuttgart** [comment]
Better contact him over at **CivFanatics** in a private conversation.
(Chances are higher that he will read it over there.)

**Comment by raystuttgart** [comment]
Did you ask Schmiddie?

**Comment by MrZorG33** [comment]
Yes. he said he understood. this is all.

**Comment by raystuttgart** [comment]
This is fixed now.
