### ISSUE TITLE
New_Hope: Python Exception causing mod failure

### ISSUE THREAD

**Issue by LT-Rascek** [We-the-People-civ4col-mod/Mod#714]
Attempting to load the mod results in a CTD.

Info:

Mod Installed in `My Documents/My Games/Civilization IV Colonization/MODS/WeThePeople`

Final Python error is 

> There are more siblings than memory allocated for them in CvXMLLoadUtility::SetVariableListTagPair
> Current XML file is: xml\Terrain/Civ4FeatureInfos.xml

Let me know if additional information is required.

**Comment by raystuttgart** [comment]
You simply did not compile a DLL as it is necessary for a development branch.
For more information contact modders over at discord or CivFanatics forum.
