### ISSUE TITLE
Missionary actions should be influenced by trade, students and nearby monasteries.

### ISSUE THREAD

**Issue by abmpicoli** [We-the-People-civ4col-mod/Mod#72]
The current code for establishing missions is silly. Mission chance is based exclusively on good relations and number of missions, plus the unit profession...

Also, the risk of losing a missionary is too big as you establish more missions.

The monastery improvement is something I don't feel tempted to build... It appears to me that the benefits are too small, and the mission costs too much.

So, I think that:

1) the monastery should be an improvement that missionaries, not pioneers, could build.

2) A populated monastery should influence nearby indian villages (say, 3 tiles around) making it easier for establishing missions after some time, and also increasing with time.

3) A "raw" chance of mission success should appear when we rover over indian villages, so the player could see when the village is "mature enough" for an actual missionary to establish the mission.

4) To have players learning professions in the village should increase the influence for trading agreements.

5) Successful trade transactions with the village should influence both conversion rate and change of mission success. On the other side, transaction failure should impact negatively.

6) Native relations will cause also an increase / decay of this influence.

7) When a missionary tries to establish a mission at a city, there should be a "success chance" , a "retreat chance" , and a "total failure" chance, that would cause the missionary to be killed and relations hit with the natives. A mission retreat would provide a random point increase.

8) There would be a set of promotions to missionary units: Missionary 1 would give a 10% chance of mission success, Missionary 2 would give a 20% ... The establish mission action would give experience points towards it. 

9) firebrand Preachers should have a bonus both for monastery work and for establishing missions. Maybe they should have the Missionary 1 promotion?

**Comment by raystuttgart** [comment]
Guys, we have a relatively simple logic for Missionaries because

A) It is quite performant
B) It is easy to understand
C) It is stable

Having 9 additional new rules and dependencies in there will not make this feature more fun and definitely not easier to understand for players.
Complicated rules do not really always make the game better.

This is basically just wasting effort to make the game worse.
