### ISSUE TITLE
incorrect count yields of goods sold in Europe/Africa

### ISSUE THREAD

**Issue by MrZorG33** [We-the-People-civ4col-mod/Mod#732]
I noticed that the formula for calculating goods sold in Europe does not match the description.
![image](https://user-images.githubusercontent.com/61798883/218480643-3968ee8d-3b47-4507-9973-058e37298d8b.png)

the description says that only 10% of the yields of goods sold in Europe (sorry, I didn’t make it to Africa) are included in the calculation. however, the number also changed when I traded with the natives, which does not match the description.

on the next screen is another calculation error. before the acquisition of goats, the ratio was 960/1150. however, after the acquisition of 50 goats, it became 975/1150, although, judging by the description, it should have become 965/1150.
![image](https://user-images.githubusercontent.com/61798883/218485572-8972d64f-9be6-4f49-997d-a66f96dbfdc8.png)

@raystuttgart, I'm assuming you did that calculation (although I could be wrong). but could you take a look at this formula?

**Comment by raystuttgart** [comment]
No, I did not do these calculations and texts.
They are either from Vanilla or from TAC.

Not everything in the game was done by me. :)

**Comment by raystuttgart** [comment]
If you do not give me a TXT_KEY I have really no idea what you are talking about.

**Comment by raystuttgart** [comment]
I will update a little bit what I found out:

It is related to this feature of veatiarvind where he changed tax increases to consider also the Yield Prices (not just amounts traded)

In DLL search for this
`// R&R, vetiarvind, Price dependent tax rate change - Start`

The message seen above is only visible if **GAMEOPTION_NO_MORE_VARIABLES_HIDDEN** is active.
(And the code related to it can be found in **Europe Screen**, **Africa Screen** and **Port Royal Screen**.)

`            elif iData1 == self.HELP_TAX_RATE:
                if gc.getGame().isOption(GameOptionTypes.GAMEOPTION_NO_MORE_VARIABLES_HIDDEN):
                    return localText.getText("TXT_KEY_TAX_BAR", (self.getTotalYieldsScore(), self.getTaxTreshold(), gc.getYieldInfo(YieldTypes.YIELD_TRADE_GOODS).getChar(),self.getChanceProb()/10,self.getChanceProb()%10)) `

As comparison, here is the TXT_KEY in XML:
```
<Tag>TXT_KEY_TAX_BAR</Tag>
<English>Yields of goods sold in Europe and Africa (only 10% are taken into account) : %d1/%d2%F3[NEWLINE][NEWLINE]There is a [COLOR_WARNING_TEXT]%d4.%d5%[COLOR_REVERT] chance that His Majesty will raise your taxes on the next turn.</English>
```

**Comment by raystuttgart** [comment]
Ok, I think I have fixed it now.
Please test and then close if it works ok.

**Comment by raystuttgart** [comment]
Ok I tested myself, it does not consider Sales to Natives anymore.

**Comment by raystuttgart** [comment]
By the way, it is calculating **prices**, not amounts.
So if you e.g. sell 100 Tobacco for 6 Gold each that is 600.
Then it will go up by 60 --> So maybe the **text could also be improved**.

**Edit:**
Adjusted German / English texsts for it already.
