### ISSUE TITLE
WTP 4.1: Some thoughts re: Powder Maker's House

### ISSUE THREAD

**Issue by Fuerstbischof** [We-the-People-civ4col-mod/Mod#737]
The way we've introduced how the Charcoaler (PROFESSION_CHARCOAL_BURNER) works in WTP is, well, not the way he does his job. Burning charcoal is not done inside a town but instead outside. This is fairly obvious for all us, but was probably done to add another profession to the Powder Maker's House (BUILDING_FIREWORKERS_HOUSE). I'm raising this question because even the production of gunpowder was not done in a typical house and clearly separated from the other buildings. Does the Fireworker (PROFESSION_FIREWORKER) needs his own building, so that he can do his job, or should we allow him to work in a more military oriented building like the Armoury (BUILDING_ARMORY)?

Out of curiosity, is adding professions to defensive buildings/barracks out of the question?

Nightinggale once raised the question if we should split the city screen. I'm in favour of exploring his proposal.

**Comment by raystuttgart** [comment]
If somebody wants to change the Buildings, Profession and Yields and feels he will get it nicely balanced go along and improve it. I will not work on this again, since I feel it was hard enough to achieve what was already created without changing it again.

Also I don`t always feel changing stuff like 1 year after something was created and massive effort was invested.
Why not suggest changes while the concept is still in work and things can be changed easily ?

There is some compromise in it, yeah I know. But it was made for gameplay, balance and effort.
You will always need to compromise something to get things working ...

But again, feel free to take the effort to completely change it again.

**Comment by Fuerstbischof** [comment]
The charburner would not consume lumber and would thus not rely on the lumberjack, he does that by himself. I'm not even sure if he cuts down entire forests like the lumberjack. He doesn't require entire logs for his work. IMHO he should compete with the lumberjack for forested tiles.

You're quite right, we don't have to go over the top re AI here, we should keep it simple. Thus we might get away with a slightly revised lumberjack as template for the revised charcoal burner. Since I won't work any longer on the text files, I might even do that by myself.

**Comment by Fuerstbischof** [comment]
@raystuttgart
@Nightinggale
The IMHO much more important question is nonetheless, if we already should start thinking about revising the city screen by splitting it.

* Two city screens might allow us to have far larger screen areas for garrison units, unassigned colonists, transports and ships in the harbour. Moving yields to/from ships and transports would be easier.
* I don't know if this is even possible, but we could split the construction menu, i.e. by moving transports and ships to a second construction menu located on the second screen. This would allow us to use the first screen more efficiently, leaving more room for builings etc.
* The three rows of yields are a bit to tiny IMHO and also the absence of tooltips is more severely felt than in 3.01. (#754)
* We have a high level of detail on the economic side of the game while on the military side we have exactly one gun, one cannon and one blade. Adding more military yields will surely not fit the current three rows of yields. 
* Having four rows of yields will OTOH even more restrict the area used by buildings. Splitting buildings across two screens is not easily done, but then the size of buildings can be slighly increased again. Moving non-producing and also military-related buildings to the second city screen would be the least-disrupting change.

**Comment by raystuttgart** [comment]
**@Fuerstbischof** 
We are easily talking about effort of 100 hours to completely redesign City Screen.
Currently I cannot imagine that anybody will have time to do this.

**Comment by MrZorG33** [comment]
@Fuerstbischof could you make a sketch/drawing of the proposed screen?
eventually, someday someone will want to do this and we will already have the concept of the City Screen. By the way, look at the City Screen by melcher kürzer. maybe you like his idea.

**Comment by raystuttgart** [comment]
I think this can be closed.
Discussions for a new Screen will require a long concept thread.
