### ISSUE TITLE
Optimizations (second round)

### ISSUE THREAD

**Issue by devolution79** [We-the-People-civ4col-mod/Mod#744]
TBA

**Comment by raystuttgart** [comment]
Are these also merged to "New Hope"?

**Comment by devolution79** [comment]
Hi ray, this are the result of various ideas and fragment of code that was laying around on my HD. Since we're close to the next release I  suppose that we should wait until we have published that so that we can sufficient testing for this branch rather than risking potential bugs.

**Comment by jo-oe** [comment]
Hi devolution,
I merged your changes here into the coordinate_class branch, that was quite an effort as we both modified the same functions ...
If you don't mind, I would be happy if we could coordinate further work if it touches the same parts of code.

I'd suggest we create a joint branch that could then be merged to the main branch after 4.0
