### ISSUE TITLE
disabling World Builder doesn't work

### ISSUE THREAD

**Issue by MrZorG33** [We-the-People-civ4col-mod/Mod#749]
while setting up a custom game, I disable World Builder.
![image](https://user-images.githubusercontent.com/61798883/220954144-0581a4f0-3695-41e1-8c69-7241838301ca.png)

but at the start of the game, the button "enter the world builder" is still active.
![image](https://user-images.githubusercontent.com/61798883/220954723-5d752bdb-6291-4979-83a2-f7ae154ab6be.png)

**Comment by Nightinggale** [comment]
The feature worked except you managed to enable the cheat backdoor, which is there to test savegames from bug reports. Now that backdoor is removed from release builds.
