### ISSUE TITLE
correct syntax in TXT_KEY_EVENT_PEASANT_WARPREP_1A?

### ISSUE THREAD

**Issue by Fuerstbischof** [We-the-People-civ4col-mod/Mod#751]
The tag TXT_KEY_EVENT_PEASANT_WARPREP_1A uses in its text %s1__player and %s3__player. This is an exception from the rule since usually %s1_player and %s3_player are used. 

WAD or typos?

**Comment by raystuttgart** [comment]
It simply does not matter how you call the variable after the %s1 or %s3.
So the additional underscore has absolutely no impact.

The only things that matter:
% --> it tells the logic that it shall put a variable in there
s --> it tells the logic that it should display it as string (and not e.g. an icon)
3 --> it tells the logic to use the 3rd variable that it has been given by the DLL.

Everything else after that really does not matter at all.
