### ISSUE TITLE
tag for city screen is "missing"

### ISSUE THREAD

**Issue by Fuerstbischof** [We-the-People-civ4col-mod/Mod#752]
City storage as shown on the top of the colony screen uses the tag of the header of its pedia entry in the concepts section: TXT_KEY_CONCEPT_NEW_STORAGE.

Having two separate tags would be nice so that the text used on the colony screen could be coloured by using [COLOR_HIGHLIGHT_TEXT].

**Comment by raystuttgart** [comment]
Done.
(Including highlighting.)
