### ISSUE TITLE
turns not fixed for later start dates

### ISSUE THREAD

**Issue by Fuerstbischof** [We-the-People-civ4col-mod/Mod#755]
Although CIV4EraInfos.xml specifies the exact turns for later game start dates these are ignored.

<Type>ERA_DISCOVERY</Type>
<iGameTurn>-1</iGameTurn>

<Type>ERA_EXPANSION</Type>
<iGameTurn>108</iGameTurn>

<Type>ERA_COLONIAL</Type>
<iGameTurn>208</iGameTurn>

<Type>ERA_INDEPENDENCE</Type>
<iGameTurn>-1</iGameTurn>

As long as we have yearly turns this should work fine, but for faster/slower games it seems to be better if we actually start using years as start dates.

**Comment by raystuttgart** [comment]
For faster / slower games these are **scaled with game speed**.
So there is absolutely no issue here.
