### ISSUE TITLE
quick quest completion

### ISSUE THREAD

**Issue by MrZorG33** [We-the-People-civ4col-mod/Mod#774]
in the new test game, I noticed a very fast completion of the quest from my king.
![image](https://user-images.githubusercontent.com/61798883/225398964-5d13d33e-46e4-41c3-ad90-57f83f093478.png)

in the previous test game, I noticed the same fast completion of the Slave Barque quest.
I assume that such quests "broke" at some point. I think they all need to be checked.

**Comment by AemonAlCaar** [comment]
Have you checked to see if the ships were there before?

So:
- Computer builds 6 ships
- Player builds 1 ship -> quest starts
- Computer already has the ships -> Quest won


As a human player I know this with the quest of the west route. You have already discovered it, but the quest has not started yet. As soon as it starts, you win the quest (ok, next turn).

**Comment by MrZorG33** [comment]
yes, I know about the quest "the way to India". however, here is a quest about 6 naval ships. given that I'm ahead of everyone else by about 300 points, they can't have that many warships. although I haven't checked. but I think it's a bug. I'll try to test the next quick quest by loading the auto-save (I can't right now).

**Comment by raystuttgart** [comment]
It is possible that this Quest is actually won by King ... :

**Comment by MrZorG33** [comment]
I didn't find this during my last translation test. I really think it's a coincidence. in any case, it will be possible to reopen.
