### ISSUE TITLE
Proposal: kill players with no cities

### ISSUE THREAD

**Issue by Nightinggale** [We-the-People-civ4col-mod/Mod#776]
It can be too hard to kill a player. For instance in a savegame I just looked at, the last ship of a player with no cities is hiding in a colony owned by another European AI.

I propose that a player should die if:

- turn is at least 50
- team has no cities
- team power is less than 5% of whoever they are at war with
- special players like the church should obviously be unaffected by this
- perhaps something with a counter of turns since the player last owned a city

When killing a player this way, let the units switch ownership to nearest non-hostile player or if none are nearby, just kill them.

This is ultimately a design decision so we should agree on how we deal with the situation of the player having to chase one last ship, which then tries to not be found. It's actually kind of important as letting the last ship/unit hide in native settlements makes it impossible to become the only European left.

**Comment by MrZorG33** [comment]
the offer is good, since such situations sometimes occur and it is really extremely difficult to chase one ship (especially on large maps). question: what will happen to the FF of the player who is planned to be "killed"?

**Comment by jo-oe** [comment]
I had been working on this issue after discussion in the forums here:
https://forums.civfanatics.com/threads/colonial-ais-are-too-hard-to-kill.681552/

I already implemented a few changes to killing colonial AIs, they will now only survive the loss of their last city if they have at least:
1 transport ship + 1 colonist equipped as settler = able to found a new city
(alternatively they have the money to buy both in Europe)
Also, if they are below a total unit number minimum (increasing over time), they will be removed from the game.
(A player with very few units also has no realistic chance of winning, but a player with a large standing army *and* a settler has a realistic chance of recovering)

Making it easier to kill an AI player was vetoed by ray and nci in the forum thread mentioned above!

Only option I could think of that might be ok with nci and ray would be a game option allowing for a special diplomatic treaty, where an AI offers to completely retreat (= be killed) after suffering an overwhelming defeat (something like < 5 % strenght of opponent etc.).
That should be quite easy to implement and is on my TODO list for 4.1.

@MrZorG33: about the FF - those already become available again on player death. There are open issues with that though, see #770

**Comment by devolution79** [comment]
I agree with the OP. It would definitely be helpful to the AI in the end-game so that it would not have to chase down every last colonists of the opponent. I've often seen this delay the AIs win be 10s of turns (which gives the human player an unfair advantage)

**Comment by raystuttgart** [comment]
Closed as this is a duplicate that @jo-oe had already worked on and improved the logic.
AI Players are now much more easy to kill.
