### ISSUE TITLE
Americas Gigantic — Random. starting nation is always New England

### ISSUE THREAD

**Issue by MrZorG33** [We-the-People-civ4col-mod/Mod#778]
when choosing any leader, it is not the country corresponding to this leader that is chosen, but New England.
_Sorry, my laptop refuses to take screenshots of the game._
![image](https://user-images.githubusercontent.com/61798883/226348206-10ea0c81-c83e-4d8c-bffb-ec18729a6d15.png)

![image](https://user-images.githubusercontent.com/61798883/226348235-7711d284-89f0-42d8-afef-0c6eb37f3362.png)

![image](https://user-images.githubusercontent.com/61798883/226348279-bdf00570-36cd-4aef-b920-0ed83d555dea.png)

**Comment by raystuttgart** [comment]
That is not a bug, that is actually a **game feature / game option** for Custom Games.

It is this here:
GAMEOPTION_LEAD_ANY_CIV

See this file:
CIV4GameOptionInfos.xml

-----

It is currently not visible in the mod.
Normally it is turned off.

But it seems like the Map Creator had activated it.

----

Summary:
This is not a bug but a feature.

**Comment by Nightinggale** [comment]
Why even have settings in the map at all? Just delete all and let it run on defaults.
