### ISSUE TITLE
cannot speed up the construction of the Government Palace

### ISSUE THREAD

**Issue by MrZorG33** [We-the-People-civ4col-mod/Mod#780]
In my test game, I can't speed up the construction of the Government Palace - it requires 50 silver in the colony. I saw this bug in the early test game "Plains", but then it disappeared. and now it has reappeared.

![image](https://user-images.githubusercontent.com/61798883/226441880-ea5ee486-144f-4acc-8725-0e2bc6359d15.png)
[translation.zip](https://github.com/We-the-People-civ4col-mod/Mod/files/11022167/translation.zip)

**Comment by raystuttgart** [comment]
Please check if there is a **Boycott** on **Silver** in **Europe**.

In that case you cannot hurry because Silver cannot be bought from Europe.
(That is a normal part of game logic then and not a bug.)

**Comment by raystuttgart** [comment]
@MrZorG33 
Please check what I had asked for.
Because if I am right we can close this issue.

**Comment by MrZorG33** [comment]
most likely you were right. I can't load that game, but after creating a similar situation with the help of WB, I did not find the problem. thanks for the tip.
