### ISSUE TITLE
units from the transport are not assigned to work

### ISSUE THREAD

**Issue by MrZorG33** [We-the-People-civ4col-mod/Mod#789]
on the colony screen, when you try to assign a unit that is in a transport, to any job, does it remain in the transport? only the landing of a unit in the garrison of the colony and the subsequent assignment to work helps. 2.8 does not have this problem.

**Comment by Nightinggale** [comment]
I'm not sure if or how it worked in 2.8, but I'm fairly certain it works differently now. The main point is that now it works.

**Comment by MrZorG33** [comment]
forgive me my forgetfulness. after someone has added a description to the tiles on the colony screen, units should be placed on the outline intended for workers (or as close to it as possible) when dragging. I forgot about it, but now I remember. it's not a bug)
