### ISSUE TITLE
The native culture radius is "strange"... "square" instead of cross... 

### ISSUE THREAD

**Issue by abmpicoli** [We-the-People-civ4col-mod/Mod#79]
The culture radius for native villages is too strange... I don't think this is an intended feature...
Take this example: 
![image](https://user-images.githubusercontent.com/1733170/45721986-c62f5980-bb80-11e8-881b-02842f940615.png)
Why would the native have this expansion as a "square", with two gaps (for apparently no good reason)?

**Comment by ErikSandbraaten** [comment]
CvPlayerAI::AI_createNativeCities() Creates the initial native cities and then assigns ownership to nearby plots based on a random factor. This probably explains the seemingly irregular shape of their culture.

**Comment by abmpicoli** [comment]
Hm... i see... it "sort of" makes sense... https://github.com/We-the-People-civ4col-mod/Mod/blob/32a8d1a5360b9071d7898ece97b69d053e9c23c0/Project%20Files/DLLSources/CvPlayerAI.cpp#L9931-L10026 ... Except that the algorithm prioritizes tiles in the lower left corner for tile expansion:

* The interation is ordered by plot index, so it will always go from plot 0,0 0,1 0,2... until the top right...

* All neighbors are considered for tile expansion, so the NW, SE,SW and NE tiles are considered ... they shouldn't, to make growth become more like the cultural radius...

In python I could simply make an array with a randomized sequence between all available plots, making plot interaction happen in a scattered pattern. That is, start with an array like [0,1,2,3,....mapsize-1], shuffle it, so it gets, like [1401,724,1,404...] randomized values... 

In c++ this is a little more annoying to do, since there isn't a function ready for that. This could be stored at the Civ globals, and then be used at plot interaction ... including at this routine... 

Also, plots that are next to more city plots should be more likely to become an extra plot, while plots that have less city plot neighbours should be less likely...

**Comment by raystuttgart** [comment]
Is this really a bug ?
Is it really worth investing time and effort?

I never heard anybody complaining about this.

Actually I almost consider it a "feature" that Native culture radius is not just the plain same everwhere but has some diversity ...
If it would always be "the cross" it would look boring.

I really suggest to leave it as it is and close the issue.
But if you really want to change this, I also don't mind if somebody continues working on this.

But we also don't need to be holier than the Pope. :)

**Comment by Nightinggale** [comment]
I never fully understood this issue as in what is the problem? In fact if we are to do anything about this, then it would be that instead of gaining a circle for each culture level, we should add one more plot, meaning we don't get huge jumps in the spread and we get it uneven. Ideally culture should spread faster on plots with roads etc.

However I don't think it's worth the time. It's way too minor for the gameplay compared to some of the other tasks.

**Comment by raystuttgart** [comment]
I don't even think that the current solution for "Native culture radius" needs to / should be changed.
I actually like that it looks a bit "strange" and thus more "natural" with a bit of variety.

**Comment by raystuttgart** [comment]
I will close this, because there really is no issue.
Nobody will work on this anyways.
