### ISSUE TITLE
Scout fails to explore ruins

### ISSUE THREAD

**Issue by andushow** [We-the-People-civ4col-mod/Mod#794]
Col WTP mod 3.0.1
There is a (random?) event to move a scout within 20 turns over a ruins tile, which I did, the scout is there in “sentry” mode waiting for the 20 turns to elapse.
On the 20th turn, however, I don't collect the reward, but get a game notification in the event log saying “Unfortunately, your expedition can no longer explore the ruins”; What am I doing wrong ?
Thanks

**Comment by raystuttgart** [comment]
I would need a **Screenshot**, but I think it only works if those Ruins are inside your Cultural Radius.
(Meaning it is possible that it requires to actually own the Plot by either a City or a Fort or something like that.)

As I said, with just text, it is hard to understand what is actually going on.

**Comment by andushow** [comment]
![Clipboard01](https://user-images.githubusercontent.com/14202199/230320918-4849f09d-aaa8-4804-afa5-cb9bba36cfd9.png)
Scout is on the correct tile, which is *not* within my cultural borders (ruins belong to a former destroyed Swedish colony)

**Comment by raystuttgart** [comment]
If it is not in your cultural borders the Event will not work --> Found a City or a Fort.
(Also it must be a seasoned Scout to my knowledge.)

**See here:**
I just tested and it works flawlessly.
(Fortify was not necessary.)

![Civ4ScreenShot0011](https://user-images.githubusercontent.com/59391125/230322272-abfc4e92-d43e-4ee8-969e-0660e9e9acba.JPG)
![Civ4ScreenShot0010](https://user-images.githubusercontent.com/59391125/230322282-4c361df7-9ff5-45c9-939e-ffd9d91679dc.JPG)

**Comment by andushow** [comment]
it's a seasoned scout, I'll try to build a fort. Thanks for the tip

**Comment by raystuttgart** [comment]
It is also possible that there was an issue in 3.0.1
But that version is outdated by 2 years.

We are short before publishing 4.0
And in 4.0 the event definitely works -> since I just tested it there.

**Comment by andushow** [comment]
Yeah, I fully agree to the mechanics “… it should not even be triggered if it is not in your cultural borders.”. Building a fort takes 16 turns for a Hardy Pioneer, so you cannot basically fulfill the quest within 20 turns **IF** the ruins are not within your cultural borders (that happened in this case).

**Comment by raystuttgart** [comment]
It is not triggered if it is not triggered if you are not the owner of the plot. (Just checked the Trigger XML and logic.)
But there may be situations where the Plot technically still belongs to you for a turn - e.g. when you lose a City.

--> The Quest Start may be triggered then (because for that 1 turn the plot is still yours)
--> But when you come to the Plot it does not belong to you anymore.

The Python Event System is a very simple System for scripting.
It may not always be working perfectly because it simply cannto consider all possible gameplay scenarios.
