### ISSUE TITLE
Crash when capturing a transport and the cargo inside the transport

### ISSUE THREAD

**Issue by Nightinggale** [We-the-People-civ4col-mod/Mod#797]
When capturing a ship using CvUnit::updateCombat, the capture code looks like:

```cpp
				if ( !GET_PLAYER(getOwnerINLINE()).isNative() && !GC.getGameINLINE().isBarbarianPlayer(getOwnerINLINE()) && !GC.getGameINLINE().isChurchPlayer(getOwnerINLINE()))
				{
					pDefender->setCapturingPlayer(getOwnerINLINE());
					CLLNode<IDInfo>* pUnitNode = pPlot->headUnitNode();
					while (pUnitNode != NULL)
					{
						CvUnit* pLoopUnit = ::getUnit(pUnitNode->m_data);
						pUnitNode = pPlot->nextUnitNode(pUnitNode);

						if (pLoopUnit != pDefender)
						{
							if (isEnemy(pLoopUnit->getCombatTeam(getTeam(), pPlot), pPlot))
							{
								pLoopUnit->setCapturingPlayer(getOwnerINLINE());
								pLoopUnit->kill(false);
```

The problem is that capturing the pLoopUnit will call kill on it and kill will delete the cargo. However pUnitNode points to the first cargo and during the next iteration that will result in pLoopUnit becoming NULL as the information about the cargo is gone.

Another related problem is that there is no single capture code. Instead it is introduce wherever and apparently we have at least 3 different capture codes, each mixed in with other code.

We should make a dedicated CvUnit::capture(PlayerTypes eNewOwner) to deal with capturing units. In case of a transport, it should call itself recursively. The last two lines should be kill followed by returning a pointer to the cloned unit. This way the old unit will exist for the duration of the function call and cargo will have kill calls prior to the transport they are in.

Attaching the same savegame as in #796 as it also reveals this issue on top of the other bug report.
[save.zip](https://github.com/We-the-People-civ4col-mod/Mod/files/11178083/save.zip)

**Comment by raystuttgart** [comment]
@Nightinggale 
Isn`t this now also already closed.
I am quite convinced it is.

**Comment by Nightinggale** [comment]
I fixed the crash, but the code to capture units is still quite unstable. Maybe we should make a new ticket for that.

**Comment by jo-oe** [comment]
What do you mean by unstable?
Not completely tested for edge cases? - yes
Convoluted and complicated? - yes, but I think it has been improved a bit
Crashing? - Since the last changes you and I made, I think there were no more crashes.

**Comment by Nightinggale** [comment]
I mean capturing units with cargo might delete the cargo.

**Comment by jo-oe** [comment]
Yeah, that is something the code is not prepared for, because the list of units on a plot does not actually understand the transport hierarchy.
But that would actually be a new feature, probably requiring to do the whole unit capture stuff in 2 passes, one for transport units and another for the transported units.

**Comment by jo-oe** [comment]
something like:
`vector<CvUnit *> CvUnit::getTransportedUnits()`
would probably be helpful
