### ISSUE TITLE
These 3 Colopedia Screens should also get 2 Columns (like almost all others)

### ISSUE THREAD

**Issue by raystuttgart** [We-the-People-civ4col-mod/Mod#802]
It is about these 3 Screens:

1) Goods and Materials
2) Terrain Features
3) Improvements

Almost all other Colopedia pages with long lists of entries have 2 columns.
These 3 Colopedia pages however do not, but would look much if they also had.

![Civ4ScreenShot0000](https://user-images.githubusercontent.com/59391125/230758167-6fda12ba-4283-4197-8a2c-2c5846bb0091.JPG)
![Civ4ScreenShot0001](https://user-images.githubusercontent.com/59391125/230758170-82e44dce-2dd2-419e-8ca0-225cd4345d42.JPG)
![Civ4ScreenShot0002](https://user-images.githubusercontent.com/59391125/230758172-a5065d75-799a-4e53-b561-21aa3c91f33d.JPG)

**Comment by Nightinggale** [comment]
I would argue that we should have some sort of shared code, which can set the columns. The number of columns can then be based on screen resolution. Perhaps we can increase font size on high resolution as well.

**Comment by raystuttgart** [comment]
Sounds even better. 👍

**Comment by raystuttgart** [comment]
I took care of this now.
Will thus close the ticket.
