### ISSUE TITLE
barracks overflow prohibits unloading of transports

### ISSUE THREAD

**Issue by MrZorG33** [We-the-People-civ4col-mod/Mod#803]
The screenshot shows that there is no "unload" button. according to the player, the barracks were overcrowded. as soon as he withdrew the extra troops, it became possible to unload the cargo. 
![image](https://user-images.githubusercontent.com/61798883/230846609-710fda13-08c1-4319-a771-ba8141064e35.png)

save provided by another player on the forum.
[mdr.zip](https://github.com/We-the-People-civ4col-mod/Mod/files/11188438/mdr.zip)

**Comment by raystuttgart** [comment]
that is already fixed.
