### ISSUE TITLE
problem with graphics of Russian dragoons

### ISSUE THREAD

**Issue by MrZorG33** [We-the-People-civ4col-mod/Mod#805]
during the attack, the head of the Russian dragoons increases, as in the screenshot. this problem is only with these units. 
![image](https://user-images.githubusercontent.com/61798883/230888016-d02d3e82-9acc-44de-9438-9c2dc7c2a8d6.png)

@Schmiddie1979 , could you look into the reason?

**Comment by raystuttgart** [comment]
This problem was already reported a while ago.

**Comment by Schmiddie1979** [comment]
@MrZorG33 

I cannot reproduce the issue. Could you please describe a bit more what you did - have you attacked or have you been attacked by the enemy?

Which unit is it exactly? Dragoons or experienced dragoons?

**Comment by Schmiddie1979** [comment]
Ok, I maybe found a quick work around for the issue. Please check and report if you get the issue again or not.

**Comment by MrZorG33** [comment]
I couldn't reproduce this problem after the fix. if it reappears in the future, we will open it again.

**Comment by MrZorG33** [comment]
@Schmiddie1979 Well, the problem has appeared again.
While attacking with the Royal Dragoons Line Infantry, I saw two large heads 
[test2.zip](https://github.com/We-the-People-civ4col-mod/Mod/files/12829779/test2.zip)

_cut off a hydra's head and two will grow in its place_ :D

You can try to reproduce the problem by loading the attached game save.
![image](https://github.com/We-the-People-civ4col-mod/Mod/assets/61798883/056a8b2f-3efb-4710-b238-689816ab1ee2)

**Comment by Schmiddie1979** [comment]
Thanks for reporting. Bug confirmed. I assume I know what causes this bug. I will look into it and analyze how it can be fixed.

**Comment by Schmiddie1979** [comment]
Ok, fixed. Please test again. I have uploaded it to develop.

**Comment by MrZorG33** [comment]
checked - great job! now everything is all right)
