### ISSUE TITLE
Founding Father Giovanni da Verrazzano discovers the Pacific automatically

### ISSUE THREAD

**Issue by Nightinggale** [We-the-People-civ4col-mod/Mod#806]
Due to revealing water goodies, Giovanni da Verrazzano will trigger discovery of the Pacific even with no discovered route across the map.

**Comment by MrZorG33** [comment]
as I said in discord - ship wrecks open a map around them for one square, so you can "open the way to asia" this way. this is not a technical error, but rather a logical one. This can be fixed by not allowing ship wrecks to be placed closer than two tiles to the Europe transition tiles.

**Comment by raystuttgart** [comment]
Ok, I understood the problem now ... 
This "intended feature" of **Revealing Water Goodies** triggers the Pacific Quest to succeed.

Maybe the "Reveal Goodies" should then simply be removed for Giovanni da Verrazzano.

**Comment by raystuttgart** [comment]
**Edit:**
I removed this from his Trait.

The bug should thus be fixed.

**Comment by MrZorG33** [comment]
guys, this is not a solution to the problem. maybe then we will remove what the other FFs give?

@Nightinggale, is it possible to do as I suggested?

**Comment by Nightinggale** [comment]
> is it possible to do as I suggested?

I will assume so, but I'm not entirely sure I like that idea either. I think the best solution would be to trigger on having a unit on a Europe plot. That way no goodie, native map reveal or similar will trigger this. You will have to send a ship through.

**Comment by MrZorG33** [comment]
yes, it would be logical. can you revert Ray's deletion and subsequently do as you wrote?
**upd.** I'm assuming this might work in the same way as the suggestion to sail to Europe when prompts are enabled. am i thinking right?

**Comment by Nightinggale** [comment]
I'm thinking we have 4 Europe types and the event can trigger depending on which Europe type we have on a plot. If unit on a plot with selected Europe type, then trigger. It might even be possible to make Western starting players trigger by reaching the east Europe access. Something to consider.

I will take a look at this once I'm done with my current task.

**Comment by MrZorG33** [comment]
> _It might even be possible to make Western starting players trigger by reaching the east Europe access._

hmm .. this will not be entirely correct based on the text of the event. maybe some new event is very suitable for such players. like traveling around the world.

**Comment by raystuttgart** [comment]
@Nightinggale 
Your solution to trigger it only if a Unit is on a Plot with "Europe West", sounds really good.
Did not think about that idea myself. :)

Then my change that removed the "Reveal" from the FF could be reverted.

**Comment by Nightinggale** [comment]
I figured out what the correct trigger conditions should be for finding the Pacific:

- Unit enters plot with Europe access
- plot is in the west (x < map width/x)
- player starting point is in the east (x > map width/2)

Now to figure out how to code this without hurting the late game performance for moving units.

**Comment by raystuttgart** [comment]
I now implemented a proper fix.
(Verazzano also has his trait back.)
