### ISSUE TITLE
create a description of production chains for goods and resources

### ISSUE THREAD

**Issue by MrZorG33** [We-the-People-civ4col-mod/Mod#809]
I'm sorry, I didn't know how to phrase it in English)

so, looking through the Discord, I noticed that people do not know what resource is needed to produce a certain product. I suggest adding this information.
for example: for the production of ceramics, peat and clay are needed. add information on the ceramics page, what resources are needed for its production. you can also add similar information for buildings.

in my opinion, this will speed up the entry of new players into the mod.

**Comment by Nightinggale** [comment]
Yeah I want to expand on colopedia to list sources of yields and have another list for what the yield can be used for (input to another yield, buildings etc). Each list item should be a link so people can click around and follow chains that way. The main problem with this approach is that somebody will need to spend time coding quite a bit in the pedia files.

**Comment by MrZorG33** [comment]
done
https://github.com/We-the-People-civ4col-mod/Mod/commit/6b75dc0985790d64cb99f9d169be29422e3e9b9a
https://github.com/We-the-People-civ4col-mod/Mod/commit/ea6c130f839c513b645d77c62ae8aafd90552209
