### ISSUE TITLE
Problem when loading Save-games

### ISSUE THREAD

**Issue by KralPalafox** [We-the-People-civ4col-mod/Mod#815]
Not ever but very often, when I try to load a savegame the game crushes.

Has anyone an idea what to do?

**Comment by raystuttgart** [comment]
And when you load a second time it works?
Or is the savegame broken ? --> If yes, send it to us please.

Also, which version do you play?

**Comment by KralPalafox** [comment]
Können wir in Deutsch schreiben? Sonst versuche ich es weiter auf englisch.

**Comment by raystuttgart** [comment]
Ja, kannst du zur Not.
Allerdings kann es sein, dass ein anderes Teammitglied dann nicht helfen kann.
Wenn du Deutsch schreibst reduzierst du die Leute die dir helfen könne auf ein Drittel.

**Comment by KralPalafox** [comment]
Ja, beim 2.Mal läuft es
Interessant: auf meinem älteren Laptop habe ich das Problem bei JEDEM Laden aus dem Spiel heraus - beim Neustart und laden des Spiels habe ich kein Problem.
Auf meinem Rechner passiert es unregelmäßig.
Die Spielstände scheinen intakt zu sein

**Comment by raystuttgart** [comment]
Ok, dann ist das eher ein Performance Problem, weil die Saves etwas groß sind.
Wenn du neu startest ist der Cache Leer, daher funktioniert es dann meistens auch.
Da können wir wenig machen, weil das Savegame ja anscheinend intakt ist.

Dennoch:
Welche Version?

**Comment by KralPalafox** [comment]
Ah okay - I'll try it
With my older Laptop (around 5-7 Years old) every load from within the game crushes - loading after restarting is no problem

On my newer and better desktop/Tower every 2. to 3. loading from within the game crushes - but the savegames are okay and work with another try.
_________________

Fresh reinstalled

**Comment by KralPalafox** [comment]
Gerätename	DESKTOP-D959KOB
Prozessor	Intel(R) Core(TM) i7-9700 CPU @ 3.00GHz   3.00 GHz
Installierter RAM	16,0 GB (15,8 GB verwendbar)

Systemtyp	64-Bit-Betriebssystem, x64-basierter Prozessor
Stift- und Toucheingabe	Für diese Anzeige ist keine Stift- oder Toucheingabe verfügbar.

Edition	Windows 11 Pro
Version	22H2
Installiert am	‎17.‎02.‎2023
Betriebssystembuild	22621.1555

Leistung	Windows Feature Experience Pack 1000.22640.1000.0

**Comment by raystuttgart** [comment]
Nein, welche Version der Mod ???

3.0.1 ?
ODER
4.0.1 ?

**Comment by KralPalafox** [comment]
You mean, to less ram?
wtp.3.0.1

**Comment by KralPalafox** [comment]
4.0.1 ?
Hast du nen Link?
und muss ich den alten erst deinstallieren?

**Comment by raystuttgart** [comment]
Then please get **4.0.1** which we published last week. ;)
We have implemented e.g. Multi-Threading for several CPUs and also many other performance improvements.

**Comment by KralPalafox** [comment]
oh sounds nice

**Comment by raystuttgart** [comment]
Schaust du nicht auch ab und zu ins Forum?
https://forums.civfanatics.com/threads/wtp-4-0-1-published-community-feedback.683126/

Oder mal auf Discord vorbei?
https://discord.com/channels/788850075673690112/788850075673690115

**Comment by KralPalafox** [comment]
ich bekenne mich schuldig :-/

**Comment by raystuttgart** [comment]
Ok, versuch es vielleicht mal mit dem neuen Release.
Es lohnt sich.

**Comment by KralPalafox** [comment]
Vielen Dank raystuttgart,
Ich lade es gerade herunter

**Comment by KralPalafox** [comment]
Now it seems to work - thanks a lot

**Comment by jo-oe** [comment]
This was probably fixed here:
https://github.com/We-the-People-civ4col-mod/Mod/commit/ffb3fa0ce8bc3146fdf85d7bf5f58363074b7786
As the OP reports no more problems, I'll close this issue.
