### ISSUE TITLE
Bucanneer on ship will capture all ships

### ISSUE THREAD

**Issue by jo-oe** [We-the-People-civ4col-mod/Mod#816]
Another edge case probably caused by the changes in updateCombat/kill/jumpTo and capture logic.
This is just we don't forget about it.
According to a discord post, the reproduction steps are (didn't test it myself ...):
- Load a bucanneer onto a transport ship
- sail the ship on the same plot as another players ship

The fix would probably have to do a some check for isHiddenNationality==true and isValidDomainForAction==false somewhere and abort the capture in that case.

**Comment by jo-oe** [comment]
Could not reproduce this. If someone experiences the same problem, please post here, otherwise we can close this issue.

**Comment by MrZorG33** [comment]
I'll check, I have one idea...

**Comment by MrZorG33** [comment]
4.0.2
I cannot confirm the capture of ships.
I confirm the capture of units that are on board the ship of another European power. however, for some reason it was not possible to capture a special unit (mounted conquistador).
[test.zip](https://github.com/We-the-People-civ4col-mod/Mod/files/11219180/test.zip)

**Comment by jo-oe** [comment]
I think you can only capture units from ships that would also be captured on land. ("civilian units")
For immersion you could imagine that the conquistadors would rather fight to death than be captured from a transport ship...

**Comment by MrZorG33** [comment]
I consider this a bug. there is no attack, just two merchant ships pass by each other.

**Comment by devolution79** [comment]
This seems very similar to a bug I fixed years ago. I don't think combat is triggered since the ships can coexist (since they are not at war) but something funky happens when the buccaneer is trying to share a plot with the other units and thus there is an "instant win" with no combat.

**Comment by jo-oe** [comment]
Can you explain the exact conditions to trigger this bug? I was not able to reproduce.

**Comment by jo-oe** [comment]
Ah, you were probably testing with 4.0.2, right? I think some of my fixes were not pulled over to master, but this should be fixed in develop :)

**Comment by MrZorG33** [comment]
@jo-oe yes, this bug is missing in develop. Then I think the topic is not relevant and let's close it.

**Comment by jo-oe** [comment]
Fixed in develop
