### ISSUE TITLE
Install problems

### ISSUE THREAD

**Issue by dixiechow** [We-the-People-civ4col-mod/Mod#819]
I just downloaded the WTP 4.0.2.  Yesterday I had downloaded the 4.0.1 and could not get it to work getting several error messages:

CoreDLL.dll not loaded missing in assets - not installed in game dir.
"There are more siblings than memory allocated for them in CvXMMLLoad utility....(it goes on and on)

I was thrilled that the 4.0.2 a set up feature but when I went to use it I got this message:

Finishing installation of We The People

ERROR: game install dir not found
You need to install mods in the Mods folder inside the game install folder
Unlike what some people say, installing mods in My Documents will eventually result in weird bugs

The Mod IS installed in the Mods folder in the game NOT in the Mods folder in My Documents.

Any help is greatly appreciated.

**Comment by raystuttgart** [comment]
Please show a screenshots of the "/Assets" folder of the mod.

**Comment by dixiechow** [comment]
Here's my screenshot:
![image](https://user-images.githubusercontent.com/130178622/231826275-c6c94251-e9eb-412c-8067-632d23d55b03.png)
Did I do this right?

**Comment by Nightinggale** [comment]
You are missing a folder. You should make ONE folder inside Mods and put all the files/folders from the mod inside it, like
Mods/WeThePeople/Assets instead of Mods/Assets

Once you do that, run setup again and it should find the game install dir and work as intended.

**Comment by dixiechow** [comment]
Is this what you mean?
![image](https://user-images.githubusercontent.com/130178622/231834824-dfe57d2f-774e-4bbb-93e6-523fd2dee9f2.png)

**Comment by raystuttgart** [comment]
Call the folder of for WTP please just "WTP". ;)
(Or something else that is short.)

Game root folder > Mods > **WTP** > content of the mod (including /Assets)

But otherwise yes. 👍

**Comment by dixiechow** [comment]
I did get my WTP up and running.  Thank you for your help.  However, after I play for 10 min or so it crashes.  I've started several games and they have all crashed.  If you can help me with this I would greatly appreciate it.

**Comment by dixiechow** [comment]
Just checked my emails so you may know this already.  I did rename the Mod
to "WTP".

**Comment by raystuttgart** [comment]
If it is still crashing please provide savegames. 👍 
But at least it is running now for you.

**Comment by Nightinggale** [comment]
If you are using the steam version, make sure you follow [the steam specific guide](https://forums.civfanatics.com/threads/important-for-all-steam-users-follow-these-instructions-to-play-wtp-without-bugs.674675/). I realized today that we forgot to add that detail to the install guide included in the download.

**Comment by dixiechow** [comment]
Thank you.  I switched to the Original Release Version in Steam.  Also here is a copy of a saved game.  It is the only WTP saved game I found although there should be more because I started a few games only to have them crash.  Here again I hope I did this right:

**Comment by dixiechow** [comment]
Maybe now?  Apparently I don't know how to provide you with a copy of a saved game.  I used copy and paste.  I used drag and drop but I don't see anything here.

**Comment by dixiechow** [comment]
It's working and I want to thank both of you for your help as it is much appreciated.  This mod is awesome and a bit overwhelming!

**Comment by raystuttgart** [comment]
Ok great that it is working now.
