### ISSUE TITLE
[develop] Build (plastered/simple) road to feature does not work

### ISSUE THREAD

**Issue by jo-oe** [We-the-People-civ4col-mod/Mod#823]
I tried to implement this feature last week, but unfortunately the pioneers will incorrectly still build the highest level of road.
I suppose there is a finish check returning the wrong value if there is still a route type to be built.
I'd suggest debugging the code from a breakpoint in the CvSelectionGroup::startMission() function.

(Unfortunately I'm unable to do this myself as I cannot debug Windows applications on my system.)

**Comment by MrZorG33** [comment]
the main branch of this issue in #427
