### ISSUE TITLE
colonist does not collect resources on the mangroves tile on LR

### ISSUE THREAD

**Issue by MrZorG33** [We-the-People-civ4col-mod/Mod#824]
mangroves sometimes appear on LR tiles.
![image](https://user-images.githubusercontent.com/61798883/232398085-50f20d92-a28e-4cd4-9916-38f4b0df2391.png)

however, the colonist cannot work on this tile as either a fisherman or a lumberjack.
![image](https://user-images.githubusercontent.com/61798883/232398100-a31c3092-5ca7-4033-b261-e6c51551c8e0.png)

was it intended (the pioneer can still cut down mangroves and then the colonist can be assigned to this tile as a fisherman) or is there a mistake?

**Comment by raystuttgart** [comment]
It was not necessarily intended like that. :)
But still I would say that it behaves immersive and correct.

------

Nobody would be cutting **Lumber** in the middle of a Large River.
And for proper Fishing you need to remove the obstacle to get to the Fish.

------

Mangroves in "Large Rivers" are an obstacle to be removed.
(I.e. the player will collect Wood from that.)

--------

So I would say it is fine like this for gameplay.

Technically we have these 3 alternatives

1) Allow Woodcutting on Large Rivers (which is currently not allowed by the Profession)
2) Change the Balancing so no more Mangroves on Large Rivers
3) Leave everything as it is: Mangroves on Large Rivers are just an obstacle to be removed for Lumber

**Comment by MrZorG33** [comment]
I like the third option. if by the end of the day no one else writes about another option, I suggest leaving it as it is.

**Comment by raystuttgart** [comment]
Ok, then let us close this, since there is nothing todo unless somebody complains - in which case we could open again.
I also like the current way best. It is most immersive.
