### ISSUE TITLE
Change production on city plot

### ISSUE THREAD

**Issue by Nightinggale** [We-the-People-civ4col-mod/Mod#83]
Medieval Conquest has an invisible button on the colony plot in the colony screen. If you click it, you can select which yield to produce in addition to food. The code and/or concept can be copied without too much hassle.

**Comment by abmpicoli** [comment]
I like it. Specially for those tiles that have, for example , hemp : if you build the city over it, you get tobacco. Total nonsense...

**Comment by ErikSandbraaten** [comment]
While I like this proposal, I have always secretly wished that the city plot would only produce a small amount of food to limit the effect of ICS.

**Comment by Nightinggale** [comment]
This proposal is about control of which yield to produce. The amount to produce of each is handled in a different function and should be a topic for a different ticket.

Since 4/4 likes this idea, I will implement it in the near future.

**Comment by abmpicoli** [comment]
This will change the save structure, right? This need to be milestone 2.8 .
