### ISSUE TITLE
Achievements regarding production of XY amount of goods do not work. 

### ISSUE THREAD

**Issue by Schmiddie1979** [We-the-People-civ4col-mod/Mod#834]
I created an achievment for the production of goods (similar to the production of bells). But it will not be triggered. Maybe the logic does not work for goods?

![image](https://user-images.githubusercontent.com/32595781/233725012-2afce01f-0056-4e03-a799-4e9c0941c9a0.png)

**Comment by raystuttgart** [comment]
@Schmiddie1979 
I think you misunderstand the logic.
It is not "produced and stored", it is "produced per turn".
So if you do it like this your Cities would need to produce 201 Blades per turn.

**Comment by Schmiddie1979** [comment]
ups, good to know!
