### ISSUE TITLE
"slave overseer" promotion does not work correctly

### ISSUE THREAD

**Issue by MrZorG33** [We-the-People-civ4col-mod/Mod#842]
4.0.2
if a unit that is garrisoned in a colony is given a "slave overseer" promotion, then the slave production bonus is not displayed and does not work. 
![image](https://user-images.githubusercontent.com/61798883/235086520-b02d4be3-5016-4065-9c5b-124b2e658e0d.png)
![image](https://user-images.githubusercontent.com/61798883/235086541-4cf043ba-f904-4d79-b795-347ea71e1ca2.png)
![image](https://user-images.githubusercontent.com/61798883/235086558-9bf7cc0d-f2a3-496f-a537-81de033726ab.png)

however, if a unit that already has such a promotion is introduced into the colony, then the bonus will work (the bonus of both units is summed up correctly).
![image](https://user-images.githubusercontent.com/61798883/235086609-7b90dfcd-5271-4b8c-830c-9d27483936e7.png)
![image](https://user-images.githubusercontent.com/61798883/235086637-d10ae64b-baa8-4999-850a-b98c091a7e24.png)
![image](https://user-images.githubusercontent.com/61798883/235086674-3ab6c3a8-1c0d-41f3-99ae-ed1db6915bde.png)

[bug_slave_overseer.zip](https://github.com/We-the-People-civ4col-mod/Mod/files/11351232/bug_slave_overseer.zip)

**Comment by raystuttgart** [comment]
@MrZorG33 
**Native Slave** has no Bonus Modifier on Food. 
Thus the Slave Production Modifier will also not work for Food.

The Slave Production Modifier is ALWAYS just applied if the Unit already has a Bonus Modifer.
This has already been discussed several times in the form.

**Comment by MrZorG33** [comment]
@raystuttgart Ray, read again what it's about and look at the photo.

**Comment by raystuttgart** [comment]
I already fixed it. ;)
It was related to the caching that was later introduced.
Will commit now.

**Comment by raystuttgart** [comment]
Fixed.
