### ISSUE TITLE
custom game - crash games

### ISSUE THREAD

**Issue by MrZorG33** [We-the-People-civ4col-mod/Mod#846]
when starting a custom game (map size doesn't matter) with any era other than Discovery, the game crashes.
The message was about 4.0.2. I checked for develop. The game crashes in both cases.

**Comment by devolution79** [comment]
Please re-test, should be fixed now

**Comment by MrZorG33** [comment]
I checked - now the game does not crash, but ..
look at the screenshots)))
![image](https://github.com/We-the-People-civ4col-mod/Mod/assets/61798883/c8f8b654-34a7-49b2-9246-594021d92bec)
![image](https://github.com/We-the-People-civ4col-mod/Mod/assets/61798883/f214af91-8e40-48b8-b6d6-113c74eb534d)

**Comment by devolution79** [comment]
I assume this is a start in the independence era?. Never really tried any of those options so it is likely to be completely untested!

**Comment by MrZorG33** [comment]
this is the beginning of any era, except for the Discovery)))
this does not add the rest of the Europeans, but a message is displayed on the screen that they left the New World.

**Comment by jo-oe** [comment]
The other Europeans "leaving the new world" is probably caused by the unit number threshold I introduced in the CvPlayer::kill logic. It has a threshold modified by game turn (=year), so if you start in 1943, it simply kills all players which have only the starting units.

**Comment by MrZorG33** [comment]
@jo-oe I ran the tests again. map size is arbitrary.

the era of "discovery" begins in 1492. players are added correctly. nobody disappears. no duplication of starting units.

the era of "expansion" begins in 1643. players are added correctly. but out of 4 Europeans, 2 for some reason left the new world. duplication of starting units.

the "colonial" era begins in 1793. players are added correctly. but out of 8 Europeans 7 left the new world. multiple duplication of starting units.

the era of "independence" begins in 1793. players are added correctly. but out of 5 Europeans 3 left the new world. multiple duplication of starting units.


before fixing the error from @devolution79, this was not the case.

**Comment by raystuttgart** [comment]
Why are you even starting games in a different era than "discovery"?
This is a feature left from Civ4BTS that makes absolutely no sense in Civ4Col.

**Comment by devolution79** [comment]
I suppose that the setting the the starting era to something other than "discovery" is not really supported by WTP. Perhaps we can remove the selection somehow or make it always set to discovery regardless of what the player selected (and perhaps show a "friendly" reminder to the player in a popup when the game starts or something like that)

**Comment by MrZorG33** [comment]
@raystuttgart just for fun)
Thus, I have found more than one bug in the game.

@devolution79 Can we even block the choice of era to start the game? in my opinion this would be the best option. at least at this stage of development of the mod.

**Comment by MrZorG33** [comment]
in the Russian translation I changed the text to select eras:

expansion - not yet supported
colonial - not yet supported
independence - not yet supported

For the rest of the language, we can do the same thing so that players do not accidentally select these eras and we do not receive error messages.
