### ISSUE TITLE
Indicator if an indian village will ever trade with you again...

### ISSUE THREAD

**Issue by abmpicoli** [We-the-People-civ4col-mod/Mod#85]
The current game doesn't show anywhere if an indian village wants to trade with you again after they reject your haggling. 

Solution suggestion: when you hover over the indian village, it shows (boycott : x turns left). Also, in the main view, place some indicator that they do not want to trade with you).

At the "native info" for the domestic advisor, place beside the good a "X(n)" showing that the native doesn't want to trade with you for "n" turns.

**Comment by abmpicoli** [comment]
Some more info... it seems that the boycott is player x player wise, and not per village. So this could be shown in the diplomatic screen?

**Comment by raystuttgart** [comment]
Yes, the idea was that you angered the complete tribe.
They are simply not completely independent villages considering the game..

But a **visualization in diplomatic screen** and maybe also on **Mouse Over a village of the Nation** (telling the turns they are currently not willing to trade) sounds like a good idea.

I will assign this issue to me and implement it if nobody disagrees.

**Comment by Nightinggale** [comment]
We could also add an icon to the city billboard if there is a trade ban. Somebody posted something about attitude lately (forum thread?) where I responded with the idea to add the attitude faces to the billboard to make it more clear when natives are upset.

There is no reason why we can't do all (help text and billboard) meaning I think it would be fine to go ahead and add it to the help text as well as the diplomacy screen. We can deal with billboards later when we have the needed graphics.

**Comment by raystuttgart** [comment]
This is fixed / improved now.
Displayed in Billboard of Native Villages.
Since the effect is City only, not displayed in Diplomacy.
