### ISSUE TITLE
Missing text for "TXT_KEY_ACHIEVE_RUSSIAN_MISSIONARY"

### ISSUE THREAD

**Issue by lelekov-ag** [We-the-People-civ4col-mod/Mod#851]
When established the mission at the native village, the _subj text appears at the Event log list (also at the popup messages).
Saves attached:
1. One turn before
2. After the _subj message appeared
[2023-05-08_Issue_saves.zip](https://github.com/We-the-People-civ4col-mod/Mod/files/11419930/2023-05-08_Issue_saves.zip)

**Comment by Schmiddie1979** [comment]
Thanks for reporting. Was a bug in the achievement description code. Has been fixed now.
