### ISSUE TITLE
CTD when loading during combat animation

### ISSUE THREAD

**Issue by ArchdukeLiet** [We-the-People-civ4col-mod/Mod#852]
I have a CTD when I attack a unit with a scout, see that my scout dies, and reload while combat animations are ongoing.
In this case it was my scout vs another scout, but I know that it happens against other units as well.
It is not always the case that the CTD occurs.
From the PythonDBG:
SCREEN OFF

PY:OnPreSave
PY:Player 0 Civilization Dutch Colonies Unit Seasoned Scout was killed by Player 35
99 SCREEN TURNED ON

----------

Reaction of Nightinggale at Discord:
_sounds like a bug in the graphics engine in the sense that it doesn't freeze the animation and then continues to read the units to display the combat even after the units have been cleared in order to read new units from the savegame. I fixed a similar crash based on cities not being deleted in memory fast enough so the engine tried to redraw them including plots, which had already been deleted from memory_

----------

I have attached a screenshot of the situation (now scout (location 65, 56) vs native camp) where such an error occurs as well. Attached is also the log. I cannot attach the save, but I have it available on request.
Please note that not at every reload there is a CTD. I estimate that it happens in roughly about 25% of the cases.

--> I have assigned Nightingale (if that is ok with you), as he has experience in fixing a similar crash. 

![CTD when loading during combat](https://github.com/We-the-People-civ4col-mod/Mod/assets/116034090/98b026d0-e946-4fed-a977-fb9a5e5fac1d)

[PythonDbg.log](https://github.com/We-the-People-civ4col-mod/Mod/files/11430279/PythonDbg.log)

**Comment by raystuttgart** [comment]
There is really no chance we can fix this.
Just do not load during animations then.

Closed because there is nothing we can do.
