### ISSUE TITLE
crash due to missing head mission

### ISSUE THREAD

**Issue by Voker57** [We-the-People-civ4col-mod/Mod#858]
[save.zip](https://github.com/We-the-People-civ4col-mod/Mod/files/11522023/save.zip)
To reproduce: choose "automate fishing", wait for save attempt and crash
Version: [16c7286](https://github.com/We-the-People-civ4col-mod/Mod/commit/16c72860c0a5948cee92481a9934415d1bce74e7)

**Comment by Nightinggale** [comment]
This is unrelated to saving. Somehow a selection group wants to continue their mission while they have an empty mission queue. This is turn makes the game read memory, which doesn't exist, which in turn causes a crash.

**Comment by Nightinggale** [comment]
Just received a new savegame for 4.0.2, which crashes in the same line for the same reason.

[AutoSave_AD-1680.zip](https://github.com/We-the-People-civ4col-mod/Mod/files/11678649/AutoSave_AD-1680.zip)

**Comment by raystuttgart** [comment]
If I understood correctly, this can now be closed as it was fixed.
