### ISSUE TITLE
Crash on loading the save

### ISSUE THREAD

**Issue by Voker57** [We-the-People-civ4col-mod/Mod#862]
subj. Version: [771a973](https://github.com/We-the-People-civ4col-mod/Mod/commit/771a973e726b3e1cd431f79f92cea2d76d5c524d)
[save.zip](https://github.com/We-the-People-civ4col-mod/Mod/files/11547544/save.zip)

**Comment by Nightinggale** [comment]
Crashes in the same line as #858 for the same reason.

**Comment by raystuttgart** [comment]
The I suggest we close this as it is a duplicate then.
