### ISSUE TITLE
Construction supplies are not loading in oxcart/wagon train/trek

### ISSUE THREAD

**Issue by dirlewagen** [We-the-People-civ4col-mod/Mod#865]
Construction supplies are not loading in

- [ ] - oxcart / wagon train / trek
- [ ] - smuggling ship / pirate frigate / privateer

Checked all other relevant units

**Comment by raystuttgart** [comment]
Yupp, because it is technically a "Unit".
And those Ships can only load Yields.

Needs to be fixed in DLL.
It is not really difficult to do so though.

**Comment by dirlewagen** [comment]
I see. The phrasing in the thread is "Every transport in the game that can transport Goods can also transport Construction Supplies" so that's why I've made this ticket, as I thought it's a bug and not a tweak in DLL.
You're mentioning wagon trains as one of the reasons for you coming up with this quite good alternative to hurry production, so it'd be great if you can make the change.

**Comment by raystuttgart** [comment]
It is fixed now.
Thanks for reporting.
