### ISSUE TITLE
too much fur

### ISSUE THREAD

**Issue by MrZorG33** [We-the-People-civ4col-mod/Mod#866]
in the mid to late game natives start spamming fur. they offer to buy it or give it as a gift in large quantities. other resources are also sometimes present, but against the background of the amount of fur, this is a "drop in the ocean". Is it possible to somehow influence the variety of goods offered by the natives?

**Comment by IFoundabugg** [comment]
Seriously, this has been an issue for a long time. In mid to late game, I am exporting more fur than every other yield combined. As you say, almost every turn the natives offer fur, and if you refuse they gift it soon after in increasingly large quantities.

**Comment by raystuttgart** [comment]
In the current logic of the "Native Trading DLL Diplo Event" they will offer the Yield they have most.
And yes in many cases this will be fur - because from fur they also get Food which makes a lot of sense for them.

It was the logical choice for me that Natives would trade or gift most what they have most.
But if somebody wants to reprogram the logic to be more varied and chose the Yield traded more randomly it of course can be done.

It is simply like always a matter of having somebody motivated to invest his time and effort ...

**Comment by victorxup** [comment]
Pretty simple solution for this: weighted probability depending on how much of each yield stored in native home city.

I've implemented it locally, can make pull request if you are interested.

**Comment by raystuttgart** [comment]
Sure, create a pull request with some comment and explanation. 👍 
Ideally also reference this issue somehow.
We can then read it and will merge it if it looks good.

**Comment by victorxup** [comment]
I suppose, then I need permission to create upstream branch or otherwise a hint - how to do it without access granted))

**Comment by raystuttgart** [comment]
I thought a Pull Request would not need special permissions ...
But I will ask @Nightinggale 

It is however already pretty late here in Central Europe.
So maybe it will take until tomorrow for an answer.

**Comment by Nightinggale** [comment]
> I thought a Pull Request would not need special permissions ...

The whole idea with pull requests is that they can be made without any permissions or connections to a project. Anybody with a GitHub account can make them, possibly for any project. Permissions will not be needed unless somebody is to make a commit, which should be added without being reviewed prior to being added.

**Comment by MatthewForrester** [comment]
> I suppose, then I need permission to create upstream branch or otherwise a hint - how to do it without access granted)

The GitHub news feed says that you forked this mod to [your own repository](https://github.com/victorxup/Mod), which was the right thing to do, but it's not there any more. Is it possible that you have accidentally deleted it (or somehow set it as private? though they will charge you for that, I think, so hard to do accidentally)? If you have accidentally deleted it, you need to fork this Mod again on GitHub. 

You also need to check whether your local repository (on your PC) knows about GitHub repository. If you open a terminal  (in Linux or Git for Windows) in the directory containing your local repository) ,then you can run `git remote -v` to check this. If it does, you should see this:

```
origin  https://github.com/victorxup/Mod.git (fetch)
origin  https://github.com/victorxup/Mod.git (push)
```

If you don't see that, then you need to tell your local repository about your repository on GitHub. On the command line (in Linux or Git for Windows) `git remote add origin http://github.com/victorxup/Mod.git`.

After you push your changes from your local repo to your GitHub repo, next time you log in to GitHub in a web browser and go `https://github.com/victorxup/Mod.git`, GitHub will ask you if you want to make a pull request to `We-the-People-civ4col-mod/Mod` and will handle everything automatically. You won't need any permissions here to do that.

If you are new to Git, don't give up! It really is horrible to learn at first (that's [why it's called git](https://www.oxfordlearnersdictionaries.com/definition/english/git?q=git)), but once you get it working it seems like magic. People can help you out.

If you know Git and are just having a bad day with it — that is me at least once a week.....

**Comment by victorxup** [comment]
Done.
Thanks for overwhelmingly full instruction)

**Comment by raystuttgart** [comment]
I think this can be closed now.
