### ISSUE TITLE
Fishing boats not able to start building while in fog

### ISSUE THREAD

**Issue by dirlewagen** [We-the-People-civ4col-mod/Mod#868]
![20230613091700_1](https://github.com/We-the-People-civ4col-mod/Mod/assets/131000498/e99ad327-b720-4749-ab68-d132ac252f43)
![20230613091812_1](https://github.com/We-the-People-civ4col-mod/Mod/assets/131000498/25270c80-7535-4068-806a-9def563f52a2)

**Comment by raystuttgart** [comment]
For balancing reasons these improvements are **only** allowed on **Bonus Resoursces**.
I think it had / has nothing to do with the fog that you were / are not allowed to build a water improvement.

So I will close this.
Unless the Plot really had a Bonus Resource - then the issue can be opened again.

**Comment by dirlewagen** [comment]
There are no Bonus Resource on that lake plot or others around it where the option to build is available, so in this case, it's an issue with the fishing boats being able to build where not supposed to.

**Comment by raystuttgart** [comment]
It is related to Fog itself.

It is flagged as 
**bNoImprovement**

Basically this has simply been taken over by "Copy&Paste" from e.g. Storms.
I removed the flag again.

So it will be possible to build on Fog Terrain Feature.
