### ISSUE TITLE
brave lieutenants are not shown in the REF list

### ISSUE THREAD

**Issue by MrZorG33** [We-the-People-civ4col-mod/Mod#876]
while reading the [forum](https://forums.civfanatics.com/threads/we-the-people-bug-reporting.636760/post-16480296), I saw a message from a user that he destroyed all the ground forces of the king, but he does not receive a message about the victory in the WOI. I asked for a save and found that there was at least one royal brave lieutenant left. however, it was not on the REF list.

also, I assume, capable captains will not be displayed in the REF list.

**Comment by raystuttgart** [comment]
**For the Unit of the King:**

It will **only** display the Units that belong to the **REF** (in Europe REF List).
(And ships that returned to Europe to possibly pick up Units there.)

It currently does **not** display any Units that are **already in the colonies**.
It acutally never did. (It just shows Remaining REF / Units in Europe.)

Anything that is acquired in the colonies does not belong to the REF.
(It would e.g. also not show Colonists, captured Ships, Wagon Trains ...)

----------

But of course it can be changed if somebody invests the time to do so.

**Comment by MrZorG33** [comment]
In this case, I think this ticket can be closed.
