### ISSUE TITLE
Colopedia missing River entry

### ISSUE THREAD

**Issue by cammcken** [We-the-People-civ4col-mod/Mod#879]
Rivers, which exist along tile edges, don't fit perfectly in either Colopedia category, but vanilla Civ has always placed it with terrain features. A Colopedia entry should at least describe the yield changes, because the river modifies many but not all, and strategy-minded players may also want to know what improvements and buildings require river adjacency.

**Comment by cammcken** [comment]
Edited. I don't know how I missed seeing Peaks this whole time.

**Comment by raystuttgart** [comment]
There is already a River entry and has always been there.
I think the Ticket can thus be closed - but I leave it up to you. 

It can be found under **"Game Concepts"** - where it always was in Civ4Col.
It would definitely be placed wrong under "Terrrains" - as it is none and also technically based on Yields not Terrains.

The entry also explains all there is to say about Rivers honestly so I do not see a problem or any need for change.
But feel free to update the text if you think it should be improved.

![Civ4ScreenShot0000](https://github.com/We-the-People-civ4col-mod/Mod/assets/59391125/82e5c37e-3e39-4ddb-9207-c855f81d8dc2)

**Comment by cammcken** [comment]
Oops. I'm too used to BtS Civ4's Pedia.

Closing then. So long as it's _somewhere_ in the Colopedia is all that matters.

**Comment by cammcken** [comment]
River entry in Game Concepts category
