### ISSUE TITLE
version 4.02 has errors when starting the mod (xml error)

### ISSUE THREAD

**Issue by gabrielalves2** [We-the-People-civ4col-mod/Mod#885]
I tried to launch the mod on windows 11 (version 4.02) and got an xml error as soon as I entered the loading screen to launch the mod; and all kinds of things I tried to do to fix it failed, I soon realized that the problem was in the mod itself since when trying to migrate to an older version (4.0) the game ran normally

**Comment by raystuttgart** [comment]
Did you read the **instructions.txt** and do what it said?
Because that is the most typical issue why the problem you describe occurs.

**Comment by gabrielalves2** [comment]
I did it the way it was instructed in the instructions and I still used compatibility mode in the executable and put it to run as administrator

**Comment by raystuttgart** [comment]
So you did double click **"setup.bat"**?
And everything was working fine without any exception?

**Comment by raystuttgart** [comment]
And are you sure you really downloaded the correct installation archive?
i.e. There is a **CvGameCoreDLL.dll** in the subfolder **/Assets** ?

This is definitely the correct download:
https://github.com/We-the-People-civ4col-mod/Mod/releases/download/4.0.2/WeThePeople-4.0.2.zip

And after running **"setup.bat"** everything should work automatically.
Unless of course it throws some errors ...

**Comment by gabrielalves2** [comment]
if I'm not mistaken in the version I downloaded there was no dll file more I took the assets of civ 4 colonization and put there maybe that's because it gave error ; and yes I clicked on the setup.bat

**Comment by raystuttgart** [comment]
The download itself should contain the CvGameCoreDLL.dll in the folder I told.
And it **MUST** be the one that comes with the mod **NOT** the one from the base game.

Please delete what you did and reinstall properly.
Use the download link I gave you.

I will close this, as it sounds like a bad installation, not like an issue with the mod,
Open it again once you reinstalled cleanly and it still does not work.

**Comment by gabrielalves2** [comment]
thanks now worked friend, thanks even by the way; amazing mod what you guys did !
