### ISSUE TITLE
Colopedia should show which level of Education Building is required for training Experts

### ISSUE THREAD

**Issue by raystuttgart** [We-the-People-civ4col-mod/Mod#887]
Currently this information is hidden in XML and not displayed in **Colopedia**.
(Showing it also during normal **Unit Mouse Over** is optional to me.)

It is this attribute (Civ4UnitInfos.xml):
**iTeachLevel**

It is actually an easy task to do ... maybe an hour or so.
As I am currently not actively modding I create this ticket as reminder.

If somebody else wants to give this a try, it is a **good first task** for a new modder to learn how it works.
It is really simple but allows to learn how XML data is read and visualized ingame.

The text could say something like this:
iTeachLevel == 1 --> requires 1st level education building to be trained 
iTeachLevel == 2 --> requires 2nd level education building to be trained
iTeachLevel == 3 --> requires 3rd level education building to be trained

**Remark:**
I would keep the wording neutral as we have renamed stuff quite often already.
Also who knows what any modmod may do in the future ... e.g. Medieval or SciFi.

**Comment by devolution79** [comment]
Added the appropriate label to hopefully attract some aspiring modders :smile:

**Comment by johan-buret** [comment]
Right now, all education buildings where an unit can graduate are listed as such in colopedia :

Exemple for a Master profession
![image](https://github.com/We-the-People-civ4col-mod/Mod/assets/7459821/418710d1-2228-49c2-958d-a246cf7132f7)

Should we reduce that to one line , e-g trained at College or better?

**Comment by MrZorG33** [comment]
in my opinion, reducing the tooltip to one line would be a useful improvement. and not only for this.
