### ISSUE TITLE
Wrong max tax rate bug

### ISSUE THREAD

**Issue by victorxup** [We-the-People-civ4col-mod/Mod#900]
MAX_TAX_RATE in GlobalDefinesAlt.xml is 60
and iInitMaxTaxRate in CIV4HandicapInfo.xml for higher difficulties is 70

So sometimes increasing maxTaxRate can actually cause it decreasing to 60%

**Comment by raystuttgart** [comment]
Thanks for notifying.
I fixed the balancing.
