### ISSUE TITLE
Bug: iAIAnimalSeaMaxPercent not working

### ISSUE THREAD

**Issue by victorxup** [We-the-People-civ4col-mod/Mod#902]
CvGame.cpp:
void CvGame::createAnimalsSea():

The following code:
iNeededAnimals = (pLoopArea->getNumTiles() * GC.getHandicapInfo(getHandicapType()).getAIAnimalLandMaxPercent()) / 100;

must be more like:
iNeededAnimals = (pLoopArea->getNumTiles() * GC.getHandicapInfo(getHandicapType()).getAIAnimalSeaMaxPercent()) / 100;

**Comment by raystuttgart** [comment]
Thanks for noticing. 👍 
I will correct it. :)

**Comment by raystuttgart** [comment]
I fixed it.
