### ISSUE TITLE
Python Code for check of citizens IN Colony but not on plot.

### ISSUE THREAD

**Issue by Schmiddie1979** [We-the-People-civ4col-mod/Mod#908]
Hello guys, 

I am currently on the trip to create new events. It is very much fun. I hope you like the events. 

There are really already many possibilities added fir Python. Since I'm not a programmer, I can mostly just copy the Python components from existing events and adapt them for new events. This works already quite well. I have good templates due to your team efforts respectively skills. 

I have a question: I would like to include more events, where Python is used to check how many different citizens (units) are present in a colony (not on a plot outside, but in the city screen). Example: For an event are required a statesman, a master carpenter and a master whale oil cooker - I would need a function where Python checks if all three experts are currently working in a colony so that the event can trigger. 

I have adapted an existing code for this and it works quite well (cheesemaker event).  

**Question: Is this code for the cheese maker event in the CvRandomEventInterface.py fine from your point of view?**

https://github.com/We-the-People-civ4col-mod/Mod/commit/1ae982766555526c22defc90474dc8bd08ca65e8

**2. question:** What should the code look like if you want to check **multiple** units as described above and not just one?

Kind regards

Schmiddie

**Comment by raystuttgart** [comment]
Well, if you want to check for multiple Units, you just do 3 checks and return false if it is not found.
Afterwards if none of those false is triggered you return a true.

Simplified something like this.
(It is just Pseudo-Code though. So do **not copy paste it 1:1** as e.g. Indenting may not match as I wrote it here.)

```
iUnitTypeA = CvUtil.findInfoTypeNum('UNIT_A')
if iUnitsCurrentA == 0
   return false

iUnitTypeB = CvUtil.findInfoTypeNum('UNIT_B')
if iUnitsCurrentA == 0
   return false
   
iUnitTypeC = CvUtil.findInfoTypeNum('UNIT_C')
if iUnitsCurrentC == 0
   return false

return true
```

**Comment by raystuttgart** [comment]
Still your logic will **not** necessarily trigger for the **specific city** that fulfills the conditions.
It may **still trigger for any city** in case the condition is true in any of the Player`s cities ...

There is no single reference of the City itself you want to check in your logic.
Your **entry point** for the logic seems to be the **Player** ... and **not the City that triggered** the event.

There are enough examples in the Python file how to get the **specific City from the EventTrigger** though. 
Then run your logic only for that one and not for all Cities of the Player.

--> Then you can trigger also the Event specific for the City that fulfills the condition. 👍 
(Give it a try, it should not be that hard with all the examples given.)

**Comment by Schmiddie1979** [comment]
Hi ray, 

thank you for your first thoughts. As I said, since I'm not a programmer and therefore I would need the complete Python section to work with. Maybe one (not necessarily you) of our community with Python skills is willing to help me out and to work with me on that Python section. 

Your second comment: Ok, great. I did not know that. As you mentioned yesterday that there currently exists no logic to check **units** **inside** a city I thought this might be the only code that works (I found it via a discussion in the old German TAC forum about Python). Hence I now need to find out which code might work.

**Comment by raystuttgart** [comment]
I will program an example. 👍

**Comment by raystuttgart** [comment]
Please check how I adjusted the "Cheese Maker".
It is now a "City Event", that checks that the Cheese Maker is inside the **specific** City.

Please read both:
- Changes in the Trigger XML
- Changes in Python

**Comment by raystuttgart** [comment]
**Edit:**
I could not yet test it though, as I have to go to eat lunch with my parents.
So please test it. (Otherwise I will test it later this afternoon myself.)

**Edit 2:**
Still found time to test it, it is working as expected.

**Comment by raystuttgart** [comment]
I think this issue can be closed then, right?

Just look in here:
`def CheckCheesemakerInCity(argsList):`

And the comment here:
`# you could add checks for several Units like this`

**Comment by Schmiddie1979** [comment]
Great. Thank you. This creates new possibilities for events with different units in a city.
