### ISSUE TITLE
Defeating a privateer attacking a player reveals their nationality.

### ISSUE THREAD

**Issue by MrZorG33** [We-the-People-civ4col-mod/Mod#921]
in my test game I just received a message: my Galleon successfully fought off a **Danish** Privateer👀 😃 
you can see this in the event log. tag of this message TXT_KEY_MISC_YOU_KILLED_ENEMY_UNIT in file CIV4GameTextInfos_Original_utf8.xml
![image](https://github.com/We-the-People-civ4col-mod/Mod/assets/61798883/3981f810-a66c-44ed-ac24-c26fe7ba19da)

unfortunately there is no save, but I will attach it as soon as I can.

**Comment by johan-buret** [comment]
I have studied the code, and with the way it works, the nationality of the privateer should have been shown onlyif  Danes and  Swedes were on the same team in your save. Heresy, I know, but it is so far the soundest hypothesis I have. 

The offending part is at line 1482 of CvUnit.cpp

The other relevant functions are
```C++
PlayerTypes CvUnit::getVisualOwner(TeamTypes eForTeam) const
const wchar* CvUnit::getVisualCivAdjective(TeamTypes eForTeam) const
```

**Comment by johan-buret** [comment]
one last question : where did the attack come from ? Were you by any chance just next to a danish port city?

**Comment by MrZorG33** [comment]
no, the Galleon was near my coast, and the Privateer sailed from somewhere.

**Comment by MrZorG33** [comment]
Today a Privateer attacked my ship from a native village, not from the open sea. the victory over him again revealed his nationality.
![Civ4ScreenShot0000](https://github.com/We-the-People-civ4col-mod/Mod/assets/61798883/323bdea3-7279-45c2-9fed-677d8650aa7d)

[before attack.zip](https://github.com/We-the-People-civ4col-mod/Mod/files/13305164/before.attack.zip)
[after attack.zip](https://github.com/We-the-People-civ4col-mod/Mod/files/13305166/after.attack.zip)

If the privateer was not destroyed during the attack, load the save again.

**Comment by johan-buret** [comment]
It should work as expected on your save. There was a logic error in the previous check.
![image](https://github.com/We-the-People-civ4col-mod/Mod/assets/7459821/6d03a6e1-6f73-405c-814b-41b5f4f47215)

**Comment by MrZorG33** [comment]
now it works correctly.
