### ISSUE TITLE
4 gameplay change proposals

### ISSUE THREAD

**Issue by Nightinggale** [We-the-People-civ4col-mod/Mod#925]
I received the following 4 proposals for changes through a PM on the forum.

### Proposal 1:

I would love to see an update where capturing enemy colonies would only give you bonuses like money, guns, soldiers, etc like once in a five turns or so (depending on how big the colony is).

Why this update:

The best part about this game is developing your own started colonies. It is so satisfying to make everything the way you want. Once I conquer enemy's colony everything gets much more complicated as suddenly I have these new colonies and units and it is so frustrating to try to optimize everything and I find that one turn might take for ever. It would be so nice just to be able to manage your own original colonies.

### Proposal 2:

Units would be no longer captured when fighting against other nations. They would just die.

Why this update:

Again everything gets too complicated when you suddenly get 60 new units. The AI uses this tactic (puts free colonists and other units all over the colony's nearest slots).

### Proposal 3

When you lose a unit on enemy's turn there would be a summarize after the enemy's turn so that you could easily see which units you lost.

Why this update:

I hate it when my trading transports get wrecked and it would be nice to see the info of what was lost so that I could easily make/buy new ones and replace them with ease.

### Proposal 4:

The AI would no longer be able to become independent.

Why this update:

I hate it when you have to play against time. The other option however would be possible that the AI would destroy its enemies (the other nations that is).

**Comment by MrZorG33** [comment]
Proposal 1.
when capturing an enemy colony, the player already receives gold and goods that were stored in this colony.

Proposal 2.
I don't think this is necessary. if you don't need the units, you can always destroy them manually, which is what I almost always do. but sometimes captured units can be useful (for example, experts in some profession).

Proposal 3.
one more notice that will be superfluous. The main log shows everything that happened. Why do we need another separate notification?

Proposal 4.
in my opinion, if this is introduced, it should only be an option for setting up the game.

**Comment by Nightinggale** [comment]
> Proposal 4.
in my opinion, if this is introduced, it should only be an option for setting up the game.

If we decide to go down this route, I think the easiest implementation would be a new victory condition. This way a custom game will allow players to pick independence (current) or independence (human only).

**Comment by MrZorG33** [comment]
yes, that's exactly what I meant.

**Comment by victorxup** [comment]
> Proposal 1:

Strongly no. This is one of the best challenges ingame. Enjoy it so much.

> Proposal 2: 

Maybe yes, maybe not, maybe probability based..
But this is also a challenge, also often much fun.

> Proposal 3:

Sometimes can be useful to see more info in game log, yep.

> Proposal 4:

What's the purpose of AI then. Maybe I don't get something?..

**Comment by Schmiddie1979** [comment]
Proposal 1: Strongly "no" as well. This is a very challenging and interesting part of the game.
Proposal 2: Strongly "no". Getting new units and integration in your colonies is also an interesting part - and maybe can also be fun. 
Proposal 3: Hm, I'm not against it, but I think it is not necessary - the player maybe needs to be a little bit attentive during the turns and then he will notice what he has lost. 
Proposal 4: WHAT? This is one of the best challenges during the game! Strongly "no" or at least only a game option...but I think it is not necessary.

**Comment by johan-buret** [comment]
"no" to all four.

**Comment by MrZorG33** [comment]
@johan-buret even if it is an option?

**Comment by johan-buret** [comment]
Adding an option means adding complexity, and I don't think it's what the mod needs most.

I dislike all four proposals, so no.

**Comment by raystuttgart** [comment]
From my side also a definite "no" to all 4 proposals.
I would never touch the mod again if that stuff was implemented.

So let us please close this.
