### ISSUE TITLE
Tax counter/threshold doesn't reset or react to getting maxed out

### ISSUE THREAD

**Issue by Nightinggale** [We-the-People-civ4col-mod/Mod#928]
From discord [1](https://discord.com/channels/788850075673690112/1055869225358606356/1167824915454504980) [2](https://discord.com/channels/788850075673690112/1055869225358606356/1168078748730523668)

> The King came up with his tax increase
I agreed to the tax increase
So the tax was raised to 1%. And the yield limit was raised from 1875 to 2025
However the yields counter was not reset to 0
So it stayed at the count before the tax increase
(in the original, once the tax increases, the counter is set to 0)
Not only that, im now selling everything and the king never wants to raise the tax

![imagem](https://github.com/We-the-People-civ4col-mod/Mod/assets/4641647/af47b107-5b00-4054-afc2-907a9dcecd6f)

https://streamable.com/m5tlp0

[Yields_Trade_Bug_Stuck.zip](https://github.com/We-the-People-civ4col-mod/Mod/files/13197808/Yields_Trade_Bug_Stuck.zip)

## Developer's comments

The code in question is poorly designed. The help text is embedded in the GUI, so one copy for each screen it can show up on. Also it's not connected to the game mechanic code, hence  they can go out of sync. This needs to be rewritten to ensure that the game mechanic and the displayed text can't go out of sync.

We likely would need a dedicated widget type to take care of the text. This means no calculations in the GUI and multiple locations can use the same code. Also the code would be in C++ rather than python, which makes sense given the context of the displayed data.

The data storage for this might need redoing as well. An EnumMap of length (trade locations), each with a class instance, which holds an EnumMap of bought and sold yields. Perhaps with #927 and yeah an EnumMap of class instances is totally a thing inside EnumMap, despite it not really being used currently.

**Comment by johan-buret** [comment]
This issue is related to #732, as in it's the King player that should determine the tax rate it wants to inflict on the colonial player

**Comment by johan-buret** [comment]
This tax code problem  was an occasion to dust up this section of code. It also provides a test case for the Widget system discussed in #929 

It also eliminates an issue of code logic duplication between Python and C++.  All the logic is now on the C++ side

**Comment by Nightinggale** [comment]
Fixed.

**Comment by johan-buret** [comment]
More testing is in order to ensure everything works alright.

**Comment by MrZorG33** [comment]
I updated the mod and ran tests. the new inscription for Port Royal is excellent)

but when selling goods in Port Royal, the counter for goods sold in Europe/Africa increases. this should not happen since the King does not know about these transactions.

**Comment by johan-buret** [comment]
Working on this issue has been the occasion of removing the cloak of complexity on the tax calculation and exposing its internals in the clearest way possible. 

Although I tend to agree that Port Royal trade should not influence, I left it "as is", because the former complexity of the code base did not let tell me whether it was  an intentional choice of the previous dev teams, or a plain mistake.

The tax calculation formula  is a whole game balance issue, that is beyond the scope of this issue.

**Comment by MrZorG33** [comment]
In my opinion, it is necessary to exclude the influence of trade in Port Royal on the trade counter in Europe. I hope others will agree with me.
you can do it?

**Comment by johan-buret** [comment]
The display has been properly fixed.

**Comment by MrZorG33** [comment]
By the way, does the counter for the number of items sold change depending on the speed of the game? Where can I see the setting for the number of items sold?
**edit**: for the speed of Buildup mode the figure is extremely small.
