### ISSUE TITLE
pirate ships don't trigger the first encounter with the chief of the native tribe

### ISSUE THREAD

**Issue by MrZorG33** [We-the-People-civ4col-mod/Mod#947]
After loading the save, you will see that you cannot trade with the natives, since contact has not been established with them. with the help of the WB, place any land or sea unit next to the native village and after that trade will become possible. thus, if you send a pirate ship to explore the coast, you will not be able to trade.
[dynamic asserts test.zip](https://github.com/We-the-People-civ4col-mod/Mod/files/13325152/dynamic.asserts.test.zip)

**Comment by Schmiddie1979** [comment]
Hm, sounds all reasonable. Pirate ships should not trigger the first encounter...!

**Comment by MrZorG33** [comment]
What I meant was that this is a ship and it should be able to trade. but until there is first contact, trading is prohibited.

my question is whether it is possible to do so to allow trading without first contact.

**Comment by raystuttgart** [comment]
No, it is impossible to initiate any trade or diplomacy without having established contact.
Also it sound pretty strange to me ... it is a bit immersion breaking almost. :(

**Comment by MrZorG33** [comment]
ok, I can understand that. but then why not give the pirate ships the opportunity to make first contact? merchant ships can do this.

**Comment by johan-buret** [comment]
From a technical point of view : 
the code to contact Natives is the same to contact another European power. It's simpler from a code point of view to make it : **Pirate ship means  no diplomacy contact no exception** than to introduce this exception.

**Comment by MrZorG33** [comment]
ok, let's close this question.
