### ISSUE TITLE
Naval unit heals negative promotion in open sea

### ISSUE THREAD

**Issue by victorxup** [We-the-People-civ4col-mod/Mod#953]
To reproduce issue, just load save and skip turn

[AutoSave_AD-1492-May.zip](https://github.com/We-the-People-civ4col-mod/Mod/files/13419670/AutoSave_AD-1492-May.zip)

**Comment by victorxup** [comment]
I suppose to fix this issue, the following section must do the **opposite**: 
AI heals neg.promotions everywhere, Human Player can heal neg.promotions only in settlements

![image](https://github.com/We-the-People-civ4col-mod/Mod/assets/23401480/46aedf7c-f265-4380-a6cf-9bdf1bf876e0)

**Comment by johan-buret** [comment]
I confirm your analysis. I will patch that shortly

**Comment by victorxup** [comment]
Or just merge my PR
