### ISSUE TITLE
Max no of recruiting points underflow

### ISSUE THREAD

**Issue by andushow** [We-the-People-civ4col-mod/Mod#959]
Using most recent version (WTP 4.1), there's a bug in the recruting algorithm; since version 4.1, it costs more (points) to recruit, the more people are waiting on the docks in the queue, this can lead to situations like this one:
![image](https://github.com/We-the-People-civ4col-mod/Mod/assets/14202199/c9921fd9-b86a-43d8-b9b0-6bb20e757da1)

How to reproduce it:
You have recruting points close to max (35/40) with several people waiting on the docks. Once we onboard the people on the docks, the recruiting max points decrease that much that they go below the available recruiting points (35).

**Comment by johan-buret** [comment]
What matters is if if the 2 overflow points are taken into account on the next round.

The current code intends cross overflow to be kept around so that the next candidate comes in faster.

It doesn't look like a bug, for now.

**Comment by andushow** [comment]
If we consider that recruiting is blocked unless a workaround is applied (unload enough people to raise the max points above the available recruiting points), then we may look into finding a permanent fix.

**Comment by johan-buret** [comment]
I have a fix ready for this. All I need is a savegame where you have this bug

**Comment by MrZorG33** [comment]
@johan-buret I attached the save (you need to open the europe screen, buy any ship capable of transporting colonists and load one of those waiting at the docks onto the ship). Excess emigration points count towards the next turn.
[dynamic asserts test.zip](https://github.com/We-the-People-civ4col-mod/Mod/files/13522272/dynamic.asserts.test.zip)

**Comment by johan-buret** [comment]
Please test and see if the fix I provided on `develop` actually corrects this issue

**Comment by MrZorG33** [comment]
works now.
