### ISSUE TITLE
Failed to start: "Failed to load python module CvEventInterface"

### ISSUE THREAD

**Issue by andushow** [We-the-People-civ4col-mod/Mod#967]
Have been successfully playing this version for a while (windows 11 pro, Version 10.0.22631 Build 22631):
https://github.com/We-the-People-civ4col-mod/Mod/releases/download/4.1/WeThePeople-4.1.zip
Since a laptop restart, with no intentional update/install/removal (python, etc.) by myself, I got the dreaded error message:

"Failed to load python module CvEventInterface"

"Failed to load python module CvAppInterface"

followed by several failry similar pop-ups.

What I've checked:
(1) files "tbb.dll" and "tbbmalloc.dll" (from v 4.1) are still in the root folder. (d:\col in my case); also, files are safe from Windows pov (unblocked for remote files)
(2) proper file "CvGameCoreDLL.dll" exists in d:\col\Mods\WTP4.1\Assets folder
(3) launch shortcut is
D:\col\Colonization.exe mod=\WTP4.1

What else shall I check ? Game version *was* working on my computer, something (windows update ?) might have happened that broke it.

![image](https://github.com/We-the-People-civ4col-mod/Mod/assets/14202199/11a23d6e-bda4-4f16-ad9a-e75a493192a7)

**Comment by raystuttgart** [comment]
But Civ4Col Vanilla is still working?
Please check.

**If yes:**
Do a clean reinstallation of the mod. (using setup)
--> Delete mod folder, download again and reinstall.

**If no:**
Do a clean reinstallation of Vanilla + mod.
--> Delete mod folder, unistall Vanilla and intall both again.

------------

Sorry, but that is all advise I have.
But it sounds like something got broken ... e.g. a corrupted file on the file system.

**Comment by andushow** [comment]
Yes, vanilla Civ is (still) working (moreover, WTP 3 mod is running fine also); To me, reinstalling the mod means simply unzipping the file to the Mods folder, isn't it ?

**Comment by andushow** [comment]
have tried "reinstalling" the mod (simply delete the existing mod sub-folder, unzip the newly downloaded file) and I get the same result, something must be off here...

**Comment by andushow** [comment]
This worked:
https://forums.civfanatics.com/threads/solved-failed-to-load-python-module-cveventinterface.149959/
remove %USERPROFILE%\Documents\My Games\%whatever you colonization folder is%
(you may want to backup your savegames first)
