### ISSUE TITLE
Can Failed Trader and Disillusioned Missionary found settlements?

### ISSUE THREAD

**Issue by victorxup** [We-the-People-civ4col-mod/Mod#968]
XML settings for Failed Trader and Disillusioned Missionary are now following:

They can found settlements in profession Settler
But they are not allowed to be assigned to Settler profession.

Is this correct?

**Comment by raystuttgart** [comment]
Yes, this is correct.

**Considering XM of the UnitL:**
As the setting in the XML (at the Unit) is not about "Founding Settlements", it is about "Joining Settlements".
If it would be changed they could not join a Settlement anymore.

**Considering gameplay:**
It was intended that those Units would not be very valuable.
Thus e.g. also not used for running around on the map to found settlements.

**Considering where "Founding Settlements" is configured:**
The actual "Founding Settlements" is configuredin the XML of the Profession.
(So the Unit is really just about "being able to join" - the actual founding is the "Profession".)

-------------

**Summary:**
Everything is working as intended.
They are not intended to found settlements, but should still be able to join them.

**Comment by victorxup** [comment]
Thanks for clarification.
So, the only thing to be fixed then - is the colopedia entry that says: "Can found new colonies in profession settler"

**Comment by raystuttgart** [comment]
As it cannot take "Profession Settler" that should not be a big issue. :)
But sure, if somebody is motivated, he could fix that in the DLL.

The "ProfessionsNotAllowed" just is simply currently not checked for that Colopedia entry.
(It would be stupid to code, as you had to loop through all 100+ Professions to notice if "Settler" was forbidden.)

The best solution would probably be to list "Professions Not Allowed" in Colopedia.
