### ISSUE TITLE
Problems getting FF although there are enough points

### ISSUE THREAD

**Issue by Mart53** [We-the-People-civ4col-mod/Mod#970]
Hi all I don't understand why FF on religion are not "popping / showing up" so that I can choose them. I play WTP4.1 / Steam in GER and just realized this know, because I'm desperately waiting on "Juana Inés de la Cruz". Any idea? She needs 1080 "religion points" and 1350 "politic points" (don't know how the right vocabulary are in the EN-COL version, but I think you know what I mean). Other FF are showing up. 

I later accepted a different FF (-> political points are reduced as you all know) and quickly clicked through the rounds and noticed the following. Religion: The political points were among those for "Bartolome de Las Casas", he was then suggested to me. I rejected him and in my opinion the suggestion would now be "Juana Inés de la Cruz"... but only when I repeated the cycle again (i.e. reducing policy points by selecting a different FF) did I finally get "Juana Inés de la Cruz" proposed.

I don't think this behavior is correct. As soon as I reject a FF, I should be suggested the next one whose points I have (regardless of which category).

BR ColMart72

I have attached a screenshot and the saved game.

[WTP41 FF Religion.zip](https://github.com/We-the-People-civ4col-mod/Mod/files/13866000/WTP41.FF.Religion.zip)

**Comment by Razonatair** [comment]
After looking into the codebase, this is actually intentional behavior in the mod. At some point it was changed to make it so only one founding father offer per turn is made. This was done to make it so players could only earn one founding father per turn, instead of an infinite number so long as they had points available. I've offered a suggestion to the other devs as to how to alter the code so the game will make another offer, if the points are available, if you refuse an offer to accept a FF. This would still ensure that only one FF can be earned per turn, but still allow for multiple offers per turn. We'll see what is decided once the others take a look at my suggestion.

**Comment by Mart53** [comment]
@Razonatair Thank you for having a look. I totally agree that you shouldn't get more than one FF per round, even if you have the points required for it. I used to play TAC (because I didn't know WTP, and I think it's really great what you did there). If I remember correctly, I've never been able to choose more than one FF in a round (I've never played Civ4 Vanialla but the previous versions and TAC). Your suggested solution is really good. The behavior at the moment is that only one comes at a time and it seems that the "FF category" doesn't change until you choose one. For example, when I rejected "Bartolome de Las Casas" and still had enough points in "Religion", the next time  I was suggested a "FF" from a different category (so wait again for "Juana Inés de la Cruz" ) => so it takes N FF until "Religion" comes back (and that's the problem). And as I said, the jump back to "Religion" only started when I started spending points on FF in other categories that I didn't even want.

**Comment by XSamatan** [comment]
> I've offered a suggestion to the other devs as to how to alter the code so the game will make another offer, if the points are available, if you refuse an offer to accept a FF. This would still ensure that only one FF can be earned per turn, but still allow for multiple offers per turn. 

Would be a good QoL change. I too often miss Sieur de Villegaignon because of the described behavior.

Regards
XSamatan

**Comment by Razonatair** [comment]
The next release will now have Founding Father Competition code that addresses all these problems. Thanks for all the saves!
