### ISSUE TITLE
"Pirate Attack" events broken

### ISSUE THREAD

**Issue by victorxup** [We-the-People-civ4col-mod/Mod#971]
When Player chooses not to pay in "Pirate Attack" events (EVENT_PIRATEATTACK1, EVENT_PIRATEATTACK2) several pirate ships must be generated. Though python functions (doPirateAttack1, doPirateAttack2) are commented out, and thus not called.
Now the player can avoid pirate ships appearing by just choosing second option (which is buggy)
And it seems that it have been so for quite a long time already

I provided a quick patch for this in following Pull Request.

**Comment by raystuttgart** [comment]
Ok, I merged the pull request.
As I said I have no idea why that had been commented out.
