### ISSUE TITLE
Fishing Nets improvement should be allowed on Large Rivers

### ISSUE THREAD

**Issue by victorxup** [We-the-People-civ4col-mod/Mod#976]
Fishing Nets improvement should be allowed on Large Rivers since some food resources can be placed there
(and they actually do with curent map generation)

**Comment by raystuttgart** [comment]
Agreed. But just like currently on Ocean it should be **only on Bonus Ressources**.
Otherwise the Fishing Nets become OP and it would be boring.

**Comment by Razonatair** [comment]
The Fishing Boats improvement has been updated to allow for placement on bonuses on Large Rivers as well.
