### ISSUE TITLE
XML Load Error and Game Crash When Launching Mod version above 3.01

### ISSUE THREAD

**Issue by lilidfdf** [We-the-People-civ4col-mod/Mod#979]
I have encountered several errors while trying to launch the mod on a Windows 10 x64 system. The errors are related to XML files, including XML load errors and text encoding errors. As a result, the game crashes. I have attached some of the error reports below:

<img width="242" alt="error report 2" src="https://github.com/We-the-People-civ4col-mod/Mod/assets/50309846/7300b999-2b63-4323-b1a8-932b45df7a7f">
<img width="199" alt="error report 3" src="https://github.com/We-the-People-civ4col-mod/Mod/assets/50309846/6c4396d3-bd8c-44aa-a5b0-5e4ff996396e">
<img width="236" alt="error report 4" src="https://github.com/We-the-People-civ4col-mod/Mod/assets/50309846/69f271ba-47f5-4cbe-bae0-61571e7d44ab">
<img width="216" alt="error report" src="https://github.com/We-the-People-civ4col-mod/Mod/assets/50309846/ceb17c6a-7318-4364-92b9-eaa7ac5eb876">

I have followed the instructions.txt file strictly and placed the mod in the correct position. My game version is the Steam version, and I have changed it to the [original_release_unsupported] version. I have tried multiple versions of the mod, ranging from 3.01 to 4.1, and all of them show similar errors. The only difference is that I can run WTP 3.01 after encountering these error reports, but I cannot do so with the higher versions. One temporary solution I found is to delete all the XML files in the \XML\Text folder, although it damages the game experience a lot. I am seeking a better solution. Can anyone help? I really like this mod and would love to try the latest version.

**Comment by johan-buret** [comment]
First, on which version of the game are you playing ? Steam? GOG ? 
Second, which are your language settings ? 

We have not tested our mod when the base codepage was something else than cp-1252  West european  or the Russian one.

Try using this utility to launchj the game https://github.com/xupefei/Locale-Emulator with the English setting, and see if the problem persist.

**Comment by MrZorG33** [comment]
I don’t see the screenshots (an error occurred when opening the page), but I assume that the necessary DLLs were not copied. open the **readme.html** file and read the section on installing the mod. I think this should help.

**Comment by Nightinggale** [comment]
> I don’t see the screenshots (an error occurred when opening the page), but I assume that the necessary DLLs were not copied. open the **readme.html** file and read the section on installing the mod. I think this should help.

No, this is most certainly related to reading the text xml files. This is way past the point where dll issues will occur.

**Comment by lilidfdf** [comment]
> First, on which version of the game are you playing ? Steam? GOG ? Second, which are your language settings ?
> 
> We have not tested our mod when the base codepage was something else than cp-1252 West european or the Russian one.
> 
> Try using this utility to launchj the game https://github.com/xupefei/Locale-Emulator with the English setting, and see if the problem persist.

Hi, I play the Steam version of the game, and it turns out that the errors were occurring because my system language was set to simplified Chinese. By following your instructions, I can now run the mod without any problems. Thanks for your help!

**Comment by Nightinggale** [comment]
> Hi, I play the Steam version of the game, and it turns out that the errors were occurring because my system language was set to simplified Chinese. By following your instructions, I can now run the mod without any problems. Thanks for your help!

Since the problem was Simplified Chinese locale, odds are that it is a problem with every single character encoding, which supports using more than one byte for each character. Since this is most non-European languages it would be a good idea to fix it once and for all.

From what I can tell, the xml encoding tag is ignored and system locale is used. Getting the reader to force use the encoding mentioned in the xml file (utf8) should fix the problem entirely. In other words there really is only a single place in the code where this can go wrong so for once it's not about finding the bug, but rather the work of fixing/rewriting the file reader. This was planned anyway because that specific part of the code is already known for being of questionable quality. It was however not known that it will downright fail completely on some computers.
