### ISSUE TITLE
Translation for Founding Father Concept in Colopedia Needed

### ISSUE THREAD

**Issue by Razonatair** [We-the-People-civ4col-mod/Mod#984]
XML_AUTO_UTF8_ConceptInfo.xml has been updated to clarify how the new Founding Father Competition works. It needs translation into the other languages now, unless someone wants me to butcher the translations using Bing or Google Translate haha.

Specifically, this is how things now work overall:

On a player's turn, a Founding Father will offer to join the player if that player has enough points to hire the Founding Father, AND that player has MORE of that Founding Father's Primary Point Type than any other player. A Founding Father's Primary Point Type is the same as the Category they are in. Political are Political, Religious are Religious, etc.

**Comment by MrZorG33** [comment]
I read the new description. Did I understand correctly that it doesn’t matter how many Political points there are, but the main ones will be specialized points (military, trade, etc.)? We don’t consider the Political branch of the FF - only political points are needed there)

**Comment by Razonatair** [comment]
To be more specific, the political points are only considered if it's a Political father, or if the Specific Points of the FF are tied. In the event of a tie, the political points are checked. I don't think explaining how the entire thing works to the player is necessary since ties are going to be really unusual, and the players can't see each other's Founding Father Points anyway. There is also the possibility of a double tie in both the Specific and Political points, in which case, the first person to call the function will receive the offer for the Founding Father.

Now, I don't know if that means in a multiplayer game that a double tie could offer to multiple human players and break the game, but it seems unlikely. This is astoundingly rare in fact based on my mental experiments. You'd have to both be capable of hiring the FF, both have the same specific points, both have the same political points, and then both be human playing a simultaneous game, not a hot seat one. I don't know enough about how the multiplayer works to know 100% if that stars-aligning event will break something.

**Comment by MrZorG33** [comment]
hmmm... is it possible to add some other condition in such an exceptional case? for example, sorting by the number of total game points?

**Comment by Razonatair** [comment]
It's possible if you mean comparing total points that each player has but it seems unnecessary. Depends what Nightinggale thinks in my opinion.

Technically there is still the one-in-a-trillion-or-more situation where the players have exactly the same total number of points while also meeting all prior conditions, but that seems excessive to account for.

**Comment by MrZorG33** [comment]
yes, such an opportunity is very rare, you are right. but I’m also worried about what will happen if this happens) let’s wait for the @Nightinggale .

**Comment by Razonatair** [comment]
Nightinggale has decided to develop an alternative solution, so translation will not be needed.
