### ISSUE TITLE
NMS - Cannot Directly Assault Unit On Roaded Hill From Unroaded Tile

### ISSUE THREAD

**Issue by Razonatair** [We-the-People-civ4col-mod/Mod#988]
So this is an interesting pathfinding error with the NMS. I've attached the save.

[New Movement, Cannot Attack Native On Hill.zip](https://github.com/We-the-People-civ4col-mod/Mod/files/14120337/New.Movement.Cannot.Attack.Native.On.Hill.zip)

In Novo Arkangelsk, I have a unit sitting on an unroaded marsh 1 West of a roaded hill tile that has a Brave on it. This roaded hill tile is connected to the roaded flat colony center tile 1 South of the original marsh. The pathfinding refuses to allow my units in the marsh to directly attack the hill, forcing them to first enter the city, and then attack on the next turn. I can only attack the hill directly by attacking up the road from the city center itself.

It seems the current algorithm doesn't have consideration for forcing assaults into rough terrain and or is somehow getting confused in some other way.

**Comment by MrZorG33** [comment]
I think I mentioned a similar problem somewhere, but I still can’t find Issue where it was mentioned (I even attached a screenshot. Or was it somewhere in a work chat?..)

**Comment by Razonatair** [comment]
Devolution has fixed this issue in the NMS with his changes to the NMS pathfinding.
