### ISSUE TITLE
Five Markets Quest provides only 2 options when done (XML issue)

### ISSUE THREAD

**Issue by victorxup** [We-the-People-civ4col-mod/Mod#995]
EVENT_FIVE_MARKETS_DONE_1 event is not linked by any EventTrigger, thus is not available for player choice.

**Comment by raystuttgart** [comment]
Again, why not just fix it and create a ticket instead ?

**Comment by MrZorG33** [comment]
As soon as I finish things at work, I'll do this. Sorry, there's no reminder/scheduling tool here. I'll try to record a reminder somewhere else.

**Comment by MrZorG33** [comment]
I tried adding the first option, but after the trigger fires, this option is inactive. in this case the parameter < bPickCity > is equal to 1.
![image](https://github.com/We-the-People-civ4col-mod/Mod/assets/61798883/57c5bbd3-7045-4b62-9f45-b01e4bc10114)

if the < bPickCity > parameter is 0, then the first option becomes active, but the building is not built in any settlement.
![image](https://github.com/We-the-People-civ4col-mod/Mod/assets/61798883/59e3112c-deb0-495e-8a3c-b17a85088ba5)

we need the help of an experienced modder who can figure out why this is happening.

**Comment by Schmiddie1979** [comment]
Thanks for reporting. I will take a look.

**Comment by Schmiddie1979** [comment]
I have added the 1 option and changed the conditions a bit. It works now with option 1 included.
