### ISSUE TITLE
Expert Trapper cannot be bought

### ISSUE THREAD

**Issue by victorxup** [We-the-People-civ4col-mod/Mod#996]
Expert Trapper is not available neither in Europe, nor in Africa or Port Royal

**Comment by raystuttgart** [comment]
Well, if you think this is a problem, then simply change it. 👍

**Comment by victorxup** [comment]
> Well, if you think this is a problem, then simply change it. 👍

That's kind of why I create an issue: to know if this was intended or just a minor bug?)

**Comment by raystuttgart** [comment]
Honestly I think that hardly anybody cares which way it is ... as it is such a minor detail.
I am fine with the way it is now ... I am also fine if you want to change it.

And again, hardly anybody is currently active that even cares about balancing details.
So opening such tickets just creates unnecessary overhead and waiting time.

**Comment by Schmiddie1979** [comment]
> > Well, if you think this is a problem, then simply change it. 👍
> 
> That's kind of why I create an issue: to know if this was intended or just a minor bug?)

This is intended and not a bug.
