### ISSUE TITLE
Quest "Trade Guns with Europe" shows wrong target number

### ISSUE THREAD

**Issue by victorxup** [We-the-People-civ4col-mod/Mod#997]
In CIV4EventInfos.xml

It shows 2000 guns for normal speed as a goal:
![image](https://github.com/We-the-People-civ4col-mod/Mod/assets/23401480/ff68de2d-f2be-4e59-91da-5598b467c415)

But as a criteria of achieval 3000 guns is defined instead:
![image](https://github.com/We-the-People-civ4col-mod/Mod/assets/23401480/9d83ff50-739b-4b0a-96f6-e05b8686f8b1)

I suppose the second one is correct.

UPD: The same issue also have at least:
- Guns, Tools, Blades for Europe

**Comment by victorxup** [comment]
The same issue also have at least:
- Guns, Tools, Blades for Europe

**Comment by raystuttgart** [comment]
Then simply correct it. :)
Why report a bug that is so easy to fix instead of directly fixing it.

**Comment by victorxup** [comment]
> Then simply correct it. :) Why report a bug that is so easy to fix instead of directly fixing it.

1. For me it's a reasonable point: to know the opinion of team. Which value would be correct, for example.
2. I've got no access rights to commit to develop))

**Comment by raystuttgart** [comment]
1) Most likely nobody will answer as hardly anybody is still active except Nightinggale
2) Please get the commit rights then from Nightinggale

--> If we work with throwing tickets the mod is dead.

As Nightinggale will be too busy to take care of it all ...
And I currently do not want to be playing nanny anymore for such small things.

**Comment by Schmiddie1979** [comment]
I can take a look at it.

**Comment by Schmiddie1979** [comment]
Issue is under review. Thanks for reporting.

**Comment by Nightinggale** [comment]
I'm going to look into redoing the xml layout a bit. Having a design, which relies on multiple event entries containing the same number is just asking for those numbers to go out of sync and then something like this happens.

**Comment by Schmiddie1979** [comment]
@raubwuerger 

We are wondering if the trade quests are all currently incorrect. I have tested various trade quests and the required number of goods and the number needed to complete the quests do not match in almost all cases.

It's kind of frustrating when the text says that 4000 goods X are required, but then you have to trade 5000 to complete the quest. As I said, it feels like this is the case with almost all quests - so I'm wondering if this is intended or really a bug resp. how it should be and what we might be overlooking.

Might you be able to look at it and provide some feedback?

**Comment by raubwuerger** [comment]
Is fixed ...

#997 Corrected trade event values. The value shown in the quest log is now matching the conclusion value.
